### ISSUE TITLE
Awkward line break in multiple component expression

### ISSUE THREAD

**Issue by taldcroft** [psf/black#3187] opened 2022-07-27 00:09 UTC
**Describe the style change**

Prefer formatting an expression with a line break before the operator instead of breaking for a getitem key. This seems to be a rare example where black is making the code far less readable.

**Examples in the current _Black_ style**

```python
            bad = (self.data[f"aoacfct{slot}"][i0:i1] != "TRAK") & self.data[
                "npnt_kalm"
            ][i0:i1]
```

**Desired style**

```python
            bad = (
                (self.data[f"aoacfct{slot}"][i0:i1] != "TRAK")
                & self.data["npnt_kalm"][i0:i1]
            )
```

**Additional context**

Maybe this is a duplicate of #236, if so feel free to close.

**Comment by felix-hilden** [comment] 2022-09-11 14:50
Thanks for the suggestion! It seems indeed to be a duplicate of the specified issue, and based on your desired formatting also #2156. So I'll close this one 👍

**Closed by felix-hilden** 2022-09-11 14:50 UTC
Labels: T: design
