### ISSUE TITLE
"fmt: skip" on colon-terminated lines either fails or moves the directive

### ISSUE THREAD

**Issue by dansebcar** [psf/black#2646] opened 2021-11-26 10:51 UTC
**Describe the bug**

Adding `# fmt: skip` after a colon (e.g. on the same line as `def`, `if`, `with` or `class`) either produces the error "Black produced different code on the second pass of the formatter." or moves the `# fmt: skip` directive below the suite (with a 2-space indent, as well as inserting a blank line between the statement introduction and the suite).

**To Reproduce**

For example, take this code:

```python
def f():  # fmt: skip
    pass
```

And run it with these arguments:

```sh
$ black file.py
```

The resulting error is:

> error: cannot format test.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_cwq0dubx.log

```diff
Mode(target_versions=set(), line_length=88, string_normalization=True, is_pyi=False, is_ipynb=False, magic_trailing_comma=True, experimental_string_processing=False)
--- source
+++ first pass
@@ -1,2 +1,6 @@
-def f(): # fmt: skip
+def f():
+
     pass
+
+
+# fmt: skip
--- first pass
+++ second pass
@@ -1,6 +1,4 @@
 def f():
 
     pass
-
-
-# fmt: skip
+  # fmt: skip
```

On the other hand, with `if` there is no internal error:

```python
if True: # fmt: skip
    pass
```

But it does become:

```python
if True:

    pass
  # fmt: skip
```

Which is not what I expected. `with` and `for` behave like `if`, `class` behaves like `def`.

**Expected behavior**

In all cases I expected black to exit without error and for the `fmt: skip` directive to remain on the same line.

**Environment**

- Black's version:  black, 21.11b2.dev6+g17e42cb (compiled: no)
- OS and Python version:  Debian Bullseye/ Python 3.9.2

**Comment by dansebcar** [comment] 2021-11-26 11:23
My naive attempt to work around this using `fmt: off` and `fmt: on` produced a different error, which may be related:

```python
class C:
    # fmt: off
    def f(self):
    # fmt: on
        pass


def g():
    pass
```

> INTERNAL ERROR: Black produced code that is not equivalent to the source on pass 1.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_c_aho8k6.log

```diff
--- src
+++ dst
@@ -25,36 +25,36 @@
           returns=
             None,  # NoneType
           type_comment=
             None,  # NoneType
         )  # /FunctionDef
+        FunctionDef(
+          args=
+            arguments(
+              args=
+              defaults=
+              kw_defaults=
+              kwarg=
+                None,  # NoneType
+              kwonlyargs=
+              posonlyargs=
+              vararg=
+                None,  # NoneType
+            )  # /arguments
+          body=
+            Pass(
+            )  # /Pass
+          decorator_list=
+          name=
+            'g',  # str
+          returns=
+            None,  # NoneType
+          type_comment=
+            None,  # NoneType
+        )  # /FunctionDef
       decorator_list=
       keywords=
       name=
         'C',  # str
     )  # /ClassDef
-    FunctionDef(
-      args=
-        arguments(
-          args=
-          defaults=
-          kw_defaults=
-          kwarg=
-            None,  # NoneType
-          kwonlyargs=
-          posonlyargs=
-          vararg=
-            None,  # NoneType
-        )  # /arguments
-      body=
-        Pass(
-        )  # /Pass
-      decorator_list=
-      name=
-        'g',  # str
-      returns=
-        None,  # NoneType
-      type_comment=
-        None,  # NoneType
-    )  # /FunctionDef
   type_ignores=
 )  # /Module
\ No newline at end of file
```

I was again hoping that nothing would be changed successfully, although I acknowledge that `fmt: off` and `fmt: on` may not be intended to work like that.

**Comment by AustinScola** [comment] 2022-03-01 14:12
Looks like this Issue is a duplicate of #2421.

I just ran into this bug too and it is pretty annoying. Is there any plan to fix this?

**Closed** 2022-07-19 21:26 UTC
Labels: T: bug, C: unstable formatting, F: fmtskip
