### ISSUE TITLE
Pip install has different version in metadata: '20.8'

### ISSUE THREAD

**Issue by jrdzha** [psf/black#1933] opened 2021-01-17 02:02 UTC
Installing black on Ubuntu, Python 3.8 results in the following error:

```
root@2971284e07e9:/# python3 -m pip install black
Collecting black
  Downloading black-20.8b1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 3.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Requested black from https://files.pythonhosted.org/packages/dc/7b/5a6bbe89de849f28d7c109f5ea87b65afa5124ad615f3419e71beb29dc96/black-20.8b1.tar.gz#sha256=1c02557aa099101b9d21496f8a914e9ed2222ef70336404eeeac8edba836fbea has different version in metadata: '20.8'
```

**To Reproduce** Steps to reproduce the behavior:

1. Using Python3.8 in Ubuntu Docker image
2. Run `python3 -m pip install black`

**Expected behavior** The pip install should work

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Ubuntu/Python 3.8.7

**Comment by ofek** [comment] 2021-01-17 02:10
We're also experiencing this in our CI https://github.com/DataDog/integrations-core/pull/8378

**Comment by seanlaw** [comment] 2021-01-17 02:19
Same here. This just started happening in the past 20 minutes on both Azure Pipelines and Github Actions

**Comment by MohamedElgammal** [comment] 2021-01-17 02:38
Same here.

**Comment by ticdenis** [comment] 2021-01-17 02:43
Same here with Github actions too

**Comment by iot-resister** [comment] 2021-01-17 03:06
Same with gitlab ci

**Comment by amanda-wee** [comment] 2021-01-17 03:09
Confirmed

**Comment by vint21h** [comment] 2021-01-17 03:13
Same at localhost using pip and pipenv.

**Comment by ichard26** [comment] 2021-01-17 03:23
**TO EVERYONE IN THIS THREAD:**

For a temporary solution is: please make sure `setuptools-scm` is installed in the environment you're installing Black to, if that fails, make sure to have `setuptools-scm` AND install black with `--no-build-isolation` 

---

\cc @cooperlees we need to publish a release with wheels ASAP IMO, how is the CHANGELOG entry verification process coming along?

**Comment by vint21h** [comment] 2021-01-17 03:34
Suddenly it starts working without any changes on my side, at localhost using pip/pipenv and at GitHub actions using pip.

**Comment by reata** [comment] 2021-01-17 03:34
My GitHub Actions is back to normal with setuptools==51.3.1 released just now. 
This seems related to setuptools==51.3.0 release 2 hours ago because my build was successful yesterday.
See https://pypi.org/project/setuptools/#history

**Comment by ichard26** [comment] 2021-01-17 03:38
You seem to be correct, @reata thanks for looking at setuptools again because I didn't notice that even though I suspected a setuptools release mishap.

**Comment by amanda-wee** [comment] 2021-01-17 03:42
Confirmed back to normal with Github Actions

**Comment by JelleZijlstra** [comment] 2021-01-18 01:09
Sounds like this was due to a broken setuptools release. Is there anything for Black to do or should we close this issue?

**Comment by ichard26** [comment] 2021-01-18 01:36
Seems reasonably safe to close this so I'll do that. We _could_ ban that broken version of setuptools in our build requirements configuration in `pyproject.toml` but that's most likely useless as the build environment will contain the newest setuptools anyway.

**Closed by ichard26** 2021-01-18 01:36 UTC
Labels: bug, installation
