### ISSUE TITLE
issue with black 

### ISSUE THREAD

**Issue by Ayesha279** [psf/black#2387] opened 2021-07-20 19:33 UTC
**Describe the bug**
error when running per-commit on file black

error: cannot format /home/ayesha/Desktop/workSpace/benchmark-comparison/ev/lib/python3.9/site-packages/pandas/io/pickle.py: INTERNAL ERROR: **Black produced code that is not equivalent to the source**.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_2pyt3r5d.log
**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- Version: 
- OS and Python version: 

**Does this bug also happen on main?**

**Additional context**

**Comment by ichard26** [comment] 2021-07-20 19:38
Hey thanks for submitting a bug report! Unfortunately this is completely unactionable for us because there's no reproduction information provided, no environment details, no reproduction steps, or even the log file which exists in cases like this to aid debugging! I'm sorry Black failed for you, but there's nothing we can do as it stands. The least we'll need is the contents of the log file (or alternatively the code Black failed to format).

Thanks!

**Comment by ichard26** [comment] 2021-07-20 19:41
P.S. to anyone following by email, my (now deleted) previous message was technically wrong, the filepath does actually provide enough information to at least attempt reproduction.

**Comment by Ayesha279** [comment] 2021-07-20 19:58
there is the log.. do you want me to sent this to you as a file?

--- src
+++ dst
@@ -296,49 +296,10 @@
               body=
                 Expr(
                   value=
                     Call(
                       args=
-                        Call(
-                          args=
-                            Name(
-                              ctx=
-                                Load(
-                                )  # /Load
-                              id=
-                                'obj',  # str
-                            )  # /Name
-                          func=
-                            Attribute(
-                              attr=
-                                'dumps',  # str
-                              ctx=
-                                Load(
-                                )  # /Load
-                              value=
-                                Name(
-                                  ctx=
-                                    Load(
-                                    )  # /Load
-                                  id=
-                                    'pickle',  # str
-                                )  # /Name
-                            )  # /Attribute
-                          keywords=
-                            keyword(
-                              arg=
-                                'protocol',  # str
-                              value=
-                                Name(
-                                  ctx=
-                                    Load(
-                                    )  # /Load
-                                  id=
-                                    'protocol',  # str
-                                )  # /Name
-                            )  # /keyword
-                        )  # /Call
                       func=
                         Attribute(
                           attr=
                             'write',  # str
                           ctx=

**Comment by ichard26** [comment] 2021-07-20 20:04
> do you want me to sent this to you as a file?

No, posting everything via GitHub via text is good enough (unless GitHub doesn't let you for some reason). Thank you for sharing the logfile! Unfortunately it doesn't actually look as useful as I would have hoped. The version and configuration of Black you're running would also be useful (but ultimately it's hard to reproduce without the source code that failed).

**Comment by felix-hilden** [comment] 2021-07-20 20:07
The referenced file *is* from a popular library though: [here](https://github.com/pandas-dev/pandas/blob/master/pandas/io/pickle.py), but at least the current version has no problems when trialed on the playground.

**Comment by ichard26** [comment] 2021-07-20 20:10
Yeah, I tried a few different revisions of that file and I wasn't able to reproduce so that's why I'm asking for either the library version (`python -m pip show pandas`) or the exact source code (it is in a virtual environment so not the easiest thing to get). I'm also wondering whether there's a specific configuration that's causing Black to misbehave.

**Comment by felix-hilden** [comment] 2021-07-20 20:11
Oh my bad, I didn't read your first message thoroughly enough!

**Comment by JelleZijlstra** [comment] 2021-07-20 20:28
From the source file I suspect it's triggering on this line: https://github.com/pandas-dev/pandas/blob/master/pandas/io/pickle.py#L106. It has a `# type: ignore` and another comment next to it; I vaguely remember we may have had bugs in the past that would have caused the code to get eaten. Perhaps you're using an old version of Black.

**Comment by Ayesha279** [comment] 2021-07-20 20:31
i think i figured it out, my virtual environment it called ev, i need to change it to .venv

**Comment by JelleZijlstra** [comment] 2021-07-20 20:35
@Ayesha279 that might explain why Black is formatting the file, but it's still a bug that Black crashes on that file. 

What version of Black are you running?

**Comment by Ayesha279** [comment] 2021-07-20 20:42
21.0.1 i think

**Comment by ambv** [comment] 2021-07-21 09:11
21.0.1 is not a version we released. Please run `black --version` and paste here what it tells you.

**Comment by ichard26** [comment] 2021-08-24 21:27
Closing since I can reproduce this issue on the file Felix linked but only Black as new as 19.10b0. A quick bisect points to PR https://github.com/psf/black/pull/1315 as the resolving commit. 20.8b1 should be the oldest released version available that has this fix (well technically 20.8b0 has it too but no one should use this version). Thanks for the report @Ayesha279 but there's nothing actionable here as far as I can tell.

**Closed by ichard26** 2021-08-24 21:27 UTC
Labels: T: bug, C: invalid code, F: comments, S: needs repro, S: awaiting response, R: outdated
