### ISSUE TITLE
Short code generates INTERNAL ERROR on second pass

### ISSUE THREAD

**Issue by ochtersk** [psf/black#2102] opened 2021-04-12 15:43 UTC
**Describe the bug**  code generates INTERNAL ERROR: Black produced different code on the second pass of the formatter.

**To Reproduce** Steps to reproduce the behavior:

Enter this code:
class SciSigFig:
    def dump(self):
        numstr = str(self)
        return '  xxxnumber:%s\n str(number):%s\n      sfcode:%s\n        sfid:%s\n     sfcount:%s\n        uexp:%s\n    notation:%s' % \
            (self.number,numstr, self.sfcode,self.sfid,self.sfcount,self.uexp,self.notation)

into Black playground https://black.vercel.app/ (accessed 11:40 EDT 04-12-2021)

** Error message:**
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_6fjvz6ci.log

Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,6 +1,15 @@
 class SciSigFig:
     def dump(self):
         numstr = str(self)
-        return '  xxxnumber:%s\n str(number):%s\n      sfcode:%s\n        sfid:%s\n     sfcount:%s\n        uexp:%s\n    notation:%s' % \
-            (self.number,numstr, self.sfcode,self.sfid,self.sfcount,self.uexp,self.notation)
-
+        return (
+            "  xxxnumber:%s\n str(number):%s\n      sfcode:%s\n        sfid:%s\n     sfcount:%s\n        uexp:%s\n    notation:%s"
+            % (
+                self.number,
+                numstr,
+                self.sfcode,
+                self.sfid,
+                self.sfcount,
+                self.uexp,
+                self.notation,
+            )
+        )
--- first pass
+++ second pass
@@ -1,15 +1,12 @@
 class SciSigFig:
     def dump(self):
         numstr = str(self)
-        return (
-            "  xxxnumber:%s\n str(number):%s\n      sfcode:%s\n        sfid:%s\n     sfcount:%s\n        uexp:%s\n    notation:%s"
-            % (
-                self.number,
-                numstr,
-                self.sfcode,
-                self.sfid,
-                self.sfcount,
-                self.uexp,
-                self.notation,
-            )
+        return "  xxxnumber:%s\n str(number):%s\n      sfcode:%s\n        sfid:%s\n     sfcount:%s\n        uexp:%s\n    notation:%s" % (
+            self.number,
+            numstr,
+            self.sfcode,
+            self.sfid,
+            self.sfcount,
+            self.uexp,
+            self.notation,
         )

**Expected behavior** A clear and concise description of what you expected to happen.

Expected reformatted code

**Environment (please complete the following information):**

- Version: [e.g. master]
- OS and Python version: [e.g. Linux/Python 3.7.4rc1]

**Does this bug also happen on master?** To answer this, you have two options:

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.

Yes, it occurs on the master

**Comment by ichard26** [comment] 2021-04-25 20:31
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:31 UTC
Labels: bug, unstable formatting
