### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by lukehodges** [psf/black#2499] opened 2021-09-17 19:54 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- Version: 
- OS and Python version: 

**Does this bug also happen on main?**

**Additional context**

simply running `black run.py` on my file brings up this error
```python
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\resume\quantum-bot\venv\Scripts\black.exe\__main__.py", line 7, in <module>
  File "d:\resume\quantum-bot\venv\lib\site-packages\black\__init__.py", line 1283, in patched_main
    main()
  File "d:\resume\quantum-bot\venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "d:\resume\quantum-bot\venv\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "d:\resume\quantum-bot\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\resume\quantum-bot\venv\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "d:\resume\quantum-bot\venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\resume\quantum-bot\venv\lib\site-packages\black\__init__.py", line 433, in main
    sources = get_sources(
  File "d:\resume\quantum-bot\venv\lib\site-packages\black\__init__.py", line 501, in get_sources
    gitignore = get_gitignore(root)
  File "d:\resume\quantum-bot\venv\lib\site-packages\black\files.py", line 125, in get_gitignore
    lines = gf.readlines()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
```

**Comment by JelleZijlstra** [comment] 2021-09-17 19:56
Looks like you have a gitignore file that contains invalid UTF-8.

**Comment by lukehodges** [comment] 2021-09-17 19:57
its just venv

**Comment by lukehodges** [comment] 2021-09-17 19:57
and the error still hapens

**Comment by lukehodges** [comment] 2021-12-02 09:27
Anyone got some ideas or should i just close this

**Comment by clavedeluna** [comment] 2022-10-22 17:27
> run.py

@lukehodges what are the contents of `run.py`?

**Comment by lukehodges** [comment] 2022-10-22 20:45
no clue this was from ages ago

**Comment by clavedeluna** [comment] 2022-10-23 11:42
@lukehodges  I'd say this is worth closing then?

**Comment by JelleZijlstra** [comment] 2022-10-23 14:20
Closing as there's no reproduction steps. If anyone runs into something similar, please open a new issue with full reproduction steps.

**Closed by JelleZijlstra** 2022-10-23 14:20 UTC
Labels: T: bug, C: crash, S: needs repro, C: file collection

**Comment by ArriW** [comment] 2022-12-14 23:35
@lukehodges 
I had the same error with using black on a directory with a `.gitignore` file that had `*/venv/*`  removing this resolved the issue.

**Comment by da1910** [comment] 2023-05-10 09:05
I had the same issue, my .gitignore file was edited by a windows app and was saved in "UTF-16 LE with BOM", converting it to UTF-8 worked like a charm.

The error is somewhat misleading however, as I (and I suspect most users) would look for the python file we tried to format, not the .gitignore file. Could we catch this error and report that we're trying to parse the .gitgnore file, rather than python source?
