### ISSUE TITLE
Crash possibly due to mismatched indents after `# fmt: off`?

### ISSUE THREAD

**Issue by Zac-HD** [psf/black#3702] opened 2023-05-24 19:52 UTC
With current latest `black, 23.3.0 (compiled: yes)`:
```python
import black

code = """
if True:
  # fmt: off
  pass
  # fmt: on
  pass
"""
black.format_str(code, mode=black.FileMode())
```
```python-traceback
Traceback (most recent call last):
  File "repro.py", line 10, in <module>
    black.format_str(code, mode=black.FileMode())
  File "src/black/__init__.py", line 1084, in format_str
  File "src/black/__init__.py", line 1089, in _format_str_once
  File "src/black/parsing.py", line 127, in lib2to3_parse
black.parsing.InvalidInput: Cannot parse: 5:0:     pass
```

This passes if you use four-space indentation.  Possibly related to #3458?

**Comment by JelleZijlstra** [comment] 2023-05-26 05:17
Duplicate of #3505

**Closed by JelleZijlstra** 2023-05-26 05:17 UTC
Labels: T: bug
