### ISSUE TITLE
Reformat on comment ignore # fmt: off & # fmt: on

### ISSUE THREAD

**Issue by xinbinhuang** [psf/black#1611] opened 2020-08-18 23:01 UTC
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

Before formatting:
```python
class A:
    ........

    minutes_available_per_week = models.PositiveIntegerField(
        # fmt: off
        default=settings.TIME_ESTIMATES["defaults"]["minutes_available_per_week"]  # type: ignore
        # fmt: on
    )

```

After formatting:
```python
    minutes_available_per_week = models.PositiveIntegerField(
        # fmt: off
        default=settings.TIME_ESTIMATES["defaults"]["minutes_available_per_week"]
        # type: ignore
        # fmt: on
    )
```

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: [e.g. master]: 19.10b0
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] Linux (WSL2): 3.7

**Does this bug also happen on master?** To answer this, you have two options:

Yes

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python -m unittest`; and
   - run `black` like you did last time.

**Additional context** Add any other context about the problem here.

**Comment by JelleZijlstra** [comment] 2021-05-30 03:39
Duplicate of #1245

**Closed by JelleZijlstra** 2021-05-30 03:39 UTC
Labels: F: comments, F: fmtoff, T: bug
