### ISSUE TITLE
Extra single quote to open docstring results in unstable formatting

### ISSUE THREAD

**Issue by sadielbartholomew** [psf/black#1926] opened 2021-01-13 23:59 UTC
**Describe the bug**

Docstrings beginning with four (or five) single quotation marks (assuming an extra quote or two has been introduced by the writer by mistake i.e. triple quote to open the string, then one or two excess ones) and having more than one non-empty line, will lead to an unreliable result from a `black` run and hence raise an error indicating there was a different result on second pass (see below).

I have determined this after encountering the error whilst formatting a codebase I work with `black` via and then investigating the cause of the instability. It seems that the docstring must have the precise form below, or the equivalent with five rather than four single quotes to open, which can serve as a **minimal example**:

```python
def some_function(self):
    ''''<text here>

    <text here, since without another non-empty line black is stable>

    '''
    <... function logic here ...>
```

Notably, the error indicating instability is not raised in the similar cases of:

* there being four single leading quotes but only a *one-line docstring*;
* there being four leading *double* quotes;
* there being four *closing* quotes (which would lead to invalid Python anyway in all but contrived cases);

as can be seen via the demo file I have copied in below. 

**To Reproduce**

1. Take this file, where `func_1` shows the bug and `func_{2-4}` give similar cases where there is no bug: 
    ```python
    def func_1(self):
        ''''This docstring has an extra single quote, oops.

        Having another non-empty line is vital to the instability somehow!

        '''
        pass  # This is *unstable* with black, raising BLK999 (also with 5 quotes)


    def func_2():
        ''''Another docstring.

        '''
        pass  # But this stable with black


    def func_3(self):
        '''' Yet another docstring. '''
        pass  # This is stable with black, too


    def func_4(self):
        """"Yet another docstring.

        Due to use of double quotes, this does not cause black instability...

        """
        pass  # This is also stable with black

    ```
2. Run vanilla `black` on it.

3. See the error `BLK999 Unexpected exception: INTERNAL ERROR: Black produced different code on the second pass of the formatter.`, though by removing the surplus single quote in `func_1` note that it represents the only case of the four which causes the instability.

**Expected behavior**

I expect `black` to always provide the same result after formatting i.e. be stable.

**Environment (please complete the following information):**

- Version:
    ```console
    $ black --version
    black, version 20.8b1
    ```
- OS and Python version: Linux Mint 19.2, Python 3.8.5 via Anaconda

**Does this bug also happen on master?**

Yes, I have tested it on master locally and the same error is raised, so the bug is also present there.

**Additional context**

n/a (all covered above).

**Comment by ichard26** [comment] 2021-04-25 20:02
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:02 UTC
Labels: bug, duplicate, unstable formatting

**Comment by sadielbartholomew** [comment] 2021-05-06 22:00
Thanks @ichard26, it's great that it has been fixed! I'll update to the new version :slightly_smiling_face:
