### ISSUE TITLE
Black breaks lines in type hints that use '|' operator.

### ISSUE THREAD

**Issue by dusktreader** [psf/black#3816] opened 2023-07-27 06:14 UTC
**Describe the style change**

Currently, black will break a long line that uses a `|` character for type hints after the `|` character resulting is very unsightly code.

If it is possible to break the line after the type hints to stay within the line limit, black should leave the type hints on a single line.

**Examples in the current _Black_ style**

```python
def foo(
    bar: Baz
    | None = Baz(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor...",
        language=Latin,
    ),
):
    pass
```

**Desired style**

```python
def foo(
    bar: Baz | None = Baz(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor...",
        language=Latin,
    ),
):
    pass
```

**Additional context**

This behavior causes flake8 to object over w503.

**Comment by JelleZijlstra** [comment] 2023-07-27 09:18
Duplicate of #2316

**Closed by JelleZijlstra** 2023-07-27 09:18 UTC
Labels: T: style
