### ISSUE TITLE
Error when using "fmt: off"

### ISSUE THREAD

**Issue by kwsp** [psf/black#3028] opened 2022-04-22 21:33 UTC
Tested on the latest version of `black` from git.

**To Reproduce**

For example, take this code:

```python
import cv2


frame = cv2.imread("test.jpg")

if True:
    # fmt: off
    cv2.putText(frame, f"# faces: {n}", (10, 30), cv2.FONT_HERSHEY_DUPLEX, 1, (255, 0, 0), 1, cv2.LINE_AA)

print("hello")
```

And run it with these arguments:

```sh
$ black file.py --target-version py39
```

The resulting error is:

> error: cannot format black_bug.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/xy/7rx63bwx6c9_0n5d50q5j5xh0000gn/T/blk_tesqobdj.log

**Expected behavior**

Shouldn't error. 

**Environment**

- Black's version: `black 22.3.1.dev25+g8ed3e3d (compiled: no)`
- OS and Python version: `Darwin/CPython 3.9.12`

**Additional context**

<details>
<summary>log</summary>

```
--- src
+++ dst
@@ -185,37 +185,37 @@
                     )  # /Name
                 )  # /Attribute
               keywords=
             )  # /Call
         )  # /Expr
+        Expr(
+          value=
+            Call(
+              args=
+                Constant(
+                  kind=
+                    None,  # NoneType
+                  value=
+                    'hello',  # str
+                )  # /Constant
+              func=
+                Name(
+                  ctx=
+                    Load(
+                    )  # /Load
+                  id=
+                    'print',  # str
+                )  # /Name
+              keywords=
+            )  # /Call
+        )  # /Expr
       orelse=
       test=
         Constant(
           kind=
             None,  # NoneType
           value=
             True,  # bool
         )  # /Constant
     )  # /If
-    Expr(
-      value=
-        Call(
-          args=
-            Constant(
-              kind=
-                None,  # NoneType
-              value=
-                'hello',  # str
-            )  # /Constant
-          func=
-            Name(
-              ctx=
-                Load(
-                )  # /Load
-              id=
-                'print',  # str
-            )  # /Name
-          keywords=
-        )  # /Call
-    )  # /Expr
   type_ignores=
 )  # /Module
\ No newline at end of file
```

</details>

**Comment by JelleZijlstra** [comment] 2022-04-22 21:37
Duplicate of #569 (or one of the others in https://github.com/psf/black/labels/F%3A%20fmtoff)

**Closed by JelleZijlstra** 2022-04-22 21:37 UTC
Labels: T: bug, F: fmtoff
