### ISSUE TITLE
Failure to parse string templates with similar quotes

### ISSUE THREAD

**Issue by andrewvaughan** [psf/black#4271] opened 2024-03-10 20:01 UTC
**Describe the bug**

~When using a ternary statement within a string template, Black fails to parse the string if the quotes used within the template are the same as the template string.~

Edit: Any template string that contains quotes of the same style as the parent template will fail.

**To Reproduce**

This fails:

```py
cmd.append(f"--{"no-" if not do_continue else ""}continue")
```

With the following error (per the playground):

```
Cannot parse: 1:17: cmd.append(f"--{"no-" if not do_continue else ""}continue")
````

But this will pass:

```py
cmd.append(f"--{'no-' if not do_continue else ''}continue")
```

_EDIT:_

These also all fail (but are correctable by switching quote types), showing it has to do with template string parsing, not ternary:

```py
cmd.append(f"--ffmpeg-location {pipes.quote(cfg["ffmpeg"])}")
cmd.append(f"--example {some_dict["key"]}")
```

These are all valid Python, however.

**Expected behavior**

Black should enforce quotes consistently, including within template strings (or, at minimum, not fail at parsing and rather throw a formatting error). Per my configurations, this should be the proper format:

```py
cmd.append(f"--{"no-" if not do_continue else ""}continue")
```

But I am forced to use single-quotes to make Black function.

_EDIT:_

"Working" examples from addition:

```py
cmd.append(f"--ffmpeg-location {pipes.quote(cfg['ffmpeg'])}")
cmd.append(f"--example {some_dict['key']}")
```

These should, at minimum, throw a validation error and not fail to parse, if enforcing different quote-styles is the intent (although, I would argue switching quote-styles is detrimental).

**Environment**

- Black's version: Current Black playground (Stable: [24.1.0](https://pypi.org/project/black/24.1.0/) | Main: [@ed770b](https://github.com/psf/black/commit/ed770b))
- OS and Python version: N/A

**Additional context**

N/A

**Comment by andrewvaughan** [comment] 2024-03-10 20:12
I have also tested that nested template strings work, but only if all nested templates have opposite quote styles:

```py
cmd.append(f"--add-header {pipes.quote(f'Referer:{parsed.scheme}://{parsed.netloc}/')}")
```

I was somewhat expecting this to be an "unsolvable" situation, but it did parse correctly when all internal quotes were single-quotes (`'`) if the parent template was double-quotes (`"`).

**Comment by JelleZijlstra** [comment] 2024-03-10 20:32
Duplicate of #3746

**Closed by JelleZijlstra** 2024-03-10 20:32 UTC
Labels: T: bug

**Comment by andrewvaughan** [comment] 2024-03-10 20:35
> Duplicate of #3746

Ah, thanks. Did a cursory search but didn't see it - I'm still getting into the habit of checking pins and not going straight to search.

**Comment by JelleZijlstra** [comment] 2024-03-10 20:37
And just to explain the behavior you're seeing: Black's parser currently treats f-strings just like normal strings, treating whatever is inside as just a string literal. Your `cmd.append(f"--add-header {pipes.quote(f'User-Agent:{browser['user-agent']}')}")` is accepted because Black just ignores whatever happens until it sees the closing double quote.
