### ISSUE TITLE
 INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by jaimemarijke** [psf/black#950] opened 2019-07-29 23:42 UTC
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Mac OS 10.14
Python version: 3.6.5
*Black* version: 19.3b0
Does also happen on master:

To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.

Just dropping by here because it told me to: "error: cannot format /Users/jaime/osmo/cosmobot-deep-learning/cosmobot_deep_learning/preprocess_image_test.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/ambv/black/issues.  This diff might be helpful: /var/folders/5g/6ydq2ctj7px9fkq309znm_fr0000gn/T/blk_d_si_ol7.log"

[blk_d_si_ol7.log](https://github.com/psf/black/files/3444586/blk_d_si_ol7.log)

I don't actually care about the issue so if this info isn't helpful please feel free to close.

**Comment by jaimemarijke** [comment] 2019-07-30 00:08
Actually, a seemingly related piece of information. My code looked something like this:

```
class TestMyFunctionA:
    # fmt: off
    @pytest.mark.parametrize(
        "some_parameter_a, some_parameter_b",
        [
            (
                "1",
                "2",
            ),
           (
                "3",
                "4",
            ),
        ],
    )
    # fmt: on
    def test_my_function(self, some_parameter_a, some_parameter_b):
        <some tests>
        ...

class TestMyFunctionB:
    def test_my_func(self):
        <some tests>
```

This caused black to break. When I moved the location of the `# fmt: off` block as below, without changing anything else, black stopped breaking.

```
class TestMyFunctionA:
    # fmt: off
    @pytest.mark.parametrize(
        "some_parameter_a, some_parameter_b",
        [
            # fmt: off
            (
                "1",
                "2",
            ),
           (
                "3",
                "4",
            ),
            # fmt: on
        ],
    )
    def test_my_func(self, some_parameter_a, some_parameter_b):
        <some tests>
        ...

class TestMyFunctionB:
    def test_my_func(self):
        <some tests>
        ...
```

**Comment by zsol** [comment] 2019-07-30 19:38
Thanks for reporting! Looks like this is a duplicate of #560

**Closed by zsol** 2019-07-30 19:38 UTC
Labels: bug, invalid code
