### ISSUE TITLE
Black not respecting fluent interfaces with parenthesis

### ISSUE THREAD

**Issue by risoms** [psf/black#2808] opened 2022-01-25 18:41 UTC
**Describe the bug**

Black doesn't seem to respect fluent interfaces with parenthesis if the object isn't callable

**To Reproduce**
For example, when using a pytest mocker.

```py
import pytest
import Session
def test_session(mocker):
    session = mocker.patch("Session")
    a = (
        session.query
            .return_value
            .filter
            .return_value
            .filter
            .return_value
            .filter
            .return_value
            .distinct
            .return_value
            .order_by
            .return_value
            .all
            .return_value
    )
```

This is converted to:

```py
import pytest
import Session
def test_session(mocker):
    session = mocker.patch("Session")
    a = session.query.return_value.filter.return_value.filter.return_value.filter.return_value.distinct.return_value.order_by.return_value.all.return_value
```

Which causes a line-length error.

**Expected behavior**

Handling similar to this

```py
import pytest
import Session
def test_session(mocker):
    session = mocker.patch("Session")
    a = (
        session.query
            .return_value
            .filter
            .return_value
            .filter
            .return_value
            .filter
            .return_value
            .distinct
            .return_value
            .order_by
            .return_value
            .all
            .return_value
    )
```

**Environment**

- Black's version: main
- OS and Python version: MacOS 2.0.1 (21A559)/Python 3.7.6

**Additional context**

**Comment by felix-hilden** [comment] 2022-01-31 21:11
Thanks for submitting this! It's likely related to #571, but let's see. In the meantime, here's a [playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AKiAJddAD2IimZxl1N_WlOfrjrgMB1TsCCoeSEI9tRpl1TYQtbjl1b89r6G1MQX7c-S_k1wcY1IqNGQ7MfcEQAkT2naZJCELqpHJ_pdTdGXgjjxTsvxIlvC1n_CwX8KLkMqwBcYGvJ72M_dQJJvi2QzxUotaO9gKfymDgly4ubx6ZZZGsytdSKVid3cUfWWGUB2troA3sl5u5_A1AAAAIQzJnaS2De3AAGzAaMFAAC26H47scRn-wIAAAAABFla) with some variations on this.

**Comment by felix-hilden** [comment] 2022-01-31 22:00
Ah, it seems to be a duplicate of #510. Let's continue the discussion there.

**Closed by felix-hilden** 2022-01-31 22:00 UTC
Labels: T: bug, F: linebreak
