### ISSUE TITLE
Issue: file "/urs/lib/python3.7/ast.py", line 35, in parse

### ISSUE THREAD

**Issue by davidhuynh1996** [psf/black#2340] opened 2021-06-17 14:23 UTC
#!/usr/bin/env python
import urllib
import json
import os
import RPi.GPIO as GPIO
import Adafruit_DHT
 
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM) 
GPIO.setup(16, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)
GPIO.setup(25, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
pwm = GPIO.PWM(18, 500)
pwm.start(100)
GPIO.setup(13, GPIO.OUT)
pwm1 = GPIO.PWM(13, 50)
from flask import Flask
from flask import request
from flask import make_response
# Flask app should start in global layout
app = Flask(__name__)
@app.route('/webhook', methods=['POST'])
def webhook():
 req = request.get_json(silent=True, force=True)
 print("Request:")
 print(json.dumps(req, indent=4))
 res = makeWebhookResult(req)
 res = json.dumps(res, indent=4)
 print(res)
 #t = str(res["speech"])
r = make_response(res)
#t= str(r.decode('utf-8'))
print("*")
print(r)
 #print ("*")
r.headers['Content-Type'] = 'application/json'
return r
def makeWebhookResult(req):
 #if req.get("queryResult").get("action") != "on-off":
 # return {}
 #if req.get("queryResult").get("action") != "on-off.condition":
 # return {}
 sp1=""
 sp2=""
 sp3=""
 sp4=""
 sp5=""
 sp6=""
 sp7=""
 sp8=""
 sp9=""
 sp10=""
 sp11=""
 sp12=""
 sp13=""
 sp14=""
 result = req.get("queryResult")
 parameters = result.get("parameters")
 val = parameters.get("on-off")
 val2 = parameters.get("led")
 val3 = parameters.get("status")
 val4 = parameters.get("percentage")
 val5 = parameters.get("status-door")
 val6 = parameters.get("temperature")
 val7 = parameters.get("unit-temperature")
 val8 = parameters.get("humidity")
 val9 = parameters.get("room")
 val10 = parameters.get("hot-cold")
if req.get("queryResult").get("action") == "on-off":
if len(val)==len(val2):
for i in range (0, len(val)):
for j in range (0, len(val2)):
if i == j:
if val[i] =="on":
if val2[j] == "all":
 GPIO.output(16, GPIO.HIGH)
 GPIO.output(23, GPIO.HIGH)
 GPIO.output(24, GPIO.HIGH)
 GPIO.output(25, GPIO.HIGH)
 sp11 = "turn on all"
 if val2[j] == "led 1":
 GPIO.output(16, GPIO.HIGH)
 sp1 = val[i] + " " + val2[j]
 if val2[j] == "led 2":
 GPIO.output(23, GPIO.HIGH)
 sp2 = val[i] + " " + val2[j]
 if val2[j] == "led 3":
 GPIO.output(24, GPIO.HIGH)
 sp3 = val[i] + " " + val2[j]
 if val2[j] == "fan":
 GPIO.output(25, GPIO.HIGH)
 sp4 = val[i] + " " + val2[j]
 if val[i] =="off":
 if val2[j] == "all":
 GPIO.output(16, GPIO.LOW)
 GPIO.output(23, GPIO.LOW)
 GPIO.output(24, GPIO.LOW)
 GPIO.output(25, GPIO.LOW)
 sp12 = "turn off all"
 if val2[j] == "led 1":
 GPIO.output(16, GPIO.LOW)
 sp5 = val[i] + " " + val2[j]
 if val2[j] == "led 2":
 GPIO.output(23, GPIO.LOW)
 sp6 = val[i] + " " + val2[j]
 if val2[j] == "led 3":
GPIO.output(24, GPIO.LOW)
 sp7 = val[i] + " " + val2[j]
 if val2[j] == "fan":
 GPIO.output(25, GPIO.LOW)
 sp8 = val[i] + " " + val2[j]
 else:
 
 for i in range (0,len(val)):
 for j in range (0, len(val2)):
 if val[i] =="on":
 if val2[j] == "led 1":
 GPIO.output(16, GPIO.HIGH)
 sp1 = val[i] + " " + val2[j]
 
 if val2[j] == "led 2":
 GPIO.output(23, GPIO.HIGH)
 sp2 = val[i] + " " + val2[j]
 if val2[j] == "led 3":
 GPIO.output(24, GPIO.HIGH)
 sp3 = val[i] + " " + val2[j]
 if val2[j] == "fan":
 GPIO.output(25, GPIO.HIGH)
 sp4 = val[i] + " " + val2[j]
 if val[i] =="off":
 if val2[j] == "led 1":
 GPIO.output(16, GPIO.LOW)
 sp5 = val[i] + " " + val2[j]
 if val2[j] == "led 2":
 GPIO.output(23, GPIO.LOW)
 sp6 = val[i] + " " + val2[j]
 if val2[j] == "led 3":
 GPIO.output(24, GPIO.LOW)
 sp7 = val[i] + " " + val2[j]
 if val2[j] == "fan":
 GPIO.output(25, GPIO.LOW)
 sp8 = val[i] + " " + val2[j] 
 speech = "OKK, " + sp1 + " " + sp2 + " " + sp3 + " " + sp4 + " "
+ sp5 + " " + sp6 + " " + sp7 + " " + sp8 + " " + sp11 + " " + sp12
 elif req.get("queryResult").get("action") == "on-off:condition":
 if val3 =="light":
 if val9 == "room 1":
 GPIO.output(16, GPIO.HIGH)
 if val9 == "room 2":
 GPIO.output(23, GPIO.HIGH)
 if val9 == "room 3":
 GPIO.output(24, GPIO.HIGH)
 #if val2 == "room 4":
 #GPIO.output(25, GPIO.HIGH) 
 if val3 =="dark":
 if val9 == "room 1":
 GPIO.output(16, GPIO.LOW)
 if val9 == "room 2":
 GPIO.output(23, GPIO.LOW)
 if val9 == "room 3":
 GPIO.output(24, GPIO.LOW)
 #if val2 == "room 4":
 #GPIO.output(25, GPIO.LOW)
 speech = "OKK, " + val3 + " " + val9
elif req.get("queryResult").get("action") == "action.dimmer":
 a=""
 for i in val4:
 if i =="%":
 break
 a=a+i
 #print a
 dc = 100.0 - float(a)
 pwm.ChangeDutyCycle(dc)
 speech = "OK, dimmer " + a + "%"
 elif req.get("queryResult").get("action") == "action.door":
 if val5 == "open":
 pwm1.start(5)
 if val5 == "close":
 pwm1.start(10)
 speech = "OK, " + val5 + " door"
 elif req.get("queryResult").get("action") == "action.temperature":
 if val6 == "temperature":
 if val7 == "C":
 humidity, temperature = Adafruit_DHT.read_retry(11, 27)
 sp9 = "temperature is " + str(temperature) + " C"
 if val7 == "F":
 humidity, temperature = Adafruit_DHT.read_retry(11, 27)
 temperature1 = temperature*1.8 + 32
 sp10 = "temperature is " + str(temperature1) + " F"
 speech = sp9 + " " + sp10
 elif req.get("queryResult").get("action") == "action.humidity":
 if val8 == "humidity":
 humidity, temperature = Adafruit_DHT.read_retry(11, 27)
 speech = "the humidity is " + str(humidity) + "%"
 elif req.get("queryResult").get("action") == "action.dht11":
 if val6 == "temperature" and val8 == "humidity":
 humidity, temperature = Adafruit_DHT.read_retry(11, 27)
 speech = " The temperature is " + str(temperature) + " C and the 
humidity is " + str(humidity) + "%"
 elif req.get("queryResult").get("action") == "action.fan":
 if val10 == "hot":
 GPIO.output(25, GPIO.HIGH)
 sp13 = "i turn on fan"
 if val10 == "cold":
 GPIO.output(25, GPIO.LOW)
 sp14 = "i turn off fan"
 speech = "OK, " + sp13 + " " + sp14
 
 
 
 else:
 return {}
 print("Response:")
 print(speech)
 return {
 "fulfillmentText": speech,
 #"fulfillmentMessages": speech ,
 #"data": {},
 #"contextOut": [],
 #"source": "BankRates"
 }
if __name__ == '__main__':
 port = int(os.getenv('PORT', 5000))
 print("Starting app on port %d" %(port))
 app.run(debug=True, port=port, host='0.0.0.0')
//
This is my code. I create a webhook to connect with dialogflow.
And the Python show this:
     ^
IndentationError: expected an indented block
>>> %Run project1.py
Traceback (most recent call last):
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/home/pi/Desktop/project1.py", line 72
    if len(val)==len(val2):
     ^
IndentationError: expected an indented block
//
I don't know how to fix, please help me!!

**Comment by felix-hilden** [comment] 2021-06-17 14:25
Hi, thanks for submitting an issue. Please make sure it is [formatted properly](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) though! Currently, it's very hard to read it.

**Comment by davidhuynh1996** [comment] 2021-06-17 14:28
Because I don't know how to explain so I write down my full code.
Please help me!

Vào 21:26, T.5, 17 Th6, 2021 Felix Hildén ***@***.***> đã
viết:

**Comment by felix-hilden** [comment] 2021-06-17 14:39
It looks like this is not an error with Black, so I'll close this for the time being. The error suggests that your code is not valid Python, so we can't help you here. If you'd like, you can produce a [playground](https://black.vercel.app/?version=main) environment that reproduces your issue with Black so we can see it more clearly. Respond here if you do!

**Closed by felix-hilden** 2021-06-17 14:39 UTC

**Comment by JelleZijlstra** [comment] 2021-06-17 14:44
I don't think this is in any way related to Black, but the problem seems to be that you don't indent your code after an `if` line. Always indent the next line after a line that ends with a colon, like `if` or `def`.

I'd also recommend using more than one space for indentation, since one space is hard to read. An autoformatter like Black can help make your code more readable.
