### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by szeitlin** [psf/black#2868] opened 2022-02-05 00:39 UTC
Confirmed that this happens on the latest version and in the playground. 

**Describe the bug**

I don't know. I can't understand what your logs are saying. 

**To Reproduce**

Run black on my file. 

For example, take this code:

I can't post this on a public repo, but I'll email it to you privately if someone is going to take a look at it. 

- Black's version: 22.1.0
- OS and Python version: MacOS version 11.6.3, python version 3.9.1

**Comment by JTmain** [comment] 2022-11-19 16:25
I'd like to take a look at this if you're happy to send it to me?

**Comment by JelleZijlstra** [comment] 2022-11-20 04:42
Sorry this didn't get a response earlier!

If you want to, you can email me a copy of the file (my email is on my GitHub profile). However, I'd recommend that you try to minimize the example yourself (this doesn't need any special knowledge: just delete half the file, see if Black still crashes, repeat). If you can limit your code to a small sample that still triggers a crash, it's easier to figure out what the issue is.

I'm going to close this issue as currently there's nothing actionable.

**Closed by JelleZijlstra** 2022-11-20 04:42 UTC
Labels: T: bug, C: invalid code
