### ISSUE TITLE
Line too long: string literal doesn't get split

### ISSUE THREAD

**Issue by crhf** [psf/black#4320] opened 2024-04-22 03:13 UTC
**Describe the bug**

A long string literal doesn't get split.

**To Reproduce**

For example, take this code:

```python
x = "aaaaaaaaaa bbbbbbbb cccccccccccc dddddddddddddd eeeeeeeeeeee fffffffffffffffff ggggggggggggggg hhhhhhhhhh"
```

And run it with these arguments:

```sh
$ black file.py
```

The file is left unchanged.

**Expected behavior**

The string gets split into something like:

```python
x = (
    "aaa ..   . fff"
    "fff ... gggggggggg.."
)
```

**Environment**

- Black's version: `24.4.0 (compiled: yes)`
- OS and Python version: `WSL ubuntu 22.04, python 3.11.7`

**Comment by hauntsaninja** [comment] 2024-04-22 03:19
Duplicate of https://github.com/psf/black/issues/4230

**Closed by hauntsaninja** 2024-04-22 03:19 UTC
Labels: T: bug
