### ISSUE TITLE
Comments within fmt: off/on are formatted

### ISSUE THREAD

**Issue by njalerikson** [psf/black#2110] opened 2021-04-15 17:31 UTC
**Describe the bug** Comments occurring directly before `# fmt: on` (but still within the `# fmt: off` block) are formatted.

**To Reproduce** Steps to reproduce the behavior:

1. Take this:
```python
# fmt: off
#poorly formatted comment
a=1
#another poorly formatted comment
#multiple lines are impacted
# fmt: on
#comment to correct
b=2
```
2. Run _Black_ on it.
3. Result versus Expected:
<table>
<tr>
<th>Result</th>
<th>Expected</th>
</tr>
<tr>
<td>

```python
# fmt: off
#poorly formatted comment
a=1
# another poorly formatted comment
# multiple lines are impacted
# fmt: on
# comment to correct
b = 2
```

</td>
<td>

```python
# fmt: off
#poorly formatted comment
a=1
#another poorly formatted comment
#multiple lines are impacted
# fmt: on
# comment to correct
b = 2
```

</td>
</tr>
</table>

**Expected behavior** I do not expect anything within the `# fmt: off`/`# fmt: on` block to be touched.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Mac 11.2.3/Python 3.9.0 and Windows 10/Python 3.9.2

**Does this bug also happen on master?** Yes - tested with https://black.now.sh/?version=master

**Comment by ichard26** [comment] 2021-04-17 00:49
Thanks for the bug report, (un)fortanately we know of this issue already (tracked in GH-1245) so I'm going to close this issue as a duplicate of that issue. 

p.s. awesome bug report, super readable and easy to parse!
p.s.s. I tried to fix this bug and I failed even after a lot of hours

**Closed by ichard26** 2021-04-17 00:49 UTC
Labels: bug, duplicate

**Comment by njalerikson** [comment] 2021-04-17 03:15
Oops! I tried searching for related bugs but clearly failed! Thanks for taking a look/closing!
