### ISSUE TITLE
Don't split type annotation with alternative union syntax

### ISSUE THREAD

**Issue by cdce8p** [psf/black#2038] opened 2021-03-12 10:47 UTC
**Describe the style change**
With postponed evaluations of type annotations it's now possible to write a `Union` as `int | None`. With black `20.8b1` this can sometimes be formatted in a misleading way.

**Examples in the current _Black_ style**

```python
from __future__ import annotations

def f():
    args: None
    | tuple = None,  # this is a really long comment with some extra information
```

**Desired style**

```python
from __future__ import annotations

def f():
    args: (
        None | tuple
    ) = None,  # this is a really long comment with some extra information
```

**Additional context**
With `from __future__ import annotations`, this syntax is valid in Python 3.7+
https://www.python.org/dev/peps/pep-0604/

**Comment by ambv** [comment] 2021-04-26 18:47
Note: the example isn't about variable annotations where this sort of split would be illegal.

It's about function arguments:
```py3
def f(
    args: tuple 
    | None = None,
):
    ...
```

Indeed, it would be nicer to format like what Black does for variable annotations:
```py3
-    some_argument: tuple | None = None  # very very very very very very very very very very very very
+    some_argument: tuple | None = (
+        None  # very very very very very very very very very very very very
+    )
```

Note that if there is no assignment, Black doesn't even attempt a split on a line that's too long:
```py3
some_argument: tuple | None  # very very very very very very very very very very very very
```

It's left as is.

**Comment by JelleZijlstra** [comment] 2022-01-29 16:46
Duplicate of #2316

**Closed by JelleZijlstra** 2022-01-29 16:46 UTC
Labels: T: design, S: accepted, F: linebreak
