### ISSUE TITLE
Extra parentheses around Enum

### ISSUE THREAD

**Issue by Mitmischer** [psf/black#2482] opened 2021-09-07 09:50 UTC
**Describe the bug**

Black adds extra parentheses around enum entries.

**To Reproduce**

Run black on the following file:

```
class enum(Enum):
    A = 0,
```

**Expected behavior**

I'd have expected no reformatting to take place. Instead I got:

```
class enum(Enum):
    A = (0,)
```

I don't know if those extra parentheses are intended behaviour. If so, what was the rationale behind those?
Is there an option to control this behaviour.

**Environment (please complete the following information):**

- Version:  21.6b0
- OS and Python version: Linux/Python 3.6.9

**Does this bug also happen on main?**

Yes.

**Comment by MarcoGorelli** [comment] 2021-09-07 10:15
Hi @Mitmischer - this is a duplicate of #897

**Comment by felix-hilden** [comment] 2021-09-07 10:59
As such, I'll close this and lets continue discussion there if the issue didn't already answer your questions!

**Closed by felix-hilden** 2021-09-07 10:59 UTC
Labels: T: bug

**Comment by Mitmischer** [comment] 2021-09-07 11:31
Oh!
Note that if an `IntEnum` is desired, the trailing comma makes the entries tuples, which is not desired (that was my actual bug in this case). So the comma should just be left out. Black did a rather good job here!

**Comment by felix-hilden** [comment] 2021-09-07 11:49
I had that happen to me once as well 😄 Black would've helped a ton to figure out the error..
