### ISSUE TITLE
black formatter may change the content of string in nested f-strings

### ISSUE THREAD

**Issue by koitococo** [psf/black#4216] opened 2024-02-07 19:11 UTC
**Describe the bug**

In Python 3.12, black formatter may change the content of string in nested f-strings

**To Reproduce**

For example, take this code:

```python
def test(parts: list[str]):
    print(f"{"-".join(parts)}")
```

And run it with these arguments:

```sh
$ black test.py --target-version=py312 
```

The resulting error is:

contents changed to:

```python
def test(parts: list[str]):
    print(f"{" - ".join(parts)}")
```

**Expected behavior**

contents of string should NOT change

**Environment**

- Black's version: 24.1.1 (compiled: yes)
- OS and Python version: [Fedora release 39/Python 3.12.1]

**Additional context**

**Comment by hauntsaninja** [comment] 2024-02-07 19:13
Duplicate of https://github.com/psf/black/issues/3746 (if you use Black's default settings, you get an error on this example, Black doesn't currently support PEP 701 at all)

**Closed by hauntsaninja** 2024-02-07 19:13 UTC
Labels: T: bug
