### ISSUE TITLE
Colon inside a range gets a colon added to it

### ISSUE THREAD

**Issue by WhyNotHugo** [psf/black#1413] opened 2020-05-15 08:36 UTC
The colon before inside a range gets a space added to it:

input:
```python
def a(code: str, pos: int):
    return code[pos: pos + 10]
```

output
```python
def a(code: str, pos: int):
    return code[pos : pos + 10]
    #              ^ Note this space
```

This seems to be the only scenario in which black adds a space **before** a colon, so I'm assuming it's a bug. Flake8 immediately complains since that's, well, wrong.

This doesn't seem to happen if ` + 10` is not there.

**Environment:**
```
$ black --version
black, version 19.10b0
$ python --version
Python 3.8.2
$ uname -a
Linux aphrodite 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux
```

**Does this bug also happen on master?:**
Yes

**Comment by hugovk** [comment] 2020-05-15 09:33
This is documented in the README:

https://github.com/psf/black/blob/master/README.md#slices

**Comment by WhyNotHugo** [comment] 2020-05-15 10:30
But it would seem that this is not enforced consistently, eg:
```python
def a(code: str, pos: int):
    x = code[pos : pos + 10]  # Spaces here
    y = code[pos:pos]  # No spaces here
```

**Comment by zsol** [comment] 2020-05-15 10:35
We should probably expand that paragraph a bit in the docs. PEP8 recommends no spaces around `:` for "simple" expressions, and extra space for "complex expressions". Black treats anything more than variable names as "complex".

**Comment by WhyNotHugo** [comment] 2020-05-15 10:37
Ah, this makes sense. I guess I'm just too used to flake8's syntax.

I think it would be good to mention, in "installation and usage", a basic configuration for flake8 that aligns with black. Would you guys accept a PR that describes this?

**Comment by WhyNotHugo** [comment] 2020-05-15 10:38
(I realise the individual settings are mentioned in different places, but I'm talking about a single-block copy-pasteable thing :) )

**Comment by zsol** [comment] 2020-05-15 10:43
FWIW here's the relevant code that implements this behavior: https://github.com/psf/black/blob/45c98cf150674dd49cb51d57f8baede4c287f043/src/black/__init__.py#L1411-L1413

I would turn off flake8 warnings related to subscripts (in fact, related to all code formatting). #1371 added an example flake8 config. If you think that needs tuning, feel free to open a PR :)

FWIW this is a duplicate of #889, #940, #1343, and possibly more. Thanks @hugovk for replying to all of them :)

**Closed** 2020-05-15 10:45 UTC
Labels: bug

**Comment by WhyNotHugo** [comment] 2020-05-15 10:53
Oh, it has! Guess I have to read the updated README! Thanks, sorry for the noise!

**Comment by CtrlMj** [comment] 2024-12-07 20:35
> This is documented in the README:
> 
> https://github.com/psf/black/blob/master/README.md#slices

facing the same issue, Mind updating the link?
