### ISSUE TITLE
Unnecessary split in left hand side of assignment due to multiline string

### ISSUE THREAD

**Issue by matejbasic** [psf/black#749] opened 2019-03-14 15:20 UTC
Hi, I'm experience strange behavior when I use dicts and triple-quotes strings, for example:
```python
a["b"] = f"""Some really long
    long string."""
```
ends up like this:
```python
a[
   "b"
] = f"""Some really long
    long string."""
```

Is it expected behavior or? If yes, how can one disable it?

Operating system: Linux Ubuntu 18.04
Python version: 3.6
*Black* version: 18.9b0
Does also happen on master: yes

**Comment by ambv** [comment] 2019-03-14 16:38
It's a bug. It stems from Black seeing that the right hand side doesn't fit in a line (it doesn't, it's a multiline string!) and tries to split the line by any other means.

In this case, it should recognize that the split made matters worse and abort. But that's not super easy to do at this point. We'll be fixing this though.

**Comment by matejbasic** [comment] 2019-03-15 09:26
Thank you for the quick response. Do you maybe know when it could be fixed?

**Comment by yilei** [comment] 2022-10-11 20:14
This also happens to the right side:

```python
a = """Not a so long string
  but multiline.""" + b.call(c=1)
```

is formatted to:

```
a = """Not a so long string
  but multiline.""" + b.call(
    c=1
)
```

even though it fits well within the line length.

**Comment by JelleZijlstra** [comment] 2022-12-19 04:06
Duplicate of #236 and #256.

**Closed by JelleZijlstra** 2022-12-19 04:06 UTC
Labels: T: design, F: linebreak
