### ISSUE TITLE
Dict with double string in value, the second string is align with key

### ISSUE THREAD

**Issue by mathben** [psf/black#2063] opened 2021-03-25 23:18 UTC
**Describe the style change** 
Help to visualize long string in dictionary. To respect pep8, force double string, but the second string is align with the key and not the value.

**Example in the current _Black_ style** 

```python
{
    "name": "Lorem ipsum dolor sit amet.",
    "description": "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
    "Lorem ipsum dolor sit amet. ",
}
```

**Desired style**

```python
{
    "name": "Lorem ipsum dolor sit amet.",
    "description": "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum "
                   "Lorem ipsum dolor sit amet. ",
}
```

**Additional context**
black, version 20.8b1
```python
black -l 100 -t py38 FILES
```

**Comment by sodul** [comment] 2021-04-13 04:28
We have a similar problem where dictionaries that had a value that would go over our line width so we put it on the next line which works well visually, but black changes it back and now we have lines that are too long.

We really do not like aligning the indents on the opening, since this is maintenance burden and all the lines need to be realigned if the key ever changes size. Black does pretty well at avoiding this trap.

For the given example this is how I believe Black should split:
```python
{
    "name": "Lorem ipsum dolor sit amet.",
    "description":
        "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit"
        " amet. Lorem ipsum Lorem ipsum dolor sit amet. ",
}
```

This would be consistent with the exisitng alignment style. I'm not sure why Black does not have a rule for that yet, or at least leave the existing `key: value` line split alone if it will go over the line width.

**Comment by sodul** [comment] 2021-04-22 18:11
This relates to #808,  #847 and  #620.

**Comment by JelleZijlstra** [comment] 2022-01-29 16:34
Duplicate of #620

**Closed by JelleZijlstra** 2022-01-29 16:34 UTC
Labels: T: design, F: linebreak
