### ISSUE TITLE
Which editors work well with black if I'm visually impaired?

### ISSUE THREAD

**Issue by maxwellmckinnon** [psf/black#1502] opened 2020-06-15 20:04 UTC
I love black and the concept, having been using it a while now.

Only one problem, I can't align with tabs anymore, and I can't have my editor render the tab as 10 spaces. I have a bit of a dyslexia problem with viewing close indents (4 spaces is noticeably problematic, especially if I'm a little tired, 2 is significantly stifling so thank you for not making it 2 :D)

Are there any editor settings that work well with black? Can something take the 4 spaces of black and render that as 10 spaces without messing up saved spacings of files I work on? I currently use pycharm.

I'm somewhat of the opinion that it's 2020 and hard-setting to 4 spaces is somewhat 1960's punchcard programming. This thought is similar to how black allows different line lengths (80 is also a legacy artifact). A tab is an indent. We just all are hardwired to think it's X number of spaces. Why can't we just use tabs as tabs, instead of 4 spaces as tabs?

![](https://hackernoon.com/drafts/cf8t3wzn.png)

**Comment by asottile** [comment] 2020-06-16 23:08
I believe this is a duplicate of #47

**Comment by ichard26** [comment] 2020-06-16 23:11
I mean, maybe there is an editor or IDE out there that support variable-sized spaces depending if it's indented related (although it sounds a bit like a pipe dream). 
> Are there any editor settings that work well with black? Can something take the 4 spaces of black and render that as 10 spaces without messing up saved spacings of files I work on? I currently use pycharm.

**Comment by maxwellmckinnon** [comment] 2020-06-17 19:46
Ah looks like a dupe of #47. Well, I hope it can be reconsidered. I love black for standardization and being opinionated and ending the bike shed. Black has provided a lot of value, so thank you!

But standardization isn't alway a virtue, just look at the world today and what following orders religiously can lead to. Nothing is perfect. Very infrequently, standardization should be broken. Says so right in the zen 9 of python.

We couldn't find a good IDE solution that converts 4 spaces to whatever people prefer, so looks like tan is an easy answer for our team for now then (black with tabs instead of spaces). One of the great things about tabs is it literally is the alignment character, and github/IDEs all know how to put it at whatever length one is personally more productive with.

Thanks for listening, and thanks for making black!

**Comment by JelleZijlstra** [comment] 2021-05-30 02:53
Closing as the only actionable request is to use tabs, and we're not making that change.

**Closed by JelleZijlstra** 2021-05-30 02:53 UTC
Labels: C: integrations, T: enhancement, T: user support

**Comment by maxwellmckinnon** [comment] 2021-06-01 02:34
We ended up going with tan! Check it out if you have the same issue

**Comment by iago-lito** [comment] 2021-06-01 08:15
@maxwellmckinnon What's tan?

**Comment by felix-hilden** [comment] 2021-06-01 08:45
I think he means a fork of Black that has some support for tabular indentation: [Tan](https://github.com/jleclanche/tan). It's a bit behind but could work if having spaces is a deal breaker.

**Comment by hauntsaninja** [comment] 2022-01-23 01:30
@ichard26 mentioned a VSCode extension https://marketplace.visualstudio.com/items?itemName=kylepaulsen.stretchy-spaces which might be useful to you
