### ISSUE TITLE
Intentional call chain with explicit parenthesis not respected

### ISSUE THREAD

**Issue by scarf005** [psf/black#3100] opened 2022-06-04 09:28 UTC
**Describe the bug**

```py
return (
    flu(files)
    .map(to_path)
    .flatten()
    .collect()  # type: ignore
)
```
this becomes
```py
return flu(files).map(to_path).flatten().collect()  # type: ignore
```
this.

**To Reproduce**
Run above code with these arguments:

```sh
$ black --target-version py310 -- test.py
```
**Expected behavior**

intentional parenthesis around method chains should be respected and not break into single statement.

**Environment**

- Black's version: main
- OS and Python version: Linux/Python 3.10.4

**Additional context**

**Comment by JelleZijlstra** [comment] 2022-06-04 15:39
I'm inclined to keep the current behavior. Black generally tries to put things in one line where possible.

**Comment by Jacob-Stevens-Haas** [comment] 2022-06-08 19:39
To perhaps paraphrase the argument, this is the call chain equivalent of [the magic trailing comma](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma)

The problem is that call-chaining with periods at the end of the line, which is legal python, breaks for the final trailing period:
```python
(
    numpy.
    array([3])
)  # works
(
    numpy.
    array([3]).
)  # SyntaxError
```

So the only way to tell `black` when you want to keep the call chain expanded vs when you want to be able to collapse it would be preceding vs trailing periods.  But then collabsible-but-too-long call chains would have a different format than 
code with intentionally expanded call chains:
```python
(
    wont()
    .get()
    .collapsed()
    .unless()
    .some_lines()
    .are_deleted()
)
```
vs
```python
(
    intentionally().
    left().
    expanded()
)

**Comment by felix-hilden** [comment] 2022-06-09 11:22
I agree with Jelle, we don't want to take previous formatting into account any more than is *absolutely necessary*.

**Comment by felix-hilden** [comment] 2022-06-15 18:14
With the maintainer rejection, I'll close this issue now.

**Closed by felix-hilden** 2022-06-15 18:14 UTC
Labels: R: rejected, T: design, F: linebreak

**Comment by ichard26** [comment] 2022-06-15 19:59
I'll note that [fluent interfaces are respected if the call chain exceeds line length limits when collapsed](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADRAG5dAD2IimZxl1N_WmXWfJWiTYLz4-Xr1oIHt6YM69TMfgPXNo4BaJrccZt6RCyf39ml3BjJb8XGfViEljQR-_xOwX7F3VQeB1J8I4Kep3RuYkzaJyF1_OZ-fc8GpHSYWc1PFYAz74GFq1vl2LQunjAwAAAAy5YjyVkCTWcAAYoB0gEAAPbRgcyxxGf7AgAAAAAEWVo=).

**Comment by maurosilber** [comment] 2023-10-03 10:41
Couldn't the explicit parenthesis be like the trailing comma?

This:
```python
(intentionally().left().expanded())
```
would format to:
```python
(
    intentionally()
    .left()
    .expanded()
)
```

While something like this, without outer parenthesis, 
```python
intentionally(
).left(
).expanded()
```
would format to:
```python
intentionally().left().expanded()
```
(if it fits in one line, of course)

In this case, the one line form is quite readable. But when we start to include parameters which are calls to other functions, it starts to get unreadable in one line:

```python
intentionally(arg=func(x=1, y=2)).left(arg=f(3)).expanded()
```
