### ISSUE TITLE
Unstable formatting internal error for docstring with tabs

### ISSUE THREAD

**Issue by aberres** [psf/black#1633] opened 2020-08-26 18:15 UTC
Just upgrade to 20.8b1. I get two internal error. In both cases I find in a docstring with tabs. Do not ask me why they are there. Someone in the past using a weird editor...

While I agree that there is no reason to keep the tabs, maybe black should not error out when replacing a tab with spaces?

**Case 1**
```
--- src
+++ dst
@@ -615,11 +615,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                'Creates a column with datetime objects, either from datetime string or date string\nand time string columns\n\nArgs:\ndefault_time:\tTime to set for nan entries, False for no replacement',  # str
+                'Creates a column with datetime objects, either from datetime string or date string\nand time string columns\n\nArgs:\ndefault_time:   Time to set for nan entries, False for no replacement',  # str
             )  # /Constant
         )  # /Expr
         If(
           body=
             If(
```

```
def make_datetime_columns(report, datetime_col, date_col, time_col, default_time=False):
    """
    Creates a column with datetime objects, either from datetime string or date string
    and time string columns

    Args:
        default_time:	Time to set for nan entries, False for no replacement
    """
```

**Case 2**
```
--- src
+++ dst
@@ -7002,11 +7002,11 @@
           body=
             Expr(
               value=
                 Constant(
                   value=
-                    'Reports the actual and corrected hours for an activity.\nUse by the helper functions, compute_activity_hours and compute_duty_hours.\n\nArgs:\ntype:\t\tACTIVITY or DUTY\nACTIVITY sums by ACTIVITY_BEGIN and ACTIVITY_END\nDUTY sums by DUTY_BEGIN and DUTY_END\nactivity:   category for which the hours are computed, e.g., FLIGHT\nname:       specifies the column name of the result, e.g., BLOCK_HOURS\n\nReturns:\nNew data frame',  # str
+                    'Reports the actual and corrected hours for an activity.\nUse by the helper functions, compute_activity_hours and compute_duty_hours.\n\nArgs:\ntype:               ACTIVITY or DUTY\nACTIVITY sums by ACTIVITY_BEGIN and ACTIVITY_END\nDUTY sums by DUTY_BEGIN and DUTY_END\nactivity:   category for which the hours are computed, e.g., FLIGHT\nname:       specifies the column name of the result, e.g., BLOCK_HOURS\n\nReturns:\nNew data frame',  # str
                 )  # /Constant
             )  # /Expr
             Assign(
               targets=
                 Name(
```

```
    def compute_hours(self, type, activity, name):
        """
        Reports the actual and corrected hours for an activity.
        Use by the helper functions, compute_activity_hours and compute_duty_hours.

        Args:
            type:		ACTIVITY or DUTY
                        ACTIVITY sums by ACTIVITY_BEGIN and ACTIVITY_END
                        DUTY sums by DUTY_BEGIN and DUTY_END
            activity:   category for which the hours are computed, e.g., FLIGHT
            name:       specifies the column name of the result, e.g., BLOCK_HOURS

        Returns:
            New data frame
        """
```

**Comment by aberres** [comment] 2020-08-26 18:18
PS: Manually replacing the tabs is an easy way to work around the problem.

**Comment by ichard26** [comment] 2020-08-26 18:42
Actually on further investigation this is not unstable formatting. In fact it's non equivalent formatting that is the problem here.

This also appears to be a duplicate of #1601.

**Closed by ichard26** 2020-08-26 18:42 UTC
Labels: bug, duplicate
