### ISSUE TITLE
Dictionaries with long keys / values not formatted by Black

### ISSUE THREAD

**Issue by ppiasek** [psf/black#2910] opened 2022-03-07 10:29 UTC
**Describe the style change**

Black ignores line length limit for dictionaries that have long key / value values, but could be split into 2 lines. 

**Examples in the current _Black_ style**

```python
my_dict = {
    "my very long key that cannot be shortened": "my very long value that unfortunately also cannot be shortened :(",
}

```

**Desired style**

```python
my_dict = {
    "my very long key that cannot be shortened":
        "my very long value that unfortunately also cannot be shortened :(",
}

```

Putting the value manually into "redundant" parenthesis makes black to split value into new line like below. Shouldn't black automatically put those kind of expressions into parenthesis?  
```python
my_dict = {
    "my very long key that cannot be shortened": (
        "my very long value that unfortunately also cannot be shortened :("
    ),

}
```

**Comment by felix-hilden** [comment] 2022-03-07 10:36
Hi! This is a duplicate of #413, we'll continue the discussion there.

**Closed by felix-hilden** 2022-03-07 10:36 UTC
Labels: F: linetoolong, F: linebreak
