### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by amyreese** [psf/black#2882] opened 2022-02-14 22:06 UTC
**Describe the bug**

Error formatting python sources in https://github.com/pytorch/fairseq

**To Reproduce**

Clone [fairseq](https://github.com/pytorch/fairseq) and run black on offending files:

```
fairseq $ black --version
black, 22.1.0 (compiled: yes)

fairseq $ black --check \
  examples/simultaneous_translation/modules/monotonic_multihead_attention.py \
  examples/speech_text_joint_to_text/criterions/text_guide_cross_entropy_acc.py \
  examples/wav2vec/unsupervised/scripts/pca.py

error: cannot format examples/wav2vec/unsupervised/scripts/pca.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/jg/hrl2p4ms1vjbn44gmmyl4p7r0000gn/T/blk_lda03pi7.log
error: cannot format examples/speech_text_joint_to_text/criterions/text_guide_cross_entropy_acc.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/jg/hrl2p4ms1vjbn44gmmyl4p7r0000gn/T/blk_ctr_udzr.log
error: cannot format examples/simultaneous_translation/modules/monotonic_multihead_attention.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/jg/hrl2p4ms1vjbn44gmmyl4p7r0000gn/T/blk_u26gqsix.log

Oh no! 💥 💔 💥
3 files would fail to reformat.
```

Debug diffs:

- [examples/simultaneous_translation/modules/monotonic_multihead_attention.py](https://gist.github.com/d0c11fed21612e54094d34b480b4cd20)
- [examples/speech_text_joint_to_text/criterions/text_guide_cross_entropy_acc.py](https://gist.github.com/8475c6128a4259d352b6c940edd9315e)
- [examples/wav2vec/unsupervised/scripts/pca.py](https://gist.github.com/f2c873f5b0c35133efffbb595fee5d2f)

**Environment**

- Black's version: 22.1.0
- OS and Python version: macOS 12.1

**Comment by jack1142** [comment] 2022-02-14 23:28
Repro for the first example can be simplified to:
```py
class SomeClass:
    def meth1(self):
        # fmt: off
        abc = 123

    def meth2(self):
        abc = 123
```

**Comment by JelleZijlstra** [comment] 2022-02-14 23:50
Thanks, this might be a duplicate of #569 in that case.

**Closed** 2022-09-24 03:37 UTC
Labels: T: bug, F: fmtoff
