### ISSUE TITLE
19.10b0 starts to depend on gcc for pip installation under docker image python:3.7.5-slim-buster

### ISSUE THREAD

**Issue by larrycai** [psf/black#1128] opened 2019-10-31 20:39 UTC
**Describe the bug** A clear and concise description of what the bug is.

this release needs gcc env to install library (`regex3`?) under popular docker image `python:3.7.5-slim-buster`, which makes complicated.

**To Reproduce** Steps to reproduce the behavior:

1. Simple reproduce in docker env, which is used in travis-ci, gitlab-ci nowadays

````
docker run python:3.7.5-slim-buster pip install black
````
2. Run _Black_ on it with these arguments '....'
3. See error

````
   unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
````

**Expected behavior** A clear and concise description of what you expected to happen.

expected to install without extra `gcc` library, it works smoothly in previous `19.3b0` release

**Environment (please complete the following information):**

**Comment by hugovk** [comment] 2019-10-31 20:43
Duplicate of https://github.com/psf/black/issues/1112.

**Closed** 2019-10-31 21:23 UTC
Labels: bug
