### ISSUE TITLE
Black fail to format long strings and comments

### ISSUE THREAD

**Issue by neoglez** [psf/black#1331] opened 2020-04-03 09:30 UTC
**Black https://github.com/python/black/commit/9ed254**

[Playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AMlAiJdAD2IimZxl1N_Wk6rl1rw4bIAS5Y5FzKS1AQz8D6YN1txl1ETKv-GQ4q0Srhh5Tr2NA63vRouQDFrttRs9MfQnbALlfh7a1NhsFI9Cg92Lj-LUDnBJb1zOD4ObEpQOb7zS34Gw8om3IWwhKwErdSD_zJGTyl9MaT6hLaN1CnoNt-Q6DUQClrTJUl8he5P9D2n9kxDUNoQMoHuOJXjUOUXC6U4D7APPuXzRJyxcgBclSrpLkjhNUFccA1fR31BURAZuVD7SsNxJKws9uY2ke-kjSoU0e4VJaWqSRB8bGuJVrvJvxKzej9rFMTV5vDMZMgXJOPXQBoh4Z_MVVgwZ9EfjNghybAp3J1E0qhW8tk0QYugOO7KaYF70CjOIFl9faH0gWCrKl8g4AnYtOWySmgXAv28Owt3wlC5StX9cXBaskXQryNfehieOIepjznXh6HyAF-EsdVlOVrKSW6AQv6uZsT2ppkMaLRxy6I_YvtRtJ18j01PXE-QicGY26hn_CnvtY-5bwA8tvnCdH92Nzbt7SL4u5krPrOpLwHhdDP-jJcup0pcfmiawHFbW_9zSJsQoQyNCeh2sWPcGQos-phKTzlLkgtVbCWaDgXEN53IxHl6UAIT8G4Zqq_Hef1aMnr7FLj_iPZ9E2w7M0Ws-EWld8ghJdSaze9um5_ZPP5DYkEpDQ9WjxHO9ksPZ_f55kJKSJ6NWxUgh1K_JqQnyBl11cIMAAAAAGf-dabqnCuMAAG-BKYGAABzOph6scRn-wIAAAAABFla)

## Options

`--line-length=88`

## Input

```python

very_long_string = "123456789123456789E123456789asgfpjaspogjojasfogjoajfgojaofjgpaojfgdfkksdkhgspkgpk/k"

# Cordoba, Spain (CNN)The fortress town of Zahara de la Sierra in southern Spain is used to fending off enemies. The Moors and Christians fought over it in medieval times, and it was sacked by the French in 1812. Now its formidable position high above the Andalusian countryside has suddenly become an invaluable asset once more.
# On March 14, Zahara cut itself off from the outside world as a dangerous coronavirus spread its tentacles across Spain. The mayor, 40-year-old Santiago Galván, decided to block all but one of the town's five entrances. Galván acted the day that Spain's "state of alarm" came into force.
```

## Output

```python
very_long_string = "123456789123456789E123456789asgfpjaspogjojasfogjoajfgojaofjgpaojfgdfkksdkhgspkgpk/k"

# Cordoba, Spain (CNN)The fortress town of Zahara de la Sierra in southern Spain is used to fending off enemies. The Moors and Christians fought over it in medieval times, and it was sacked by the French in 1812. Now its formidable position high above the Andalusian countryside has suddenly become an invaluable asset once more.
# On March 14, Zahara cut itself off from the outside world as a dangerous coronavirus spread its tentacles across Spain. The mayor, 40-year-old Santiago Galván, decided to block all but one of the town's five entrances. Galván acted the day that Spain's "state of alarm" came into force.

```

## Output

```python
very_long_string = (
    "123456789123456789E123456789asgfpjaspogjojasfogjoajfg"
    "ojaofjgpaojfgdfkksdkhgspkgpk/k")

# Cordoba, Spain (CNN)The fortress town of Zahara de la Sierra in southern
# Spain is used to fending off enemies. The Moors and Christians fought over it
# in medieval times, and it was sacked by the French in 1812. Now its
# formidable position high above the Andalusian countryside has suddenly become
# an invaluable asset once more.
# On March 14, Zahara cut itself off from the outside world as a dangerous
# coronavirus spread its tentacles across Spain. The mayor, 40-year-old
# Santiago Galván, decided to block all but one of the town's five entrances.
# Galván acted the day that Spain's "state of alarm" came into force.
```

**Comment by ichard26** [comment] 2020-05-03 17:34
@neoglez _Black_ currently doesn't wrap long string literals or merge string literals that happen to be on the same line. There is an open issue regarding this: #182. I would also have to guess _Black_ doesn't wrap long comments for the same reason for strings. It would require modifying the AST which isn't 100% safe and has a bunch of edge cases to be dealt with. Although it should be mentioned that there is a pull request for better string handling, it is #1132. Except, it is a very large PR and probably will take a lot of time to become merged.

Just a 'in case you didn't know' since your issue appears to be a bug report IMO.

**Comment by bbugyi200** [comment] 2020-05-04 19:16
@neoglez It should be noted that #1132 will not change the output of the example that you gave above since the example string has no spaces in it. This would be undesirable, for example, in the case of long URLs.

**Comment by paride** [comment] 2020-09-16 22:14
#1132 has been merged but apparently black still doesn't wrap long lines, even if they contain spaces. I even tried with the very same example given in #1132's description and it doesn't work:

```
$ cat test.py 
#!/usr/bin/python3

fstring = f"f-strings definitely make things more {difficult} than they need to be for {{black}}. But boy they sure are handy. The problem is that some lines will need to have the 'f' whereas others do not. This {line}, for example, needs one."

$ black test.py
All done! ✨ 🍰 ✨
1 file left unchanged.

$ black --version
black, version 20.8b2.dev23+g811decd
```

**Comment by ichard26** [comment] 2020-09-16 22:18
@paride the feature was unstable and causing a bunch of crashes so the decision was made to lock the feature under a hidden flag (PR https://github.com/psf/black/pull/1609).

**Comment by paride** [comment] 2020-09-16 22:27
@ichard26 thanks for the pointer!

**Comment by ichard26** [comment] 2021-05-30 03:57
Closing since 1) the `--experimental-string-processing` flag has landed which handles the string part of this issue, 2) making it the default is tracked separated in https://github.com/psf/black/issues/2188, and 3) the comments case in tracked specifically in https://github.com/psf/black/issues/1713.

Thanks for the suggestions, at least one of them got accepted :)

**Closed by ichard26** 2021-05-30 03:57 UTC
Labels: F: comments, F: strings / docstrings, S: accepted, T: design

**Comment by 1Mark** [comment] 2021-08-01 19:48
Why isn't `--experimental-string-processing` mentioned when you do `black --help`?

**Comment by 1Mark** [comment] 2021-08-01 19:48
> Closing since 1) the `--experimental-string-processing` flag has landed which handles the string part of this issue, 2) making it the default is tracked separated in #2188, and 3) the comments case in tracked specifically in #1713.
> 
> Thanks for the suggestions, at least one of them got accepted :)

Why isn't --experimental-string-processing mentioned when you do black --help?

**Comment by JelleZijlstra** [comment] 2021-08-01 20:35
It's experimental! We plan to turn it on by default in the future.

**Comment by 1Mark** [comment] 2021-08-01 20:39
> It's experimental! We plan to turn it on by default in the future.

git has loads of experimental features, they are still mentioned in the cli docs. How else are people supposed to try them so you can receive more testing + feedback :)

**Comment by kehh** [comment] 2022-03-25 05:05
With the latest version of black (22.1) this is now enabled by using the `--preview` flag on black:
https://black.readthedocs.io/en/stable/change_log.html#highlights

**Comment by lafolle** [comment] 2022-05-17 19:19
Hi there,

i'm still unable to format long comments with the `--preview` flag. 

version info- black, 22.3.0 (compiled: yes)

Test file:
```py
def boom() -> None:

    """There’s an increasing regulatory and consumer pressure on companies to do a better job protecting sensitive customer data. Yet, despite this pressure, data breaches and compliance issues continue to plague the tech industry."""

    # There’s an increasing regulatory and consumer pressure on companies to do a better job protecting sensitive customer data. Yet, despite this pressure, data breaches and compliance issues continue to plague the tech industry

    pass
```

Command output:
```bash
root@ca9009d07c58:/opt/# black -v --line-length 80 --preview test_line.py
Identified `/opt/` as project root containing a .git directory.
Sources to be formatted: "test_line.py"
Using configuration from project root.
test_line.py wasn't modified on disk since last run.

All done! ✨ 🍰 ✨
1 file left unchanged.
```

Am I missing something? My understanding is that the functionality is protected behind `--preview` flag -> hence with the flag the comments should still be formatted?

**Comment by JelleZijlstra** [comment] 2022-05-17 19:27
The `--preview` flag will format long strings but not long comments. There are no current plans to split long comments.

**Comment by evgenyzdanovich** [comment] 2024-05-21 14:16
JFYI, the issue is still in-place for me:

`black --preview --line-length=120 test_transaction.py`

does not split long string fields.

my versions are:
black, 23.7.0 (compiled: yes)
Python (CPython) 3.10.12

**Comment by glebret** [comment] 2024-06-05 09:05
Do you plan to strip comment line also ? Flake is raising error, Black doesn't allow us to solve them.

**Comment by felixjichao** [comment] 2024-06-25 05:11
From Version 24.1.0,
`--preview --enable-unstable-feature string_processing`

> https://black.readthedocs.io/en/stable/change_log.html#id21
> Remove the long-deprecated --experimental-string-processing flag. This feature can currently be enabled with --preview --enable-unstable-feature string_processing. (#4096)
