### ISSUE TITLE
Trailing comma added after *args

### ISSUE THREAD

**Issue by vnavkal** [psf/black#1356] opened 2020-04-23 02:51 UTC
**Describe the bug**
If the definition of a function with `*args` in the signature is broken into multiple lines, a trailing comma is added.  The trailing comma is not valid, at least in Python 2.7.

**To Reproduce**

1. Take this file, called say `some_filename.py`:
```python
def loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong_function_name(*args):
    pass
```
2. Run `black -t py27 some_filename.py`
3. Now the contents of `some_filename.py` are
```python
def loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong_function_name(
    *args,
):
    pass
```
Attempting to import this file in Python 2.7 raises a `SyntaxError` because of the trailing comma after `*args`.

**Expected behavior**
I'd expect the function definition to be split into multiple lines as above, but with no trailing comma after `*args`.

**Environment (please complete the following information):**

- Version: 19.10b0
- OS: Ubuntu 16.04.6 LTS
- Python version: 2.7.12 (I know, I know...)

**Does this bug also happen on master?**
Yes, I observed the same behavior when I ran the version on master on my machine.  One small caveat: on my installation, running black tests `python setup.py test` failed, I think due to unrelated errors (something about `OSError: [Errno 24] Too many open files`).  I didn't bother debugging this further, but let me know if you'd like more information about it.

**Additional context**
In the black documentation, there's this paragraph:
> One exception to adding trailing commas is function signatures containing *, *args, or **kwargs. In this case a trailing comma is only safe to use on Python 3.6. Black will detect if your file is already 3.6+ only and use trailing commas in this situation. If you wonder how it knows, it looks for f-strings and existing use of trailing commas in function signatures that have stars in them. In other words, if you'd like a trailing comma in this situation and Black didn't recognize it was safe to do so, put it there manually and Black will keep it.

So perhaps the logic that determines whether it's safe to add trailing commas is incorrect?

**Comment by felixdivo** [comment] 2020-05-06 08:31
If you are for some reason still on Python 2, you can configure black like this: `--target-version py27`. See [here](https://github.com/psf/black#command-line-options).

**Comment by ichard26** [comment] 2020-05-09 17:13
@felixdh Other than the fact that Python 2.X has reached end of life. The problem is that even passing in `--target-version py27` (or `-t py27`) doesn't stop _Black_ from putting a `<py36` incompatible trailing comma after `*args` in a function signature. 

```
(black-rHKUX7ap) R:\Programming\black>black test.py --target-version py27
reformatted test.py
All done! ✨ 🍰 ✨
1 file reformatted.

(black-rHKUX7ap) R:\Programming\black>type test.py # prints out the contents of a file
def loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong_function_name(
    *args,
):
    pass

(black-rHKUX7ap) R:\Programming\black>bash  # only my WSL Ubuntu installation has Python 2.7
sir2651@DESKTOP-CJA0CE3:/mnt/r/Programming/black$ python2.7 test.py
  File "test.py", line 3
    ):
    ^
SyntaxError: invalid syntax
```

**Environment (please complete the following information):**

* _Black_ Version: 19.10b1.dev87+g4501f22 
* OS: Windows 10 Home Edition Build 18363 /  Ubuntu 18.04.4 LTS in Windows Subsystem for Linux
* Python version: Python 3.8.1 on Windows / Python 2.7.17 on Ubuntu

**Comment by vnavkal** [comment] 2020-05-10 02:16
Thanks @ichard26, yes, that's right.  Black inserts the trailing comma even when `--target-version py27` is specified, and inserting it results in invalid Python 2.7 code.

**Comment by ichard26** [comment] 2020-06-16 20:49
For further reference for the one who will fix this one day. This bug also applies to `**kwargs` with `--target-version py35` -> #1463.

**Comment by AntoineD** [comment] 2020-08-03 07:52
Same issue here with black 19.10b0 and python 2.7, it works fine with 19.3b0.

**Comment by mikenerone** [comment] 2021-02-03 17:06
Any chance of some movement on this? It affects Python 3.5 as well (yes, I know also EOL, but I'm stuck with it on one project).

**Comment by ichard26** [comment] 2021-02-03 17:20
I can try to commit some more time to this to resolve this, but I can't give any promises. 

> It affects Python 3.5 as well (yes, I know also EOL, but I'm stuck with it on one project).

Don't worry, we're still supporting Python 2.7 so it's fine Python 3.5 has to be supported too

**Comment by iscai-msft** [comment] 2021-07-13 15:50
Hello, I'm running into this bug with python 2.7 as well. Specifically, I'm getting a trailing comma after `**kwargs` if `**kwargs` is the only thing in the method signature, and the method signature is long enough that black wraps and I get `**kwargs` by itself on it's own line:

<img width="389" alt="Screen Shot 2021-07-13 at 11 49 52 AM" src="https://user-images.githubusercontent.com/43154838/125483983-31af15c5-bbb5-4bc6-a756-debe7d56e02b.png">


I'm not using the CLI to call black, but instead am directly calling `format_file_contents` with a mode whose target version is set to `TargetVersion.PY27`.

Have there been any updates? Thanks for looking into this issue!

**Comment by felix-hilden** [comment] 2022-01-29 16:38
We don't support Python 2 anymore, so I'll be closing this issue!

**Comment by felix-hilden** [comment] 2022-01-29 16:48
Buuuut the issue with <3.6 still persists <sub>thanks Richard ❤️</sub>

**Comment by JelleZijlstra** [comment] 2022-12-19 03:52
We don't support 3.5 any more either.

**Closed by JelleZijlstra** 2022-12-19 03:52 UTC
Labels: T: bug, F: trailing comma
