### ISSUE TITLE
Mixing tabs and spaces under some circumstances causes black to error

### ISSUE THREAD

**Issue by tim-mccurrach** [psf/black#1398] opened 2020-05-08 23:00 UTC
**Describe the bug** A clear and concise description of what the bug is.
Mixing spaces and tabs in certain (but not all) situations causes black to fail hard.

**To Reproduce** Steps to reproduce the behavior:

1. Take a file with the following content:
```
class bar:
    def foo(self):
        print("hello")  # white space is 8 spaces
    	print("world")  # white space is 4 spaces followed by a tab
```
2. Run _Black_ on it 
3. See error
```
INTERNAL ERROR: Black produced code that is not equivalent to the source. Please report a bug
```

**Expected behavior** A clear and concise description of what you expected to happen.
I would expect to produce an error statement along the lines of:
```
error: cannot format -: unindent does not match any outer indentation level
```
as is the case in the following example:
```
def foo():
    print("hello")  # white space is a tab
    print("goodbye")  # white space is 4 spaces
```
or just a generic syntax error. But not to fail completely.

**Environment (please complete the following information):**

- Version: 19.10b0
- OS and Python version: [e.g. macOS Catalina 10.15.4/Python 3.7.3]

**Does this bug also happen on master?** To answer this, you have two options:
The bug doesn't happen at https://black.now.sh/?version=master although, I think the online editor might be converting spaces to tabs automatically. But yes, running it locally checking out the latest master branch I get the same error.

**Comment by ichard26** [comment] 2020-05-10 19:03
@tim-mccurrach _Black_ isn't failing hard. It's just failing because it has detected that it will be making unsafe changes to the AST of the code file. If you run _Black_ with `--fast` which disables those sanity checks, you don't see the error. Instead you get a perfectly well-formatted file. _Black_ converts those tabs into spaces, not sure if this is the result of `typed-ast` or of _Black_ itself, but when _Black_ checks the newly formatted file with 100% spaces against the original one with tabs, it fails due to the AST trees not being equivalent.

Although your second example is interesting with the `error: cannot format`...

**Comment by pietdaniel** [comment] 2020-07-16 04:44
just received this error as well where `»` denotes tab. The error message was odd as I'd expect a `ERROR: Mixed tabs and spaces message` instead of internal error.

```python
# file.py
class Foo:
    def fn(self):
»       pass
```

```bash
black file.py
```

```bash
```

**Comment by ichard26** [comment] 2020-08-03 01:17
This is a duplicate of https://github.com/psf/black/issues/952.

**Closed** 2020-08-03 21:02 UTC
Labels: bug
