### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter. 

### ISSUE THREAD

**Issue by phiresky** [psf/black#1836] opened 2020-11-23 12:29 UTC
On this file:

[rendezvous.py.txt](https://github.com/psf/black/files/5582901/rendezvous.py.txt)

black, version 20.8b1

error: cannot format rendezvous.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.

**Comment by ichard26** [comment] 2021-04-25 20:05
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:05 UTC
Labels: bug, duplicate, unstable formatting
