### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by holdenweb** [psf/black#1425] opened 2020-05-17 13:00 UTC
**Describe the bug** Running black on the given source file produced the following message:

    error: cannot format src/scan.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.
    Please report a bug on https://github.com/ambv/black/issues.
    

    This diff might be helpful: /var/folders/nw/mlld5h7j1kd7tbcx4mrm60780000gn/T/blk_uc8j73zv.log

The log file is attached.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file 
```
"""
scan.py:    When a new scan appears in the appropriate directory this program is
            triggered with the path of the file as an argument.
"""
import glob
import os
import shutil
import sys

from filler import fill
from forms import DateField
from forms import DirectoryField
from forms import Field
from forms import Form
from forms import ObjectField
from forms import PlainTextField
from forms import TextField
from forms import TimestampField
from hu import ObjectDict

ARCHIVE_DIR = os.environ.get('ARCHIVE_DIR', os.path.join(os.path.expanduser('~'), ".archive"))
db_path = os.path.join (ARCHIVE_DIR, ".database")

form = Form(
    [
        TimestampField("scanned_at", hidden=True),
        DateField("document_date"),
        PlainTextField("description"),
        DirectoryField("link_dir"),
    ]
)

if __name__ == '__main__':
    for file_arg in sys.argv[1:]:
        try:\
            # Get information from user
            data =  ObjectDict(fill(form))
            # Compute archive path
            y, m, d = data.scanned_at[:10].split('-')
            dir_path = os.path.join(ARCHIVE_DIR, y, m, d)
            os.makedirs(dir_path, exist_ok=True)
            num_files = len(glob.glob(os.path.join(dir_path, "*")))
            file_num = f"file_{num_files:04}"
            file_name, ext = os.path.splitext(os.path.basename(file_arg))
            archive_path = os.path.join(dir_path, f"{file_num}{ext}")
            # Compute path for destination link
            user_path = os.path.join(data.link_dir, f'{file_name}{ext}')
            print(data, y, m, d, dir_path, file_name, ext, archive_path, user_path)
            # Move input file to archive, then link to archive file under original name
            shutil.move(file_arg, archive_path)
            os.symlink(archive_path, user_path)
            # TODO: Store archival record
        except InterruptedError:
            sys.exit("Cancelled by user.")
```
2. Run _Black_ on it with no arguments '....'

3. See error

**Expected behavior** Black should run to completion and terminate normally or report a fault with the source it processed..

**Environment (please complete the following information):**

- Version: [e.g. master]  black, version 19.10b0
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] MacOS 10.15.4, Python 3.7.2

**Does this bug also happen on master?** To answer this, you have two options:

No

**Additional context** Add any other context about the problem here.

The issue appears to be the continued `try` statement followed by a comment. In master this gets reformatted so the comment is appended to the try, so the bug may well be fixed. Removing the backslash following `try:` also removed the error.

[blk_qq943832.log](https://github.com/psf/black/files/4640264/blk_qq943832.log)

**Comment by saroup** [comment] 2020-09-09 18:24
I think the issue is related to this line:
if __name__ == '__main__':
I am not sure how to ignore it tho or fix it.

**Comment by holdenweb** [comment] 2020-09-09 20:12
Really? That's pretty standard Python. What make you suspect that particular statement?

**Comment by JelleZijlstra** [comment] 2020-09-15 15:12
It's actually because of the `try:\` (note the backslash) followed by a comment line. We need two passes to remove the backslash and indent the comment properly.

**Comment by holdenweb** [comment] 2020-09-25 15:00
I doubt there's any useful future action to be taken on this issue, so I'm closing it. Thanks to responders.

**Comment by ichard26** [comment] 2021-01-12 04:35
I'm reopening this issue since 1) it's valid and needs to be fixed even if it may seem like it won't be (sorry about that btw, the Black project fully relies on volunteer donated time so progress is super slow), and 2) fixing this might mean #1913 is also fixed since it exhibits similar behaviour.

**Comment by holdenweb** [comment] 2021-01-12 08:37
Your call, thanks for adding your wisdom. I'm pretty busy with a change of role at work presently, so understand the "progress is super slow" comment. If any tuits appesr later I'll get back to you to see whether I can help with a fix.

**Comment by ichard26** [comment] 2021-04-02 19:50
Closing as the current latest version (20.8b1) and master (201b331e55948d187fc150101bebf5262e160290) doesn't fail on this case. @holdenweb thanks for the report!

**Closed by ichard26** 2021-04-02 19:50 UTC
Labels: bug, unstable formatting
