### ISSUE TITLE
Have an opinion about spaces around f-string arguments

### ISSUE THREAD

**Issue by dimaqq** [psf/black#3090] opened 2022-05-28 03:13 UTC
Today `black` allows both of these:

```py
a = f"{None}"
b = f"{ None }"
```

```command
> black test.py
All done! ✨ 🍰 ✨
1 file left unchanged.
```

Perhaps an **opinionated** tool should have an opinion here.

**Comment by JelleZijlstra** [comment] 2022-05-28 03:15
Unfortunately we don't format the insides of f-strings yet. Contributions welcome!

Duplicate of #567.

**Closed by JelleZijlstra** 2022-05-28 03:15 UTC
Labels: T: enhancement
