### ISSUE TITLE
Inconsistent spacing around top level functions

### ISSUE THREAD

**Issue by zmwangx** [psf/black#647] opened 2018-12-20 20:18 UTC
Operating system: macOS 10.14.2
Python version: 3.7.1
*Black* version: 18.9b0
Does also happen on master: yes

---

I have a bit of OS-specific code that looks like this (when formatted by black):

```py
import os

if os.name == "posix":
    import termios

    def foo():
        pass


elif os.name == "nt":
    try:
        import msvcrt

        def foo():
            pass

    except ImportError:

        def foo():
            pass


else:

    def foo():
        pass


other_code()
```

Note now `foo` has two empty lines below it most of the time (including in `if..elif..else`), except in the `try` block of a `try..except`.

Is this intentional? Seems to me there's no need to waste an extra line when the function definition is in any block; one empty line should be enough.

**Comment by ambv** [comment] 2020-03-04 16:08
This is indeed the case: https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFlAKtdAD2IimZxl1N_WlwxRhR7MSgE-ANVlfGy-Pf-urovcUul06DGIKtNJ_PI3I6sH4UsuvCCJK3cSn3O4qbqqEoVdC4RVidtOakKqE1C2PRTK-dEU4CIhv140rXetsz6FlHHNcogH0t3yNeHxqr6iAwuCmSu430fNaT3oxW598BtIbDYmvw9WdVHpVPmNBsa5a2N64u1JlxqaEp3vqccXdLeWyZdVl1aJp0nIQ-QAAAA7ohML_SstGsAAccB5gIAAOsZSAKxxGf7AgAAAAAEWVo=

This is caused by Black discovering that those functions are in fact top level and applying two blank lines before the next *top-level* statement (which is why it doesn't happen before the `except ImportError` line in the example).

We'd accept a fix for this but probably not something we'll be working on soon.

**Comment by felix-hilden** [comment] 2021-10-19 20:59
In my opinion a good style would be:

- No blanks after indenting in or out
- Exactly one blank line before and after defs and classes on the same level as other code

so the example provided would look like:

```python
import os

if os.name == "posix":
    import termios

    def foo():
        pass
elif os.name == "nt":
    try:
        import msvcrt

        def foo():
            pass
    except ImportError:
        def foo():
            pass
else:
    def foo():
        pass

other_code()
```

I'm not 100 % sure about dropping the empty line after, I think leaving it up to the user would be okay. But this is fine in my opinion.

**Closed** 2021-12-01 23:06 UTC
Labels: T: user support, T: design, F: empty lines, S: accepted
