### ISSUE TITLE
error: cannot format views.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.

### ISSUE THREAD

**Issue by mark0978** [psf/black#1170] opened 2019-11-20 20:57 UTC
**Describe the bug**
error: cannot format views.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/j0/_h3b8hwj3ylg96ww2jrz7rrh0000gn/T/blk__cfjz4yn.log

**To Reproduce** Steps to reproduce the behavior:

1. Take this repo https://github.com/mark0978/simple-saas.git  (on the black-error tag)
2. Run _Black_ on it with these arguments `black saas/views.py`
3. See error

If I use wing to fix the spaces/tabs formatting first, it does not crash, so this appears to be related to whitespace in the original file (which is abysmal).

**Expected behavior** A clear and concise description of what you expected to happen.
File should be formatted correctly.

**Environment (please complete the following information):**

- Version: **commit de6f4b1f6bd3211e80bc5a5f1f88e6ef69a550aa (HEAD -> master, origin/master, origin/HEAD)**
- OS and Python version: **Mac 10.15.1  Python 3.7.5**

**Does this bug also happen on master?** To answer this, you have two options:

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch. **It does not happen here**
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python setup.py test`; and
   - run `black` like you did last time.
**But it does happen here (space cleanup on the web version???)**

**Additional context** Log file attached
```
--- src
+++ dst
@@ -144,37 +144,54 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'\n    This view must by inherited by any view that should be accessed only\n    if the user making the request is part of a business that is registered\n    ',  # bytes
+                '\n    This view must by inherited by any view that should be accessed only\n    if the user making the request is part of a business that is registered\n    ',  # str
             )  # /Constant
         )  # /Expr
         FunctionDef(
           args=
             arguments(
               args=
-                Name(
-                  ctx=
-                    Param(
-                    )  # /Param
-                  id=
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
                     'self',  # str
-                )  # /Name
-                Name(
-                  ctx=
-                    Param(
-                    )  # /Param
-                  id=
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
                     'request',  # str
-                )  # /Name
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
               defaults=
+              kw_defaults=
               kwarg=
-                'kwargs',  # str
-              type_comments=
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
+                    'kwargs',  # str
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
+              kwonlyargs=
               vararg=
-                'args',  # str
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
+                    'args',  # str
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
             )  # /arguments
           body=
             Assign(
               targets=
                 Name(
@@ -194,10 +211,23 @@
                         Load(
                         )  # /Load
                       id=
                         'request',  # str
                     )  # /Name
+                    Starred(
+                      ctx=
+                        Load(
+                        )  # /Load
+                      value=
+                        Name(
+                          ctx=
+                            Load(
+                            )  # /Load
+                          id=
+                            'args',  # str
+                        )  # /Name
+                    )  # /Starred
                   func=
                     Attribute(
                       attr=
                         'initial',  # str
                       ctx=
@@ -227,38 +257,30 @@
                                 )  # /Load
                               id=
                                 'super',  # str
                             )  # /Name
                           keywords=
-                          kwargs=
-                            None,  # NoneType
-                          starargs=
-                            None,  # NoneType
                         )  # /Call
                     )  # /Attribute
                   keywords=
-                  kwargs=
-                    Name(
-                      ctx=
-                        Load(
-                        )  # /Load
-                      id=
-                        'kwargs',  # str
-                    )  # /Name
-                  starargs=
-                    Name(
-                      ctx=
-                        Load(
-                        )  # /Load
-                      id=
-                        'args',  # str
-                    )  # /Name
+                    keyword(
+                      arg=
+                        None,  # NoneType
+                      value=
+                        Name(
+                          ctx=
+                            Load(
+                            )  # /Load
+                          id=
+                            'kwargs',  # str
+                        )  # /Name
+                    )  # /keyword
                 )  # /Call
             )  # /Assign
             If(
               body=
-                TryExcept(
+                Try(
                   body=
                     Assign(
                       targets=
                         Name(
                           ctx=
@@ -315,14 +337,10 @@
                                       id=
                                         'request',  # str
                                     )  # /Name
                                 )  # /Attribute
                             )  # /keyword
-                          kwargs=
-                            None,  # NoneType
-                          starargs=
-                            None,  # NoneType
                         )  # /Call
                     )  # /Assign
                     Assign(
                       targets=
                         Attribute(
@@ -357,19 +375,18 @@
                               id=
                                 'team_member',  # str
                             )  # /Name
                         )  # /Attribute
                     )  # /Assign
+                  finalbody=
                   handlers=
                     ExceptHandler(
                       body=
                         Raise(
-                          inst=
+                          cause=
                             None,  # NoneType
-                          tback=
-                            None,  # NoneType
-                          type=
+                          exc=
                             Call(
                               args=
                               func=
                                 Name(
                                   ctx=
@@ -377,14 +394,10 @@
                                     )  # /Load
                                   id=
                                     'MemberDoesNotExist',  # str
                                 )  # /Name
                               keywords=
-                              kwargs=
-                                None,  # NoneType
-                              starargs=
-                                None,  # NoneType
                             )  # /Call
                         )  # /Raise
                       name=
                         None,  # NoneType
                       type=
@@ -403,11 +416,11 @@
                                 'BusinessTeamMember',  # str
                             )  # /Name
                         )  # /Attribute
                     )  # /ExceptHandler
                   orelse=
-                )  # /TryExcept
+                )  # /Try
               orelse=
               test=
                 UnaryOp(
                   op=
                     Not(
@@ -438,14 +451,10 @@
                                     'request',  # str
                                 )  # /Name
                             )  # /Attribute
                         )  # /Attribute
                       keywords=
-                      kwargs=
-                        None,  # NoneType
-                      starargs=
-                        None,  # NoneType
                     )  # /Call
                 )  # /UnaryOp
             )  # /If
             Return(
               value=
@@ -458,14 +467,17 @@
                 )  # /Name
             )  # /Return
           decorator_list=
           name=
             'initial',  # str
+          returns=
+            None,  # NoneType
           type_comment=
             None,  # NoneType
         )  # /FunctionDef
       decorator_list=
+      keywords=
       name=
         'BusinessAPIView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -479,37 +491,54 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'\n    This view must be inherited by any view that should be accessed only if\n    there is an active subscription present for a business to which\n    the user that is making the api call belongs to\n    ',  # bytes
+                '\n    This view must be inherited by any view that should be accessed only if\n    there is an active subscription present for a business to which\n    the user that is making the api call belongs to\n    ',  # str
             )  # /Constant
         )  # /Expr
         FunctionDef(
           args=
             arguments(
               args=
-                Name(
-                  ctx=
-                    Param(
-                    )  # /Param
-                  id=
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
                     'self',  # str
-                )  # /Name
-                Name(
-                  ctx=
-                    Param(
-                    )  # /Param
-                  id=
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
                     'request',  # str
-                )  # /Name
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
               defaults=
+              kw_defaults=
               kwarg=
-                'kwargs',  # str
-              type_comments=
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
+                    'kwargs',  # str
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
+              kwonlyargs=
               vararg=
-                'args',  # str
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
+                    'args',  # str
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
             )  # /arguments
           body=
             Assign(
               targets=
                 Name(
@@ -529,10 +558,23 @@
                         Load(
                         )  # /Load
                       id=
                         'request',  # str
                     )  # /Name
+                    Starred(
+                      ctx=
+                        Load(
+                        )  # /Load
+                      value=
+                        Name(
+                          ctx=
+                            Load(
+                            )  # /Load
+                          id=
+                            'args',  # str
+                        )  # /Name
+                    )  # /Starred
                   func=
                     Attribute(
                       attr=
                         'initial',  # str
                       ctx=
@@ -562,36 +604,28 @@
                                 )  # /Load
                               id=
                                 'super',  # str
                             )  # /Name
                           keywords=
-                          kwargs=
-                            None,  # NoneType
-                          starargs=
-                            None,  # NoneType
                         )  # /Call
                     )  # /Attribute
                   keywords=
-                  kwargs=
-                    Name(
-                      ctx=
-                        Load(
-                        )  # /Load
-                      id=
-                        'kwargs',  # str
-                    )  # /Name
-                  starargs=
-                    Name(
-                      ctx=
-                        Load(
-                        )  # /Load
-                      id=
-                        'args',  # str
-                    )  # /Name
+                    keyword(
+                      arg=
+                        None,  # NoneType
+                      value=
+                        Name(
+                          ctx=
+                            Load(
+                            )  # /Load
+                          id=
+                            'kwargs',  # str
+                        )  # /Name
+                    )  # /keyword
                 )  # /Call
             )  # /Assign
-            TryExcept(
+            Try(
               body=
                 Assign(
                   targets=
                     Name(
                       ctx=
@@ -652,22 +686,15 @@
                         )  # /keyword
                         keyword(
                           arg=
                             'is_active',  # str
                           value=
-                            Name(
-                              ctx=
-                                Load(
-                                )  # /Load
-                              id=
-                                'True',  # str
-                            )  # /Name
+                            Constant(
+                              value=
+                                True,  # bool
+                            )  # /Constant
                         )  # /keyword
-                      kwargs=
-                        None,  # NoneType
-                      starargs=
-                        None,  # NoneType
                     )  # /Call
                 )  # /Assign
                 Assign(
                   targets=
                     Attribute(
@@ -694,19 +721,18 @@
                         )  # /Load
                       id=
                         'subscription',  # str
                     )  # /Name
                 )  # /Assign
+              finalbody=
               handlers=
                 ExceptHandler(
                   body=
                     Raise(
-                      inst=
+                      cause=
                         None,  # NoneType
-                      tback=
-                        None,  # NoneType
-                      type=
+                      exc=
                         Call(
                           args=
                           func=
                             Name(
                               ctx=
@@ -714,14 +740,10 @@
                                 )  # /Load
                               id=
                                 'NoActiveSubscriptionFound',  # str
                             )  # /Name
                           keywords=
-                          kwargs=
-                            None,  # NoneType
-                          starargs=
-                            None,  # NoneType
                         )  # /Call
                     )  # /Raise
                   name=
                     None,  # NoneType
                   type=
@@ -740,11 +762,11 @@
                             'Subscription',  # str
                         )  # /Name
                     )  # /Attribute
                 )  # /ExceptHandler
               orelse=
-            )  # /TryExcept
+            )  # /Try
             Return(
               value=
                 Name(
                   ctx=
                     Load(
@@ -754,14 +776,17 @@
                 )  # /Name
             )  # /Return
           decorator_list=
           name=
             'initial',  # str
+          returns=
+            None,  # NoneType
           type_comment=
             None,  # NoneType
         )  # /FunctionDef
       decorator_list=
+      keywords=
       name=
         'SubscriptionAPIView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -856,10 +881,11 @@
                     )  # /Name
                 )  # /Attribute
             )  # /Tuple
         )  # /Assign
       decorator_list=
+      keywords=
       name=
         'LoginView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -873,11 +899,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'\n\tIf signup form is accessed via an activation link, form will be prefilled with some information.\n\tTo retrieve that information, use this API with the activation key\n\t',  # bytes
+                '\n\tIf signup form is accessed via an activation link, form will be prefilled with some information.\n\tTo retrieve that information, use this API with the activation key\n\t',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(
@@ -900,21 +926,23 @@
         )  # /Assign
         FunctionDef(
           args=
             arguments(
               args=
-                Name(
-                  ctx=
-                    Param(
-                    )  # /Param
-                  id=
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
                     'self',  # str
-                )  # /Name
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
               defaults=
+              kw_defaults=
               kwarg=
                 None,  # NoneType
-              type_comments=
+              kwonlyargs=
               vararg=
                 None,  # NoneType
             )  # /arguments
           body=
             Assign(
@@ -931,19 +959,16 @@
               value=
                 Call(
                   args=
                     Constant(
                       value=
-                        b'key',  # bytes
+                        'key',  # str
                     )  # /Constant
-                    Name(
-                      ctx=
-                        Load(
-                        )  # /Load
-                      id=
-                        'None',  # str
-                    )  # /Name
+                    Constant(
+                      value=
+                        None,  # NoneType
+                    )  # /Constant
                   func=
                     Attribute(
                       attr=
                         'get',  # str
                       ctx=
@@ -973,17 +998,13 @@
                                 )  # /Name
                             )  # /Attribute
                         )  # /Attribute
                     )  # /Attribute
                   keywords=
-                  kwargs=
-                    None,  # NoneType
-                  starargs=
-                    None,  # NoneType
                 )  # /Call
             )  # /Assign
-            TryExcept(
+            Try(
               body=
                 Return(
                   value=
                     Call(
                       args=
@@ -1022,30 +1043,25 @@
                                 )  # /Load
                               id=
                                 'key',  # str
                             )  # /Name
                         )  # /keyword
-                      kwargs=
-                        None,  # NoneType
-                      starargs=
-                        None,  # NoneType
                     )  # /Call
                 )  # /Return
+              finalbody=
               handlers=
                 ExceptHandler(
                   body=
                     Raise(
-                      inst=
+                      cause=
                         None,  # NoneType
-                      tback=
-                        None,  # NoneType
-                      type=
+                      exc=
                         Call(
                           args=
                             Constant(
                               value=
-                                b'Activation key not found',  # bytes
+                                'Activation key not found',  # str
                             )  # /Constant
                           func=
                             Attribute(
                               attr=
                                 'ValidationError',  # str
@@ -1060,14 +1076,10 @@
                                   id=
                                     'serializers',  # str
                                 )  # /Name
                             )  # /Attribute
                           keywords=
-                          kwargs=
-                            None,  # NoneType
-                          starargs=
-                            None,  # NoneType
                         )  # /Call
                     )  # /Raise
                   name=
                     None,  # NoneType
                   type=
@@ -1086,18 +1098,21 @@
                             'BusinessTeamMember',  # str
                         )  # /Name
                     )  # /Attribute
                 )  # /ExceptHandler
               orelse=
-            )  # /TryExcept
+            )  # /Try
           decorator_list=
           name=
             'get_object',  # str
+          returns=
+            None,  # NoneType
           type_comment=
             None,  # NoneType
         )  # /FunctionDef
       decorator_list=
+      keywords=
       name=
         'PrefillSignupView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -1192,10 +1207,11 @@
                     )  # /Name
                 )  # /Attribute
             )  # /Tuple
         )  # /Assign
       decorator_list=
+      keywords=
       name=
         'SignupView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -1209,11 +1225,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'\n\tSending email to a team member with an activation key that will be used to reset password\n\t',  # bytes
+                '\n\tSending email to a team member with an activation key that will be used to reset password\n\t',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(
@@ -1297,10 +1313,11 @@
                     )  # /Name
                 )  # /Attribute
             )  # /Tuple
         )  # /Assign
       decorator_list=
+      keywords=
       name=
         'ResetPasswordView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -1314,11 +1331,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'\n\tUsing the activation key sent in the mail, password will be reset using new password\n\t',  # bytes
+                '\n\tUsing the activation key sent in the mail, password will be reset using new password\n\t',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(
@@ -1402,10 +1419,11 @@
                     )  # /Name
                 )  # /Attribute
             )  # /Tuple
         )  # /Assign
       decorator_list=
+      keywords=
       name=
         'ResetPasswordConfirmationView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -1426,11 +1444,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'\n\tReturns information about the user to which this auth token belongs to and the corresponding business.\n\tCan be used in settings\n\t',  # bytes
+                '\n\tReturns information about the user to which this auth token belongs to and the corresponding business.\n\tCan be used in settings\n\t',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(
@@ -1479,21 +1497,23 @@
         )  # /Assign
         FunctionDef(
           args=
             arguments(
               args=
-                Name(
-                  ctx=
-                    Param(
-                    )  # /Param
-                  id=
+                arg(
+                  annotation=
+                    None,  # NoneType
+                  arg=
                     'self',  # str
-                )  # /Name
+                  type_comment=
+                    None,  # NoneType
+                )  # /arg
               defaults=
+              kw_defaults=
               kwarg=
                 None,  # NoneType
-              type_comments=
+              kwonlyargs=
               vararg=
                 None,  # NoneType
             )  # /arguments
           body=
             Return(
@@ -1579,23 +1599,22 @@
                                     'self',  # str
                                 )  # /Name
                             )  # /Attribute
                         )  # /Attribute
                     )  # /keyword
-                  kwargs=
-                    None,  # NoneType
-                  starargs=
-                    None,  # NoneType
                 )  # /Call
             )  # /Return
           decorator_list=
           name=
             'get_object',  # str
+          returns=
+            None,  # NoneType
           type_comment=
             None,  # NoneType
         )  # /FunctionDef
       decorator_list=
+      keywords=
       name=
         'MeView',  # str
     )  # /ClassDef
     ClassDef(
       bases=
@@ -1616,11 +1635,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'\n    Sending invitation to a team member to join SessionFox\n    ',  # bytes
+                '\n    Sending invitation to a team member to join SessionFox\n    ',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(
@@ -1666,10 +1685,11 @@
               id=
                 'InviteTeamMemberSerialiser',  # str
             )  # /Name
         )  # /Assign
       decorator_list=
+      keywords=
       name=
         'InviteTeamMemberView',  # str
     )  # /ClassDef
   type_ignores=
 )  # /Module
```

**Comment by JelleZijlstra** [comment] 2019-11-23 04:37
Apparently Black parses this code as Python 2 before formatting and as Python 3 after. I'm not quite sure why.

**Comment by JelleZijlstra** [comment] 2021-05-30 03:31
Still reproduces, here is a minimized repro:
```
class BusinessAPIView(APIView):

    def initial(self, request, *args, **kwargs):
		if not request.user.is_anonymous():
			try:
				team_member = BusinessTeamMember.objects.get(user=request.user)
			except BusinessTeamMember.DoesNotExist:
				raise MemberDoesNotExist()

```
It's something to do with mixed tabs and spaces.

**Comment by JelleZijlstra** [comment] 2021-05-30 03:34
Duplicate of #952.

**Closed by JelleZijlstra** 2021-05-30 03:34 UTC
Labels: C: invalid code, T: bug
