### ISSUE TITLE
Black error when executing notebook with papermill 2.0.0 and higher

### ISSUE THREAD

**Issue by VDEHans** [psf/black#1464] opened 2020-05-27 09:05 UTC
see https://github.com/nteract/papermill/issues/498

**To Reproduce** Steps to reproduce the behavior:

1. create a notebook with parameters
2. Run notebook with papermill
3. See error:
Writing grammar tables to /home/AD/hvd1v2w/.cache/black/19.10b0/Grammar3.7.7.final.0.pickle
 Writing failed: [Errno 2] No such file or directory: '/home/AD/hvd1v2w/.cache/black/19.10b0/tmp6jo8l_ml'
 Generating grammar tables from /home/AD/hvd1v2w/.conda/envs/stuks-productiviteit-refactor/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
 Writing grammar tables to /home/AD/hvd1v2w/.cache/black/19.10b0/PatternGrammar3.7.7.final.0.pickle
 Writing failed: [Errno 2] No such file or directory: '/home/AD/hvd1v2w/.cache/black/19.10b0/tmpy8vr4ksk'
![image](https://user-images.githubusercontent.com/64588639/82998994-b67c3f80-a008-11ea-97cc-1806da89b245.png)

**Expected behavior** 
No errors when using black through papermill for formatting the parameters part of the notebook 

**Environment (please complete the following information):**

- Version: black version 19.10b0
- OS and Python version:  Linux/Python 3.7.7

**Comment by ichard26** [comment] 2020-07-04 16:18
This is probably caused by #1223.

**Comment by ichard26** [comment] 2020-09-16 23:24
This is a duplicate of #1143.

**Closed by ichard26** 2020-09-16 23:24 UTC
Labels: bug, duplicate
