### ISSUE TITLE
Feature request: check code snippets

### ISSUE THREAD

**Issue by cgthayer** [psf/black#1076] opened 2019-10-18 21:14 UTC
Feature request: I'd like to be able to run black on a few lines or a function/method within a larger file. I currently use emacs and elpy, which let's me highlight a region and attempt to format it with black, but unless it's at the top-level it doesn't work.  Black would need to understand that a section of code may be an indented block.

**Comment by JelleZijlstra** [comment] 2019-10-18 21:27
An integration could do this by de-indenting the code, formatting it with Black, then re-indenting it by the amount it originally de-indented it.

**Comment by jrosdahl** [comment] 2019-10-19 09:05
See https://github.com/wbolster/emacs-python-black which does this via https://github.com/wbolster/black-macchiato.

**Comment by ichard26** [comment] 2020-09-27 02:17
While #1352 is a duplicate of this issue (which itself is a duplicate of #987), that issue has more context, information, and a solution suggestion(!), so closing this in favour of that one.

**Closed by ichard26** 2020-09-27 02:17 UTC
