### ISSUE TITLE
NTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by Linekio** [psf/black#1945] opened 2021-01-27 09:54 UTC
I produced the minimal code "az.py":
```
class Foo:

    def bar(self, length_18_variable):
        if cond1:
            while cond2:
                length_18_variable = aaaa(length_18_variable.bbbb, length_18_variable.cccc, length_18_variable.ddd) + r(a=1)
```
```
black az.py
error: cannot format az.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_qdnb6p5f.log
```
here the diff file:
```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,8 +1,9 @@
-
 class Foo:
-
     def bar(self, length_18_variable):
         if cond1:
             while cond2:
-                length_18_variable = aaaa(length_18_variable.bbbb, length_18_variable.cccc, length_18_variable.ddd) + r(a=1)
-
+                length_18_variable = aaaa(
+                    length_18_variable.bbbb,
+                    length_18_variable.cccc,
+                    length_18_variable.ddd,
+                ) + r(a=1)
--- first pass
+++ second pass
@@ -1,9 +1,12 @@
 class Foo:
     def bar(self, length_18_variable):
         if cond1:
             while cond2:
-                length_18_variable = aaaa(
-                    length_18_variable.bbbb,
-                    length_18_variable.cccc,
-                    length_18_variable.ddd,
-                ) + r(a=1)
+                length_18_variable = (
+                    aaaa(
+                        length_18_variable.bbbb,
+                        length_18_variable.cccc,
+                        length_18_variable.ddd,
+                    )
+                    + r(a=1)
+                )
```
black, version 20.8b1
Linuxmint 20 cinnamon
python3.8.5

This bug also happen on master

**Comment by jonadaly** [comment] 2021-01-27 10:58
I have what looks like the same problem (20.8b1):

```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -85,11 +85,16 @@
     if end_date:
-        midnight_next_day: datetime = datetime(end_date.year, end_date.month, end_date.day, tzinfo=timezone.utc) + timedelta(days=1)
+        midnight_next_day: datetime = datetime(
+            end_date_parsed.year,
+            end_date_parsed.month,
+            end_date_parsed.day,
+            tzinfo=timezone.utc,
+        ) + timedelta(days=1)

--- first pass
+++ second pass
@@ -85,16 +85,19 @@
     if end_date:
-        midnight_next_day: datetime = datetime(
-            end_date.year,
-            end_date.month,
-            end_date.day,
-            tzinfo=timezone.utc,
-        ) + timedelta(days=1)
+        midnight_next_day: datetime = (
+            datetime(
+                end_date_parsed.year,
+                end_date_parsed.month,
+                end_date_parsed.day,
+                tzinfo=timezone.utc,
+            )
+            + timedelta(days=1)
+        )
```

**Comment by adalke** [comment] 2021-01-29 10:59
Same here, also with 20.8b1.

```
% cat case1.py
msg = ("Could not %(decoder_name)s decode tag %(tag)r value %(encoded_fp)s: %(err)s, %(where)s" %
           dict(decoder_name="A", tag=args.fp_tag,
               where=location.where(), err=err, encoded_fp="A"))
% black case1.py
error: cannot format case1.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter. ...
% cat /var/folders/7h/qqvrpj2j5tl4q72w4q815pyc0000gq/T/blk_kk6lssnu.log
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,3 +1,10 @@
-msg = ("Could not %(decoder_name)s decode tag %(tag)r value %(encoded_fp)s: %(err)s, %(where)s" %
-           dict(decoder_name="A", tag=args.fp_tag,
-               where=location.where(), err=err, encoded_fp="A"))
+msg = (
+    "Could not %(decoder_name)s decode tag %(tag)r value %(encoded_fp)s: %(err)s, %(where)s"
+    % dict(
+        decoder_name="A",
+        tag=args.fp_tag,
+        where=location.where(),
+        err=err,
+        encoded_fp="A",
+    )
+)
--- first pass
+++ second pass
@@ -1,10 +1,7 @@
-msg = (
-    "Could not %(decoder_name)s decode tag %(tag)r value %(encoded_fp)s: %(err)s, %(where)s"
-    % dict(
-        decoder_name="A",
-        tag=args.fp_tag,
-        where=location.where(),
-        err=err,
-        encoded_fp="A",
-    )
+msg = "Could not %(decoder_name)s decode tag %(tag)r value %(encoded_fp)s: %(err)s, %(where)s" % dict(
+    decoder_name="A",
+    tag=args.fp_tag,
+    where=location.where(),
+    err=err,
+    encoded_fp="A",
 )
```
and the same error message with:
```
% cat case2.py
def f():
    return "Options(skip_ids=%r, show_ids=%r, show_id_indices=%r, skip_fps=%r, show_fps=%r)" % (
           self.skip_ids, self.show_ids, self.show_id_indices, self.skip_fps, self.show_fps)
% cat /var/folders/7h/qqvrpj2j5tl4q72w4q815pyc0000gq/T/blk_9qb5q853.log
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,3 +1,11 @@
 def f():
-    return "Options(skip_ids=%r, show_ids=%r, show_id_indices=%r, skip_fps=%r, show_fps=%r)" % (
-           self.skip_ids, self.show_ids, self.show_id_indices, self.skip_fps, self.show_fps)
+    return (
+        "Options(skip_ids=%r, show_ids=%r, show_id_indices=%r, skip_fps=%r, show_fps=%r)"
+        % (
+            self.skip_ids,
+            self.show_ids,
+            self.show_id_indices,
+            self.skip_fps,
+            self.show_fps,
+        )
+    )
--- first pass
+++ second pass
@@ -1,11 +1,8 @@
 def f():
-    return (
-        "Options(skip_ids=%r, show_ids=%r, show_id_indices=%r, skip_fps=%r, show_fps=%r)"
-        % (
-            self.skip_ids,
-            self.show_ids,
-            self.show_id_indices,
-            self.skip_fps,
-            self.show_fps,
-        )
+    return "Options(skip_ids=%r, show_ids=%r, show_id_indices=%r, skip_fps=%r, show_fps=%r)" % (
+        self.skip_ids,
+        self.show_ids,
+        self.show_id_indices,
+        self.skip_fps,
+        self.show_fps,
     )
```

**Comment by ichard26** [comment] 2021-04-25 20:21
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:21 UTC
Labels: bug, duplicate, unstable formatting
