### ISSUE TITLE
Treat double-width unicode characters

### ISSUE THREAD

**Issue by hallazzang** [psf/black#1154] opened 2019-11-12 14:15 UTC
**Describe the style change**
Black currently does not handle double-width characters(i.e. CJK characters) different from single-width characters.
This leads black to make some lines too long to see in small(~88 characters width) window.
Please check the example below.

**Examples in the current _Black_ style**
Consider this input:
```python
foo = (
    ("aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb"),
    ("안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요"),
)
```

If I run `black --diff main.py`, then I get this result:
```diff
@@ -1,4 +1,15 @@
 foo = (
-    ("aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb", "aaaaabbbbb"),
+    (
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+        "aaaaabbbbb",
+    ),
     ("안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요"),
 )
```

**Desired style**
I want black to style my code like this:

```
foo = (
    (
        "aaaaabbbbb",
        "aaaaabbbbb",
        "aaaaabbbbb",
        "aaaaabbbbb",
        "aaaaabbbbb",
        "aaaaabbbbb",
        "aaaaabbbbb",
        "aaaaabbbbb",
        "aaaaabbbbb",
    ),
    (
        "안녕하세요",
        "안녕하세요",
        "안녕하세요",
        "안녕하세요",
        "안녕하세요",
        "안녕하세요",
        "안녕하세요",
        "안녕하세요",
        "안녕하세요",
    ),
)
```

But black prevents it, rather does this:
```diff
@@ -8,17 +8,8 @@
         "aaaaabbbbb",
         "aaaaabbbbb",
         "aaaaabbbbb",
         "aaaaabbbbb",
     ),
-    (
-        "안녕하세요",
-        "안녕하세요",
-        "안녕하세요",
-        "안녕하세요",
-        "안녕하세요",
-        "안녕하세요",
-        "안녕하세요",
-        "안녕하세요",
-        "안녕하세요",
-    ),
+    ("안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요", "안녕하세요",),
 )
```

**Additional context**
```console
$ black --version
black, version 19.10b0
```

**Comment by ichard26** [comment] 2020-09-27 01:43
#1197 is a duplicate of this issue, but it has more context and discussion, so closing this in favour of that.

**Closed by ichard26** 2020-09-27 01:43 UTC
Labels: design
