### ISSUE TITLE
Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by camold** [psf/black#2014] opened 2021-03-01 16:00 UTC
```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,3 +1,7 @@
 test = "\n".join(
-        ["first slightly longer line", "one long line expression", "another long line expression"]
-    ) + ("blubber test" if True else "")
+    [
+        "first slightly longer line",
+        "one long line expression",
+        "another long line expression",
+    ]
+) + ("blubber test" if True else "")
--- first pass
+++ second pass
@@ -1,7 +1,10 @@
-test = "\n".join(
-    [
-        "first slightly longer line",
-        "one long line expression",
-        "another long line expression",
-    ]
-) + ("blubber test" if True else "")
+test = (
+    "\n".join(
+        [
+            "first slightly longer line",
+            "one long line expression",
+            "another long line expression",
+        ]
+    )
+    + ("blubber test" if True else "")
+)
```

- Version: black, version 20.8b1
- Linux: uname -a => Linux 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Python 3.8.0 (default, Oct 28 2019, 16:14:01)

**Comment by ichard26** [comment] 2021-04-25 20:12
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:12 UTC
Labels: bug, duplicate, unstable formatting
