### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by jugmac00** [psf/black#1862] opened 2020-12-09 14:20 UTC
**Describe the bug** A clear and concise description of what the bug is.
Formatting failed with following error:

> INTERNAL ERROR: Black produced different code on the second pass of the formatter

**To Reproduce** Steps to reproduce the behavior:
use code like this:
```
class CompanyLocation:
    @security.private
    def longPrintString(self):
        """ return long printstring """
        return "%s  [%d Licences/%d active), %d active maintenance contracts, %d employees]" % (
            self.addressSingleLine(),
            len(self.licences()),
            len(self.activeLicences()),
            len(self.activeMaintenanceContracts()),
            len(self.employees())
        )
```

run black with no arguments (except above file)

**Expected behavior** A clear and concise description of what you expected to happen.
it should work

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Ubuntu 18.04, Python 3.7.9

**Does this bug also happen on master?** To answer this, you have two options:
Yes - problem still exists on master, ie in the web version.

**Additional context** Add any other context about the problem here.

diff provided by black for debugging purposes
```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1158,16 +1158,19 @@
         )
 
     @security.private
     def longPrintString(self):
         """ return long printstring """
-        return "%s  [%d Licences/%d active), %d active maintenance contracts, %d employees]" % (
-            self.addressSingleLine(),
-            len(self.licences()),
-            len(self.activeLicences()),
-            len(self.activeMaintenanceContracts()),
-            len(self.employees())
+        return (
+            "%s  [%d Licences/%d active), %d active maintenance contracts, %d employees]"
+            % (
+                self.addressSingleLine(),
+                len(self.licences()),
+                len(self.activeLicences()),
+                len(self.activeMaintenanceContracts()),
+                len(self.employees()),
+            )
         )
 
     @security.private
     def mainAddress(self):
         """ return main address """
--- first pass
+++ second pass
@@ -1158,19 +1158,16 @@
         )
 
     @security.private
     def longPrintString(self):
         """ return long printstring """
-        return (
-            "%s  [%d Licences/%d active), %d active maintenance contracts, %d employees]"
-            % (
-                self.addressSingleLine(),
-                len(self.licences()),
-                len(self.activeLicences()),
-                len(self.activeMaintenanceContracts()),
-                len(self.employees()),
-            )
+        return "%s  [%d Licences/%d active), %d active maintenance contracts, %d employees]" % (
+            self.addressSingleLine(),
+            len(self.licences()),
+            len(self.activeLicences()),
+            len(self.activeMaintenanceContracts()),
+            len(self.employees()),
         )
 
     @security.private
     def mainAddress(self):
         """ return main address """
```

**Comment by hellocoldworld** [comment] 2020-12-09 17:45
same issue here

**Comment by ichard26** [comment] 2021-04-25 20:15
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:15 UTC
Labels: bug, duplicate, unstable formatting
