### ISSUE TITLE
Unstable formatting with long conditional expression

### ISSUE THREAD

**Issue by wyattanderson** [psf/black#1804] opened 2020-11-03 20:41 UTC
**To Reproduce**

Run Black on this code:

```python
if shopify_order_action in [SHOPIFY_HEADER_ORDER_FULFILLED, SHOPIFY_HEADER_ORDER_PARTIALLY_FULFILLED] and (not fulfillments or len(fulfillments) == 0):
    pass
```

The code itself isn't fantastic, for sure, but it still breaks Black, and that ain't great.

Reformatting fails with `error: cannot format testcase.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.`.

**Environment (please complete the following information):**

- Version: latest release on PyPI and on `master`
- OS and Python version: Mac OS X, Python 3.8.5

**Does this bug also happen on master?**

Yes, running this on black.now.sh also fails.

**Comment by mik-laj** [comment] 2020-11-04 14:57
I have more examples.
https://github.com/apache/airflow/pull/12091

**Comment by ichard26** [comment] 2021-04-25 20:15
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:15 UTC
Labels: bug, duplicate, unstable formatting
