### ISSUE TITLE
Internal error when encountering consecutive fmt: off's

### ISSUE THREAD

**Issue by harrybiddle** [psf/black#1938] opened 2021-01-22 14:38 UTC
**Describe the bug** Black raises an internal error when it encounters a `# fmt: off` right after a `# fmt: off` if there is a dedent between them.

**To Reproduce** Steps to reproduce the behavior:

1. Create a file containing the following code:
   ```python
    def foo():
        # fmt: off
        pass
    
    def bar():
        # fmt: off
        pass
   ```
2. Run _Black_ on it with no arguments 
3. See following error:
   ```
   error: cannot format failure.py: INTERNAL ERROR: Black produced invalid code: invalid syntax (<unknown>, line 7). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: /var/folders/_m/s00h1rdj3m75ptngsv9tv52w0000gp/T/blk_klgdij_m.log
    ```

**Expected behavior** I would expect Black to exit with no error and no changes to the file. The first `# fmt: off` should have ended when the function returns, since there is a dedent.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Mac Big Sur / Python 3.6.9

**Does this bug also happen on master?** Yes, according to https://black.now.sh/?version=master

**Additional context** Black works fine if you add lines `# fmt: on` after the `pass`. However, my understanding is that this is implied by the dedent, and in any case should not produce an internal error in Black.

**Comment by ichard26** [comment] 2021-01-24 02:11
Hey thanks for the bug report! Unfortunately (or fortunately?) we've seen this behaviour before and already have a bug report filed for it (#569) so I'll be closing and marking this issue as a duplicate of that one.

**Closed by ichard26** 2021-01-24 02:11 UTC
Labels: bug, duplicate, invalid code

**Comment by harrybiddle** [comment] 2021-01-24 09:27
Ah, sorry for the double report! I did have a search for existing issues, but I must have missed that one



[https://www.sei.org/signature/SEI.png]<https://www.sei.org/?utm_source=email-signature>

[https://www.sei.org/signature/twitter.png]<https://twitter.com/SEIresearch>[https://www.sei.org/signature/facebook.png]<http://www.facebook.com/StockholmEnvironmentInstitute>[https://www.sei.org/signature/linkedin.png]<http://www.linkedin.com/company/stockholm-environment-institute>
        Harry Biddle
Data engineer
harry.biddle@sei.org
+46 73 805 5420
Stockholm Environment Institute

[cid:9-trase_f964f5ce-347c-4054-b236-d921a6e0a6f0.png]<https://trase.earth/>

Transparency for Sustainable Economies www.trase.earth<http://www.trase.earth>


________________________________
