### ISSUE TITLE
Inline comments shift strangely in multi-line function calls

### ISSUE THREAD

**Issue by bzoracler** [psf/black#2349] opened 2021-06-28 08:30 UTC
**Describe the bug**

The last inline comment in multi-line function call shifts to underneath the last parameter in a `fmt: on...fmt: off` block

**To Reproduce**

Running default `black` arguments on this code block

```
def f(**kwargs):
    pass


p = f(
    # fmt: off
    param_1=1,  # First comment
    param_2=2,  # Second comment shifts <---------
    # fmt: on
    param_3         =               5 # This line Needs formatting
)

```

Formats it to

```
def f(**kwargs):
    pass


p = f(
    # fmt: off
    param_1=1,  # First comment
    param_2=2,
    # Second comment shifts <---------
    # fmt: on
    param_3=5  # This line Needs formatting
)

```

**Expected behavior**

No shifting of the second comment line:

```
def f(**kwargs):
    pass


p = f(
    # fmt: off
    param_1=1,  # First comment
    param_2=2,  # Second comment shifts <---------
    # fmt: on
    param_3=5  # This line Needs formatting
)

```

**Environment (please complete the following information):**

- Version: 
- OS and Python version: 

**Does this bug also happen on main?**

Yes ([see online black formatter](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEwALRdAD2IimZxl1N_WlbvK5V9HvpcDm6xD0q-pSEWxlV0U3eVLkZLYY4vsFxU8rxnhpyBZKHgKIzq83dYnQ1xIhrEgubcypml47nm13WtMTEg8hdOqML-kzZCyVfxEgWHjjFpbkXb5r8rUrX329_SvVVoWFMGWoxAkksGiy6Hh5_ONipOVuotlW6_TYc6D5Rt3jcP2Y_zczpCEE7U58Gq-ARSS6LBssBkirUDGj7k5hVWyIUUqmhDxgAts1MFtO_LjwAB0AGxAgAA0xxBSrHEZ_sCAAAAAARZWg==))

**Comment by JelleZijlstra** [comment] 2023-04-29 01:59
Seems like a duplicate of #1245.

**Closed by JelleZijlstra** 2023-04-29 01:59 UTC
Labels: F: comments, F: fmtoff
