### ISSUE TITLE
whitespace before ':'  -- `if (ct := await cts.filter(tag=t).first()) :`

### ISSUE THREAD

**Issue by waketzheng** [psf/black#1235] opened 2020-01-19 12:44 UTC
**black version:** `black, version 19.10b1.dev16+g1ab87a3`
**python -V:** `Python 3.8.1`
**pyproject.toml:**
```
[tool.black]
line-length = 88
py38 = true
skip-string-normalization = true
```
**snippet after reformatted:** 
```py
# models/bill.py
class BillCell(BaseModel):
    tag: BillTags = fields.CharEnumField(BillTags)

    async def get_tag_display(self):
        t = self.tag
        if t in CustomTag:
            cts = self.bill.billitem.custom_tags
            if (ct := await cts.filter(tag=t).first()) :
                return ct.name
        return BillTags.get_label(t)
```
**$ flake8 models/bill.py**   # line 100 is: `if (ct := await cts.filter(tag=t).first()) :`
```
models/bill.py:100:55: E203 whitespace before ':'
```
Why the line 100 not reformatted as `if (ct := await cts.filter(tag=t).first()):`?

**Comment by emakryo** [comment] 2020-01-31 19:01
I saw a similar case;
```
x = [1, 2, 3]
i = 0
print(x[i + 1:])
```

black changes the last line into `print(x[i + 1 :])`.

**Comment by JelleZijlstra** [comment] 2020-02-01 05:54
@emakryo that's a different (and expected) piece of behavior, for which see https://github.com/psf/black#slices.

The original issue is a duplicate of #1174.

**Closed by JelleZijlstra** 2020-02-01 05:54 UTC
Labels: bug
