### ISSUE TITLE
Exploding short arguments after multi-line string

### ISSUE THREAD

**Issue by moredatarequired** [psf/black#945] opened 2019-07-25 23:00 UTC
Operating system: Ubuntu 18.04.2
Python version: 3.6.8
Black version: 19.3b0
Does also happen on master: Yes (tested on [black.now.sh/?version=master](black.now.sh/?version=master))

This might be a duplicate of #789 , and/or intended behavior, but I don't understand it.

*Input*:
```python3
msg = """
Message {foo} over three lines.
""".format(foo)
```

*Actual output*:
```python3
msg = """
Message {foo} over three lines.
""".format(
    foo
)
```

*Expected output*:
(no change)

If this is the intended behavior, could you explain the rationale? The style guide doesn't seem (to me) to indicate that black will make this change.

**Comment by zsol** [comment] 2019-07-30 19:39
Duplicate of #256.

**Closed by zsol** 2019-07-30 19:39 UTC
