### ISSUE TITLE
Internal error when run

### ISSUE THREAD

**Issue by Natsuki-gh** [psf/black#1708] opened 2020-09-15 10:45 UTC
black responds:
INTERNAL ERROR: Black produced different code on the second pass of the formatter

**To Reproduce**
test_file.py contents:
```
class AClass:
    def decode(self, data):
        assert data[0:1] == self.IDENTIFIER, "Error: Invalid message identifier %c %s" % (data[0],self.__class__.__name__)
```
$ black test_file.py
output:
"error: cannot format test_file.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_fk8mxhbz.log
Oh no! 💥 💔 💥
1 file failed to reformat."

contents of logfile:
```
--- source
+++ first pass
@@ -1,4 +1,9 @@
 class AClass:
     def decode(self, data):
-        assert data[0:1] == self.IDENTIFIER, "Error: Invalid message identifier %c %s" % (data[0],self.__class__.__name__)
+        assert (
+            data[0:1] == self.IDENTIFIER
+        ), "Error: Invalid message identifier %c %s" % (
+            data[0],
+            self.__class__.__name__,
+        )
 
--- first pass
+++ second pass
@@ -1,9 +1,7 @@
 class AClass:
     def decode(self, data):
-        assert (
-            data[0:1] == self.IDENTIFIER
-        ), "Error: Invalid message identifier %c %s" % (
-            data[0],
-            self.__class__.__name__,
+        assert data[0:1] == self.IDENTIFIER, (
+            "Error: Invalid message identifier %c %s"
+            % (data[0], self.__class__.__name__,)
         )
```
**Environment:**
black (19.10b0)
Linux Mint 19.3 4.15.0-117-generic
Python 3.6.9

**Comment by pazzarpj** [comment] 2020-09-17 13:18
I have similar issues
black, version 20.8b1
python 3.6, 3.7, 3.8
Agent name: 'Azure Pipelines 7'
Agent machine name: 'fv-az133'
Current agent version: '2.174.2'
Operating System
Microsoft Windows Server 2016
10.0.14393


[control.py](https://github.com/PyFixate/Fixate/blob/df4ed81b91d5909d58c725a42b681ef639291b04/src/fixate/core/control.py)
```
--- src
+++ dst
@@ -3501,11 +3501,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                'Discrete PID control\nThe recipe gives simple implementation of a Discrete Proportional-Integral-Derivative (PID) controller.\nPID controller gives output value for error between desired reference input and measurement feedback to\nminimize error value.\nMore information: http://en.wikipedia.org/wiki/PID_controller\n\ncnr437@gmail.com\n\n######\tUsage #########\n\np=PID(3.0,0.4,1.2)\np.setPoint(5.0)\nwhile True:\npid = p.update(measurement_value)',  # str
+                'Discrete PID control\nThe recipe gives simple implementation of a Discrete Proportional-Integral-Derivative (PID) controller.\nPID controller gives output value for error between desired reference input and measurement feedback to\nminimize error value.\nMore information: http://en.wikipedia.org/wiki/PID_controller\n\ncnr437@gmail.com\n\n######     Usage #########\n\np=PID(3.0,0.4,1.2)\np.setPoint(5.0)\nwhile True:\npid = p.update(measurement_value)',  # str
             )  # /Constant
         )  # /Expr
         FunctionDef(
           args=
             arguments(
```
[kbhit.py](https://github.com/PyFixate/Fixate/blob/df4ed81b91d5909d58c725a42b681ef639291b04/src/fixate/ui_cmdline/kbhit.py)
```
--- src
+++ dst
@@ -426,11 +426,11 @@
           body=
             Expr(
               value=
                 Constant(
                   value=
-                    'The self._ values indicate the user values as entered if valid.\nThe self.__ values are the sanitised values used internally in the system to parse between functions\n\nLimitations:\nThe function generator switches internal relays at certain thresholds.\nTry to avoid these ranges in design if the function generator is loaded with a relatively low impedance\nTable of ranges on the same relay arrangement\nMin mVpp    Max mVpp\n4           60\n60.1        199.9\n200\t        599.9\n600\t        2000\n2001        6000\n6001        20000\n\n\n:param instrument:\n:return:',  # str
+                    'The self._ values indicate the user values as entered if valid.\nThe self.__ values are the sanitised values used internally in the system to parse between functions\n\nLimitations:\nThe function generator switches internal relays at certain thresholds.\nTry to avoid these ranges in design if the function generator is loaded with a relatively low impedance\nTable of ranges on the same relay arrangement\nMin mVpp    Max mVpp\n4           60\n60.1        199.9\n200             599.9\n600             2000\n2001        6000\n6001        20000\n\n\n:param instrument:\n:return:',  # str
                 )  # /Constant
             )  # /Expr
             Expr(
               value=
                 Call(
```
[config_util.py](https://github.com/PyFixate/Fixate/blob/df4ed81b91d5909d58c725a42b681ef639291b04/src/fixate/core/config_util.py)
```
--- src
+++ dst
@@ -7840,11 +7840,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                'The only serial type instrument we use is the BK Precision 178x. So we just going to hard code\t\ncalling the identity method on that class.\t\n:return:',  # str
+                'The only serial type instrument we use is the BK Precision 178x. So we just going to hard code\ncalling the identity method on that class.\n:return:',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(
@@ -7968,11 +7968,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                'Create a backup of `file_path` in the same directory. Appends ".bak" to the file name.\t\n:param file_path:\t\n:return: Pathlib.Path object which is the path of the new file',  # str
+                'Create a backup of `file_path` in the same directory. Appends ".bak" to the file name.\n:param file_path:\n:return: Pathlib.Path object which is the path of the new file',  # str
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(
```
[rigol_dg1022.py](https://github.com/PyFixate/Fixate/blob/df4ed81b91d5909d58c725a42b681ef639291b04/src/fixate/drivers/funcgen/rigol_dg1022.py)
```
--- src
+++ dst
@@ -556,11 +556,11 @@
           body=
             Expr(
               value=
                 Constant(
                   value=
-                    'The self._ values indicate the user values as entered if valid.\nThe self.__ values are the sanitised values used internally in the system to parse between functions\n\nLimitations:\nThe function generator switches internal relays at certain thresholds.\nTry to avoid these ranges in design if the function generator is loaded with a relatively low impedance\nTable of ranges on the same relay arrangement\nMin mVpp    Max mVpp\n4           60\n60.1        199.9\n200\t        599.9\n600\t        2000\n2001        6000\n6001        20000\n\n\n:param instrument:\n:return:',  # str
+                    'The self._ values indicate the user values as entered if valid.\nThe self.__ values are the sanitised values used internally in the system to parse between functions\n\nLimitations:\nThe function generator switches internal relays at certain thresholds.\nTry to avoid these ranges in design if the function generator is loaded with a relatively low impedance\nTable of ranges on the same relay arrangement\nMin mVpp    Max mVpp\n4           60\n60.1        199.9\n200             599.9\n600             2000\n2001        6000\n6001        20000\n\n\n:param instrument:\n:return:',  # str
                 )  # /Constant
             )  # /Expr
             Expr(
               value=
                 Call(
```

**Comment by caio96** [comment] 2020-09-19 06:47
I also have a similar problem with the following code:

```py
class Visitor:
    def check(self):
        if a == 's':
            assert type.type.type.names == [self.typemap["array"], self.typemap["char"]], line + f"{var} initialization type mismatch"
```

And I get the following error log using https://black.now.sh/ with:
- master version (@811dec)
- stable (20.8b1)

```
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_wxlnuncb.log

Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,5 +1,7 @@
 class Visitor:
     def check(self):
-        if a == 's':
-            assert type.type.type.names == [self.typemap["array"], self.typemap["char"]], line + f"{var} initialization type mismatch"
-
+        if a == "s":
+            assert type.type.type.names == [
+                self.typemap["array"],
+                self.typemap["char"],
+            ], (line + f"{var} initialization type mismatch")
--- first pass
+++ second pass
@@ -2,6 +2,8 @@
     def check(self):
         if a == "s":
             assert type.type.type.names == [
                 self.typemap["array"],
                 self.typemap["char"],
-            ], (line + f"{var} initialization type mismatch")
+            ], (
+                line + f"{var} initialization type mismatch"
+            )
```

**Comment by ichard26** [comment] 2021-04-25 20:11
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

---

ps. @pazzarpj that looks like docstring handling issues, not the instability this issue was focused on. There has been a lot of fixes in this regard (e.g. https://github.com/psf/black/pull/2037 and https://github.com/psf/black/pull/1740), so I'd appreciate if you could test with what's on master and see your issues are still present.

**Closed by ichard26** 2021-04-25 20:11 UTC
Labels: bug, duplicate, unstable formatting
