### ISSUE TITLE
Internal error: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by 0ssigeno** [psf/black#1905] opened 2021-01-05 10:13 UTC
**Describe the bug** 
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

**To Reproduce** 
``` black internal_error.py```

Log file:
```diff
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,5 +1,11 @@
 def test():
     if True:
-        info_message = "md5 {} with status {}, evaluation {} was not removed because it belongs to the campaign" \
-                       " with id {}".format(sample.md5, sample.general_evaluation, sample.status,
-                                            related_campaigns_id)
+        info_message = (
+            "md5 {} with status {}, evaluation {} was not removed because it belongs to the campaign"
+            " with id {}".format(
+                sample.md5,
+                sample.general_evaluation,
+                sample.status,
+                related_campaigns_id,
+            )
+        )
--- first pass
+++ second pass
@@ -1,11 +1,8 @@
 def test():
     if True:
-        info_message = (
-            "md5 {} with status {}, evaluation {} was not removed because it belongs to the campaign"
-            " with id {}".format(
-                sample.md5,
-                sample.general_evaluation,
-                sample.status,
-                related_campaigns_id,
-            )
+        info_message = "md5 {} with status {}, evaluation {} was not removed because it belongs to the campaign" " with id {}".format(
+            sample.md5,
+            sample.general_evaluation,
+            sample.status,
+            related_campaigns_id,
         )

```
**Expected behavior**
Black correctly format the file

**Environment (please complete the following information):**

- Version: [e.g. master]
 ```bash 
ossigeno@cobalto ~ % black --version
black, version 20.8b1
```
- OS and Python version: [e.g. Linux/Python 3.7.4rc1]
```bash
ossigeno@cobalto /tmp % uname -o    
GNU/Linux
ossigeno@cobalto /tmp % py --version
Python 3.7.5
```

**Comment by mvolfik** [comment] 2021-02-22 20:01
Likely a duplicate of #1629 , as this file works after applying #1958

**Comment by ichard26** [comment] 2021-04-25 19:47
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:47 UTC
Labels: bug, duplicate, unstable formatting
