### ISSUE TITLE
File failed to reformat

### ISSUE THREAD

**Issue by KennedyRichard** [psf/black#3267] opened 2022-09-09 20:59 UTC
**Describe the bug**

File failed to format. Both the file and diff are attached to this message.

Error present in both newest version of black (used `pip install --upgrade black` to make sure) and [online formatter]  (https://black.vercel.app/?version=main).

**Environment**

Operating system: Linux (xubuntu 22.04 64bits)
Python version: 3.10.4
black.`__version__` == '22.8.0'

**The resulting error**

running `black main.py` produces the following error:
```
error: cannot format main.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_l5hj035o.log

Oh no! 💥 💔 💥
1 file failed to reformat.
```
[issue_files.zip](https://github.com/psf/black/files/9538616/issue_files.zip)

Thank you for your selfless work.

**Comment by KennedyRichard** [comment] 2022-09-10 13:59
Just another bit of information that might be useful:

The `main.py` file in question is a battle-hardened file which has been part of a [public repository](https://github.com/IndiePython/nodezator) and in use for many years, even before being uploaded to github a couple of months ago, so there's probably no problem with the file itself. At least none that I can identify myself.

Here's an additional link to the file at the specific commit where I tried `black main.py` on it: [main.py](https://github.com/IndiePython/nodezator/blob/73c910554d1d94c464aaa2e863d7308d95150444/nodezator/menu/main.py)

**Comment by felix-hilden** [comment] 2022-09-11 13:37
The issue is resolved ([playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4FHXF_9dAD2IimZxl1N_Wk8FsCt4z31aJ7Qq3Z7vK0W_0PbsenYir8AaSgUwEagCpGIPcr1AG6DclyxruyElIytl3DAY6wvUzkn6PrlsA56GyZPSb9v-4gTm3huQ2Z2lxbVihZsN1gfaDiDfIfyeNebAjOE1G_oiXgdPMVQBUbyVVn8d1tbezGc5lD4IgQY1nF0SpXIAdcstUEF8qId5v3MvnaIKFY5FNaroPGAf7De0HuhAGmGW1trdyllSguJAGV2zbYl9uYKxzxjVM3BVVnoGbdZ9YuTSZpCbGmfvHie7FdWRrOjxHeJeCglrjoD-73nHgxOO5hih5P2z3AFINpTinXQbdwgViFg5Z8e90PYnD4hmSsjnL5UAWw_MNvVtxdlphM1v6QmkwMj9DxcKwMZMymarFkPR06Ib53xlPz4m715XVNwr_bZa5giGgmYj47huDSiq7qjVIBjPaYrpWoY7sfDTIX2fAqZlWgB_tAbwPw09UkbxBi2D-gx3-BBpB5TsWQiFQ8FHuYVY0DtCG9UuREeD39wlbPjy8d0eioIE-CnmHXjeVFTp3Ntk-P5BP26J6JpNCm_VoU4fWTQ7_A62V2nz4GdJMD8PhU5Wf_C9rCWhrxjUJAuk9XGMFlbI3xt6Mqrs-aS7cIbBWCAfGjg5Tde66PHoMTBEx0qpbWa3yGeXL47M8EeE0VsqGOmM2tFusYdYSXjfKonBhtAZz6vOjNI8yyHwtPY5ixHlrJ6CDprln463CM9qTqNrcA1FCAN_6RzX7JiVylkM9dWBIdH_uF7qwLXmi4FbnZy2SRy36iSPvQLT_3gyaaf-x2bq1CNJ_ioYuVYP9c-Z7VQQxUZW2HVkpXDWEQvBB49PGv1ZkXH1pSqF37A8B9Ia3kWKhR6r_1E3_oAvStPZ-YJ9Z3FMSYGtKq3iUp0h1auYgRqzL5FTzA6nGw5gYTRzWehSCbWPD-bpikFfDls872EqufVtEe15kiAw7xsRKkTaPojs5KakcKL7oNBntBtJQ0hEaq19HC0OZTXjmBVuZT6y1mQbqs-vWkntv06m-QttVj6gBJumzTj9bPkRNGrK2gpcmrdNthx8kQY2H1GstWSzW2jusXmYfBmXrrV5QRdUCHwn5G4sJB-WA87Q257Wq7pg_NuyF69LkZVIhH-_gy5sMzLsIB1MZBQmj6ZHqeriP17lV43a5b1On7Z9afqDL0Jqn_n03dqXjjm581bMtjCjYie2zNTpK7P25iFhqrMbyk_0NrdCWzbi2R5ZQud7bdTEvVzxKCIdAYD7Ifr6aKjfAiwUtHY9qiQoVcUMfGy7O4gmYjcg_xrA5uz5Nw8Yo-vt68jZf5L2ggQTIwFZNwqkXJDK1n_FtG_FcDOfPyHYNqPJ5w_M5UPD9EZzEcX59tfTiBDzjqBq8uZre7UZS7YhzIqDz3vuXBY4pr5pl9gQKapUY1qfmNLA-BzaaK1cMGko-Tcga_4Dnpm05NOnjTbranDpCLRUIp1OuRGsP8yP7uZ7M7bcRB3CemfsYrpbcIoztZqN2SSiZPWTz4dqqr_bBz63alReD4NdgjycOVTR4iSRGk43F90mtkg4wbuM93Rbj7e9np20y3XlVthOb3TTIdePzy3YUx8z-9qwYCAlUbQq6BYuIdE4cNJroddYX1HBO_vW3q37eRoVjmqNGj1HafNUwy8bvYpXbk4IitSAaIqZ1yX8TVvSIRlIRtUKyhs2WzVfbQ92HTfTKsGFBBK1ZSNRGaw47ZKOUe7NnlEs9tpyg3hxs-y6VEbTt-Oqo_yfnMypRxb9fcnJLBLkvgiX6Wh8tXxrJx4Q2-RsRIa5Sclzb1S1XEvzPcuu08up16Aj945D7fv3ca_sQBX8h868gshrIG6UvnkO2IwtLJpLLEia5O3AlNCDC1x2NESmBjP-Ca0YaCh3h_PgTkMuTVJx43wdXUa7iJEqWE3iSXRojMma4zSvvqf7OwfCnDWkjyEXrxvQk5U8O_ZYAQ4ynoBaTyQEbAFKuTFz7vI5K4_xJ3_arbNwNsNgjUEJM3y4wFOwu2TC45n_QtCUZU4K6G2NVMRMKSpgLxMyJDPBQgVGb1b_a4ydvhncdLRN6ojo72fdMYB7V_4nI-GQUlBbFrwZS8kSTo9zYpK3ae-rlQstGF9mG1sKlFAeIl8F1raciglzwxwczYorD6VTaVN1BVG27rvUkGFE-rO9neTTxl6oqN8LJpiVOp0CZNswjiITtL3lgPJr-7fHFfF5JAKrDUxsEiZt14_Jp2wLSgRxGR4q0B7PSZHY3vfP08gI-y0ocUWur01fboHV7VEwhMRdIQ7fgOmBIXPV1I93fes0fzg9d8loWG7IP1mZSS-zaeLOPzYTlIsvyyY7VfQuPlDsuXXEZaeHt46XfVWfr269jfSwMrNKbW5WbMhR7V0pWDRE47r3Nn_cxgNfc1Qcb9jdbMl034ek-OxUujd-z11km6oRCqWW3gfa4tvLh99rHmww82jlAIBQ5dS5AwVDSg6-EviEKNg7iQNM0_hYe6raMI9sdSCFEaPreCTNNCeE5jr2yp0cE0QrEsNIa6y-ijauQfs1dcousnuuY-A87I9-l_N_NhMkMl5kb1CDJmYCq2WAlED3Qj_DdKupseIOSdGJj6tNkQ-L2MTzSng6hrMPJHrA9yzonzFMomYnV3NrP85bYJoctbNZKVEvACL6kCfEWtIgHZG1yM_uWOMaevWXN8e10TgDx70gNKUp3eQlk-n_stDm9IzDDStbeQbA7yHMJhZLl8ENCDAkTW5m8AJeiG5Djdo2HH2jMOFQYab7bVBqeLL5IaafTiWu3XQ8EBF1z8XRUDko9H1YEA3Z0jR0Yrkkyi45_oauZNYzRBcKQIl3qYwBlM5zccutPMwXyU5HPeNDXHjRdEsJOnwb5P91NQlpQXQprlGZrZy5jKepejJ4qJk80-8hO5zjwNTzAnd__eweZg8u0gTjKZsEx4scOJwp76KTPL5xyz1bGZKpr0XIRUpXmP8jRB1AavTxPOx-Nx3DzgRASy3rqC_zNmPwj8a2CeomJ_8koFw7zacR3tGtldDQ2TXKlCe1HHo0AcwCXoOSCcXOI0zi63y9cjtj1kXxYklkKLQLeg-n6lM4NppndXNK9G5wal0a9rE4yGKvGflyso9mEq7iKbMzHCAulZyI5L_lROkcRa0FHsDxMnJz6F8T2tYHMXE4dsldQyk9cj2qc6JzWayoQy-P2aGOQyJ7Lc0jQTMWDi3rq9jEGzBKJIt0Rcw96RINPwzzPbPjhTwn8mOkgu5KmlMCuyNNH6uHSvkhpSLHMS8Z5hi8JtHSZBE2tKmvCmyZvX0VVxZ-GEHwU-GlooGv71Bzf2CDxWFFqdyEx6Q3QUPOrAuBlWpPl7LwwHsp5v8_RwJEAygiIohKcVuvLpjzejOjRrCQLd9XtxaoT17h9iCiWZJ6wAbUU8Rpnd8JgnACe-kiTceBcOOy-mv1T2MTN-c3ex5fus23LIlpd-6101UjX_i4B8XOzM9OLW2aVtkFaOLCIymf5taS_vNl9sjhFwt03FR8DlDBDcUOdqUKZrPspwvdonJ885hI0JKJsQhXb2HgS-4mehNHK4K0-MrWaTclbQwN9_8A62Fb7M1SISZfccJY92cr5_ElkgRV840JNtRvzxg1Bf6pwuq4QZHD1NImx5vtXortYWIO6PRw4mwSUI017qIj5hpGeZhiduAZTGPT26ZCuX_fYNdXi9z973yB83TFDOntv1s5phPadkEfQvdgw-ZCF1H0wcty8lZuykMvoA8BwOJhnTJbxaf62tRN-ew4ESB0wTAKMVEH-Q3MScvPSzasyVXHGERan1RlnTx9i4d_v-kTrf3HqurFftyXr_292slhNZ4GpiCAtY4ljEvYg2-IDxvGhWg0N9b8p5uJVOcYfZXmXlav9NwVEtnlLxGlBUoCr2yNy6Qd2O6un4tnVbJofBw4x2kuJpShp58L9MO1y-MZ3Q9t6xLguy-5R5jnOMMPlRHaNEZGam12JdmnJ88cOlJfyLOqXfct2BAC8lOyZeUuRwwdPRbtvOUeVUXZ6y8L5ZQUNnhsujA8j1hhEzqCG07vKg7LHWrG2wncft1gecUTfjVqaRtwrZ7J1p6YfOZuuzjxrxoFYeU-SoWYkDXnrEG8NJMD3_uOfvIbE5vbg0ioHzN0rR8E_R5zqVVWESCC0mBMbX759zcGDFyVPhVpEneurdzaHAF0NUoaylRmx3kcr4NspnXx-omdyuthBAVmA2RWso5rwlYp1x6oBZN7tBC3vNGCHEapfg9MkhU6g00O9-Gz5wMW8Kj1pFHAeSLShBi4kOPxENLfOSOVNza6xMZM2C3kZ1WMbxUkR8mIov5vikeAfb1XpvwIkuw8Orsmcx7xplJDl6xSnWfrRdGXvnPhD9phthg6oAOipj0gOAvpDEkUMHlZanqU-dLclHR8nDkGAwCaPrHezOV2yS8pmd48tbOfZXMKcrrXf78Flou_6NjtvDBXG60xTlHH3tZHG6ARfZuOyoAT9gI-iAcMR11PdKki7ZrZyrUQj5L0BUfYTHCL8IV2mJXfq3Q_3KgrWXtWk3kr1bOVsueUq3C7jkXQtNiHyZwefShN7zF00IiMZ7ot2uUCR-GhPGQYKfe_dL-ZqQQ9CqpH4JIc87_0l9y0Ek03zB37R8J3fdslY51FBPSYTrLiTHLHHCR1wEZzyUxtWfrK9cTxKpl4GZIIfWAPEqtqzJORfg6G1qyB1lh580Mx10eeaGHEYXF7YOvJnowfCoxJ1BANLhH0hD3txQ8aESTTf7EJ4wOn3ifUL4e-cM7KquifrYGv_RjY05-OuyGm8T9TZfAdzXp4_DD-zkUuZDxKUjE2ioO5rtNHm0spZ6I_Uacz-T7soRPbDf2Wfu0--YnkkHP0ex7yRzUKyjViqenlGGrteFgcnVyQuE4-i9wLn-LhHTQ6bBVeFVxy1Mxq3SLbii9z1G9sHaFs1jhT2OpDy5Ao3KhA25WRP9Axng8FwP0cELAAlO61pnccdMnHa9G_IPYyY92TMvFUjhjArxnpu5YnExCs9itKA-UxKgw6hBSmp5GAEBY2n-P8C0zyPHkvj1lBA59cNyzDUijKkKn3h9cKDrYNSV9e4P5TCWDhpssK-LGCEChvB_StsaHEhXZMlx1f4N5fXiv9PUpFhFADqOgwV8dIjF9Cb3FBQzaB-U_6UBKJIpSVJiouWr6U-snJ85xKN82JjzlhnT6yLjG-XiIjop4Gn_H7VifVDzIh1t1Boys1mZlkdWKa4R24SAtGcpLaxpF6Df2yg6GUNrPdtWpEzs68RzWAQ0ricQ8C6MRInm5rplRWa2L2Ld6IjcHX7Myoizv7laWyB29nyWRluADn1wY-7RHAtw-_cD5OeCZpyGGum90BpJkr1_JlWX-IsO1RHxceoKbi1htO0UJiD9SZdBY5w0_WMK5juZ2mEg0gREq3nougHcrgHXavmmjEpmsbL7iHvyifb9CvJtV6ItITY5yiK-PRZR2lsPzxG-LJidokCNPMtiJa0aiogYHXHkAxWbI3ZrE_vd7LUPEUdMyB0DwGl76SNbjf2ZI0plioB1XgSNSLfEowf24xPHoS1sl0PeTS4P3ZsegEcIIMxfo3FUvypeBt7LDlbaa3lqD-oKvVN7IGkWI24ejRa1AefweD01zshVsI1L4CbU6QIDKDgAMXxeWK6B__gGahmS8G_a4XK1lZNdigWP4d_bkU4spkP-7SMnzox_MW9PPMRRyqd5cVMJkUhbGMQB72gogL4ZQp5uma9_go1RVQqVAKXzCKFgqzFFZomGhnPSA5zpTdp23OeMWjWqWrhiih-VmnpiNhr2cxMyT8jyDNCmEQPtuu4qA6dLrLjBg7mThpdPiIZ2Z_0bhS-qDPWdCzHEg_UlCcotADMRZU3xO278Oyyfar2Z8mTCsiu6gYZyAHLlpPDnW3ypPyFdR-PgBz6rSvaeV2XHkffLOyOnXi8B78sAF9y8jijizJalLvDFzZxJbVrfd7Kl06xcRKSMEUariVnaTafTwr1Yb-ULJbsnBdcmQiYZyAIDbumi2F47S2CK-BDSHBZzJON3i4PyIHqjqtl2PG-vuu7lUDEo9Xh48MO6Pvwvt5jOJe6Vf7h2Pydy8PCar6ZQ6rk97H8Xuq8pKqK9xfGhfQlgErZQnsnnH1d5Nm41jLocgeO7yNvya7IQjtiz1NSrR4uiZfBrf18h_g7q5tdLhUMLReQKBDLDMNYbHVrD7Y18WQCNwgAmC_nl-TfZxkg3JKfHqQ08Ps-D0j6YQcXqtWF7WmW3cN6nQ-8fW5HxC6OXGMPT_XE4RmOQsFYHyKNnGexYv8i5hl_ttLawel_lWkNnfmq2lz2qrs1UIei53fZsUKptZDiIjqZpYIHgRzpTUphGYU8MD0dwPruXLS5fe8HAbxf_LIV3SchL5pyu0xepMSV8oape8j5AikNFlAbfS0TegT6-Lr2JZmHNsTAvp3iLlDJqLoVeMVnuqdNToZMp__Hc-IaTACPnqXbI_jr7DGSp-HRe-7wDd7ssCcQ49GraReVMiF4x0tzs1nWaQFbTib1i2Y2J2sjQL1vQoWHBtc-0OkR3GZPNtLrJdWPbvo0fpyRPZ_qL07CqeCoUmYLxJw3xPST5-cFVhEF4eXOJ-X2Hcx40liWqcx2p4lchHtEAwmIpXkZJgfaqkRsum3WZ9tyEznaXSfXZuSSRkQ39v118b4Y8G-TrP1q0wjakQoC-V-Qvtn5vAlyfbksVVfXV0mfj3uWtRvKvbbX-cFGc47yG3KQnnc4xog3iBOibu9XpSBE-ZECfQxZpEEP6YaQdrwECniC2sDR7g6EiizqkMedq-KXWLZXNwQ0N96FsojIruGcT2eNOPxZOoBPIrgxnPGscRH3q4iDnu9Y2JOwm1_v48-QJfH9CDXIg_e-64yL9rlghpk4Xk4HsY_gbbiJGRPiLw_6dX5wR-bBy9u3gHXcTsNya0DgelHDBIdZ7D89NaYvSUDb8jj6RJra2_-3Ne-LHmbjfu9bps7ocsDdrHzC6FMfnyNOjMYYf26aedAUPwW49Bca0tpV-4RBDpWXXW-6oilhRMws6lpnmMfVnOQcUUCCCMKHCmbKaM5UNziqFzs9_v2mjFd_QvyTmueU9-3VLQPmJRH0tDgit0iKgobqMMfO5kMfBAfOGM7UtO-DWfoRRg_Z8GLCv3QcqVkNa4FspE5CAZbEDNEREVibGzVmG8PhjnV-JDYmqkFD2bswsyC-aRGJbp_MN1NECRxahau3y94hM96MQrC8x-FewrQ80CA7ake8-gPsy7RPjFsVAFZeEeow7sJ9hUq6iewoO4Ctd7r4HSEfC0KwX33V-avmkdtCqdCqH5hSryYnngeERBFoozvwZjqFi2_smv6cO-GbTtrmdEyo-Im6S2yCxq-lUXyul4TWPuvB6Dr9P2u8ggvUEJ2Q5o-KZ0BbM8iSRi3Sc0MJduDmLHN5Kz0lJG6zKWnXXInVjzniwpEsvJtqrbSm4_-3GnLvy--JToYLOJ6Z9x4KNsepkRB-5aUQsZCmhO-nLxVa7wjOvmVuj9kkeipe-goEFpLNN8qs1e7-mqs5bkhPLmDH7i9_7X2Em6cPqbgmVqt3sY1pEvrsmzUcU6ywdr81j_n2twlmNnH6H1PZqqgzxNYaXwdBulAoz1yaolEFQomuG7gL44BGlspzVRM2WKvByVXETRmkkRdYzT_t8x5HUmaGPU0IBB5KKRqiaeOvHDU3LGNTALBAV9ILTTsHnHJAbvOYLENsfQFOTVp_dZfOGYO7b3ptqkRtiTTEQ84vcqf3K3qu_ASjKZdvYuCJJoWVTH8h3CLP0zvlJ970tN2pJZ6ouIrzH_1SFnA0kUTaas-X8nraRRb6BoxKraUEZZx7vG2T6iC6R6f7IiLWN2mRdycNl7HBJvkbsR_x8gBlA4fbbuBJgns_3PKzbyEDfCgbGGFItnVEOt3Ouz9zy62U-_7BBk9oJmu_rhejUvJlUJHeuXHttUYIYHsVNL4u29RHextHVwC8VLqC-mrAxGs66PQIb-VPpQad9yqBiqLZcwFIbetU9kEAWQzr8OIk998o9ebLnc940ATFrr4qCpCiirv4gzSz7ETGYaskCC-9U35tDh9NkgwlSmCh2zBQizxOIq_qh9a4Zaoa4oEIelyu09CXDUAAADw7TEdJK7y7AABmzDYowEA1ckQNLHEZ_sCAAAAAARZWg==)) when the space after `\` in the class docstring is removed. This issue is already reported in #3079, so I'll close this as a duplicate. Thanks for reporting though!

**Closed by felix-hilden** 2022-09-11 13:37 UTC
Labels: T: bug

**Comment by KennedyRichard** [comment] 2022-09-11 13:48
After removing the character I'm able to black-format the file. I've subscribed to the original issue so I can be updated of the progress on the issue.  Again, thank you for your selfless work.
