### ISSUE TITLE
Move imports to top of scope

### ISSUE THREAD

**Issue by jcpunk** [psf/black#4073] opened 2023-11-27 20:01 UTC
**Describe the style change**

I've inherited some code with odd import conventions.  It would be nice if black forcibly moved the imports into lumps together.

**Examples in the current _Black_ style**

```python
import os

if a:
  import system
  print('here')
  import os.path

import platform
```

**Desired style**

```python
import os
import platform

if a:
  import os.path
  import system

  print('here')
```

**Additional context**

In theory this will help clarify what imports are active at a given part of the code without actually altering the AST. As I understand it, having the imports "at the top of the scope" is "the right way" to declare them.

**Comment by hauntsaninja** [comment] 2023-11-27 21:34
The example you've shown does change the AST (and semantics). As such, this is a duplicate of https://github.com/psf/black/issues/333

**Closed by hauntsaninja** 2023-11-27 21:34 UTC
Labels: T: style
