### ISSUE TITLE
INTERNAL ERROR: Black produced invalid code: f-string: expecting '}'

### ISSUE THREAD

**Issue by max-wittig** [psf/black#4151] opened 2024-01-12 09:09 UTC
**Describe the bug**

Internal crash

**To Reproduce**

Run the code down below

For example, take this code:

```python
  File "src/black/__init__.py", line 1476, in assert_equivalent
  File "src/black/parsing.py", line 140, in parse_ast
email = "test@example.com"
query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
    filter=f"mail eq '{email}' or startswith(userPrincipalName, '{email.split("
    @ ")[0]}')",
    count=True,  # required
)
```

And run it with these arguments:

```sh
$ black .
```

The resulting error is:

> [> cannot format file.py: INTERNAL ERROR: ...](error: cannot format whatever.py: INTERNAL ERROR: Black produced invalid code: f-string: expecting '}' (<unknown>, line 3). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: /var/folders/lg/s80890fd1ts6s1w69c8lg03m0000gn/T/blk_jssqz16j.log)

**Expected behavior**

It should format correctly

**Environment**

- Black's version: 23.12.1
- OS and Python version: macOS 14.2.1, Python (CPython) 3.12.1

**Comment by hauntsaninja** [comment] 2024-01-12 09:12
Duplicate of https://github.com/psf/black/issues/3746

**Closed by hauntsaninja** 2024-01-12 09:12 UTC
Labels: T: bug

**Comment by max-wittig** [comment] 2024-01-12 11:33
@hauntsaninja Hi! This is not 3.12 code. This is normal f string formatting.

**Comment by JelleZijlstra** [comment] 2024-01-12 14:56
Could you share what your input code was?

**Comment by max-wittig** [comment] 2024-01-12 15:25
As listed above:

```python
email = "test@example.com"
query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
    filter=f"mail eq '{email}' or startswith(userPrincipalName, '{email.split("
    @ ")[0]}')",
    count=True,  # required
)
```

**Comment by JelleZijlstra** [comment] 2024-01-12 15:39
That code is valid only in 3.12+, so Shantanu was correct in closing this.

**Comment by max-wittig** [comment] 2024-01-12 15:52
Okay sorry. I didn't know that I wrote 3.12 code
