### ISSUE TITLE
code inside fstring not getting formatted

### ISSUE THREAD

**Issue by jerryc05** [psf/black#3213] opened 2022-08-08 03:16 UTC
**Describe the bug**

code inside fstring not getting formatted
**To Reproduce**

 

For example, take this code:

```python
def fff():
    return 0
    
    
print(   f"asdasd {   fff  ()   } dasdasd"     )
```

And run it with https://black.vercel.app/?version=main:

The result is:

```python
def fff():
    return 0


print(f"asdasd {   fff  ()   } dasdasd")
```

**Expected behavior**

```python
def fff():
    return 0


print(f"asdasd {fff()} dasdasd")
```

**Environment**

- Black's version: 
- OS and Python version: 

**Additional context**

**Comment by ichard26** [comment] 2022-08-08 03:19
Hey @jerryc05 thanks for filing a bug report. This is actually a long-standing shortcoming of Black that we've yet resolved. To keep things more organised, I'll be closing this issue as a duplicate of https://github.com/psf/black/issues/567.

**Closed by ichard26** 2022-08-08 03:19 UTC
Labels: T: bug, R: duplicate, F: strings, C: parser
