### ISSUE TITLE
Change List[...] formatting on function parameter type-hints

### ISSUE THREAD

**Issue by jacobchrismarsh** [psf/black#1386] opened 2020-05-07 20:07 UTC
When a function has enough arguments to put each parameter on its own line, and one of those parameters is a List, Set, etc. with a default argument that is not the correct type, it gets very gross looking.

**Examples in the current _Black_ style** Think of some short code snippets that show
how the current _Black_ style is not great:

**Problematic style**
```python
def foo(
    really_long_arg_1_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: int,
    string_arg: List[
        str
    ] = "some_really_long_string..........................................",
) -> int:
    return 0
```

**Desired style** How do you think _Black_ should format the above snippets:

```python
def foo(
    really_long_arg_1_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: int,
    string_arg: List[str] = (
        "some_really_long_string.........................................."
    ),
) -> int:
    return 0
```

This is a unique case, but it is gross formatting nonetheless

**Comment by JelleZijlstra** [comment] 2022-01-29 16:32
Duplicate of #1765

**Closed by JelleZijlstra** 2022-01-29 16:32 UTC
Labels: T: design, F: linebreak
