### ISSUE TITLE
Support the Github Action Problem Matcher.

### ISSUE THREAD

**Issue by flavono123** [psf/black#3832] opened 2023-08-07 08:39 UTC
**Is your feature request related to a problem? Please describe.**

I want to add a [problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) for the Github Action.

**Describe the solution you'd like**

the official github action of "black" supports the problem matcher.

**Describe alternatives you've considered**

provide a matcher JSON for black.

**Additional context**

i did follow this, from a random python repo which implement the black problem matcher.
- issue: https://github.com/mlflow/mlflow/issues/5933
- PR(diff): https://github.com/mlflow/mlflow/pull/5984/files
but it is too simple, do not annotate line by line.

- tested result
![image](https://github.com/psf/black/assets/20619567/e7a256a7-aab7-451e-8fd8-cdfcc769b8d1)

there are more violations in the file but just annotate in the first line of the file

**Comment by hauntsaninja** [comment] 2023-08-08 05:24
Thanks, duplicate of https://github.com/psf/black/issues/1764

**Closed by hauntsaninja** 2023-08-08 05:24 UTC
Labels: T: enhancement, C: integrations
