### ISSUE TITLE
Internal error when formatting a with statement with #fmt off

### ISSUE THREAD

**Issue by ikriv** [psf/black#1737] opened 2020-10-02 19:11 UTC
Internal error when formatting certain 'with' statements.
[formatter_error_sample.py.txt](https://github.com/psf/black/files/5319847/formatter_error_sample.py.txt)

**To Reproduce** Steps to reproduce the behavior:

1. Take attached file 'formatter_error_sample.py' (remove the .txt extension)
2. Run _Black_ on it with no arguments (black formatter_error_sample.py)
3. See error: INTERNAL ERROR

**Expected behavior** No internal error, some formatted output

**Environment (please complete the following information):**

- Version: black.linux, version 19.3b0+86.g48afd8
- OS and Python version: [e.g. Linux/Python 3.7.5+]

**Does this bug also happen on master?** yes, verified online

**Comment by ichard26** [comment] 2020-10-02 19:54
Thanks for the report @ikriv! This appears to be a duplicate of #1286 (which is just another example of #569). Over-indented code generation due to `fmt: off` applying after of an indented block is what #569 is all about. That's what we see in the diff when disabling Black's safety checks:

```diff
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black temp.py --diff --color --fast
--- temp.py	2020-10-02 19:25:32.003590 +0000
+++ temp.py	2020-10-02 19:41:06.710511 +0000
@@ -3,7 +3,7 @@
         # fmt: off
         with some_long_expression_here(that_would_break_line),\
              some_other_expression():
         # fmt: on
             pass
-    def c() -> None:
-        pass
+        def c() -> None:
+            pass
would reformat temp.py
All done! ✨ 🍰 ✨
1 file would be reformatted.
```

<details>
<summary><b>My environment</b></summary>

* _Black_ version: `master` (283d999) 
* Python version: `CPython 3.8.5`
* OS version: `Ubuntu 20.04.01 LTS`

</details>

**Closed by ichard26** 2020-10-02 19:54 UTC
Labels: bug, duplicate, invalid code
