### ISSUE TITLE
Ugly line splitting for 3.10+ union type hints

### ISSUE THREAD

**Issue by NiklasRosenstein** [psf/black#3649] opened 2023-04-16 20:12 UTC
**Describe the bug**

I've run across an issue where the following code gets formatted not very nicely. This particular snippet should IMO already satisfy Black with `line_length=120`.

```py
def main(
    client: AppRole,
    role_name: str = Option(..., help="The name of the role to generate a secret ID for", metavar="ROLE_NAME"),
    secret_id: str | None = Option(
        None,
        help="A custom secret ID to use. If not specified, one will be generated.",
        metavar="SECRET_ID",
    ),
    metadata: str | None = Option(None, help="JSON-formatted metadata to associate with the secret ID", metavar="JSON"),
    metadata_file: Path | None = Option(
        None,
        help="A file containing JSON-formatted metadata to associate with the secret ID",
    ),
) -> None:
    """Generate a new secret ID for an approle."""
```

But running Black 23.3.0 over it gives an ugly split before two of the three `| None` parts:

```py
def main(
    client: AppRole,
    role_name: str = Option(..., help="The name of the role to generate a secret ID for", metavar="ROLE_NAME"),
    secret_id: str
    | None = Option(
        None,
        help="A custom secret ID to use. If not specified, one will be generated.",
        metavar="SECRET_ID",
    ),
    metadata: str | None = Option(None, help="JSON-formatted metadata to associate with the secret ID", metavar="JSON"),
    metadata_file: Path
    | None = Option(
        None,
        help="A file containing JSON-formatted metadata to associate with the secret ID",
    ),
) -> None:
    """Generate a new secret ID for an approle."""
```

**To Reproduce**

Run `black example.py --line-length 120` on the above snippet.

**Expected behavior**

Black should not split `str | None` before the `|`. There appears to be no reason to do so as the line is not too long.

**Environment**

- Black's version: 22.3.0
- OS and Python version: Python 3.8.10

**Additional context**

**Comment by yilei** [comment] 2023-04-26 04:25
This is a duplicate of #2316

**Closed** 2023-04-26 04:39 UTC
Labels: T: bug
