### ISSUE TITLE
Exclude property is not working in black

### ISSUE THREAD

**Issue by kunal5** [psf/black#1584] opened 2020-08-11 13:48 UTC
**Describe the bug** A clear and concise description of what the bug is.
Giving a file name to be excluded while running black via pre-commit is not excluding that file and formatting it.

**To Reproduce** Steps to reproduce the behavior:
`.pre-commit-config.yml file`
```
repos:
-   repo: https://github.com/ambv/black
    rev: stable # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    -   id: black
        language_version: python3 # Should be a command that runs python3.6+
        args: ['--config=pyproject.toml', '-v']
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args: ['--config=.flake8']
-   repo: git@github.com:pre-commit/mirrors-jshint
    rev: v2.12.0
    hooks:
    -   id: jshint
        language_version: 4.2.1
        entry: jshint squadrun/static/js/app/*
        args:
        - --exclude-path=squadrun/static/js/app/.jshintignore
        exclude: squadrun/static/js/libs/*
-   repo: git@github.com:SquadRun/mirrors-jscs
    sha: c7807cc8634375013f90942c5d927e3f7c55ab6b
    hooks:
    -   id: jscs
        language_version: 4.2.1
        entry: jscs squadrun/static/js/app/
        exclude: squadrun/static/js/libs/*
-   repo: local
    hooks:
    -   id: squadrun_linter
        entry: ./shell_scripts/squadrun_linter.sh
        name: squadrun_linter
        language: script
        files: ‘’

```
My pyproject.toml file
```
[tool.black]
target-version = ['py27']
line-length = 120
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
  | apps/core/migrations/0002_auto_20200707_1828.py
)
'''
```
Here I have explicitly given the name of the file to be excluded i.e. `apps/core/migrations/0002_auto_20200707_1828.py`
3. See error
This file is not excluded. Here is the snapshot for running black command. `apps/core/migrations/0002_auto_20200707_1828.py` got successfully formatted.
<img width="694" alt="Screenshot 2020-08-11 at 7 14 49 PM" src="https://user-images.githubusercontent.com/15965156/89904935-24e39d80-dc07-11ea-9f4e-378403042291.png">

**How can I fix this?**
Please help!
Thanks!
- Version: stable version
- OS and Python version: [e.g. MacOS/Python 2.7.]

**Comment by hugovk** [comment] 2020-08-11 13:52
I'd guess it's a problem with the `exclude` regex. 

Try changing it to something of this form:

```yaml
# ...
    -   id: my-hook
        exclude: >
            (?x)^(
                path/to/file1.py|
                path/to/file2.py|
                path/to/file3.py
            )$ 
```

See https://pre-commit.com/#regular-expressions

**Comment by kunal5** [comment] 2020-08-11 14:13
@hugovk , yes this is working but in this I have to explicitly name each and every file... there are 100s of migration files which I want to exclude.... how can I do that... something like `apps/core/migrations/*` is not working

**Comment by hugovk** [comment] 2020-08-11 17:38
Ah yes, you're already excluding from Black's config in `pyproject.toml`, so ideally there should be no need to duplicate that exclude for pre-commit's config.

But the Black exclude list is ignored when run from pre-commit. This sounds like a duplicate of https://github.com/psf/black/issues/438.

There's a few suggestions in there.

1. https://github.com/psf/black/pull/1032 added a new `--force-exclude` option to Black, you can change your Black `exclude` to `force-exclude` so it will always exclude despite whatever it gets from pre-commit/the CLI. However, this was only added to Black in March and hasn't been released yet (see #1583/#517 for the next release).

2. I think the best for now is, if you're only calling Black through pre-commit, then move your exclude list to `.pre-commit-config.yaml`

3. (There's another suggestion with `args: [.]` and some other options, but it's not recommended.)

**Comment by kunal5** [comment] 2020-08-11 17:55
@hugovk  But exclude is working fine in python3 project but not in python2. Can this be related to python version as well ?

**Comment by hugovk** [comment] 2020-08-11 18:04
Black only works with Python 3.

**Comment by kunal5** [comment] 2020-08-11 18:05
No... it only wants python3 environment and it works for python 2 files as well. It is working in my case

**Comment by hugovk** [comment] 2020-08-11 18:12
Okay, it shouldn't matter which sort of files you're processing with Black.

I suggest you do number 2 above, or if that doesn't work, create a minimal Git repo of your setup to demonstrate.

**Comment by ichard26** [comment] 2020-12-13 01:56
The solutions provided by @ hugovk are correct (`20.8b1` has been released so you can use force-exclude). Given that there is no response from OP and nothing actionable for us, I'll be closing this issue. 

To OP: please reply with more information (a reproducible case would be ideal!) if you are still hitting your issue

**Closed by ichard26** 2020-12-13 01:56 UTC
Labels: bug, command line
