### ISSUE TITLE
Unexpected behavior on `# fmt: off`

### ISSUE THREAD

**Issue by kenoss** [psf/black#2179] opened 2021-05-02 14:36 UTC
**Describe the bug** Unexpected behavior on `# fmt: off`

**To Reproduce** Steps to reproduce the behavior:

See https://github.com/kenoss/pyproject-indirect-import-detector/issues/1 for description and logs.
CI result: https://app.circleci.com/pipelines/github/kenoss/pyproject-indirect-import-detector/20/workflows/8a28ef32-2449-4fac-b779-f32f763fd66f/jobs/73
code: https://github.com/kenoss/pyproject-indirect-import-detector/tree/3387f880e9dcf4a420f65bd62267df202bf8004c

1. Run `poetry run pysen run lint`

**Expected behavior** Lint without errors.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Ubuntu, python 3.9.

For more details, see CI.

**Does this bug also happen on master?** To answer this, you have two options:

Yes.
https://black.vercel.app/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AZQAopdAD2IimZxl1N_WlwxRhR7MSgE-ANVleJ-rgTrlRI7Fy_DC6Yqfx_V25y6ijjUbSUqpEaTvG6PKMySx1Oib_-pFT2VqC5I55ge_rwfP0iZG5w3a44eurFTwcte416Fc3Ej2UUyvZE5plHlwcIGt-QUzkopx6Dmsvg3rSDYZhtm9zLsyQPRQDMy8GmtbNVGU5Fg4QGBebt8W1HSf0ENdSeMP44n-PDxHpxvawPTU3ZrcD_BtsKYpOvLV5guGmPcrZe6GI0mSQviJoycgBLFmMVUqMCfh4IEPwqIoAkgsGpFaUBgl47qDDYjRKDO21MRpfbvF9VR8JnP3fb_rqnOe0DgMOTkJbBhurstI1L0ey8TpJk00IaowQO0HEWysPV-1sJWzyTBeciEtkBfW34md5FhGL-bKnL_SbeSW52SSb5MPtAHEsjhAc3i9bCTf-CYxY3AenzcghFYVWNzgFrXp5iNgcgCKYbluq-t376Wz_oq2kTYWw-KnuImU1l3ibtoqBzBLD-IXS9Xrp1U34EhEkZtUYn_NdWn_1z39cRnbadKgh7qdesr5coF5zkMkafLVKEVee2_49CEZm8xTADU7neWMdd3qIhUI0775a3I3j2h91BFfJe8ehkWFHLyilfk0iQ47XT8Lvf6ErAAMzzqXiym5AfisMuNho-k67rFUeOvjaYU2alqrqZZ32J7wjfc_c9OWxokCyntuWmelgRYmKZ5rpFT6HTNmU4b4dySIVWld1h8fZrjcHlUCTMZUQSCMCc6znTwdqwQsrU11fwV-efCnM8hxpgq3yEgT8lqcHXJ1FmpXPfZZHyq7D4OtOtr-9175Wt_Fw6OAUPnr5tCclN9nlYCe6XS5XHm-roAAAAADMs4bRNxLgYAAaYF0QwAAMaOAlOxxGf7AgAAAAAEWVo=

https://black.vercel.app/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ArFBHVdAD2IimZxl1N_WlkPinBFoEmuTTvQf-76aGuocxle33mGRp_tNMPxYwcNh9hg-CzWFaGfKDX9xabxdGgds2emWephOupamgeoQxcojx4_DTYWnlaODu6FQ5SZ1bxwMu9UIL66mvLMXQn2tJFV5CL6sebl5iltvNGiFt8o5UX8g9SMcOrhX813CNSSPWo8RfDaUHQQ5GY4rXc89SZjY-j1Ep2ZZVKSnEbKBCR3l9nntrlMe_zJLdgHR76Vot43HKfCykz5py2stOweUs5ZfIxHtFBpLfq6g0AuQgY7lKCGtlf74tV4RP0MLtXVajv1HcdYMuLTLVMGQ5Q8yiKqsngsfvpF-orUUVM_5oiHeFSsRgkJMoSDO0IWshDZjUHiKCfY1NMt1fnOrcQGiRKm74enFK2oZQz_plWj4F08PK3NynAoV9o9kCfF0hWicGYED9qP-4QezyV36v6QsSGgxIh7PHBe5yO5w1GmXu1IKzAf5zHhygkNAFS7UBe2fSiFwikcljJfd770vNh6SyQ_wF-7-kxVRVVDRAQ18xPHbbDjNDhOaBI8FGdCvSbB9zeae1EL1OIFuLtc6wCRw4GNmJoBC_gygwOLadQDwQcooEuHLYqVbeZTfHlKhaoQgxgB10bICmVgY2QJ5shUokCgMHSW2dR7Rhac4ucsMmFwasSVGdzLSLbNv98cVWSteZnt-Ku5PwN2UwXe1MG_pXx4czvCYYU795SnYGoCGCMBkFUCp0vPGN0MTX4YeX5C1w_QUO7ftacpdWAP2-U2jM-yA8d62VHV71o06gBmgHuFIhhzom_Lc3qYPOy-J-ZhS1b_EEHD5HA5jjttcydnRX5W8rLYKqrOQFmPE2AXGKhgqFXem2Hl_Dbrj-ZWxDmE3eSvRgFKSbik53vdwN8CV7rCbaWuojegizhiqjZ8xQIlRBaaznMRfc-NgrWwfvlKXzRIXIKDSjF69h9vMaiNvCBEd2OiOsS5Oyijt20n9zrDotL7Blg8fEW14GQOP-xQm-n0pi58Zn_IHLi2L3hJyiShWZLa6GyA6ZOXB5beAf6tRPBLrIFUTWFVTftKYaZWwS4utHZ9_dOSYAJB61_eePxe7eL28zZ4WVAiV_e_dgV7JIZku4CGoFwwIsITw4FHTsmv9BSDDZnqJ87JFEB5th5Oxhc1C8uX8q6IaD7XqmRfBwDI7TJvzi0w0RJMyITFsZ_IN2EWeFgBL1Lhzj2qP8Q0-U61sKjD3x6haaYVE1yuzzTUmG4W9r278eax3kQ_Ah3LBysQQRvp17z6UVAz-B3XH8V8zBY3TU_0rsc1_2NT0L7BgJofXjHYBlVbcINmZOkGjJnbWcWNeunqCobyWfrOcb_pjtVRXsigCEVQUa2jVbTguW1UVVJTEwbvd2ZLHKsiZOGQfz32yw78kZ965SQb-TwXzkauu9-7R5Tjzm9VYqjag4EXbslH3eOPqvQ3YA1iE3MoTPMuN2iAypdmhaQRPhN1qY_ODpAo4bBx0Sm49HmA0G1FdGCjm1AAAAAA4lWCEDqPVnYAAZEJxhUAAAujtFGxxGf7AgAAAAAEWVo=

https://black.vercel.app/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4Bp4B3tdAD2IimZxl1N_WlwxRhR7MSgExKg_39haIOkvzh2I7RRGxN74OUWVgdYiA7brJptCv8HGCgbpkutdiBV5o9WJca3b2ltY8Hpf03lkqphMQ81zMW--qtvXzCsQNaLNZi0NDlTku8PRIe0IrpYRmlAAAxZAn2IBHpFsMx97Gl9sMUdSToSwoxVL3He1Z-IevpBfUhtQWEz2zawe9hQh9cnjdQzL9DuKQHEpZTKV1-WJFucrw0FG8y3P_IDRNAN5Epg_aXi1Nw2JcqKq6iYAg-UC507HX9lB55iGIsjPVLwsJUrdnxSJpxlheYBHVe05Q8vVshuOAaNg9ppiCZ_w0A1SrY9t0MiQSvLB_wIlwOcG_SDJ2Sha9YMRPNWiaM46pLfN_7fXN_PcNhZTXdun7OTnZWZGSrJnr3MXQTkMRq1TgWgcr74tjyBsTP-ZEaiIwykXX3kY57AQoKnIjVXksZ7_sGD3WjqDG-UfE75I6-xrih3MyUELhN-eks_EwPekkQcjxr9_Sg0b6-doCBOhdocRL48j_S5nUPOW3BAoVRn46DXBWRX1qUBVgMpXWRP66jpB3bvRq1-RAeJfwX1d-Q2YyeclNAYFgmSJ7byGz1_vGI_e9U_nhOqgHEBzkj4n88EObRnM5Hwy6p-KykQtFdCUzIL0UYPsgT5fxN3B_yd1F0aSYSjf1WZ1vk1MVvVhMh_NPpp5DPwL-FlfEVeveUxCLCpGdN2UD8nWQU6Awr5dsJM2YfmR7vJEd7d74P0tuIVgjNjxlhfwHgw49vpcDyMcIRHL9-6ANwaPKC8IuNoY8lerpKwudm9nW479gxZRUmER1fhO4wOgoHaVrAZbX2ibdHbex-ensoBIgsD2o-vgrArzqh1zYodsHSxwqdPpl8uLRgWb7z9X_uZeJAKvKnXVEnRYOrEWx8Z7wv1LXw9mPO9SwkVeBg3q_13r50AwMVsiEb0OTJMPZbpi-uYqVIGkwZNVXJ-7OFrKjtitDa86KYWYMK3fKp8_tRhw6ym9ADNqr2VFq-nhyj-CQq59Sjt6i8GDQ9bLLC0awjlaGhr6D_Hko906BFBUUqNAI6lpIGpVKl9tnTdDla99x82DXdCf4ViQeVY4urDJ3DNCCoVxVCWLyzZF4vrscn02KYIQSENgrPpK7fsR6ADJMAHyZHZBWMsqIAsFq4YCW9PCJCieuExBsH-CU7b5PBAbu1-KLmKbFJ9pfZ9IHkMRzq_cg_dJ0zS_pbFDahVbFSHMPzcXfDW4DqqRcR4jFXuXxBthqnuxSuzUtViE06MzlwuwimZNg6OK8cE_Fdu-e-LMC_GXDbMlvNroTIHXDnvr97KcTQvnt7iN2opv7tJDRe8sIiL44nAI7k9kgNB6qegL4Fui1guLWVT1vScG1HUzzWpJPEDiP_XG73g6SYuXP5Ku3uMeWzmWPmDS9qmEZRCcIe7L_jurM0ZEvpDsAqrIdoIjDlyzCcl7zl9yT5KDeZbkxSRCDU2WVomYnvNv4RXXbCYhf6oprGSWHMM-kZaZtIsUazisbiUFYz7IK3tvnWU2Hn3_W_L-I5cDD3SVIVsTpwU7BthW_WAXLyieU0144jUBCan3D0kpN7HJHQqiEdyFzGHZ8yhIqirjOMmPqIAk38L_z4nHputlAjO8kbOKJLnUxkdaCMeCcUdlq73gAr21mfz1pyeowwyg7AqNX6YrWWf1cXidu-hH9eyiKvLK9P3dN19MfP82puB6zifWpi3rbjmAZwqjSh91nS9m1a-LZ0vRCBsLUAXM27_07bvnlt1Qq-87UBzzcCQF-upAXT4X1uotl1tbktVO6itAe1ys5QSfPjrqypX61DtNtz0fZFwik1LjQ48NmNsVFbAMXUanAptLrH9u57S62ffe_Is3oDn7YhIWZEVraLvs0wrsztmDSd30O8tRut_1b6QUWsJ47CSqI904tYNpP-z20SiRRbgPj1h-8RnnkV713jj5xnaFAZ__I8mDl18qjjevhFyDXNtfawCTq4NbYJfn0oNK8uenYGgKIu4AoHSkm68rFwEK2yEUkXQ3argp9WErqFoIjKoNM7hBLr8VbfoxLsMuHcir3erFusOq-euHZN3kg7TkzhODW82KKx5QTn3aA_RwzBfu69_4qD462PPiBDvXrHv7nNmdyAUSBC3OlCY37F6Y2vyY4qX1YXBgsIjnFIov5HdFfs5aWs_puBv3LPZdH3C8F4Mh6uB772EZp3Kdg1rklGjIrs_OqT5kOa-LoHf0-lQzvPVxgpLJiPnNNbDwVv1n7JfgAc8Fz3i_asvxiZmetsnY3kynM_TVfjVCatPgOR6NzqzQpeDIvzEZnWOVXpL31bW1FXEhkyTwUyb_dQG9SRloHKiiy-IdDXn6aGhwt-r_6CZ_S9tS6HXCohYJECMLcE3sWJoMVPXfZMW7CtLKvgZmq_-YnhRn0D5DQAMibRO6Llp70KwOPOIjvnYOlHs8KGAl6gZeNf3L9_4Ecuo5J7oZORtf9GhLOcETFpx7NoLaJHy3KmdJsII65aOwlw6RCtJt9tjJKiWkTBbqyM4AAPavyhp2VkWVAAGXD_k0AACWcWqZscRn-wIAAAAABFla

**Additional context** NaN

**Comment by ichard26** [comment] 2021-05-02 18:16
Hi @kenoss,

This is a very common issue, so I'll be closing this as a duplicate of GH-569. But in short, the issue is that Black accidentally increases the indention of any code that follows a `# fmt: off` that is untermined and falls off its enclosing function scope. Closing any `# fmt: off` with `# fmt: on` in the same function should fix your issue.

I hope that helps, thanks for reporting!

**Closed by ichard26** 2021-05-02 18:16 UTC
Labels: bug

**Comment by kenoss** [comment] 2021-05-02 19:46
Thanks for the quick reply and helpful information!
