### ISSUE TITLE
Black confusion when \ is used in f-string expression part.

### ISSUE THREAD

**Issue by gmos** [psf/black#2295] opened 2021-05-31 23:20 UTC
**Describe the bug**

In:
```
print("this is ok")
print("this is ok")
print(f"this is an error {1}")
print("this is ok")
print(f"this is an error {'\n'}")
```
Python reports error on line 5 but Black formats without error.

In:
```
print("this is ok")
print("this is ok")
print(
    f"this is an error {1}"  
)
print("this is ok")
print(f"this is an error {'\n'}")
```
Python reports error on line 7, but Black reports error on line 4.

**To Reproduce**

See above.

**Expected behavior**

Black reporting error in both cases on the correct line.

**Environment (please complete the following information):**

- Version: version 20.8b1
- OS and Python version:  Windows 10, Python 3.9.0

**Does this bug also happen on main?**
No, for both samples an error is given. However, no line number is reported.

**Additional context**
None.

**Comment by JelleZijlstra** [comment] 2021-06-01 00:35
This is a duplicate of #423 and #1263.

**Closed by JelleZijlstra** 2021-06-01 00:35 UTC
Labels: C: parser
