### ISSUE TITLE
Issue with the "Magic Trailing Comma" in collections in function calls

### ISSUE THREAD

**Issue by scolby33** [psf/black#1433] opened 2020-05-18 16:05 UTC
**Describe the bug** Trailing commas are left in collections that remain on one line in a function call
**To Reproduce** Steps to reproduce the behavior:

1. Take this file:
```python
test_call(
    {"some_key": "some_value", "other_key": "other_value",}
)
```
This also happens with the set literal `{"some_key", "some_value", "other_key", "other_value",}` and the list literal `["some_key", "some_value", "other_key", "other_value",]`.

2. Run _Black_ on it with these arguments `black black_test.py`
3. See error: the file is unchanged

**Expected behavior**
Based on the [documentation on trailing commas](https://github.com/psf/black#trailing-commas), I would expect the final comma after `"other_value"` to be removed.

> Unnecessary trailing commas are removed if an expression fits in one line.

This case doesn't match either of the stated exceptions: it is neither a tuple expression with one element nor a function signature with a `*`.

Based on the [documentation on the magic trailing comma](https://github.com/psf/black#the-magic-trailing-comma), I would expect the dictionary literal to be expanded to multiple lines.

> Now, you can communicate that you don't want [the literal collapsed to one line] by putting a trailing comma in the collection yourself. When you do, Black will know to always explode your collection into one item per line.

**Environment (please complete the following information):**

- Version: 19.10b0, installed via pipx
- OS and Python version: macOS 10.15.4 with Python 3.8.2 installed via pyenv

**Does this bug also happen on master?** Yes: tested on the Black Playground

**Comment by ichard26** [comment] 2020-05-18 16:08
Seems rather similar to #1169.

**Comment by scolby33** [comment] 2020-05-18 16:13
Agreed! Please close as a dupe if appropriate. I missed that issue in my search before submitting this.

**Comment by cooperlees** [comment] 2020-06-16 22:51
Duplicate of https://github.com/psf/black/issues/1169

**Closed by cooperlees** 2020-06-16 22:51 UTC
Labels: bug
