### ISSUE TITLE
Unstable formatting in long assignment expression with square brackets and parentheses

### ISSUE THREAD

**Issue by jtv8** [psf/black#2093] opened 2021-04-08 09:02 UTC
**Describe the bug** It is possible to produce unstable formatting when _Black_ tries to break down a long assignment expression by expanding both square brackets and parentheses to span multiple lines.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file:
```
if True:
    if True:
        if True:
            if True:
                if True:
                    twelve_chars.loc[
                        twelve_chars.Attrib == 'ABCD',
                        ninechars + 'SevenCHR' + four + '_X'
                    ] = (some_numerator / denominator)
```

2. Run _Black_ on it with these arguments: default arguments
3. See error
```
error: cannot format <REDACTED>.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: <REDACTED>\blk_dr8xohwx.log
Oh no! \U0001f4a5 \U0001f494 \U0001f4a5
1 file failed to reformat.
```

Log output:

```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -2,8 +2,8 @@
     if True:
         if True:
             if True:
                 if True:
                     twelve_chars.loc[
-                        twelve_chars.Attrib == 'ABCD',
-                        ninechars + 'SevenCHR' + four + '_X'
+                        twelve_chars.Attrib == "ABCD",
+                        ninechars + "SevenCHR" + four + "_X",
                     ] = (some_numerator / denominator)
--- first pass
+++ second pass
@@ -4,6 +4,8 @@
             if True:
                 if True:
                     twelve_chars.loc[
                         twelve_chars.Attrib == "ABCD",
                         ninechars + "SevenCHR" + four + "_X",
-                    ] = (some_numerator / denominator)
+                    ] = (
+                        some_numerator / denominator
+                    )
```

**Expected behavior** 

Either of the following outputs would be acceptable::

```
if True:
    if True:
         if True:
            if True:
                 if True:
                     twelve_chars.loc[
                         twelve_chars.Attrib == "ABCD",
                         ninechars + "SevenCHR" + four + "_X",
                     ] = (some_numerator / denominator)
```

or

```
if True:
    if True:
         if True:
            if True:
                 if True:
                     twelve_chars.loc[
                         twelve_chars.Attrib == "ABCD",
                         ninechars + "SevenCHR" + four + "_X",
                     ] = (
                         some_numerator / denominator
                     )
```

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Windows/Python 3.9.2

**Does this bug also happen on master?** Yes

**Additional context** None

**Comment by ichard26** [comment] 2021-04-25 20:33
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:33 UTC
Labels: bug, unstable formatting
