### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by VorpalBlade** [psf/black#1878] opened 2020-12-22 13:48 UTC
**Describe the bug**
I got the following message:

```
error: cannot format SmartSketchMirror.FCMacro: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_3y73wcv0.log
```

**To Reproduce**

1. Take the attached file after unpacking it (extension indicates a FreeCAD macro, it is a normal Python file otherwise)
2. Run _Black_ on it with no arguments.
3. See error (log also attached)

File that triggers as well as log:  [files.tar.gz](https://github.com/psf/black/files/5730134/files.tar.gz)

**Expected behavior**
I should not get an error, and it should produce a sensible reformat

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Linux: Ubuntu 18.04, Python 3.6.9

**Does this bug also happen on master?**
Yes (tested with  https://black.now.sh/?version=master)

**Comment by VorpalBlade** [comment] 2020-12-22 13:54
I tested 19.10b0. That version works fine.

**Comment by MikhailZex** [comment] 2020-12-27 07:46
Have the same issue on select files. Here's the diff of one of them - [black diff.](https://gist.github.com/MikhailZex/98733289fe585ab7c0d48c3325803fc6)

**Comment by ichard26** [comment] 2021-04-25 20:05
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:05 UTC
Labels: bug, duplicate, unstable formatting
