### ISSUE TITLE
Cannot parse f-string.  

### ISSUE THREAD

**Issue by Hendler** [psf/black#4046] opened 2023-11-14 11:43 UTC
File can not be formatted

```python
from datetime import datetime
created = 1699960500
dt = datetime.fromtimestamp(created)
a = "hello"
n = "world"
print(f"{a}. {n} ({dt.strftime("%Y-%m-%d-%H:%M:%S")})")

```

And run it with these arguments:

```sh
$ black file.py
```

The resulting error is:

error: cannot format file.py:
Cannot parse: 9:35: print(f"{a}. {n} ({dt.strftime("%Y-%m-%d-%H:%M:%S")})")

**Expected behavior**

Passes black or makes correction.
 Perhaps this is resolved elsewhere. e.g. https://github.com/psf/black/pull/1132

**Environment**
 
- Black's version: black==23.11.0
- OS and Python version: MacOS 14.0 (23A344) , Python 3.12.0

**Comment by JelleZijlstra** [comment] 2023-11-14 13:31
Duplicate of #3746. Note this syntax is new in Python 3.12.

**Closed by JelleZijlstra** 2023-11-14 13:31 UTC
Labels: T: bug
