### ISSUE TITLE
Error when running black in the env with Python 3.6.0

### ISSUE THREAD

**Issue by mariosasko** [psf/black#1739] opened 2020-10-02 21:01 UTC
**Describe the bug** 
In the README, it is specified that black supports Python 3.6 or higher

**To Reproduce**
1. Use environment with Python 3.6.0 installed
2. Run: black --check --line-length 90 --target-version py36 src tests examples
3. Error:
```
Traceback (most recent call last):00:00
  File "/usr/local/bin/black", line 11, in <module>00:00
    load_entry_point('black==0.0.0', 'console_scripts', 'black')()00:00
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point00:00
    return get_distribution(dist).load_entry_point(group, name)00:00
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point00:00
    return ep.load()00:00
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load00:00
    return self.resolve()00:00
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve00:00
    module = __import__(self.module_name, fromlist=['__name__'], level=0)00:00
  File "/usr/local/lib/python3.6/site-packages/black/__init__.py", line 57, in <module>00:00
    from blib2to3 import pygram, pytree00:00
  File "/usr/local/lib/python3.6/site-packages/blib2to3/pygram.py", line 13, in <module>00:00
    from .pgen2 import driver00:00
  File "/usr/local/lib/python3.6/site-packages/blib2to3/pgen2/driver.py", line 39, in <module>00:00
    from . import grammar, parse, token, tokenize, pgen00:00
  File "/usr/local/lib/python3.6/site-packages/blib2to3/pgen2/pgen.py", line 7, in <module>00:00
    from typing import (00:00
ImportError: cannot import name 'NoReturn'
```
**Expected behavior** 
black should run successfully

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Linux/Python 3.6.0

**Does this bug also happen on master?**
Didn't check this.

**Additional context**
From what I see, the issue is that `NoReturn` was added to the `typing` module in 3.6.2. So maybe the README should be updated.

**Comment by ichard26** [comment] 2020-10-02 21:05
Hey thanks for the report @mariosasko, but this is a duplicate of #1666!

**Closed by ichard26** 2020-10-02 21:05 UTC
Labels: bug, duplicate

**Comment by mariosasko** [comment] 2020-10-02 21:20
Yes, found the original issue so went to close it myself.
