### ISSUE TITLE
Indentation of method call after multiline string

### ISSUE THREAD

**Issue by Samrose-Ahmed** [psf/black#2028] opened 2021-03-08 06:53 UTC
Note: Reading the docs, not sure if this a bug or style request
 
**Describe the bug** 

Black oddly indents method calls on string after long multiline string. A very common python usecase it write a long mutliline
string and follow it with e.g. `.replace("\n", " ")`.

**To Reproduce** 

1. Take this file '...'
```python
long_text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
make a specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\
""".replace("\n", " ")
```
2. Run _Black_ on it with these arguments (line length 120)
3. See:
```python
long_text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
make a specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\
""".replace(
    "\n", " "
)
```

**Expected behavior** A clear and concise description of what you expected to happen.

```python
long_text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
make a specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\
""".replace("\n", " ")
```

It gets even worse as we chain the calls e.g.

```python
long_text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
make a specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\
""".replace(
    "\n", " "
).replace(
    "\t", " "
)
```

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: [ Linux/Python 3.8.8]

**Does this bug also happen on master?** To answer this, you have two options:
Yes

**Additional context** Add any other context about the problem here.

I can get around this with:

```python
long_text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
make a specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\
"""
long_text = long_text.replace("\n", " ").replace("\t", " ")
```

But it seems a bit odd just to satisfy the formatter. Is this expected based on the style?

**Comment by ichard26** [comment] 2021-04-02 21:01
Duplicate of https://github.com/psf/black/issues/2028.

**Closed by ichard26** 2021-04-02 21:01 UTC
Labels: bug, duplicate
