### ISSUE TITLE
INTERNAL ERROR while formatting (log included)

### ISSUE THREAD

**Issue by teverus** [psf/black#4396] opened 2024-07-05 13:15 UTC
**Describe the bug**

I was formatting my code when an error broke. The console said that I needed to report it, so here I am

**To Reproduce**

[blk_zse1vd0s.log](https://github.com/user-attachments/files/16110113/blk_zse1vd0s.log)
I have no idea how to reproduce it, but I'll attach a log file.

The resulting error is:

> INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\XXX\AppData\Local\Temp\blk_zse1vd0s.log

**Expected behavior**

Not this...

**Environment**

- Black's version:  24.4.2
- OS and Python version:  Win 10, Python 3.10

**Additional context**

Good luck and thank you :)

**Comment by MeGaGiGaGon** [comment] 2024-07-05 23:32
Looks to be a duplicate of #3608, just using a dict instead of a tuple.
Minimum reproduction: [playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AChAFVdAD2IimZxl1N_Wm_vzTQ-P7fAWrcV3C3WMS1C4sLPK25U4pyoWzwJuhoWN_aE5hX4VugxyAaqq_FV2m8SVBlzLr-gCrA-PC5-qzmnrLSHkIRdWSFx1rIAAAAAzvJjjNgyhV4AAXGiAQAAACqhcLGxxGf7AgAAAAAEWVo=)

**Closed** 2024-07-05 23:35 UTC
Labels: T: bug, F: fmtskip
