### ISSUE TITLE
black not respecting max-length flag

### ISSUE THREAD

**Issue by onlinejudge95** [psf/black#2239] opened 2021-05-17 10:31 UTC
**Describe the bug**
`black` does not respect the `--line-length` default of **88** on a `with` statement

**To Reproduce** Steps to reproduce the behavior:

1. Take the following piece of code defined in the following [branch](https://github.com/unofficialopensource-knit/email_service/blob/async-views/src/blueprints/email/utils.py)
```python
async def send_batch_mail_async(params: List[Dict[str, Union[str, int, dict]]]) -> None:
    """
    Helper method to send batch mails asynchronously.
    This opens a new thread as sending a mail is an I/O bound process
    """
    with current_app._get_current_object().app_context(), mail.get_connection() as connection:
        messages = [
            EmailMessage(
                param["subject"],
                render_template(
                    f"email/{param['template_id']}.txt", **param["template_params"]
                ),
                param["sender"],
                [param["receiver"]],
                connection=connection,
            )
            for param in params
        ]
        connection.send_messages(messages)
```
2. Run black with the following arguments `black --config config/pyproject.toml .`
3. Config file used is
```toml
[tool.black]
verbose = true
target-version = ["py39"]
exclude = "migrations"
```

**Expected behavior**
Expectation from `black` is to be able to format the `with` statement in constraint to the `--line-length` config parameter.

**Environment (please complete the following information):**

- `black` version: **21.5b1**
- OS version: **ubuntu-20.04**
- Python version: **3.9.4**

**Does this bug also happen on main?** 
Yes the same issue persists using the main branch as well.
[Link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ANbAaZdAD2IimZxl1N_WlPS-KmmddHYvuhXbXWQOz_fJuuroVHY8BoZHYH_7o3TQtp0HJPirIeoiT7nI_b9K1iOnKobyc2MyCcEcjGqOxYjozJ-pgtxeFMPtI8b0pqVUK1Imr6LmaGdZLqcoEyvGBDXAAC2f7OYUaaYfJ0UmOELMwXNtgo69fYabOLLS8ATXi1PB3nDUL8zav_t-sI1mC2pf2y2Ex9CJD7cw2WgjgXab4s7f4PKTbm217LoVWiPXrGxpJq8tKqxXMtQ29CiCKzPmIrPCaQ_wYsWYhUebQ-wRgEcbCETkIR5aQnp4e9BY81HlNrZsbinwrzE8lB4MTaBCLtNblG-8r_mC9m5KfORlObsB0b9rqagmi8M6y1bHvyhDLUD6cz1TfagQH04q2e9gwFFRHPIlV9UyfKg4p1MsS7Y44Iq6kMyApbgkeK1ynJSJWs--YGnFrRTj-SCxuii8wH6ciqXi1fxV19Hmtjz8LVnOxcEsSZK8AJN9gGEYqSMBn0IDHtnk2PHA4uRJOeqrvjU4VgkGY_giC2piz3TykTKQrAPgzGxbftgAAAAE0HJNlDdlSEAAcID3AYAACFr2rCxxGf7AgAAAAAEWVo=)
Screenshot
![Screenshot from 2021-05-17 15-38-48](https://user-images.githubusercontent.com/44158581/118472527-90264700-b726-11eb-9127-6e31379c7ecd.png)
 

**Additional context**
Issue is reported in the following GitHub action run https://github.com/unofficialopensource-knit/email_service/pull/40/checks?check_run_id=2599706530

**Comment by JelleZijlstra** [comment] 2021-05-17 13:47
Duplicate of #664.

**Closed by JelleZijlstra** 2021-05-17 13:47 UTC
