### ISSUE TITLE
Unnecessary linebreak on 3.10-style Union types.

### ISSUE THREAD

**Issue by kthy** [psf/black#3301] opened 2022-09-30 08:29 UTC
**Describe the style change**

Black 22.8.0 makes typing hints in Python ≥ 3.10 harder to read by line breaking on the pipe (type union) operator without any apparent reason.

**Examples in the current _Black_ style**

I'm writing a FastAPI application:

```python
from fastapi import APIRouter, Query

router = APIRouter(prefix="/black", tags=["black"])


@router.get("/foo")
async def foo(
    param1: str
    | None = Query(
        default=None, title="A parameter", description="A longer description of the parameter."
    ),
    param2: str
    | None = Query(
        default=None,
        title="Another parameter",
        description="A longer description of the other parameter.",
    ),
) -> str:
    """Docstring goes here."""
    return f"{param1=} {param2=}"
```

**Desired style**

```python
from fastapi import APIRouter, Query

router = APIRouter(prefix="/pfx", tags=["pfx"])


@router.get("/foo")
async def foo(
    param1: str | None = Query(
        default=None, title="A parameter", description="A longer description of the parameter."
    ),
    param2: str | None = Query(
        default=None,
        title="Another parameter",
        description="A longer description of the other parameter.",
    ),
) -> str:
    """Docstring goes here."""
    return f"{param1=} {param2=}"
```
**Additional context**

If you remove the ` | None` part of the typing hint, a linebreak is not inserted by Black.

`str | None` for types is syntax introduced in Python 3.10. Python 3.9 and earlier had `Union[str, None]` which is not susceptible to the problem.

**Comment by CalumY** [comment] 2022-09-30 09:26
This seems similar to #3296 which is a duplicate of #2316.

**Comment by kthy** [comment] 2022-09-30 09:45
Thanks, I'd tried to search for existing issues but came up blank. Closing as dupe.

**Closed** 2022-09-30 09:46 UTC
Labels: T: design
