### ISSUE TITLE
.gitignore is ignored by black if more than one source location is specified

### ISSUE THREAD

**Issue by szandara** [psf/black#3291] opened 2022-09-27 13:19 UTC
**Describe the bug**

When adding more than one source entry, black ignores the .gitignore entries.

**To Reproduce**

content of .gitignore

```
generated/*
```

Running

```
black test src
```
produces

```
$ black --check tests src
would reformat generated/jtd/__init__.py

Oh no! 💥 💔 💥
1 file would be reformatted, 29 files would be left unchanged.
```

Running
```
black src
```

produces

```
$ black --check src
All done! ✨ 🍰 ✨
```

**Expected behavior**

```
$ black --check test src
All done! ✨ 🍰 ✨
```

**Environment**

- Black's version: 22.8.0
- OS and Python version: MacOS m1

**Additional context**

works with Black version: 22.6.0

**Comment by aaossa** [comment] 2022-10-07 20:46
The bug seems to be caused by this section of `get_sources`:

https://github.com/psf/black/blob/b60b85b234d6a575f636d0a125478115f993c90c/src/black/__init__.py#L660-L670

In the first run (the first `SRC`) `exclude` is `None`, but then the value gets overridden by `re_compile_maybe_verbose(DEFAULT_EXCLUDES)`, so in the second iteration the condition is not met and skips to `gitignore = None`. 

This can be fixed by creating a flag before the for loop, something like `is_default_exclude = exclude is None`, and check if the value is false afterwards:

```python
if is_default_exclude:
    exclude = re_compile_maybe_verbose(DEFAULT_EXCLUDES)
    gitignore = get_gitignore(root)
    p_gitignore = get_gitignore(p)
    # No need to use p's gitignore if it is identical to root's gitignore
    # (i.e. root and p point to the same directory).
    if gitignore != p_gitignore:
        gitignore += p_gitignore
else:
    gitignore = None
```

**Comment by felix-hilden** [comment] 2022-10-15 08:22
@aaossa Would be greatly appreciated!

**Closed** 2022-11-05 05:10 UTC
Labels: T: bug, C: file collection
