### ISSUE TITLE
Incorrectly adding space in slice

### ISSUE THREAD

**Issue by Keou0007** [psf/black#1701] opened 2020-09-13 16:22 UTC
I have a simple one liner that replaces the characters at the beginning of a string with a different (shorter) string.
To achieve this I do a slice of the second string using a `len` call on the first string.

```
string2 = string1 + string2[len(string1):]
```

black incorrectly adds a space into the slice, like so

```
string2 = string1 + string2[len(string1) :]
```

PyCharm then highlights this as incorrect (PEP8: E203 whitespace before ':').

I'm using blackd server, version 20.8b1.

**Comment by hugovk** [comment] 2020-09-13 17:24
This is by design, please see https://black.readthedocs.io/en/stable/the_black_code_style.html?highlight=E203#slices

**Comment by ichard26** [comment] 2020-09-13 17:43
Also a duplicate of #1541, #1448, #1437, #1413, #1343, #1332, #1323, #1029, #889, #785, #565, #544, #492, #403, #354, #350, #311, #279, #264, and #227...

*contemplating why I decided to become a triager for Black*

Anyway, please disable flake8's `E203` as it is not PEP 8 compliant.

**Closed by ichard26** 2020-09-13 17:43 UTC
Labels: duplicate, not a bug

**Comment by indepndnt** [comment] 2021-07-23 15:07
This is one of the places I ended up trying to figure this out for myself. So, for future travelers, at least as the time of this writing, here is how you disable E203 in PyCharm (2021.1.3):

1. Open Settings (File>Settings, or Ctrl-Alt-S)
2. Editor>Inspections>PEP 8 coding style violation (or search "pycodestyle")
3. Under Options click "+" and add "E203"
4. Click OK

![image](https://user-images.githubusercontent.com/17837901/126802146-f880a544-7ecd-42fe-8a88-fcf277dbd31c.png)

**Comment by jjbankert** [comment] 2021-11-12 10:14
> This is by design, please see https://black.readthedocs.io/en/stable/the_black_code_style.html?highlight=E203#slices

That link was broken for me, this link works: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html?highlight=E203#slices

**Comment by codeskipper** [comment] 2024-07-18 14:38
See also [Flake8 ignore list for Black compatibility #38](https://github.com/telekom/HPOflow/issues/38)
