### ISSUE TITLE
Markdown formatting of Docstrings broken by removal of Trailing-Whitespace

### ISSUE THREAD

**Issue by ethanmsl** [psf/black#3540] opened 2023-02-01 17:38 UTC
Some tools, including LSPs and useful auto-documentors like [pdoc](https://github.com/mitmproxy/pdoc) (note: **not** the malicious and parasitic "pdoc3") allow **markdown formatting of docstrings**.

That [requires the use of _trailing whitespace_ in order to indicate soft line breaks](https://www.markdownguide.org/basic-syntax/#line-breaks).   [swapped link for clarity -- just a reference to trailing whitespace in Markdown syntax]
However black ([in AST non-respecting fashion](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#ast-before-and-after-formatting)) 'cleans up' trailing whitespace.

While I understand that reducing options to discuss is an excellent feature of Black's and those not using Markdown formatting would prefer trailing whitespace be cleaned up -- the option to have Markdown consistent / docstring ignoring formatting would prevent Black from breaking other tools and valid formatting options.

I'm filing this as a bug due to this explanation of the behavior in black's docs: 
> While the result is technically an AST difference ... all real-world uses of docstrings that we’re aware of sanitize indentation and leading/trailing whitespace anyway.

Which misses the Markdown formatting use of trailing whitespace.

---------
this is true on most current version of Black and across OSs, however here is the context in which I used it:
black, 22.12.0 (compiled: no)
Python (CPython) 3.10.9
macOS 13.2

**Comment by JelleZijlstra** [comment] 2023-02-01 17:53
Can you clarify why trailing whitespace is required? The guide you link to says, at https://arcticicestudio.github.io/styleguide-markdown/rules/whitespace.html#trailing, that trailing whitespace should *not* be used.

**Comment by felix-hilden** [comment] 2023-02-01 20:18
Seems like a duplicate of #3306

**Comment by ethanmsl** [comment] 2023-02-02 06:18
@JelleZijlstra 

Confusing choice of link on my part.  I was just linking the first example I found of trailing-whitespace as part of markdown formatting.  (in case some reader were unfamiliar)

That particular guide _also_ & separately has personal preferences that involve not using trailing-whitespace and just having sentences flow together or have line breaks between.  But that's idiosyncratic to that project.  Use of trailing-whitespace is common in Markdown formatting.

**Comment by ethanmsl** [comment] 2023-02-02 06:24
@felix-hilden - yes, [that seems to be the same issue](https://github.com/psf/black/issues/3306).  
Please feel free to mark this as a duplicate.  
(I don't have the option to mark as duplicate myself, I believe.)

**Comment by felix-hilden** [comment] 2023-02-02 08:17
Thanks 👌 let's continue discussion on that issue

**Closed by felix-hilden** 2023-02-02 08:17 UTC
Labels: T: bug, F: docstrings
