### ISSUE TITLE
Black folds ellipsis (`...`) symbol like `class test: ...`, which causes `flake8` to raise `E701` error.

### ISSUE THREAD

**Issue by cainmagi** [psf/black#4213] opened 2024-02-05 22:19 UTC
## **The issue**

The newest `black` folds the ellipsis (`...`) to the previous line. This change may violate `flake8` `E701` rule if ellipsis is used for defining a class.

## **To Reproduce the issue**

The following codes will not raise `flake8` errors:

```python
def test():
    ...


class test2:
    ...

```

After running `black`, the results are

```python
def test(): ...


class test2: ...  # E701: Multiple statements on one line (colon)

```

Note that the function `test` will not raise `E701`, however the class definition will.

This issue may be caused by a bug of `flake8`. But I am not sure whether `black` is the one that should be changed because I remember that the previous version of `black` will not fold the `...` to the previous line.

## **Additional context**

* **`black version: 24.1.1`**
* `flake8 version: 7.0.0 (mccabe: 0.7.0, pycodestyle: 2.11.1, pyflakes: 3.2.0)`
* `python version: 3.9.0`

**Comment by cainmagi** [comment] 2024-02-05 22:26
This issue may be related to this one:

https://github.com/PyCQA/pycodestyle/issues/231

The problem is that `pycodestyle` has not supported the one-liner for classes yet. It looks problematic for me to let `black` prefer the one-liner style. It looks more reasonable for me if the `...` is put on a new line, which will not raise any errors.

**Comment by dankrzeminski32** [comment] 2024-02-05 22:29
Duplicate of #4173

**Comment by cainmagi** [comment] 2024-02-05 22:31
@dankrzeminski32 Thank you for finding this! Since it duplicates, should I close this issue now?

**Closed** 2024-02-05 22:37 UTC
Labels: T: style

**Comment by dankrzeminski32** [comment] 2024-02-05 22:39
@cainmagi I believe so, feel free to consult the [updated docs](https://black.readthedocs.io/en/latest/guides/using_black_with_other_tools.html#labels-why-pycodestyle-warnings) related to this issue.
