### ISSUE TITLE
Code was formatted differently on a second pass, causing INTERNAL ERROR

### ISSUE THREAD

**Issue by michaeldimchuk** [psf/black#1854] opened 2020-12-01 17:33 UTC
**Describe the bug**
Ran `black` to format a file, it crashed with the following error message:
```
black another.py
error: cannot format another.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/yw/l2bbp5p5645d4tdw2xyg7rtsvkc9df/T/blk_z5aztnq8.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**To Reproduce**
Can either use the same configuration or the default one, result is the same. Here's my `pyproject.toml` configuration:
```
[tool.black]
line-length = 120
```

Here's the contents of the file being formatted:
```
from enum import Enum, auto
from typing import Dict, Optional


class SomethingFairlyLong(Enum):
    FIRST = auto()
    SECOND = auto()
    THIRD = auto()
    FOURTH = auto()


def my_function(value: str, body: Dict[str, str]) -> Optional[str]:
    found_value = None
    if value in [SomethingFairlyLong.FIRST.name, SomethingFairlyLong.SECOND.name, SomethingFairlyLong.THIRD.name] and body.get("hello_there"):
        found_value = body.get("hello_there")
    return found_value
```

Here's the contents of the log file shown in the error message above:
```
Mode(target_versions=set(), line_length=120, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -9,8 +9,12 @@
     FOURTH = auto()


 def my_function(value: str, body: Dict[str, str]) -> Optional[str]:
     found_value = None
-    if value in [SomethingFairlyLong.FIRST.name, SomethingFairlyLong.SECOND.name, SomethingFairlyLong.THIRD.name] and body.get("hello_there"):
+    if value in [
+        SomethingFairlyLong.FIRST.name,
+        SomethingFairlyLong.SECOND.name,
+        SomethingFairlyLong.THIRD.name,
+    ] and body.get("hello_there"):
         found_value = body.get("hello_there")
     return found_value
--- first pass
+++ second pass
@@ -9,12 +9,16 @@
     FOURTH = auto()


 def my_function(value: str, body: Dict[str, str]) -> Optional[str]:
     found_value = None
-    if value in [
-        SomethingFairlyLong.FIRST.name,
-        SomethingFairlyLong.SECOND.name,
-        SomethingFairlyLong.THIRD.name,
-    ] and body.get("hello_there"):
+    if (
+        value
+        in [
+            SomethingFairlyLong.FIRST.name,
+            SomethingFairlyLong.SECOND.name,
+            SomethingFairlyLong.THIRD.name,
+        ]
+        and body.get("hello_there")
+    ):
         found_value = body.get("hello_there")
     return found_value
```

**Expected behavior:**  It shouldn't fail formatting

**Environment:**
Black version: 20.8b1
OS: macOS Catalina 10.15.7
Python: 3.8.6

**Does this bug also happen on master?**
Yes, I ran the same code through https://black.now.sh/?version=master and got the same output.

**Comment by ichard26** [comment] 2021-04-25 20:12
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:12 UTC
Labels: bug, duplicate, unstable formatting
