### ISSUE TITLE
Cannot parse a complex conditional list comprehension inside of an f-string

### ISSUE THREAD

**Issue by aphexcx** [psf/black#4166] opened 2024-01-24 23:38 UTC
**Describe the bug**

Black unexpectedly can't parse complex conditional list comprehensions inside of f-strings. Check out the example below.

**To Reproduce**

For example, take this code:

```python
subdirs = ["foodir", "bardir", "tests"]

subdir_options = f" ({", ".join([dir for dir in subdirs if dir != "tests"])})" if subdirs else ""
```

And run it with these arguments:

```sh
$ black file.py --target-version py312
```

The resulting error is:

> Cannot parse: 128:71: subdir_options = f" ({", ".join([dir for dir in subdirs if dir != "tests"])})" if subdirs else ""

**Expected behavior**

Black should parse this valid python.

**Environment**

- Black's version: 23.12.1
- OS and Python version: 3.12.1

**Update**
This *does* work if I change the f-string to use single quotes!:

```python
subdirs = ["foodir", "bardir", "tests"]

subdir_options = f' ({", ".join([dir for dir in subdirs if dir != "tests"])})' if subdirs else ""
```

**Comment by JelleZijlstra** [comment] 2024-01-24 23:43
Duplicate of #3746. (Note this syntax only works in Python 3.12 and higher.)

**Closed by JelleZijlstra** 2024-01-24 23:43 UTC
Labels: T: bug

**Comment by aphexcx** [comment] 2024-01-24 23:44
Thanks! I found a workaround, see above.
