### ISSUE TITLE
Black breaks tab-formatted doc strings

### ISSUE THREAD

**Issue by nbirnel** [psf/black#3830] opened 2023-08-04 16:45 UTC
black, version 20.8b1

**Describe the bug**

error: cannot format  {...}/parser.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_wg0dl3cf.log

```
cat /tmp/blk_wg0dl3cf.log
--- src
+++ dst
@@ -399,11 +399,11 @@
           body=
             Expr(
               value=
                 Constant(
                   value=
-                    'According to CVSS official numbers https://nvd.nist.gov/vuln-metrics/cvss\nNone \t0.0\nLow \t0.0-3.9 \tLow \t0.1-3.9\nMedium \t4.0-6.9 \tMedium \t4.0-6.9\nHigh \t7.0-10.0 \tHigh \t7.0-8.9\nCritical \t9.0-10.0',  # str
+                    'According to CVSS official numbers https://nvd.nist.gov/vuln-metrics/cvss\nNone    0.0\nLow     0.0-3.9         Low     0.1-3.9\nMedium  4.0-6.9         Medium  4.0-6.9\nHigh    7.0-10.0        High    7.0-8.9\nCritical        9.0-10.0',  # str
                 )  # /Constant
             )  # /Expr
             Assign(
               targets=
                 Name(
```

**Comment by hauntsaninja** [comment] 2023-08-05 00:33
The version of Black you're using is ancient. I believe the issue is fixed in any non-ancient Black.

**Closed by hauntsaninja** 2023-08-05 00:33 UTC
Labels: T: bug, C: crash, F: docstrings
