### ISSUE TITLE
Black handles mixed tabs/spaces files badly.

### ISSUE THREAD

**Issue by adamfaulkner** [psf/black#952] opened 2019-08-01 03:39 UTC
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Linux, ubuntu 19.04
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: Yes

---
When I attempt to format this (terrible) file, black crashes. Note the first line has 1 tab, the second line has 8 spaces.

```
def foo():
	line1 = 'foo'
        line2 = 'bar'
```

```
error: cannot format /tmp/test.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/python/black/issues.  This diff might be helpful: /tmp/blk_2fxkvvlh.log

[blk_2fxkvvlh.log](https://github.com/psf/black/files/3454785/blk_2fxkvvlh.log)
```
Obviously this isn't a huge priority for me, but it does make migrating a massive project a little bit harder, and it seems like a bug to me.

**Comment by szborows** [comment] 2019-11-28 20:03
I have encountered this today. I've copied some code to the Vim and somehow Vim switched to the tab mode. There was one offending tab that caused the problem. It took me couple of minutes to find out what's happening. I investigated this a little and it seems to be similar to #1170 

How to reproduce:
```bash
echo -n "def foo():\n    def bar():\n\tpass" | python3 black.py -
```

Black log file shows some differences:

```
--- src
+++ dst
@@ -3,40 +3,46 @@
     FunctionDef(
       args=
         arguments(
           args=
           defaults=
+          kw_defaults=
           kwarg=
             None,  # NoneType
-          type_comments=
+          kwonlyargs=
           vararg=
             None,  # NoneType
         )  # /arguments
       body=
         FunctionDef(
           args=
             arguments(
               args=
               defaults=
+              kw_defaults=
               kwarg=
                 None,  # NoneType
-              type_comments=
+              kwonlyargs=
               vararg=
                 None,  # NoneType
             )  # /arguments
           body=
             Pass(
             )  # /Pass
           decorator_list=
           name=
             'get_goto_input',  # str
+          returns=
+            None,  # NoneType
           type_comment=
             None,  # NoneType
         )  # /FunctionDef
       decorator_list=
       name=
         'goto',  # str
+      returns=
+        None,  # NoneType
       type_comment=
         None,  # NoneType
     )  # /FunctionDef
   type_ignores=
 )  # /Module
```

With trace module I tracked down that when the tab is present, this is getting called:

```
filename: /repo/black/venv/lib/python3.7/site-packages/typed_ast/ast27.py, modulename: ast27, funcname: parse
```

It looks that tab character enables 2.7 parsing. 3.x parsing happens regardless of the tab char presence, but maybe then outcome of 2.7 parsing is taken into account?

Even passing `--target-version py37` doesn't help and 2.7's `parse()` is still called.

**Comment by szborows** [comment] 2019-11-28 22:09
I have debugged the code and it looks like culprit is somewhere around `parse_ast` function. It's called twice: first time with original input, and the second time with produced output.

During the first call due to the tab character `ast.parse` will throw `TabError` which is a subclass of `SyntaxError` and is caught. There's continue statement in except block so eventually it hits `ast27.parse(src)`, which is 2.7 parsing.

During the second time there's no tab character anymore, so `TabError` is not thrown. Since there are differences in AST between Py2 and Py3 (e.g. `kwonly_args`), these AST simply differ.

```python3
def parse_ast(src: str) -> Union[ast.AST, ast3.AST, ast27.AST]:
    filename = "<unknown>"
    if sys.version_info >= (3, 8):
        # TODO: support Python 4+ ;)
        for minor_version in range(sys.version_info[1], 4, -1):
            try:
                return ast.parse(src, filename, feature_version=(3, minor_version))
            except SyntaxError:
                continue
    else:
        for feature_version in (7, 6):
            try:
                return ast3.parse(src, filename, feature_version=feature_version)
            except SyntaxError:
                continue

    return ast27.parse(src)
```

@JelleZijlstra I think this may answer your question in #1170

**Comment by szborows** [comment] 2019-11-28 22:55
for the record: this fix works for python3 but it breaks py2 tests

```diff
diff --git a/black.py b/black.py
index 1c35643..92cdd9c 100644
--- a/black.py
+++ b/black.py
@@ -3703,14 +3703,17 @@ def parse_ast(src: str) -> Union[ast.AST, ast3.AST, ast27.AST]:
                 return ast.parse(src, filename, feature_version=(3, minor_version))
             except SyntaxError:
                 continue
-    else:
+    elif sys.version_info > (3, 0):
         for feature_version in (7, 6):
             try:
                 return ast3.parse(src, filename, feature_version=feature_version)
             except SyntaxError:
                 continue
-
-    return ast27.parse(src)
+        raise AssertionError(
+            "Failed to parse input source code. Please double-check that it is correct."
+        )
+    else:
+        return ast27.parse(src)


 def _fixup_ast_constants(
```

**Comment by JelleZijlstra** [comment] 2021-05-29 04:35
The code in the original example produces a TabError in Python 3 (you can't mix tabs and spaces) but it does work in Python 2 so I guess Black should accept it.

**Comment by felix-hilden** [comment] 2022-01-29 16:32
We've stopped supporting Python 2 code, so I'll be closing this issue!

**Closed by felix-hilden** 2022-01-29 16:32 UTC
Labels: T: bug, C: invalid code
