### ISSUE TITLE
Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by rsokl** [psf/black#2003] opened 2021-02-24 04:08 UTC
Black produced different code on the second pass of the formatter.

**Black's log**:

```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -22,8 +22,13 @@
 
     # tensor.grad.dtype should always match tensor.dtype
     assert out.grad.dtype == out.dtype
     assert x.grad.dtype == x.dtype
 
+
 @pytest.mark.parametrize("ufunc", ufuncs)
 def test_constant_propagates_correctly(ufunc):
-    tensor = tensors(dtype=st.sampled_from([np.float64, np.float32, int]), shape=(1,), elements=st.just(1)) | st.just([1.])
+    tensor = tensors(
+        dtype=st.sampled_from([np.float64, np.float32, int]),
+        shape=(1,),
+        elements=st.just(1),
+    ) | st.just([1.0])
--- first pass
+++ second pass
@@ -25,10 +25,13 @@
     assert x.grad.dtype == x.dtype
 
 
 @pytest.mark.parametrize("ufunc", ufuncs)
 def test_constant_propagates_correctly(ufunc):
-    tensor = tensors(
-        dtype=st.sampled_from([np.float64, np.float32, int]),
-        shape=(1,),
-        elements=st.just(1),
-    ) | st.just([1.0])
+    tensor = (
+        tensors(
+            dtype=st.sampled_from([np.float64, np.float32, int]),
+            shape=(1,),
+            elements=st.just(1),
+        )
+        | st.just([1.0])
+    )
```

**Environment (please complete the following information):**

- Version: black, version 20.8b1
- OS and Python version:Windows / Python 3.7.3

**Comment by ichard26** [comment] 2021-04-25 20:08
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:08 UTC
Labels: bug, duplicate, unstable formatting
