### ISSUE TITLE
Line wrapping on generic functions using the type parameter syntax

### ISSUE THREAD

**Issue by PaulWassermann** [psf/black#3929] opened 2023-10-06 23:33 UTC
**Describe the style change**

The suggested style change regards the type parameter syntax introduced in Python 3.12. 

When formatting lines too long, I think line-wrapping should occur in the arguments' parenthesis rather than in the type parameters' brackets.

**Examples in the current _Black_ style**

This would work with any generic function using the new type parameter syntax with a long enough signature (longer than the `line-length`).

```python

type SupportedDataTypes = float
type Tensor = list

def sum_backward[
T: SupportedDataTypes
](a: Tensor[T], grad: Tensor[T]) -> dict[Tensor[T], Tensor[T]]:
    ...
```
**Desired style**

I think this kind of line-wrapping, keeping the type parameters list on a single line when possible, should be preferred over what currently happens as it is more readable.

```python

type SupportedDataTypes = float
type Tensor = list

def sum_backward[T: SupportedDataTypes](
    a: Tensor[T], 
    grad: Tensor[T]
) -> dict[Tensor[T], Tensor[T]]:
    ...
```

**Comment by arre-ankit** [comment] 2023-10-12 09:35
In which section we have to implement this syntax can you give more context about the files where we have to change the syntax ?

**Comment by rajesh604** [comment] 2023-10-15 06:09
hi can you assign me this issue?

**Comment by JelleZijlstra** [comment] 2023-10-15 21:54
We don't generally assign issues. However, PRs are welcome!

**Comment by Benfinch1** [comment] 2023-10-28 21:56
WHAT TO DO IF YOUR CRYPTOCURRENCY IS LOST OR STOLEN?


If you’ve been duped, there may be little you can do to make things right. You have no other choice except to contact a recovery company. I am aware of numerous trustworthy recovery organizations, but LOST RECOVERY MASTERS are my top option due to how swiftly they assisted me in recovering my lost bitcoins that I had placed with a negligent broker. Contact Lost Recovery Masters. There will surely be steps taken to assist you in locating your misplaced cryptocurrency. They give top agents that are highly qualified and trained to assist you in recovering your stolen or lost cryptocurrencies. Based on my own findings, I wholeheartedly support this healing organization. contact them through

Website https://lostrecoverymasters.com/  
Support team Mail   [Support@lostrecoverymasters.com](mailto:Support@lostrecoverymasters.com)
WhatsApp: +1(204)819-5505.

**Comment by hauntsaninja** [comment] 2024-12-18 03:09
Duplicate of https://github.com/psf/black/issues/4071 , PR welcome

**Closed by hauntsaninja** 2024-12-18 03:09 UTC
Labels: T: style, S: accepted
