### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by calebsander** [psf/black#1702] opened 2020-09-13 21:11 UTC
**Describe the bug**
See title. Black requested that I open an issue.

**To Reproduce**
Try to format the following file (`black test.py`):
```py
def test_search(client):
    assert set(execute_search(
        email="",
        username="",
        name=None,
        house_id=None,
        building_id=None,
        grad_year=None
    )) == set([])
```

This is a minimized excerpt from a larger yapf-formatted file.

**Expected behavior**
Successful formatting, as this is valid Python code.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: macOS 11.0, Python 3.8.2

**Does this bug also happen on master?** Yes

**Additional context** 

Black's log file:
```diff
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,9 +1,11 @@
 def test_search(client):
-    assert set(execute_search(
-        email="",
-        username="",
-        name=None,
-        house_id=None,
-        building_id=None,
-        grad_year=None
-    )) == set([])
+    assert set(
+        execute_search(
+            email="",
+            username="",
+            name=None,
+            house_id=None,
+            building_id=None,
+            grad_year=None,
+        )
+    ) == set([])
--- first pass
+++ second pass
@@ -1,11 +1,14 @@
 def test_search(client):
-    assert set(
-        execute_search(
-            email="",
-            username="",
-            name=None,
-            house_id=None,
-            building_id=None,
-            grad_year=None,
+    assert (
+        set(
+            execute_search(
+                email="",
+                username="",
+                name=None,
+                house_id=None,
+                building_id=None,
+                grad_year=None,
+            )
         )
-    ) == set([])
+        == set([])
+    )
```

**Comment by ichard26** [comment] 2021-04-25 19:55
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:55 UTC
Labels: bug, duplicate, unstable formatting
