### ISSUE TITLE
Comment in redundant parentheses gets removed accidentally

### ISSUE THREAD

**Issue by jfcherng** [psf/black#4199] opened 2024-01-31 09:16 UTC
**Describe the bug**

Comment in redundant parentheses gets removed accidentally. 

**To Reproduce**

For example, take this code:

```python
def return_true():
    return (
        (
            True  # this comment gets removed accidentally
        )
    )
```

And run it with these arguments:

```sh
$ black test.py
```

It removes the comment accidentally.

```python
def return_true():
    return True
```

**Expected behavior**

```python
def return_true():
    return True  # this comment gets removed accidentally
```

**Environment**

- Black's version: 24.1.0 (compiled: yes)
- OS and Python version: Windows 10 x64, Python (CPython) 3.12.1

**Comment by hauntsaninja** [comment] 2024-01-31 10:02
Thanks for the issue, that's pretty bad of Black. Looks like this is a duplicate of #3815

**Closed by hauntsaninja** 2024-01-31 10:02 UTC
Labels: T: bug
