### ISSUE TITLE
Function empty line spacing with preceding comment

### ISSUE THREAD

**Issue by cas--** [psf/black#600] opened 2018-11-08 10:22 UTC
There is an issue with function spacing that has a preceding comment. I did see an existing issue #56 and the docs snippet below but neither quite apply here.

> Black will not put empty lines between function/class definitions and standalone comments that immediately precede the given function/class.

**Input**
```python
var = 0
# Comment
def func():
    pass
```
**Output**
```python
var = 0
# Comment
def func():
    pass
```
**Expected**
```python
var = 0


# This is a func.
def func():
    pass
```

I think that the extra empty lines are expected before a function and by Black not touching it, it does raise a Flake8 warning: 

    E306 expected 1 blank line before a nested definition, found 0

### Comment omitted 
**Input**
```python
var = 0
def func():
    pass
```
**Output**
```python
var = 0


def func():
    pass
```

### Comments between multiple functions
**Input**
```python
def func1():
    pass
# Comment
def func2():
    pass
```

**Output**
```python
def func1():
    pass


# Comment
def func2():
    pass
```

Operating system: Linux
Python version: 3.6
*Black* version: 18.9b0
Does also happen on master: yes

**Comment by ambv** [comment] 2020-03-04 09:53
Workaround for now: put those blank lines in manually, Black will keep them.

**Comment by JelleZijlstra** [comment] 2021-05-30 04:16
This is a duplicate of #246.

**Closed by JelleZijlstra** 2021-05-30 04:16 UTC
Labels: F: empty lines, T: bug
