### ISSUE TITLE
Can't use with GitHub actions

### ISSUE THREAD

**Issue by Destaq** [psf/black#1586] opened 2020-08-11 17:22 UTC
I followed the instructions in the README and generated a file named `black.yml` under `.github/workflows/`. However, when I pushed to master, an error occurred:

```
Could not find file '/home/runner/work/_actions/_temp_5819819e-a4d4-412a-8e33-e24210fc984b/_staging/psf-black-6bedb5c/docs/contributing_to_black.md'.
```
This means I am unable to use `black` for GitHub CI. Is there any solution to this?

**Comment by hugovk** [comment] 2020-08-11 17:42
This is a duplicate of https://github.com/psf/black/issues/1520. 

A workaround is to point to `master` (not advisable as it's a moving target), or better, pick a specific commit. See:

* https://github.com/psf/black/issues/1520#issuecomment-649674725

**Comment by ichard26** [comment] 2020-08-11 17:42
Hi @Destaq.

So the problem here is that since stable, we have restructured the documentation and code which probably messed up with the paths. The solution to this issue is a new release which the stable branch tracks. There is currently an issue open for a new release: #1583. So unfortunately, you will be unable to use `black` stable for GitHub Actions until a new release is available. There is two immediate solutions, 1. use Black on master: `psf/black@master`, but I don't recommend that since it can be prone to instability, or 2. Use the newest commit that works: `psf/black@fcf97961061982656a1384ecc1628e217a52a88c`

Also, duplicate of #1520.

**Closed by ichard26** 2020-08-11 17:42 UTC
Labels: bug, duplicate
