### ISSUE TITLE
black breaks long statement within `[]` and not around `and`

### ISSUE THREAD

**Issue by bbkane** [psf/black#1974] opened 2021-02-07 16:51 UTC
**Describe the bug** A clear and concise description of what the bug is.

`black` replaces:

```
            is_standard_front_matter = (lines[0] == lines[3] == "---\n") and lines[1] == "layout: default\n"
```

with

```
            is_standard_front_matter = (lines[0] == lines[3] == "---\n") and lines[
                1
            ] == "layout: default\n"
```

It's subjective (and apologies if this should be a style issue, not a bug), but because the `and` has lower precedence than the conditionals around it, I would find it easier to read if `black` created teh newline around the `and`:

```python
            is_standard_front_matter = (lines[0] == lines[3] == "---\n") \
                and lines[1] == "layout: default\n"
```

This does require a backslash, so reasonable people could disagree :) . I skimmed black's style guide, but didn't see a case representing this. Please close this issue if I'm mistaken about this as a bug. 

**To Reproduce** Steps to reproduce the behavior:

1. Take this file '...'

```python
lines = [
    "---\n",
    "layout: default\n",
    "title: my title\n",
    "---\n",
]


def need_indent():
    def need_more_indent():
        def even_more_indent():
            is_standard_front_matter = (lines[0] == lines[3] == "---\n") and lines[1] == "layout: default\n"
```

2. Run _Black_ on it with these arguments '....'

```
$ cat tmp.py| black -
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

lines = [
    "---\n",
    "layout: default\n",
    "title: my title\n",
    "---\n",
]


def need_indent():
    def need_more_indent():
        def even_more_indent():
            is_standard_front_matter = (lines[0] == lines[3] == "---\n") and lines[
                1
            ] == "layout: default\n"
reformatted -
All done! ✨ 🍰 ✨
1 file reformatted.
```

3. See error

```
            is_standard_front_matter = (lines[0] == lines[3] == "---\n") and lines[
                1
            ] == "layout: default\n"
```

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: MacOS/Python 3.8.7

**Does this bug also happen on master?** To answer this, you have two options:
See  [the black playground](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGBAMFdAD2IimZxl1N_Wl9TkLp-WoWtVQ3aK8noItl2W5_qQs2C_aEP4yZMM6foTNeMxvsnaDGp6Ni26mZMAueRwMtHPUA609a7WQ_vcYIMtFqS_n5ztadFEpyW0ioaemzc-ZELb793i23HOOtyCc9SQNMnqhv3DxPSSDPKR3ZtrdXVcqFXmrBZ5O6HLLckeqw0vt7waVThbMQKfKwDWSm0nI_ge9EQgQhhUquS5ZJ-5DwSfwXPH5_3ugnYoZh8a1YusnSNmQAAAAAAgY7P8LgnQ7gAAd0BggMAAHUygxWxxGf7AgAAAAAEWVo=)

**Additional context** Add any other context about the problem here.

**Comment by JelleZijlstra** [comment] 2022-01-29 16:35
Duplicate of #236

**Closed by JelleZijlstra** 2022-01-29 16:35 UTC
Labels: T: design, F: linebreak
