### ISSUE TITLE
Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by jdherg-brilliant** [psf/black#2022] opened 2021-03-05 22:41 UTC
**Describe the bug**
Running Black on the given snippet produces the second-pass error.

**To Reproduce** Steps to reproduce the behavior:

Open this [Black playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADnAHJdAD2IimZxl1N_WlkOEznFeNp7qQQjoQdQO1isRX_k3kMPmEbsGSfg-9FQAw_XrovVp293bde0TID4mAPgF96aC5sSX-v0StK1dDsUSwVQDh3b7WZ4u5pGFH8hc-i8_5wHGYsCwdgLNSyeZApuigeoD9FCAAAAAGmENbCriOxTAAGOAegBAAAli4bIscRn-wIAAAAABFla).

Alternatively, paste this code into the Black playground:

```python
foo = bar(
    "x123456789x123456789x123456",
    x123456789x123456789x12("x123456789x12345678",
                            "true")) in (baz,)
```

**Expected behavior** A clear and concise description of what you expected to happen:
Successful formatting by Black.

**Actual behavior** Second-pass error fires:

```diff
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_jl_w30jh.log

Mode(target_versions=set(), line_length=88, string_normalization=True, magic_trailing_comma=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,4 +1,4 @@
 foo = bar(
     "x123456789x123456789x123456",
-    x123456789x123456789x12("x123456789x12345678",
-                            "true")) in (baz,)
+    x123456789x123456789x12("x123456789x12345678", "true"),
+) in (baz,)
--- first pass
+++ second pass
@@ -1,4 +1,7 @@
-foo = bar(
-    "x123456789x123456789x123456",
-    x123456789x123456789x12("x123456789x12345678", "true"),
-) in (baz,)
+foo = (
+    bar(
+        "x123456789x123456789x123456",
+        x123456789x123456789x12("x123456789x12345678", "true"),
+    )
+    in (baz,)
+)
```

**Environment (please complete the following information):**

Black playground.

**Does this bug also happen on master?** To answer this, you have two options:
Yes

**Additional Context**

I've tried to make this a fairly minimal case: the bug doesn't repro if any of the `xNNNN` tokens are shortened or any of the tokens are removed.

Thanks for reviewing! :)

**Comment by jdherg-brilliant** [comment] 2021-03-05 22:58
Starting from a different part of our codebase that was triggering an error, this feels similar enough that I'm going to add it here rather than make a new issue:

[Playground](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC2AF5dAD2IimZxl1N_WlkOEznFeP514JeBuWaHqLoN6NuylXckostYtcY8a4lIAPl90aA4j0klQ2dxxrKGzWrrRXMlAHCcwW1O3_bejD-WICwnq3jgBQyzrs5ldxd1W4zxBgAAAACOo3iCi15_NwABercBAAAAG0m3c7HEZ_sCAAAAAARZWg==)

```python
foo = x123456789 in ("x123456789", "x123456789", "x123456789") and x123456789x123456789 in ("x",)
```
leads to
```diff
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_qo44gbdk.log

Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1 +1,5 @@
-foo = x123456789 in ("x123456789", "x123456789", "x123456789") and x123456789x123456789 in ("x",)
+foo = x123456789 in (
+    "x123456789",
+    "x123456789",
+    "x123456789",
+) and x123456789x123456789 in ("x",)
--- first pass
+++ second pass
@@ -1,5 +1,9 @@
-foo = x123456789 in (
-    "x123456789",
-    "x123456789",
-    "x123456789",
-) and x123456789x123456789 in ("x",)
+foo = (
+    x123456789
+    in (
+        "x123456789",
+        "x123456789",
+        "x123456789",
+    )
+    and x123456789x123456789 in ("x",)
+)
```

**Comment by jdherg-brilliant** [comment] 2021-03-05 23:39
Oh jeez I somehow missed the pinned issue -- it looks like this is perhaps that class of error (or at least trailing commas are being added on the first pass). Should I just add these examples there and close this out?

**Comment by ichard26** [comment] 2021-04-25 19:50
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:50 UTC
Labels: bug, duplicate, unstable formatting
