### ISSUE TITLE
Feedback on formatting style

### ISSUE THREAD

**Issue by geeanlooca** [psf/black#1526] opened 2020-06-30 16:07 UTC
**Describe the bug** Consider the following python class

```python
class MZM:
    def output(self, laser, drive):
        if np.isfinite(self.extinction_ratio_dB):
            er = 10 ** (-self.extinction_ratio_dB / 20)
            modulated_laser_x = (1 - er) * modulated_laser_signal.iq[0] + er * laser.iq[0]
```

The line starting with `modulated_laser_x =`  is longer than the 88-character limit, and is formatted as 

```python
class MZM:
    def output(self, laser, drive):
        if np.isfinite(self.extinction_ratio_dB):
            er = 10 ** (-self.extinction_ratio_dB / 20)
            modulated_laser_x = (1 - er) * modulated_laser_signal.iq[0] + er * laser.iq[
                0
            ]
```

**Is this the correct behaviour?**
 This is what I want to know. I expected something along the lines of

```python
class MZM:
    def output(self, laser, drive):
        if np.isfinite(self.extinction_ratio_dB):
            er = 10 ** (-self.extinction_ratio_dB / 20)
            modulated_laser_x = (
                (1 - er) * modulated_laser_signal.iq[0] 
                + er * laser.iq[0]
             )
```

**To Reproduce** Steps to reproduce the behavior:

1. Take the first snippet above
2. Run _Black_ on it either without arguments or with these arguments: `-t py36`
3. See the result in the second snippet above

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: 19.10b0
- OS and Python version: Windows 10/Python 3.7.4

**Does this bug also happen on master?** 
Yes, see [this](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AE1AMFdAD2IimZxl1N_WlXnON2nzN3uBdyt54bSOaU7jMnN5cQHH0gZyduo8lWuvsrOCzY5T8EVOlHn4MoMKHBwKYpOOge-3yBQakUNsIlDzLE-mY1KYWQ2tYbqlEi3Mc7NttuIG2tSbAT5121moEzt-72XN9Txxkl3KMwpYz5VxXI3GushXLvJ6E2lInJCu2MXQX3BMkGGz7I51MYdtoLYNAxo4D9FoyTwJqM46ZFIoJEyNQAAi03LH73G40J9j0P7xKIuNVIAAAAA5AWlzTyQzp8AAd0BtgIAALQ3CGuxxGf7AgAAAAAEWVo=)

**Comment by JelleZijlstra** [comment] 2022-01-29 16:21
Duplicate of #2364

**Closed by JelleZijlstra** 2022-01-29 16:21 UTC
Labels: T: design, F: linebreak
