### ISSUE TITLE
Remove unnecessary brackets around function parameters

### ISSUE THREAD

**Issue by saroad2** [psf/black#2900] opened 2022-02-28 13:32 UTC
**Describe the style change**

The following code:
```python
def foo(a)
    print(a)

foo(a=([1, 2, 3]))
```

Should be changed into:
```python
def foo(a)
    print(a)

foo(a=[1, 2, 3])
```

**Examples in the current _Black_ style**

As for now, the example above doesn't change by _Black_.

**Desired style**

When circular brackets are not used to break up command parameters into different lines, it should be removed entirely

**Additional context**

I use python 3.9 on Windows computer.

**Comment by JelleZijlstra** [comment] 2022-02-28 14:57
Similar to #1123, #2338, #2522, #608. This is a good idea, but I'm going to say it's a dupe of #608.

**Closed by JelleZijlstra** 2022-02-28 14:57 UTC
Labels: T: design, F: parentheses
