### ISSUE TITLE
Trailing comma in single element list

### ISSUE THREAD

**Issue by Czaki** [psf/black#1250] opened 2020-01-30 11:32 UTC
**Describe the style change** Not add trailing comma in single element list 

**Examples in the current _Black_ style** Think of some short code snippets that show
how the current _Black_ style is not great:

```python
    def get_getter_and_setter_function(
        widget: QWidget,
    ) -> typing.Tuple[typing.Callable[[QWidget,], typing.Any], typing.Callable[[QWidget, typing.Any], None]]:
    pass
```

**Desired style** How do you think _Black_ should format the above snippets:

```python
    def get_getter_and_setter_function(
        widget: QWidget,
    ) -> typing.Tuple[typing.Callable[[QWidget], typing.Any], typing.Callable[[QWidget, typing.Any], None]]:
    pass
```

**Additional context** If someone would like to see wfole code context it si here

**Comment by ndwhelan** [comment] 2020-02-05 17:27
The desired functionality was apparently removed after `18.9b0`. I'm curious if this was intentional?

**Comment by zsol** [comment] 2020-02-06 21:40
Correct, this is a duplicate of #1202

**Closed by zsol** 2020-02-06 21:40 UTC
Labels: design
