### ISSUE TITLE
Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by tcbegley** [psf/black#1995] opened 2021-02-21 12:28 UTC
**Describe the bug**

Ran black on some unit tests and got the error

```
 INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.
```

I've included a minimal reproduction of the failing code below.

**To Reproduce**

1. Take this file

    ```python
    def test_shape():
        assert some_function(
            data,
            more_data,
            kwarg1=kwarg1_longish_name,
            kwarg2=kwarg2_longish_name,
            kwarg3=kwarg3,
            kwarg4=kwarg4
        ).shape == (dim1_shape,)
    ```
2. Run _Black_ on it with no arguments: `black .`
3. See error: 
    ```
    error: cannot format test_shape.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.
    ```

**Environment (please complete the following information):**

- Version: master & 20.8b1
- OS and Python version: macOS + Python 3.8.6

**Does this bug also happen on master?**
[Yes](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AE1AJ9dAD2IimZxl1N_WlbvK5V_5PM4OL7mBVpDk4Lc5eUE7FNoP1sQ2cREpU8gRKzdgbmU6QKxS87eukdF6VnAh6aTuA79oxFzkCBCZw_8Zp85VI4Uphb7j7HYGtcEK0AU8wkZpU1mzMHz4sPWKza23JxVC9oiWL-f3-Ke41fRtkrrSipFS4FYIvlhCI38hcoP2OdkCclMMabh7Tz9IBwnfIpvdQAA4jF0Mw7zR9gAAbsBtgIAAPPbpbWxxGf7AgAAAAAEWVo=)

**Additional context**

The first pass adds a trailing comma to `kwarg4`. The second pass wraps the expression in the assert statement in parentheses and expands onto multiple lines. Manually adding the trailing comma before running Black resolves the issue.

**Comment by mvolfik** [comment] 2021-02-22 17:14
Probably the same issue as in #1629 , as black processes this file without issue with #1958 checked out

**Comment by ichard26** [comment] 2021-04-25 19:52
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:52 UTC
Labels: bug, duplicate, unstable formatting
