### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by semajson** [psf/black#1855] opened 2020-12-01 17:38 UTC
**Describe the bug** When running black over the following code:
```
from test import ErrorDescription, event

def create_html_diags(html):
    if (True):
        if (True):
            if (True):
                try:
                    # Link to the Error
                    error_description_obj = ErrorDescription.objects.get(message = event["header"][:300])
                    html += '<a href="/errors/error%s/">CODE Error</a>' % error_description_obj.id
                    if error_description_obj.err_num is not None and error_description_obj.err_num != 0:
                        html += ' <small> - ERROR <a href="http:wwww.example.com/website?error=%s">%s</a></small>' % (
                            error_description_obj.err_num, error_description_obj.err_num)

                except:
                    html += "Internal  Error"
```
The error `INTERNAL ERROR: Black produced different code on the second pass of the formatter.` is reported

**To Reproduce** Run black over code snippet posted above

**Expected behavior** Black formats the file without error

**Environment :**

- Version: 20.8b1
- OS and Python version: Centos 7 / Python 2.7.5 (although code was from a python 2 script, I don't think it's a python 2 specific issue)

**Does this bug also happen on master?** Yes, it repos on https://black.now.sh/?version=master

**Additional context** Output of the of the diff file:
```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,17 +1,29 @@
 from test import ErrorDescription, event
 
+
 def create_html_diags(html):
-    if (True):
-        if (True):
-            if (True):
+    if True:
+        if True:
+            if True:
                 try:
                     # Link to the Error
-                    error_description_obj = ErrorDescription.objects.get(message = event["header"][:300])
-                    html += '<a href="/errors/error%s/">CODE Error</a>' % error_description_obj.id
-                    if error_description_obj.err_num is not None and error_description_obj.err_num != 0:
-                        html += ' <small> - ERROR <a href="http:wwww.example.com/website?error=%s">%s</a></small>' % (
-                            error_description_obj.err_num, error_description_obj.err_num)
-
+                    error_description_obj = ErrorDescription.objects.get(
+                        message=event["header"][:300]
+                    )
+                    html += (
+                        '<a href="/errors/error%s/">CODE Error</a>'
+                        % error_description_obj.id
+                    )
+                    if (
+                        error_description_obj.err_num is not None
+                        and error_description_obj.err_num != 0
+                    ):
+                        html += (
+                            ' <small> - ERROR <a href="http:wwww.example.com/website?error=%s">%s</a></small>'
+                            % (
+                                error_description_obj.err_num,
+                                error_description_obj.err_num,
+                            )
+                        )
                 except:
                     html += "Internal  Error"
-
--- first pass
+++ second pass
@@ -16,14 +16,11 @@
                     )
                     if (
                         error_description_obj.err_num is not None
                         and error_description_obj.err_num != 0
                     ):
-                        html += (
-                            ' <small> - ERROR <a href="http:wwww.example.com/website?error=%s">%s</a></small>'
-                            % (
-                                error_description_obj.err_num,
-                                error_description_obj.err_num,
-                            )
+                        html += ' <small> - ERROR <a href="http:wwww.example.com/website?error=%s">%s</a></small>' % (
+                            error_description_obj.err_num,
+                            error_description_obj.err_num,
                         )
                 except:
                     html += "Internal  Error"
```

**Comment by ichard26** [comment] 2021-04-25 20:20
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:20 UTC
Labels: bug, duplicate, unstable formatting
