### ISSUE TITLE
Split long call chains joined by binary operators on the operator

### ISSUE THREAD

**Issue by juanrgon** [psf/black#1781] opened 2020-10-23 00:01 UTC
**Describe the style change** 

When encountering long statements joined with a binary operator (e.g. `statement + statement`), where the statements are long call chains (e.g. `session.query(models.C.id).order_by(models.C.id.asc()).all()`), instead of splitting the entire statement on the binary operator, black splits the overall statement at the first part of the call chain that would go over the line limit.

It would be better if black always split on the operator in these cases.

**Examples in the current _Black_ style** 

```python
variable = function.bar.example(argument_1, argument_2) + function.foo.example(
    argument_1, argument_2
)
```

**Desired style**

```python
variable = (
    function.bar.example(argument_1, argument_2)
    + function.foo.example(argument_1, argument_2)
)
```

**Comment by violetele** [comment] 2020-11-22 10:34
This seems like it might be an inconsistency in the [code style](https://github.com/psf/black/blob/master/docs/the_black_code_style.md) (or, maybe unclear behavior in an ambiguous case?). Between these rules:

>**How Black wraps lines**
>
>...
>
>If not, Black will look at the contents of the first outer matching brackets and put that in a separate indented line.
---
>**Line breaks & binary operators**
>
>Black will break a line before a binary operator when splitting a block of code over multiple lines. This is so that Black is compliant with the recent changes in the PEP 8 style guide, which emphasizes that this approach improves readability.
---
>**Parentheses**
>
>Some parentheses are optional in the Python grammar. Any expression can be wrapped in a pair of parentheses to form an atom. There are a few interesting cases:
>
>...
>
>In those cases, parentheses are removed when the entire statement fits in one line, or if the inner expression doesn't have any delimiters to further split on. If there is only a single delimiter and the expression starts or ends with a bracket, the parenthesis can also be successfully omitted since the existing bracket pair will organize the expression neatly anyway. Otherwise, the parentheses are added.

It's not super clear which one takes precedence in this case. Like @juanrgon I'd argue that PEP8's guidance on binary operators is the nicest choice.

**Comment by jack89roberts** [comment] 2020-11-23 09:15
I come across this fairly often in if statements, e.g. black produces this:
```python   
if (a_long_variable.startswith("A") or a_long_variable.startswith("B")) and len(
    a_long_variable
) == 2:
    print("AB")
```
whereas I think something like this is much more readable (though it adds an extra line):
```python
if (
    (a_long_variable.startswith("A") or a_long_variable.startswith("B"))
    and len(a_long_variable) == 2
):
    print("AB")
```
which incidentally is the result black produces if you make the if statement longer:
```python
if (
    (a_long_variable.startswith("A") or a_long_variable.startswith("B"))
    and len(a_long_variable) == 2
    and a_long_variable[-1] == "Z"
):
    print("AB")
```

**Comment by adigitoleo** [comment] 2020-11-27 12:56
Tiny clarification: the expressions need not be function calls.

Example (manual):

```python
class Compare:
    # __init__ assigns self.attr{1,2,3} as usual...
    def __eq__(self, other) -> bool:
        if self.__class__ is other.__class__:
            return (
                (self.attr1, self.attr2, self.attr3)
                == (other.attr1, other.attr2, other.attr3)
            )
        ...
```

Example (black):

```python
class Compare:
    # __init__ assigns self.attr{1,2,3} as usual...
    def __eq__(self, other) -> bool:
        if self.__class__ is other.__class__:
            return (self.attr1, self.attr2, self.attr3) == (
                other.attr1,
                other.attr2,
                other.attr3,
            )
        ...
```

It seems like this part of the above quoted specs is particularly relevant:

> If there is only a single delimiter and the expression starts or ends with a bracket, the parenthesis can also be successfully omitted

So perhaps binary operators could be treated differently from "delimiters" in this context.

**Comment by andersk** [comment] 2021-05-21 22:05
Possible duplicate of #1254 and the other issues linked from there.

**Comment by JelleZijlstra** [comment] 2022-01-29 16:31
Duplicate of #1254 

(belated thanks to @andersk )

**Closed by JelleZijlstra** 2022-01-29 16:31 UTC
Labels: T: design, F: linebreak
