### ISSUE TITLE
Dict format make value indent at key level when there is if expr in values

### ISSUE THREAD

**Issue by jiamo** [psf/black#991] opened 2019-08-21 01:59 UTC
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:
Operating system:
mac_os_x: 10.14.5
Python version:
3.7.3
*Black* version:
black, version 19.3b0
Does also happen on master:
yes

such as:

            {
                "event_type": "album_comment",
                "album_id": album_id,
                "user_id": user_id,
                "comment_id": str(comment_obj.id),
    -            "parent_comment_id":
    -                str(comment_obj.parent_comment_id) if comment_obj.parent_comment_id else '',
    -            "reply_comment_id":
    -                str(comment_obj.reply_comment_id) if comment_obj.reply_comment_id else '',
    +            "parent_comment_id": str(comment_obj.parent_comment_id)
    +            if comment_obj.parent_comment_id
    +            else '',
    +            "reply_comment_id": str(comment_obj.reply_comment_id)
    +            if comment_obj.reply_comment_id
    +            else '',
                "time": datetime.datetime.utcnow(),
            }

While I think the `if` should not at the same level as the another keys.

**Comment by zsol** [comment] 2019-08-21 06:54
Duplicate of #620.

**Closed by zsol** 2019-08-21 06:54 UTC
