### ISSUE TITLE
`# fmt: off` fails to stop formatting on a comment block

### ISSUE THREAD

**Issue by fpdotmonkey** [psf/black#2329] opened 2021-06-11 23:05 UTC
**Describe the bug**

I have this file header in my source that I'd like to not mess with since it's got license information for code that isn't mine.  So I wrap it in `# fmt: off; ...; # fmt: on` to preserve the block, but the block gets formatted anyway (a space gets added after the `#`).

Before black:

```py
# fmt: off
#===- cindex-dump.py - cindex/Python Source Dump -------------*- python -*--===#
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
#===------------------------------------------------------------------------===#
# fmt: on
```

After black:

```py
# fmt: off
# ===- cindex-dump.py - cindex/Python Source Dump -------------*- python -*--===#
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ===------------------------------------------------------------------------===#
# fmt: on
```

**To Reproduce**

1. Put the top code block in a file
1. Run _Black_ on it
1. Code gets formatted

**Expected behavior**

Code doesn't get formatted

**Environment (please complete the following information):**

- Version:  `__main__.py, version 20.8b1`
- OS and Python version:  `Ubuntu 18.04.5 LTS`, `Python 3.6.9`

**Does this bug also happen on main?**

**Comment by ichard26** [comment] 2021-06-11 23:09
Hey, thanks for reporting the bug! Unfortunately (or fortunately?) this is a duplicate of https://github.com/psf/black/issues/1245 so I'll be closing this.

**Closed by ichard26** 2021-06-11 23:09 UTC
Labels: F: comments, F: fmtoff, R: duplicate, T: bug
