### ISSUE TITLE
Wrapping `[]` braces

### ISSUE THREAD

**Issue by shenek** [psf/black#1709] opened 2020-09-16 07:56 UTC
**Describe the style change** 
Wrapping `[]` vs `()` braces precedence.
**Examples in the current _Black_ style** 
```python
    sorted_ips = sorted(((ip, stat) for ip, stat in self._ips.items()), key=lambda x: x[1])[
        : ForwarderSupervisor.ZCONF_BUFFER_COUNT
    ]
```

**Desired style** 

```python
    sorted_ips = sorted(
        ((ip, stat) for ip, stat in self._ips.items()), key=lambda x: x[1]
    )[:ForwarderSupervisor.ZCONF_BUFFER_COUNT]
```

**Comment by GriceTurrble** [comment] 2020-10-01 17:07
Agreed, I prefer this choice, particularly when it does something like this:

```python
obj = dict()
obj[
    "comment"
] = "See how the key is exploded to a multi-line component because Black doesn't want to chop up the string?"
```

**Comment by minusf** [comment] 2020-11-13 11:35
here is another example:

```py
        # before
        response["Content-Disposition"] = f'attachment; filename="{pk.lower()}-file.yml"'

        # after
        response[
            "Content-Disposition"
        ] = f'attachment; filename="{pk.lower()}-file.yml"'
```

i know style is subjective but i think this is a massive step backwards for readability.  `dict` keys on the left side should never go multiline...

**Comment by ichard26** [comment] 2021-05-30 03:43
While the duplication in this area is absolutely ridiculous, I'll be closing this as a duplicate of #1280.

I'm sure similar cases are covered by some other still open issue :)

**Closed** 2021-05-30 03:44 UTC
Labels: R: duplicate, T: design
