### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by JohnVillalovos** [psf/black#2103] opened 2021-04-12 18:56 UTC
INTERNAL ERROR: Black produced code that is not equivalent to the source

**To Reproduce** Steps to reproduce the behavior:

1. Take this file https://github.com/beaker-project/beaker/blob/8fc7edc07aeb6e545d4c80e5649601edad27b14b/Server/bkr/server/mail.py
2. Run _Black_ on it.
3. INTERNAL ERROR: Black produced code that is not equivalent to the source

**Expected behavior** A clear and concise description of what you expected to happen.
It works

**Environment (please complete the following information):**

- Version: version 20.8b1
- OS and Python version: Linux/Python Python 3.8.7

Diff from error

```
--- src
+++ dst
@@ -6617,11 +6617,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b' Send a system reservation notification to \n    job owner, and to job CC list if any. ',  # bytes
+                b'Send a system reservation notification to\n    job owner, and to job CC list if any.',  # bytes
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(

```

**Comment by akavipat** [comment] 2021-04-16 16:00
This simple code also breaks Black
[firestore_export.txt](https://github.com/psf/black/files/6326400/firestore_export.txt)

error: cannot format bmo-ai-sftp-gcp-cad/utils/firestore_export.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/ambv/black/issues.  This diff might be helpful: /var/folders/ff/fz1n6k812_b3tq95_5cn0d8m0000gn/T/blk_be8xnzmn.log
All done! 💥 💔 💥
1 file failed to reformat.

Diff is below.
--- src
+++ dst
@@ -248,11 +248,11 @@
               value=
                 Call(
                   args=
                     Constant(
                       kind=
-                        'u',  # str
+                        None,  # NoneType
                       value=
                         'No such document!',  # str
                     )  # /Constant
                   func=
                     Name(

**Comment by JelleZijlstra** [comment] 2021-04-16 16:16
@akavipat that looks like a different bug

**Comment by ichard26** [comment] 2021-04-16 16:19
Also, I see "Please report a bug on https://github.com/ambv/black/issues", you must be running an old version of Black. Trying your code with `20.8b1` [works just fine on the Black Playground](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AHSARZdAD2IimZxl1N_WlwxRhR7MSgFP0OztOs3VFGnwR4lFYroIBqZaEaApZ9SxCO8vuXFQav4cR2c4pCfZA06mQJFg9w6qvE8dy3iT_AmeLsYmjteoQKKouE2S5oLDADdg8mR1Lzb9vZvJPme3HUNC72WtQTYuHH9kPq4GH84anEy19OyMt5wOOzluCGUVGY3O3jIjeL41osAraBT7W8X4JtAJEE-CLru5_o-a9fVux6S-tqMwsEPB8JgatyDr5HF_GFLYChigw6EjLAG9oWzeMFLiIh0ys6_ohZU-gYxzWN6jXeEgqUe0G1jJtjhmfHS_vH2VhM2eXrdvTH1h2QfhtxCRDHpXR9GFv2-Z8oufIcsgU4RWpTQzKb_AAAA1suYPmyMd_8AAbIC0wMAAO2dMNixxGf7AgAAAAAEWVo=).

**Comment by akavipat** [comment] 2021-04-16 17:55
My bug is OSX specific I think.  I'm running Version 20.8b1.   The problem is the 'u' in `print(u'No such document!')`.    There is no problem on Windows machine.  On Mac it breaks.

**Comment by JohnVillalovos** [comment] 2021-04-16 18:02
@akavipat   I think you should open your own issue. I don't think the one I reported and yours are the same issue.

**Comment by CiderMan** [comment] 2021-04-22 06:48
There is a PR open (#2037) which should fix the original error reported in this issue. The error mentioned by @akavipat does not seem to be the same root cause so is unlikely to be fixed by that PR.

**Closed** 2021-04-22 15:40 UTC
Labels: bug
