### ISSUE TITLE
Imports crossing line length even after formatting

### ISSUE THREAD

**Issue by prasanth-nw** [psf/black#3845] opened 2023-08-19 02:26 UTC
**Is your feature request related to a problem? Please describe.**

I am planning to use black for my existing large codebase. till now it didnt have any formatters used.
black does change a lot of code along with replacing code with backslashes to paranthesis which i am fine with to maintain consistency. but my import statements are greater than 79 chars even after formatting because of nested module structure and long file names which doesn't look good in my code.

**Describe the solution you'd like**
why not ignore import statements with black slashes for formatting with a configuration? 
or 
if after the format if the line is still crossing 79 chars why not leave it as before?

**Describe alternatives you've considered**
i could add fmt:off/on for import statements set but again that is a redundant work and increases comments in code.

**Additional context**
ex: from psf_black_github.nested_module_structure.\
    internal_adapters_should_be_used_for internal purpose
    
 after format this will be greater than 79 chars again.
 
 i searched ways to handle this but i couldn't find any. and this is a blocker for me to use black.

**Comment by hauntsaninja** [comment] 2023-08-19 05:25
You haven't provided a complete example, but I think this is a duplicate of https://github.com/psf/black/issues/3324

**Closed by hauntsaninja** 2023-08-19 05:25 UTC
Labels: T: enhancement
