### ISSUE TITLE
Inconsistent code formatting error

### ISSUE THREAD

**Issue by whs** [psf/black#1978] opened 2021-02-09 16:42 UTC
**Black v20.8b1**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADuAJ9dAD2IimZxl1N_Wlws4TBexXdmg613D2W2qfKWxerYSuL3K1ZfV4loUfcNMx82RHHwXaElt3COuIetGX5sp9OsS0Fve3D0JPCdd4jPqakEWnB7ZkRTr0ayMvAqGRP9p2GVY_b4oK2NwE91XwIAky1SPFvDpSUeCRn9qAwBfD2fGU_JORh70cQVbePHICwZlfyx3_Xsy9DubFWJzglgLhgd4gAAEaLsKMeDOL8AAbsB7wEAAIIl5gGxxGf7AgAAAAAEWVo=)

## Options

`--line-length=88`
`--safe`

## Input

```python
if True:
    pass
elif feature in (QWebEnginePage.DesktopVideoCapture, QWebEnginePage.DesktopAudioVideoCapture) and self.app.has_permission('pixel'):
    pass
```

## Output

```python
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_t3rp1oih.log

Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,4 +1,7 @@
 if True:
     pass
-elif feature in (QWebEnginePage.DesktopVideoCapture, QWebEnginePage.DesktopAudioVideoCapture) and self.app.has_permission('pixel'):
+elif feature in (
+    QWebEnginePage.DesktopVideoCapture,
+    QWebEnginePage.DesktopAudioVideoCapture,
+) and self.app.has_permission("pixel"):
     pass
--- first pass
+++ second pass
@@ -1,7 +1,11 @@
 if True:
     pass
-elif feature in (
-    QWebEnginePage.DesktopVideoCapture,
-    QWebEnginePage.DesktopAudioVideoCapture,
-) and self.app.has_permission("pixel"):
+elif (
+    feature
+    in (
+        QWebEnginePage.DesktopVideoCapture,
+        QWebEnginePage.DesktopAudioVideoCapture,
+    )
+    and self.app.has_permission("pixel")
+):
     pass

```

## Expected

If I write it by hand I'd prefer

```python
if True:
    pass
elif (
    feature in (
        QWebEnginePage.DesktopVideoCapture,
        QWebEnginePage.DesktopAudioVideoCapture
    )
    and self.app.has_permission('pixel')
):
    pass
```

The code is from https://github.com/whs/runekit/blob/master/runekit/app/view/browser_window.py

**Comment by mvolfik** [comment] 2021-02-22 18:51
This is a duplicate of #1629 , as the short sample works after applying #1958. However, when I take the [full file](https://raw.githubusercontent.com/whs/runekit/67ce199dd294d443af2e989324be2214f25d91d4/runekit/app/view/browser_window.py), black still fails. I'll report in the #1629 thread and suggest closing this.

**Comment by ichard26** [comment] 2021-04-25 20:19
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:19 UTC
Labels: bug, duplicate, unstable formatting
