### ISSUE TITLE
black on windows failed to write to Cache

### ISSUE THREAD

**Issue by raybellwaves** [psf/black#1703] opened 2020-09-14 16:20 UTC
Isntalled black via a conda yaml file

```
name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - black
  - ...
```

When opening `jupyter lab` I see
```
Generating grammar tables from C:\Users\XXXXXX\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\blib2to3\Grammar.txt
Writing grammar tables to C:\Users\XXXXXX\AppData\Local\black\black\Cache\20.8b1\Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: 'C:\\Users\\XXXXXX\\AppData\\Local\\black\\black\\Cache\\20.8b1\\tmp2h8c2bh_'
Generating grammar tables from C:\Users\XXXXXX\AppData\Local\Continuum\anaconda3\envs\test_env\lib\site-packages\blib2to3\PatternGrammar.txt
Writing grammar tables to C:\Users\XXXXXX\AppData\Local\black\black\Cache\20.8b1\PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: 'C:\\Users\\XXXXXX\\AppData\\Local\\black\\black\\Cache\\20.8b1\\tmp2saxt6p8'
```

Looking in C:\Users\XXXXXX\AppData\Local\black\black\Cache I see 19.10b0 but no 20.8b1. I believe last time it was able to add that folder so unsure what happened this time.

- Version: 20.8b1
- OS and Python version: Windows 10. Python 3.8.

**Comment by raybellwaves** [comment] 2020-09-14 16:24
Manually added the 20.8b1 folder to the Cache folder and worked fine next time I opened jupyter lab

**Comment by ichard26** [comment] 2020-09-16 23:23
Duplicate of #1143.

**Closed by ichard26** 2020-09-16 23:23 UTC
Labels: bug, duplicate
