### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by mrm-david** [psf/black#1842] opened 2020-11-27 09:51 UTC
What happened
```
black -S -l 120 tb.py
error: cannot format tb.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_h13esjbk.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

Versions

```
$ python3 --version
Python 3.8.5
$ black --version
black, version 20.8b1
$ uname -a
Linux xxxxxxxxx 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Test code that fails : (tp.py)

```python
def fields_Boolean(compute):
    pass

mrm_weight_material_required = fields_Boolean(compute="_get_mrm_weight_material_required")

def _get_mrm_weight_material_required(self):
    for rec in self:
        rec.mrm_weight_material_required = rec.state not in ("xxxxx", "yyyyyyyy", "zzzzz") and \
                                           rec.mrm_material_id.element_id.code in ("uu", "ww")
```

Log: 
[blk_h13esjbk.log](https://github.com/psf/black/files/5607149/blk_h13esjbk.log)

**Comment by ichard26** [comment] 2021-04-25 20:12
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:12 UTC
Labels: duplicate, unstable formatting
