### ISSUE TITLE
Don't wrap `| None` on a new line

### ISSUE THREAD

**Issue by Olegt0rr** [psf/black#3874] opened 2023-09-10 16:07 UTC
**Describe the style change**

I don't like current behavior on documented FastAPI handlers.

```python
@router.get("/path")
async def some_handler(
    can_restrict_members: bool | None = Query(None, description="Can restrict members?"),  # the line is toooooo long
):
    ...
```

**Examples in the current _Black_ style**

```python
async def some_handler(
    can_restrict_members: bool
    | None = Query(
        None,
        description="Can restrict members?",
    ),
):
    ...
```

**Desired style**

```python
async def some_handler(
    can_restrict_members: bool | None = Query(
        None,
        description="Can restrict members?",
    ),
):
    ...
```

**Additional context**
```txt
black==23.9.0
```

**Comment by JelleZijlstra** [comment] 2023-09-10 21:44
Thanks, duplicate of #2316. (I agree this style is ugly and we should change it. PRs welcome!)

**Closed by JelleZijlstra** 2023-09-10 21:44 UTC
Labels: T: style
