### ISSUE TITLE
PythonTidy.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.

### ISSUE THREAD

**Issue by jidanni** [psf/black#2002] opened 2021-02-24 02:13 UTC
I ran black on https://github.com/witsch/PythonTidy/blob/master/PythonTidy.py and got INTERNAL ERROR: Black produced code that is not equivalent to the source. black, version 20.8b1

**Comment by CiderMan** [comment] 2021-02-25 09:42
Given that file is Python2, this is likely a duplicate of [#1844](https://github.com/psf/black/issues/1844).

**Comment by jidanni** [comment] 2021-02-26 02:03
Maybe the error message should say "Is this python2? If so, all bets are off."

**Comment by ichard26** [comment] 2021-02-26 02:21
> Maybe the error message should say "Is this python2? If so, all bets are off."

Black explicitly supports formatting Python 2.7 code, it just needs to be run via a CPython 3.6 or higher installation, so "all bets are off" doesn't seem right. Unfortunately due to time constraints, fixes haven't landed.

**Comment by jidanni** [comment] 2021-02-26 03:21
All I know is it happened with
```
$ python3 --version
Python 3.9.1+
$ black --version
black, version 20.8b1
```

**Comment by CiderMan** [comment] 2021-02-26 09:50
The file you are running Black on is Python 2. I am not a Black developer but I investigated a similar issue and found that it was an issue related to parsing Python 2 specifically. I even came up with a hack/workaround/fix that resolved the issue but, until I am told whether it is a fix or a hack, I'm not taking it further...

**Closed** 2021-04-22 15:40 UTC
Labels: bug
