### ISSUE TITLE
Strange linebreak

### ISSUE THREAD

**Issue by keli** [psf/black#1863] opened 2020-12-10 13:26 UTC
I suppose this is a bug. Take the following code:

```python
if (self.rotation_days > 1 and default_ratio < self.default_ratio) or target.attrs[0].subattr.expiry not in expiries:
    pass
```

And black formatted output became:
```python
if (self.rotation_days > 1 and default_ratio < self.default_ratio) or target.attrs[
    0
].subattr.expiry not in expiries:
    pass
```
- Version: master
- OS and Python version: Mac/Python 3.6.3/3.8.2

**Comment by JelleZijlstra** [comment] 2022-01-29 16:39
Duplicate of #236

**Closed by JelleZijlstra** 2022-01-29 16:39 UTC
Labels: T: bug, T: design, F: linebreak
