### ISSUE TITLE
Output successful executions to stdout and errors messages to stderr

### ISSUE THREAD

**Issue by Wlodarski** [psf/black#1311] opened 2020-03-20 14:19 UTC
**Feature request**
To increase interoperability with other software, open the door to other forms of automation, allow forensics, proper pipe redirections, and a multitude of other related advantages, it would be interesting to output successful executions and errors to their separate appropriate standard outputs, ``sys.stdout`` and ``sys.stderr``,  as it is the universally expected behavior on all platforms since the 1970's.

**Describe the solution you'd like** 
Something in the vain of (or whatever works) :
```python
import sys
...
       if report.return_code:
           out("Oh no! 💥 💔 💥", file=sys.stderr)  # to stderr
       else:
           out("All done! ✨ 🍰 ✨", file=sys.stdout)  # to stderr
```

**Reference**:
 - https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

**Comment by cooperlees** [comment] 2020-03-20 14:43
This is a duplicate of #1285. Please follow along there and look at suggestion of https://github.com/psf/black/commit/b3e5ea576a5b725731f0c6eb69be5534795fffbd
- Awaiting other black maintainers to agree or disagree ...

**Closed by cooperlees** 2020-03-20 14:43 UTC
Labels: duplicate, enhancement
