### ISSUE TITLE
Sort imports

### ISSUE THREAD

**Issue by JoshPaulie** [psf/black#2391] opened 2021-07-22 15:53 UTC
**Is your feature request related to a problem? Please describe.**

Having to run isort is an additional step when formatting code.

**Describe the solution you'd like**

Black sorts imports (similar to isort) and removes unused. 

**Additional context**

Black is great, just an idea to make it better.

**Comment by JelleZijlstra** [comment] 2021-07-22 16:12
Duplicate of #333.

**Closed by JelleZijlstra** 2021-07-22 16:12 UTC
