### ISSUE TITLE
(🎁) Ability to specify default files in the config

### ISSUE THREAD

**Issue by KotlinIsland** [psf/black#3646] opened 2023-04-14 05:50 UTC
I want to be able to specify the default files within the configuration file so that I don't need to duplicate this config in different places.

```toml
[tool.black]
files = ["src", "scripts"]
```

Then it is possible to invoke black without passing any paths:
```
👉 black
yada yada yada ✨
```

Related: https://github.com/charliermarsh/ruff/issues/3970

**Comment by ichard26** [comment] 2023-04-16 20:06
This is a duplicate of https://github.com/psf/black/issues/861. While I have little authority now being inactive, I'm still not convinced this is a good idea.

**Comment by JelleZijlstra** [comment] 2023-04-17 02:11
Closing as a duplicate (I knew it was one but couldn't find the old one).

**Closed by JelleZijlstra** 2023-04-17 02:11 UTC
Labels: R: duplicate, T: enhancement, C: configuration, C: file collection
