### ISSUE TITLE
Comments end up colliding after reformatting multiline arithmetic expression

### ISSUE THREAD

**Issue by cfbolz** [psf/black#1033] opened 2019-09-24 17:18 UTC
Operating system: Ubuntu
Python version: Python 3.7.3
*Black* version: 19.3b0
Does also happen on master: Yes

Thanks a lot for all your amazing work on black!

I understand that always getting the placement of comments always right is probably hard or impossible, but I was still very surprised by this behaviour of black. This code:

```python
x = (
    100 * 2 +  # direct ints
    400 * 4 +  # larger ints
    500 * 2 +  # unmodified
    1000 * 10  # floats
)
```

get's turned into:

```python
x = (
    100 * 2
    + 400 * 4  # direct ints
    + 500 * 2  # larger ints
    + 1000 * 10  # unmodified  # floats
)
```

This means that the comments get moved to the wrong part of the expressions, and then in the last line two comments are merged. I'd hope for this kind of output:

```python
x = (
    100 * 2  # direct ints
    + 400 * 4  # larger ints
    + 500 * 2  # unmodified
    + 1000 * 10  # floats
)
```

**Comment by hugovk** [comment] 2019-09-24 17:26
Duplicate of https://github.com/psf/black/issues/771?

**Comment by cfbolz** [comment] 2019-09-24 20:50
yes, I agree that it's very similar, but I found the fact that the two comments end up being next to each other particularly disconcerting.

**Comment by JelleZijlstra** [comment] 2023-04-29 01:31
This is #379.

**Closed by JelleZijlstra** 2023-04-29 01:31 UTC
Labels: F: comments
