### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter. -- long line with comparison to set subtraction of 2 sets

### ISSUE THREAD

**Issue by AlbertoEAF** [psf/black#1877] opened 2020-12-21 16:54 UTC
**Describe the bug**

The following code is enough to trigger the bug:
```python
e = dict()

assert {} == {"inputs", "outputs", "pipeline_execution_id", "results", "state", "task_config", "task_config_id", "id", "started_at", "updated_at", "finished_at"} - set(e[0].keys())
```

The bug doesn't show up if I either:
- Use the right hand side (RHS) of the comparison alone. 
- Wrap the RHS in parenthesis.

**Environment (please complete the following information):**

- **Version:** 20.8b1
- **OS and Python version:** Ubuntu 18.04, clean virtual env with python3.7 + black

**Does this bug also happen on master?** 

Yes

**Comment by mvolfik** [comment] 2021-02-22 20:30
Works with #1958, so likely a duplicate of #1629

**Comment by ichard26** [comment] 2021-04-25 20:05
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:05 UTC
Labels: bug, duplicate, unstable formatting
