### ISSUE TITLE
Black crashes when trying to format this example

### ISSUE THREAD

**Issue by lsorber** [psf/black#1889] opened 2020-12-28 01:27 UTC
Black crashes when trying to format this example:

```python
φ = np.exp(
    1j * (X @ self.Z_ if self.shift_ is None else X @ self.Z_ - self.shift_),
    dtype=np.complex64 if X.dtype == np.float32 else None
) / np.sqrt(self.num_features)
```

[Diff from black.now.sh](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEHALRdAD2IimZxl1N_Wk6vSDCUqxr_eHoLlC3bOGVKNHnshRsvRxDWD5QpqMVJA0eTfwTK79hChOb5qXnWD6hOoAtqaAOkXcnEAwaSpjOBt2vRWF3Ma2EIPuuemD8NyHhw2SChiaZ2nzGnirfTK_GS4krqSWgiz4QZkiAI5tKOmyOD4z5CDKkHZYwXZuy3BC5BUrvoW4WW04tDp7uo5GunRR4ipeqaZsIwUONBDoTvuZ1yH32e125OAAB1WDUPlnPXvQAB0AGIAgAA-Ktix7HEZ_sCAAAAAARZWg==):
```diff
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_dckjw0xt.log

Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,4 +1,4 @@
 φ = np.exp(
     1j * (X @ self.Z_ if self.shift_ is None else X @ self.Z_ - self.shift_),
-    dtype=np.complex64 if X.dtype == np.float32 else None
+    dtype=np.complex64 if X.dtype == np.float32 else None,
 ) / np.sqrt(self.num_features)
--- first pass
+++ second pass
@@ -1,4 +1,7 @@
-φ = np.exp(
-    1j * (X @ self.Z_ if self.shift_ is None else X @ self.Z_ - self.shift_),
-    dtype=np.complex64 if X.dtype == np.float32 else None,
-) / np.sqrt(self.num_features)
+φ = (
+    np.exp(
+        1j * (X @ self.Z_ if self.shift_ is None else X @ self.Z_ - self.shift_),
+        dtype=np.complex64 if X.dtype == np.float32 else None,
+    )
+    / np.sqrt(self.num_features)
+)
```

**Comment by mvolfik** [comment] 2021-02-22 20:28
Works with #1958, so likely a duplicate of #1629

**Comment by ichard26** [comment] 2021-04-25 20:20
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should
 be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:20 UTC
Labels: bug, duplicate, unstable formatting
