### ISSUE TITLE
Black produces invalid code with nested comprehension against generator statement with comments

### ISSUE THREAD

**Issue by pipermerriam** [psf/black#1798] opened 2020-10-30 17:41 UTC
- Version: `19.10b0`
- OS and Python version: Linux/3.8.2

When trying to format this:

```python
from typing import Tuple, Sequence

def get_subtree_proof_nodes(
        chunk_index_groups: Sequence[Tuple[int, ...], ...],
) -> Tuple[int, ...]:
    subtree_node_paths = (
        # We take a candidate element from each group and shift it to
        # remove the bits that are not common to other group members, then
        # we convert it to a tree path that all elements from this group
        # have in common.
        chunk_index
        for chunk_index, bits_to_truncate
        # Each group will contain an even "power-of-two" number of# elements.
        # This tells us how many tailing bits each element has# which need to
        # be truncated to get the group's common prefix.
        in ((group[0], (len(group) - 1).bit_length()) for group in chunk_index_groups)
    )
    return subtree_node_paths
```

Black produces this error: 

```
error: cannot format arst.py: INTERNAL ERROR: Black produced invalid code: invalid syntax (<unknown>, line 5)
```

The invalid output it produces is:

```python
from typing import Tuple, Sequence


def get_subtree_proof_nodes(
    chunk_index_groups: Sequence[Tuple[int, ...], ...],
) -> Tuple[int, ...]:
    subtree_node_paths = (
        # We take a candidate element from each group and shift it to
        # remove the bits that are not common to other group members, then
        # we convert it to a tree path that all elements from this group
        # have in common.
        chunk_index
        for chunk_index, bits_to_truncate# Each group will contain an even "power-of-two" number of# elements.# This tells us how many tailing bits each element has# which need to# be truncated to get the group's common prefix. in (
            (group[0], (len(group) - 1).bit_length()) for group in chunk_index_groups
        )
    )
    return subtree_node_paths
```

You can see that it incorrectly merges the `in` statement into the comment.

**Comment by ichard26** [comment] 2020-10-31 03:00
Oh dear that doesn't look good. This is probably a dupe of #563, but regardless can confirm this is still an issue on current master (8c8af4f1612dc29358490a7d04dd4ff2f5d4939d). I'm on Ubuntu 20.04.01 LTS and using CPython 3.8.5.

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black temp.py --diff --color
error: cannot format temp.py: INTERNAL ERROR: Black produced invalid code: invalid syntax (<unknown>, line 5). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: /tmp/blk_hmesyz0o.log
Oh no! 💥 💔 💥
1 file would fail to reformat.
(black) ichard26@acer-ubuntu:~/programming/oss/black$ cat temp.py | black --fast - 
from typing import Tuple, Sequence


def get_subtree_proof_nodes(
    chunk_index_groups: Sequence[Tuple[int, ...], ...],
) -> Tuple[int, ...]:
    subtree_node_paths = (
        # We take a candidate element from each group and shift it to
        # remove the bits that are not common to other group members, then
        # we convert it to a tree path that all elements from this group
        # have in common.
        chunk_index
        for chunk_index, bits_to_truncate# Each group will contain an even "power-of-two" number of# elements.# This tells us how many tailing bits each element has# which need to# be truncated to get the group's common prefix. in (
            (group[0], (len(group) - 1).bit_length()) for group in chunk_index_groups
        )
    )
    return subtree_node_paths
[snip]
```

**Comment by JelleZijlstra** [comment] 2021-05-29 02:52
Still crashes on current main.

**Comment by JelleZijlstra** [comment] 2021-05-30 02:36
But as @ichard26 said this is really the same issue as #563.

**Closed by JelleZijlstra** 2021-05-30 02:36 UTC
Labels: C: invalid code, F: comments, T: bug
