### ISSUE TITLE
Black inconsistent about arguments with many alternative types

### ISSUE THREAD

**Issue by Illviljan** [psf/black#2767] opened 2022-01-12 19:34 UTC
**Describe the style change**
Black is not consistent when arguments can be many types.

This is the original format, both `stat_lengthh` and `stat_lengths` have the same typing but one has parenthesis around it:
```python
from __future__ import annotations

from typing import Any, Mapping


class test:
    def pad(
        self,
        stat_lengthh: (int | tuple[int, int] | Mapping[Any, tuple[int, int]] | None) = None,
        stat_lengths: int | tuple[int, int] | Mapping[Any, tuple[int, int]] | None = None,
    ):
        pass
```

**Examples in the current _Black_ style**

Black formats the same typing in two different ways making it hard to see they are exactly the same:
```python
from __future__ import annotations

from typing import Any, Mapping


class test:
    def pad(
        self,
        stat_lengthh: (
            int | tuple[int, int] | Mapping[Any, tuple[int, int]] | None
        ) = None,
        stat_lengths: int
        | tuple[int, int]
        | Mapping[Any, tuple[int, int]]
        | None = None,
    ):
        pass
```

**Desired style**
I prefer the variant with parenthesis. 

```python
from __future__ import annotations

from typing import Any, Mapping


class test:
    def pad(
        self,
        stat_lengthh: (
            int | tuple[int, int] | Mapping[Any, tuple[int, int]] | None
        ) = None,
        stat_lengths: (
            int | tuple[int, int] | Mapping[Any, tuple[int, int]] | None
        ) = None,
    ):
        pass
```

**Additional context**

**Comment by felix-hilden** [comment] 2022-01-12 19:36
All for the consistency, but personally I'm not sure which style would be better. Thanks for reporting!

**Comment by JelleZijlstra** [comment] 2022-01-12 19:37
I also prefer the parenthesized version, since it makes it easier to see where each new parameter starts.

Anyway, this is a duplicate of #2316.

**Closed by JelleZijlstra** 2022-01-12 19:37 UTC
Labels: T: design, F: linebreak
