### ISSUE TITLE
IndentationError on valid Python triggered by fmt: off

### ISSUE THREAD

**Issue by DRMacIver** [psf/black#3705] opened 2023-05-25 14:21 UTC
When running black (tested with version 23.3.0) as follows:

```
import black

code = """
if True:
 if True:
  # fmt: off
  pass
"""

black.format_str(code, mode=black.Mode())
```

This produces the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/black/__init__.py", line 1084, in format_str
  File "src/black/__init__.py", line 1089, in _format_str_once
  File "src/black/parsing.py", line 94, in lib2to3_parse
  File "src/blib2to3/pgen2/driver.py", line 213, in parse_string
  File "src/blib2to3/pgen2/driver.py", line 140, in parse_tokens
  File "src/blib2to3/pgen2/driver.py", line 104, in __next__
  File "src/blib2to3/pgen2/tokenize.py", line 529, in generate_tokens
    start, end = pseudomatch.span(1)
  File "<tokenize>", line 4
    pass
IndentationError: unindent does not match any outer indentation level
```

Variations on this example that do not cause black to error:

1. Changing it to four space indents.
2. Removing the #fmt: off
3. Reducing the level of nesting to that of a single 

This example seems extremely similar to #3702, but produces a different error from a different location so seemed worth reporting as its own thing.

**Comment by JelleZijlstra** [comment] 2023-05-26 05:18
Duplicate of #3505

**Closed by JelleZijlstra** 2023-05-26 05:18 UTC
Labels: T: bug
