### ISSUE TITLE
Cannot format: INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by mangelozzi** [psf/black#3154] opened 2022-07-04 14:55 UTC
Output requested me to file the attached bug:

**Black https://github.com/psf/black/commit/b859a3**

[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AIBASxdAD2IimZxl1N_WlkPinBFn628DOx5CgGZMM6rczYy5AFFvS7GvvAcBgTKC6rZh1PJdxQSC5PI0jWsyZtrQUwnYdrknWC8iUW6_Z49oHy0yA6A8jg6sDY_xIiep4SsSkCAHm63RLX0cW6xllU84CeWHSj8E64S73IucAfZyxc-U_XZdDzvu5F00HDo7gSG_mBJBs3Fl4_Aqg6mvZ355OThFS6PwbcVgeIKUtQv3Np0KV8ezkeNZJT8d-QndUcTJGwdJ6u3-1gjIKJSW5xmtyQ6khLGQnKCGI8TAlTuGdag12loZdC70QUAO9MXUwrPv52qZWpK5mhJiBkD9OGXyoiD-Dlc5zRh6a2V4e6FyDRV89EvX_3BGTtkSh4XRk3h3Sa4XgbpokY5lmUSJ_cjAAB3Z0qp3zHvbQAByAKCBAAACM13BLHEZ_sCAAAAAARZWg==)

## Options

`--line-length=88`
`--safe`

## Input

```python
from django.test import SimpleTestCase

from .. import typers

class filter_Tests(SimpleTestCase):
    def test_ok(self):
        for filter in (
            'blur', 'brightness', 'contrast', 'drop-shadow', 'grayscale',
            'hue-rotate', 'invert', 'opacity', 'saturate', 'sepia',
        ): # fmt: skip
            val = f"{filter}(123)"
            self.assertEqual(val, typers.filter(val))
```

## Output

```python
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_y8xv5gkb.log

Mode(target_versions=set(), line_length=88, string_normalization=True, is_pyi=False, is_ipynb=False, magic_trailing_comma=True, experimental_string_processing=False, python_cell_magics=set(), preview=False)
--- source
+++ first pass
@@ -1,12 +1,25 @@
 from django.test import SimpleTestCase
 
 from .. import typers
 
+
 class filter_Tests(SimpleTestCase):
     def test_ok(self):
         for filter in (
-            'blur', 'brightness', 'contrast', 'drop-shadow', 'grayscale',
-            'hue-rotate', 'invert', 'opacity', 'saturate', 'sepia',
-        ): # fmt: skip
+            "blur",
+            "brightness",
+            "contrast",
+            "drop-shadow",
+            "grayscale",
+            "hue-rotate",
+            "invert",
+            "opacity",
+            "saturate",
+            "sepia",
+        ):
+
             val = f"{filter}(123)"
-            self.assertEqual(val, typers.filter(val))
\ No newline at end of file
+            self.assertEqual(val, typers.filter(val))
+
+
+# fmt: skip
--- first pass
+++ second pass
@@ -18,8 +18,6 @@
             "sepia",
         ):
 
             val = f"{filter}(123)"
             self.assertEqual(val, typers.filter(val))
-
-
-# fmt: skip
+  # fmt: skip

```

## Expected

**Comment by felix-hilden** [comment] 2022-07-04 14:59
Hi! Thanks for submitting, but I'll close this as a duplicate of #2646

**Closed by felix-hilden** 2022-07-04 14:59 UTC
Labels: T: bug, R: duplicate, C: unstable formatting, F: fmtskip
