### ISSUE TITLE
Undesired split after multiline triple quoted string.

### ISSUE THREAD

**Issue by iago-lito** [psf/black#1876] opened 2020-12-21 08:37 UTC
I've got an undesired split after multiline `"""` string when searching the sea monster in yesterday's AoC:

```python
pattern = """
                  # 
#    ##    ##    ###
 #  #  #  #  #  #   
""".strip(
    "\n"
)
```

I'd rather keep what I initially wrote:

```python
pattern = """
                  # 
#    ##    ##    ###
 #  #  #  #  #  #   
""".strip("\n")
```

I'm also suprised because none of the above hits the max width, any idea why the splitting occurs?

**Comment by ichard26** [comment] 2020-12-22 16:32
Duplicate of #256.

Why the line break?
> Black considers multiline strings as always not fitting a single line (per definition), so it tries to break the line if possible. I agree that in this case the result is sub-optimal. I'll see what I can do to improve this.

https://github.com/psf/black/issues/256#issuecomment-392666428

**Closed by ichard26** 2020-12-22 16:32 UTC
Labels: design, duplicate
