### ISSUE TITLE
Error when formatting a project containing requirements.txt file

### ISSUE THREAD

**Issue by wjwatkinson** [psf/black#1845] opened 2020-11-29 19:04 UTC
I am using black gitlab ci to make sure that merge requests are properly formatted before they are merged. It is a django project hosted on aws elastic beanstalk. In order to work with elastic beanstalk I need the requirements.txt file in the same folder as the manage.py file. In my project structure these are both within a mysite folder:
```
project
|-mysite
  |-mysite
  |-templates
  |- manage.py
  |- requirements.txt
|-README.md
```

When I run `black` on the mysite folder, it errors on the requirements.txt file.
`error: cannot format ...mysite/requirements.txt: Cannot parse: 1:11: Django==3.0.8`

To resolve this I am storing the `requirements.txt` file in the project root directory and copying it into the mysite folder before deploying. This works, but I am curious if there is a better way of handling this.

**Comment by ichard26** [comment] 2020-12-12 19:28
Black's default regex for `--include` means any files that don't have a `.py` or `.pyi` extension are automatically skipped so the requirements file should't be collected. Did you by any chance configure `--include` in a pyproject.toml file? Or maybe the files inside the directory are being passed to Black's CLI directory (`black mysite/*`?) and therefore aren't subject to the include and exclude regexes.

**Comment by wjwatkinson** [comment] 2020-12-14 16:32
Thanks @ichard26 for some reason black mysite/ was not finding any files locally, so I had been using black mysite/*. When I started using pipenv and black version 19.10b0 black mysite/ is finding the expected files and ignoring requirements.txt! I appreciate the help!

**Comment by ichard26** [comment] 2020-12-25 02:49
Sorry to bug you but "for some reason black mysite/ was not finding any files locally" doesn't sound good. Even though what was reported originally here is `not a bug`, you probably shouldn't need to use `black mysite/*`. I want to figure out whether something did change between versions `19.10b0` and `20.8b1`. So, if possible, could you possibly come up with a small reproducible case that shows the behaviour you stated above?

If not for whatever reason that's okay, but please just let me know so I can close this issue and prevent it from staying open and useless.

**Comment by wjwatkinson** [comment] 2021-01-04 15:20
@ichard26 sorry for the slow response here. I was taking some time away from the computer over the holidays :)

I just spent some time trying to reproduce the issue using 19.10b0, 20.8b0, 20.8b1, but was unable to. I also looked through the git history of the project to see if there was a different version in there, but it had unfortunately not been committed until I got it working using 19.10b0. Based on these tests it is seeming like it was human error, so you should be okay to close this. I appreciate the help!

**Comment by ichard26** [comment] 2021-01-04 15:26
No issue taken! At least I have now one less issue on my "to-do" list of github notifications :D

> I was taking some time away from the computer over the holidays :)

That's good to hear :)

**Closed by ichard26** 2021-01-04 15:26 UTC
Labels: not a bug
