### ISSUE TITLE
Internal Error when using #fmt: off

### ISSUE THREAD

**Issue by williamjamir** [psf/black#1805] opened 2020-11-04 22:30 UTC
**Black v20.8b1**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC4AG5dAD2IimZxl1N_Wk6tt2q7MPb5h5_MZZGBrAZ65YQ8GysuFpPGUBLMJcmZh93OXPJHvemAKPdGQHTQTQAWIJhf6J4iwJy4jQf89_5yNB01iCw081dX1FZ0MP3HW2nsMSyVpGOIWk4tLhtv-yG0m-8AAAAAIMOX4PGIj90AAYoBuQEAAPShpiCxxGf7AgAAAAAEWVo=)

## Options

`--line-length=88`
`--safe`

## Input

```python

def testA():
    # fmt: off
    assert 1 == 1
    # ftm: on


def testB():
    ...
```

## Output

```python
INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_br_2qz1n.log

--- src
+++ dst
@@ -32,46 +32,46 @@
               ops=
                 Eq(
                 )  # /Eq
             )  # /Compare
         )  # /Assert
+        FunctionDef(
+          args=
+            arguments(
+              args=
+              defaults=
+              kw_defaults=
+              kwarg=
+                None,  # NoneType
+              kwonlyargs=
+              posonlyargs=
+              vararg=
+                None,  # NoneType
+            )  # /arguments
+          body=
+            Expr(
+              value=
+                Constant(
+                  kind=
+                    None,  # NoneType
+                  value=
+                    Ellipsis,  # ellipsis
+                )  # /Constant
+            )  # /Expr
+          decorator_list=
+          name=
+            'testB',  # str
+          returns=
+            None,  # NoneType
+          type_comment=
+            None,  # NoneType
+        )  # /FunctionDef
       decorator_list=
       name=
         'testA',  # str
       returns=
         None,  # NoneType
       type_comment=
         None,  # NoneType
     )  # /FunctionDef
-    FunctionDef(
-      args=
-        arguments(
-          args=
-          defaults=
-          kw_defaults=
-          kwarg=
-            None,  # NoneType
-          kwonlyargs=
-          posonlyargs=
-          vararg=
-            None,  # NoneType
-        )  # /arguments
-      body=
-        Expr(
-          value=
-            Constant(
-              kind=
-                None,  # NoneType
-              value=
-                Ellipsis,  # ellipsis
-            )  # /Constant
-        )  # /Expr
-      decorator_list=
-      name=
-        'testB',  # str
-      returns=
-        None,  # NoneType
-      type_comment=
-        None,  # NoneType
-    )  # /FunctionDef
   type_ignores=
 )  # /Module

```

## Observation

If I remove either `# fmt` or testB than everything works fine.

**Comment by ichard26** [comment] 2020-11-04 22:34
Hey thanks for reporting but I'm closing this issue as it is a duplicate of #569.

**Closed by ichard26** 2020-11-04 22:34 UTC
Labels: bug, duplicate, invalid code
