### ISSUE TITLE
Syntax error for variable with type hint assigned to a tuple lacking parentheses

### ISSUE THREAD

**Issue by brettcannon** [psf/black#1374] opened 2020-05-02 18:09 UTC
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Try to format `variable: tuple = False, ""` ([Playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABbAEddAD2IimZxl1N_Wmp8WjEM7tySKog-Iz6JHbXjGRRL8YV_F-p-PvbWJwD_yVK6BP5AEmU1002_rXPpowH_T0Y0Hqif_ZQ8V0wAAABlYIu5Ge5c3gABY1yQkIsMH7bzfQEAAAAABFla))
2. Run _Black_ on it with no arguments
3. See error
```
error: cannot format tester.py: Cannot parse: 1:23: variable: tuple = False, ""
Oh no! 💥 💔 💥
```

**Expected behavior** A clear and concise description of what you expected to happen.

No error.

**Environment (please complete the following information):**

- Version: 19.10b0
- OS and Python version: macOS Catalina, CPython 3.8.2

**Does this bug also happen on master?**

Yes.

**Additional context** Add any other context about the problem here.

**Comment by JelleZijlstra** [comment] 2020-05-02 18:12
Duplicate of #1368.

**Closed by JelleZijlstra** 2020-05-02 18:12 UTC
Labels: bug
