### ISSUE TITLE
Black comments out my code (aborts with INTERNAL ERROR)

### ISSUE THREAD

**Issue by Zac-HD** [psf/black#1358] opened 2020-04-23 09:23 UTC
**Black v19.10b0** - [Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACjAHhdAD2IimZxl1N_WjIzHZ1LMyYSfGQWe9JD04RQk4g83QUYADGS6ScwEDRI-kY60Z-p9RhUJb1QZTLKMBsowZy5HARYL3WzxtAlj9qwWZ5DBoj7quPEHrLWfHgrifLe8s0O-Qy093CjgfmH7uoV5yW1uFNLEo1MJSkAAABtKUuHkIGYpgABlAGkAQAAXU0Ju7HEZ_sCAAAAAARZWg==)

## Input

```python
@decorator(
    # a comment
    call_this()  # type: ignore
)
def test():
    pass
```

## Output

```python
@decorator(
    # a commentcall_this()  # type: ignore
)
def test():
    pass
```

(and I must say the workflow to report an issue from the playground is fantastic!)

**Comment by ichard26** [comment] 2020-10-05 23:11
Duplicate of #1287 and was already fixed on master before being filed. See PR https://github.com/psf/black/pull/1315. A quick check verifies that this bug is definitely non-existent still:

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ git checkout 20.8b1
Previous HEAD position was 92c611c add bracket check in split_line (#1315)
HEAD is now at 2354126 v20.8b1
(black) ichard26@acer-ubuntu:~/programming/oss/black$ cat temp.py
@decorator(
    # a comment
    call_this()  # type: ignore
)
def test():
    pass
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black temp.py --diff --color
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```

**Environment:**
* Black version: `20.8b1`
* Python version: `CPython 3.8.5`
* OS version: `Ubuntu 20.04.01 LTS`

**Closed by ichard26** 2020-10-05 23:11 UTC
Labels: bug, duplicate, invalid code
