### ISSUE TITLE
Black moves type annotations when fixing value unpacking

### ISSUE THREAD

**Issue by adamfaulkner** [psf/black#953] opened 2019-08-01 03:50 UTC
Operating system: Linux, ubuntu 19.04
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: yes
---
The following (bad) code is reformatted from
```
def foo():
    # type: () -> None
    line1, = 'foo',
```
to this
```
def foo():
    (  # type: () -> None
        line1,
    ) = (
        "foo",
    )
```

And causes black to crash with this error message: 
```
error: cannot format /tmp/test.py: INTERNAL ERROR: Black produced invalid code: misplaced type annotation (<unknown>, line 2). Please report a bug on https://github.com/python/black/issues.  This invalid output might be helpful: /tmp/blk_dddtfxzy.log
```
[blk_dddtfxzy.log](https://github.com/psf/black/files/3454822/blk_dddtfxzy.log)

I think this is actually syntactically valid, so it would be nice if black didn't break on it. It's not a huge problem aside from an annoyance when reformatting a large project.

**Comment by zsol** [comment] 2019-08-02 18:43
Wow that's really unfortunate. We'll look at fixing this

**Comment by ichard26** [comment] 2021-05-29 03:43
Confirmed on version 20.8b1 and 21.5b1, Black no longer fails to format this and now also produces decent enough output: 

```diff
~/programming/misc/issuestats via v3.8.5 (env) took 356ms 
1❯ cat test.py
def foo():
    # type: () -> None
    line1, = 'foo',

~/programming/misc/issuestats via v3.8.5 (env) 
❯ black test.py --check --diff --color
--- test.py	2021-05-29 03:38:31.000345 +0000
+++ test.py	2021-05-29 03:39:40.517547 +0000
@@ -1,3 +1,3 @@
 def foo():
     # type: () -> None
-    line1, = 'foo',
+    (line1,) = ("foo",)
would reformat test.py
Oh no! 💥 💔 💥
1 file would be reformatted.
``` 

I'm sure there's some debate about whether the parentheses should be added or not (https://github.com/psf/black/issues/445 seems to cover the left side at least). 

Since this issue is done serving its original purpose, closing. Thank you for reporting!

**Closed by ichard26** 2021-05-29 03:43 UTC
Labels: C: invalid code, T: bug
