### ISSUE TITLE
Changing the library name

### ISSUE THREAD

**Issue by guillaume-miara** [psf/black#1554] opened 2020-07-16 15:49 UTC
As a foreword, I would like to start by asking people who will answer this to make an effort to respect every opinion and that hateful comments don't really bring anything to a discussion. 

Git is renaming the default branch from `master` to `main`
There is a general movement towards removing some words in the software engineering world because of the connotations they carry from other contexts. 

This has an impact. People in my team are reluctant to the idea of using `black` formatter for this reason. 

I personally disagree with that decision (I am biased because I like `black` :) ), but completely respect that opinion.

Given that context, I am wondering if there has been any discussions around potentially changing the name of the library to something less controversial?

**Comment by BuSSioR** [comment] 2020-07-17 07:38
Sir, is this a bait? Black is a colour, not a hate speech.

**Comment by iago-lito** [comment] 2020-07-17 08:07
cc #1363

**Comment by zsol** [comment] 2020-07-17 08:14
Duplicate of #1363.

**Closed by zsol** 2020-07-17 08:14 UTC

**Comment by SanketDG** [comment] 2020-07-17 08:18
Can we lock this, if there are no more narratives to be said?
