### ISSUE TITLE
Cannot format file (black produced different code on the second pass of the formatter)

### ISSUE THREAD

**Issue by rickystewart** [psf/black#1770] opened 2020-10-19 17:42 UTC
I'm unable to format some files with `black` version 20.8b1.

Steps to reproduce:

1. Use https://hg.mozilla.org/mozilla-central/raw-file/d4e1e62aed03db1d447f6b31b8d1347c2ad2e43b/testing/web-platform/tests/tools/ci/tests/test_jobs.py (we have other examples of similarly failing Python files in-tree, but this is the shortest example I was able to find)

2. Run `black test_jobs.py`

3. See error:

```
error: cannot format testing/web-platform/tests/tools/ci/tests/test_jobs.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_p0353uz5.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

Expected behavior: No failure to reformat.

Environment:
- Version: 20.8b1 (installed with Pip)
- OS and Python version: Ubuntu 20.04.1 LTS, Python 3.8.5

This bug also occurs on master (tested on https://black.now.sh/?version=master)

**Comment by hugovk** [comment] 2020-10-19 17:52
Here's a smaller repro with latest `master` (`black, version 20.8b2.dev36+g4070527`):

```python
def test_stability():
    assert jobs.get_jobs(["css/build-css-testsuite.sh",
                          "css/CSS21/test-001.html"],
                         includes=["stability"]) == {"stability"}
```

Log:
```diff
Mode(target_versions={<TargetVersion.PY38: 8>, <TargetVersion.PY37: 7>, <TargetVersion.PY36: 6>}, line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,4 +1,5 @@
 def test_stability():
-    assert jobs.get_jobs(["css/build-css-testsuite.sh",
-                          "css/CSS21/test-001.html"],
-                         includes=["stability"]) == {"stability"}
+    assert jobs.get_jobs(
+        ["css/build-css-testsuite.sh", "css/CSS21/test-001.html"],
+        includes=["stability"],
+    ) == {"stability"}
--- first pass
+++ second pass
@@ -1,5 +1,8 @@
 def test_stability():
-    assert jobs.get_jobs(
-        ["css/build-css-testsuite.sh", "css/CSS21/test-001.html"],
-        includes=["stability"],
-    ) == {"stability"}
+    assert (
+        jobs.get_jobs(
+            ["css/build-css-testsuite.sh", "css/CSS21/test-001.html"],
+            includes=["stability"],
+        )
+        == {"stability"}
+    )
```

**Comment by globau** [comment] 2020-10-20 04:49
This is caused by the changes in 586d24236e6b57bc3b5da85fdbe2563835021076

**Comment by LeoAzLiu** [comment] 2020-10-30 07:58
Any temporary solution about this? pls.

**Comment by ciknight** [comment] 2020-11-18 07:03
I appeared the same problem, which version can work now？

**Comment by ichard26** [comment] 2020-11-18 15:09
Black version `19.10b0` may work, no guarantees though.

**Comment by ciknight** [comment] 2020-11-19 09:17
> Black version `19.10b0` may work, no guarantees though.

Black version `19.10b0` is work, thanks.

**Comment by ichard26** [comment] 2021-04-25 20:14
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:14 UTC
Labels: bug, duplicate, unstable formatting
