### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter. 

### ISSUE THREAD

**Issue by andrewdotn** [psf/black#2049] opened 2021-03-16 15:56 UTC
When trying to format a file, I got an error message telling me to report the issue here.

**To Reproduce**

1. Take this file

```
def x():
    assert y(
        [
            {"blahblah": ["blahblahblahblah"]}
        ],
        [{"blahblah": ["blahblahblahblah"]}],
        [{"blahblah": ["blahblahblahblah"]}]
    ) == {"x": "a", "y":  []}
```

2. Run _Black_ on it with these arguments: `black foo.py`
3. See error

**Expected behavior**

No error message

**Environment:**

- Version: master @ 20.8b2.dev111+g5446a92f0161
- OS and Python version: macOS 11, Python 3.9.1

**Additional context** Add any other context about the problem here.

```
Mode(target_versions={<TargetVersion.PY38: 8>, <TargetVersion.PY36: 6>, <TargetVersion.PY37: 7>}, line_length=88, string_normalization=True, magic_trailing_comma=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,9 +1,6 @@
 def x():
     assert y(
-        [
-            {"blahblah": ["blahblahblahblah"]}
-        ],
         [{"blahblah": ["blahblahblahblah"]}],
-        [{"blahblah": ["blahblahblahblah"]}]
-    ) == {"x": "a", "y":  []}
-
+        [{"blahblah": ["blahblahblahblah"]}],
+        [{"blahblah": ["blahblahblahblah"]}],
+    ) == {"x": "a", "y": []}
--- first pass
+++ second pass
@@ -1,6 +1,9 @@
 def x():
-    assert y(
-        [{"blahblah": ["blahblahblahblah"]}],
-        [{"blahblah": ["blahblahblahblah"]}],
-        [{"blahblah": ["blahblahblahblah"]}],
-    ) == {"x": "a", "y": []}
+    assert (
+        y(
+            [{"blahblah": ["blahblahblahblah"]}],
+            [{"blahblah": ["blahblahblahblah"]}],
+            [{"blahblah": ["blahblahblahblah"]}],
+        )
+        == {"x": "a", "y": []}
+    )
```

**Comment by klieret** [comment] 2021-03-18 17:15
Hi @andrewdotn : I can confirm this is happening also for other version.

But for anyone stuck with this issue: You can work around it by simply adding the missing comma that black wanted to add in its first pass.

**Comment by ichard26** [comment] 2021-04-25 20:18
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:18 UTC
Labels: bug, duplicate, unstable formatting
