### ISSUE TITLE
Black keeps redundant parentheses around optional kwarg invocation

### ISSUE THREAD

**Issue by dimaqq** [psf/black#1151] opened 2019-11-11 07:33 UTC
```py
(xx-wNEHA9fb-py3.8) … ~/xx> black x.py
All done! ✨ 🍰 ✨
1 file left unchanged.
(xx-wNEHA9fb-py3.8) … ~/xx> cat x.py
foo(a=1, **{"b": 2} if bar() else {}, c=3)
foo(a=1, **({"b": 2} if bar() else {}), c=3)
```

Somehow `black` considers both OK, which makes me wonder, if perhaps `black` somehow considers the two *different*.

```
black, version 19.10b0
Python 3.8.0
```

**Comment by ichard26** [comment] 2021-05-30 03:20
Closing since this is a duplicate of #1123. Thank you for the suggestion though!

**Closed by ichard26** 2021-05-30 03:20 UTC
Labels: R: duplicate, T: design
