### ISSUE TITLE
Give an option to adjust the method signature formatting.

### ISSUE THREAD

**Issue by couling** [psf/black#1796] opened 2020-10-29 14:30 UTC
Black produces formatting that is unclear (for some) and can make code frustratingly slow to read.  I suspect that if I raise an issue asking for it to be changed it will be closed without much consideration.  So if Black's default must be as it is, then could we have an enhancement so that users can chose?

Black [says about itself](https://pypi.org/project/black/) that "Black enforces formatting that conforms to PEP 8".  However the indendenting style of method signatures deviates from that described in PEP-8.  PEP-8 says:

```python
# Add 4 spaces (an extra level of indentation) to distinguish arguments from the rest.
def long_function_name(
        var_one, var_two, var_three,
        var_four):
    print(var_one)
```
But Black prefers to do this to "distinguish arguments from the rest":
```
def long_function_name(
        var_one, var_two, var_three, var_four
):
    print(var_one)
```

**Why is this so frustrating to some?**

In every (other) context, Python and it's style guides are white-space aware.  The core language uses white space to delineate the start and end of blocks.  The style guides (including PEP-8) continue this trend.  So as a general rule Python mandates that nothing should be tabbed out before the end of the block.

This is true even of dictionaries and other similar constructs, notice how the closing bracket is permissable where it is because the closing bracket **and** the tabbing **both** show the end of the block:

```python
foo = {
    'x': 1,
    'y': 2,
}
```

The problem with seeing `):` tabbed back out on it's own line is that it confuses they eye into thinking the block (the method) has ended.  For some of us, that slows down reading significantly.

**Possible solutions**

Add an option that will cause Black to follow the pattern shown by PEP-8 examples.  At the very least this should:
- Use two tabs to list parameters
- Put the closing bracket on the same line as parameters if it (and the return type) will fit.  Otherwise put it on it's own line, tabbed in to the same level as the parameters.

**Comment by MarcoGorelli** [comment] 2020-10-29 14:34
Hi - is this a dupe of #1178?

**Comment by couling** [comment] 2020-10-29 14:49
@MarcoGorelli Ah, ha.  Well I was right about my first comment then, where I said:

> I suspect that if I raise an issue asking for it to be changed it will be closed without much consideration.

As was demonstrated [here](https://github.com/psf/black/issues/1178#issuecomment-565266460):

> Black isn't going to change this style now because it would be too disruptive for our users.
> [closed]

So I don't think this is a duplicate specifically because I am NOT asking for the core style to be changed.

I don't want to inflict this opinion on others (no matter how right "know" I am).  But I would like (_please_) an enhancement that let's me turn on PEP-8 compliance.  That should be much less contentious.

That is to say.  Please don't mark this a s a dupe of a closed bug report demanding the core formatting is changed.  That's not what I'm asking for.  I'm asking for an enhancement to add a switch enabling it.

**Comment by cooperlees** [comment] 2020-10-29 15:12
As another side not you may have missed, another goal of black was to have as little options and configuration as possible.  This is so that if a code base was black formatted you know what you’re getting. You’re proposing to further skew that goal.

This vision was taken from the success of gofmt and other very non configurable auto formatters.

**Comment by couling** [comment] 2020-10-29 15:31
@cooperlees I understand and respect that.  If I understand correctly that is derived from a need to keep maintenance low, adding options hurts testing, and maintaining particularly testing with all possible option combinations.

For some of us this is critical to adoption. Perhaps one way to satisfy the need to keep options to a minimum might be a single (unified) option of "compliance level" or "compliance type".  While that is still an extra option, yes, it prevents it needing to be a single purpose option.  Theoretically It would open the door to making other (future?) disruptive changes where they are about conforming to "the" standard but without adding options or changing the default behaviour.

**Comment by JelleZijlstra** [comment] 2021-05-29 02:54
We're not going to change this behavior.

**Closed by JelleZijlstra** 2021-05-29 02:54 UTC
Labels: T: enhancement
