### ISSUE TITLE
A dictionary with a key-value combination that exceeds the line length is not wrapped

### ISSUE THREAD

**Issue by carmenbianca** [psf/black#3279] opened 2022-09-22 08:09 UTC
**Describe the bug**

The line length is not respected when a key-value combination in a dictionary is very long.

**To Reproduce**

Take this code:

```python
foo = {
    "very_long_line_that_goes_on_and_on_and_on": "another_very_long_line_that_doesnt_end_expediently",
}
```

Run black against it, and the file remains unchanged.

**Expected behavior**

```python
foo = {
    "very_long_line_that_goes_on_and_on_and_on": (
        "another_very_long_line_that_doesnt_end_expediently"
    ),
}
```

**Environment**

- Black's version:  22.1.0
- OS and Python version:  Fedora 36, Python 3.10.6

**Additional context**

Black _does_ correctly wrap the following file:

```python
foo = {
    "very_long_line_that_goes_on_and_on_and_on": ("another_very_long_line_that_doesnt_end_expediently"),
}
```

**Comment by JelleZijlstra** [comment] 2022-09-23 01:21
Duplicate of #413

**Closed by JelleZijlstra** 2022-09-23 01:21 UTC
Labels: T: bug, F: linetoolong
