### ISSUE TITLE
black does not format expressions inside f-string

### ISSUE THREAD

**Issue by MareinK** [psf/black#1201] opened 2019-12-12 02:16 UTC
**Describe the bug**
Black does not seem to format expressions inside f-strings.

**To Reproduce**
Example file contents:

```python
1+2
f"{1+2}"
```

Result after running black:

```python
1 + 2
f"{1+2}"
```

**Expected behavior**
Expected result after formatting:

```python
1 + 2
f"{1 + 2}"
```

**Environment:**

- Version: 19.10b0
- OS and Python version: Arch Linux, Python 3.8.0

**Does this bug also happen on master?**
Yes (tried in online version)

**Comment by JelleZijlstra** [comment] 2019-12-12 05:32
Duplicate of #567 (although this issue actually has a better title).

**Closed by JelleZijlstra** 2019-12-12 05:32 UTC
Labels: bug
