### ISSUE TITLE
multiple `with open` with long file names on same statement

### ISSUE THREAD

**Issue by capitalaslash** [psf/black#1719] opened 2020-09-22 14:38 UTC
**Describe the style change** Better management of multiple `with open` on same statement

**Examples in the current _Black_ style** 

```python
with open("a_very_long_file_name", "w") as a, open(
    "another_very_long_filename", "w"
) as b:
     pass
```

**Desired style** How do you think _Black_ should format the above snippets:

```python
with open("a_very_long_file_name", "w") as a, \
     open("another_very_long_filename", "w") as b:
    pass
```

**Additional context** `yapf` keeps the snippet as shown in the desired section, `autopep8` adds an indentation for the second line. No solution is really great, but `black`'s solution is really unreadable imho.

**Comment by sjohannes** [comment] 2020-10-07 00:17
This duplicates https://github.com/psf/black/issues/557 and https://github.com/psf/black/issues/664 I think?

**Comment by ichard26** [comment] 2020-10-07 00:33
Yeah fair enough - I didn't take a deep look as I didn't want to explain how we in fact have plans to handle multiple context managers better even though it looks like this better handling has landed already since this corner case is detailed in the  [documentation](https://github.com/psf/black/blob/master/docs/the_black_code_style.md) :-)

Thanks @sjohannes!

*this counts as a bug as the expected behaviour has been documented*

**Closed by ichard26** 2020-10-07 00:33 UTC
Labels: bug, duplicate

**Comment by capitalaslash** [comment] 2020-10-07 15:14
The documentation saying that this should work is quite confusing...
I understand that #664 is still in the works and it requires 3.9, or will it work also on older versions?

**Comment by ichard26** [comment] 2020-10-07 16:56
@capitalaslash yeah unfortunately the documentation has been added before the actual support has been added. The plan in #664 will work on older Python versions as we are special casing context managers. See https://github.com/psf/black/issues/664#issuecomment-593905179 and the comment below it.
