### ISSUE TITLE
Slicing of bracketed expressions is broken by removal of the brackets

### ISSUE THREAD

**Issue by michael-sayapin** [psf/black#1575] opened 2020-08-07 06:20 UTC
**Describe the bug**

Slicing of bracketed expressions is broken by too eager removal of the brackets.

**To Reproduce**

1. Try to reformat a file containing `return ('%x' % value)[-12:]`
2. The resulting expression is not producing equivalent result: `return '%x' % mac[-12:]`

**Expected behavior**

Expected to not remove the brackets in this case.

**Environment (please complete the following information):**

- Version: master
- OS and Python version: Linux, Python 3.7.4

**Does this bug also happen on master?** To answer this, you have two options:

Yes.

**Comment by JelleZijlstra** [comment] 2020-08-07 17:08
I can't reproduce this on master:
```
$ echo "('%x' % value)[-12:]" | python3 -m black -
("%x" % value)[-12:]
reformatted -
All done! ✨ 🍰 ✨
1 file reformatted.
```

**Comment by ichard26** [comment] 2020-08-07 18:52
@JelleZijlstra Interestingly I can reproduce this on master.

| Condition | Command | Output  |
|---|---|---|
| Black with `-c` | `black -c "return ('%x' % value)[-12:]"` | `return "%x" % value[-12:]` |
| Black with a file  | `black test.py` | `error: cannot format test.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.` |
| Black with input read from `stdin` | `echo ('%x' % value)[-12:] \| black -`  | ` error: cannot format -: INTERNAL ERROR: Black produced code that is not equivalent to the source.` |

This was my session:

```console
(black-rHKUX7ap) R:\Programming\black>echo return ('%x' % value)[-12:] > test.py
                                                                                                                                                                                                                                                                
(black-rHKUX7ap) R:\Programming\black>type test.py                                                                                                                      
return ('%x' % value)[-12:]
                                                                                                                                                                                                                                                                                                                     
(black-rHKUX7ap) R:\Programming\black>black test.py --check                                                                                                                                                                                                                    
error: cannot format test.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\User\AppData\Local\Temp\blk_0tsx_tzh.log                                                                                             
Oh no! 💥 💔 💥                                                                                                                                                         
1 file would fail to reformat.
                                                                                                                                                                                                                                                                                                                  
(black-rHKUX7ap) R:\Programming\black>black test.py --fast --check                                                                                                                                                                                                              
would reformat test.py                                                                                                                                                  
Oh no! 💥 💔 💥                                                                                                                                                         
1 file would be reformatted.
                                                                                                                                                                                                                                                                                                                    
(black-rHKUX7ap) R:\Programming\black>black test.py --fast                                                                                                                                                                                                                      reformatted test.py                                                                                                                                                     
All done! ✨ 🍰 ✨                                                                                                                                                      
1 file reformatted.
                                                                                                                                                                                                                                                                                                                             
(black-rHKUX7ap) R:\Programming\black>type test.py                                                                                                                      
return "%x" % value[-12:]
                                                                                                                                                                                                                                                                                                                       
(black-rHKUX7ap) R:\Programming\black>black -c "return ('%x' % value)[-12:]"                                                                                            
return "%x" % value[-12:]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
(black-rHKUX7ap) R:\Programming\black>echo return ('%x' % value)[-12:] | black -                                                                                                                                                                                                                                    
error: cannot format -: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\User\AppData\Local\Temp\blk_i2fy39_v.log                                                                                                   
Oh no! 💥 💔 💥                                                                                                                                                         
1 file failed to reformat.                                                                                                                                                                                                                                                                                                                      
```

**Environment:**
* Black version: `master` (b59a5246577346e6da2cc2802015f08524abf545)
  * Black configuration: `pyproject.toml` in the Black repo
* Python version: `CPython 3.8.1`
* OS version: `Windows 10 Home Build 18363`

**Comment by JelleZijlstra** [comment] 2020-08-07 19:10
Oops, I thought I was on master but was actually in 19.3b1. It does reproduce on master. This is a bad bug; we should fix it before the next release.

**Comment by ichard26** [comment] 2020-08-07 19:19
Git bisect points to commit 544ea9c217cad9459d7b60665db787e94b52f93d as the first bad commit.

**Comment by davidszotten** [comment] 2020-08-12 15:27
> Git bisect points to commit [544ea9c](https://github.com/psf/black/commit/544ea9c217cad9459d7b60665db787e94b52f93d) as the first bad commit.

that's a merge, i think the original commit is https://github.com/psf/black/pull/1132/commits/459eb35dc4541cd73a9a1c4abae2a3f0d7c26fd0

not sure what "This commit does not belong to any branch on this repository." means

**Comment by davidszotten** [comment] 2020-08-14 12:17
i think we can close this? (possible pending #1600)

**Closed** 2020-08-14 16:18 UTC
Labels: bug
