### ISSUE TITLE
INTERNAL ERROR

### ISSUE THREAD

**Issue by Ksengine** [psf/black#1815] opened 2020-11-11 14:09 UTC
this is log from pnline playground
```python
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_7ca5igc7.log

Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -34,15 +34,15 @@
     from urllib.parse import urlencode
 
 except ImportError:  # Py2
     from SocketServer import ThreadingMixIn
     from urllib import urlencode
-    
+
 __author__ = "Kavindu Santhusa"
 __version__ = "2.0.0"
 __license__ = "MIT"
-__status__ = 4 # see setup.py
+__status__ = 4  # see setup.py
 
 logger = logging.getLogger(__name__)
 logging.basicConfig()
 
 # python compatability
@@ -92,18 +92,19 @@
 HTTP_CODES[431] = "Request Header Fields Too Large"
 HTTP_CODES[451] = "Unavailable For Legal Reasons"  # RFC 7725
 HTTP_CODES[511] = "Network Authentication Required"
 _HTTP_STATUS_LINES = dict((k, "%d %s" % (k, v)) for (k, v) in HTTP_CODES.items())
 
+
 def log_traceback(ex):
     if PY3:
         ex_traceback = ex.__traceback__
     else:
         _, _, ex_traceback = exc_info()
-    tb_lines = ''
+    tb_lines = ""
     for line in traceback.format_exception(ex.__class__, ex, ex_traceback):
-        tb_lines+=str(line)
+        tb_lines += str(line)
     return tb_lines
 
 
 class WebSocketError(socket_error):
     """
@@ -629,15 +630,23 @@
             results = self.app(self.environ, self.start_response)
 
         except Exception as e:
             self.start_response()
             log = log_traceback(e)
-            err = "<h1>Internal Server Error(500)</h1><p><b>%s :%s</b></p><p><samp><pre>%s</pre></samp></p><a href=\"https://github.com/Ksengine/wsocket/issues/new?%s\" target=\"blank\"><button><h3>report</h3></button></a>" % (
-                type(e).__name__,
-                str(e),
-                log,
-                urlencode({'title':type(e).__name__,'body':'```python\n'+log+'\n```'})
+            err = (
+                '<h1>Internal Server Error(500)</h1><p><b>%s :%s</b></p><p><samp><pre>%s</pre></samp></p><a href="https://github.com/Ksengine/wsocket/issues/new?%s" target="blank"><button><h3>report</h3></button></a>'
+                % (
+                    type(e).__name__,
+                    str(e),
+                    log,
+                    urlencode(
+                        {
+                            "title": type(e).__name__,
+                            "body": "```python\n" + log + "\n```",
+                        }
+                    ),
+                )
             )
             return [err.encode("utf-8")]
 
         if not allow_write:
             return []
@@ -762,17 +771,17 @@
         self.protocol = protocol
         self.app = app or self.wsgi
         self.onclose = Event(self.on_close)
         self.onmessage = Event(self.on_message)
         self.onconnect = Event(self.on_connect)
-    
+
     def on_close(self, message):
         print(message)
 
     def on_connect(self, client):
         print(client)
-        client.send('you connected')
+        client.send("you connected")
 
     def fake(*args, **kwargs):
         pass
 
     def on_message(self, message, client):
@@ -816,11 +825,11 @@
 
         wsock = environ.get("wsgi.websocket")
         if not wsock:
             start_response()
             return "<h1>Hello World!</h1>"
-            
+
         self.onconnect(wsock)
         while True:
             try:
                 message = wsock.receive()
                 if message:
@@ -833,11 +842,11 @@
 
     def __call__(self, environ, start_response):
         if "wsgi.websocket" in environ or environ.get("REQUEST_METHOD", "") != "GET":
             r = Response(environ, start_response, self.app)
             return r.process_response()
-            
+
         if (
             environ.get("HTTP_UPGRADE", "").lower() != "websocket"
             or "upgrade" not in environ.get("HTTP_CONNECTION", "").lower()
         ):
             r = Response(environ, start_response, self.app)
@@ -933,10 +942,11 @@
 # for version compat
 class WebSocketHandler(FixedHandler):
     def get_app(self):
         return WSocketApp(self.server.get_app())
 
+
 def run(app=WSocketApp(), host="127.0.0.1", port=8080, **options):
     handler_cls = options.get("handler_class", FixedHandler)
     server_cls = options.get("server_class", ThreadingWSGIServer)
 
     if ":" in host:  # Fix wsgiref for IPv6 addresses.
--- first pass
+++ second pass
@@ -630,23 +630,20 @@
             results = self.app(self.environ, self.start_response)
 
         except Exception as e:
             self.start_response()
             log = log_traceback(e)
-            err = (
-                '<h1>Internal Server Error(500)</h1><p><b>%s :%s</b></p><p><samp><pre>%s</pre></samp></p><a href="https://github.com/Ksengine/wsocket/issues/new?%s" target="blank"><button><h3>report</h3></button></a>'
-                % (
-                    type(e).__name__,
-                    str(e),
-                    log,
-                    urlencode(
-                        {
-                            "title": type(e).__name__,
-                            "body": "```python\n" + log + "\n```",
-                        }
-                    ),
-                )
+            err = '<h1>Internal Server Error(500)</h1><p><b>%s :%s</b></p><p><samp><pre>%s</pre></samp></p><a href="https://github.com/Ksengine/wsocket/issues/new?%s" target="blank"><button><h3>report</h3></button></a>' % (
+                type(e).__name__,
+                str(e),
+                log,
+                urlencode(
+                    {
+                        "title": type(e).__name__,
+                        "body": "```python\n" + log + "\n```",
+                    }
+                ),
             )
             return [err.encode("utf-8")]
 
         if not allow_write:
             return []
```

this log is from console
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/black/__init__.py", line 671, in reformat_one
    src, fast=fast, write_back=write_back, mode=mode
  File "/usr/local/lib/python3.7/dist-packages/black/__init__.py", line 813, in format_file_in_place
    dst_contents = format_file_contents(src_contents, fast=fast, mode=mode)
  File "/usr/local/lib/python3.7/dist-packages/black/__init__.py", line 940, in format_file_contents
    assert_stable(src_contents, dst_contents, mode=mode)
  File "/usr/local/lib/python3.7/dist-packages/black/__init__.py", line 6174, in assert_stable
    ) from None
AssertionError: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_u0yeukhk.log
error: cannot format wsocket.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_u0yeukhk.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```
why? my code has no syntax error

**Comment by maffoo** [comment] 2020-11-30 20:22
duplicate of #1629.

For what it's worth, you might be able to fix this in your case by changing from `%`-formatting to using `.format`:
```python
err = '<h1>Internal Server Error(500)</h1><p><b>{}: {}</b>...'.format(
    type(e).__name__,
    e,
    log,
    ...
)
```

**Comment by JelleZijlstra** [comment] 2021-05-29 02:36
Yes, this looks like #1629. Please reopen if you still see a crash with this code under the latest release.

**Closed by JelleZijlstra** 2021-05-29 02:36 UTC
Labels: T: bug
