### ISSUE TITLE
AST error

### ISSUE THREAD

**Issue by buddhhu** [psf/black#2403] opened 2021-07-27 14:12 UTC
Getting `failed to parse source file. AST error message: expression cannot contain assignment, perhaps you meant "=="? (<unknown>, line 73)` even if there is no error.

The code is 
```python
async def download_episode(download_url):
    anime_name = name_parser(download_url)
    filename = anime_name + download_url[-4:]
    make_directory(anime_name)
    download_path = os.path.join(anime_name, filename)
    if not os.path.exists(download_path):
        await (
            await asyncio.create_subprocess_shell(
                f'youtube-dl "{download_url}" -o "{download_path}"',
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
        ).communicate()
        clear_tmp(anime_name)
    return download_path
```

Last line of code is line 74
And raises error at line 73 `clear_tmp(anime_name)`, which is

```python
def clear_tmp(directory):
    for i in os.listdir(directory):
        if i[-4:] == "part":
            os.remove(os.path.join(directory, i))
```

Argument used was `black .` and after this error I changed it to `black --fast .` which gives no error like that.

Black version: 21.7b0
Python version: 3.9.6

**Comment by JelleZijlstra** [comment] 2021-07-27 16:37
I'm still unable to reproduce this. Could you post the full file and the flags that you are using for Black? A https://black.vercel.app/ link could also be helpful.

**Comment by buddhhu** [comment] 2021-07-27 16:55
Don't know it's not giving error now with same arguments `black .`

**Comment by ichard26** [comment] 2021-08-12 02:42
Since we haven't been able to get a reproducer I'll close this issue. Given Amit can't reproduce this, there's a good chance this bug has been fixed by a newer version of Black anyhow. Thanks for reporting tho!

**Closed by ichard26** 2021-08-12 02:42 UTC
Labels: T: bug, S: needs repro
