### ISSUE TITLE
Unable to format when return type is too long

### ISSUE THREAD

**Issue by johanvergeer** [psf/black#1768] opened 2020-10-19 11:53 UTC
**Describe the bug** Formatting fails when return type is too long

**To Reproduce** Steps to reproduce the behavior:

1. Create a function with a single parameter and declare a long return type

```python
def display_div(*inputs: List[Output]) -> Union[Dict[str, str], Tuple[Dict[str, str]], List[Dict[str, str]]]:
    pass
```

2. Run _Black_ on it
3. See error

```
error: cannot format C:\workspace\myproject\dashboard\components.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\me\AppData\Local\Temp\blk_17qde6nn.log
```

**Expected behavior** A clear and concise description of what you expected to happen.

I would expect Black to format the code like this

```python
def display_div(
    *inputs: List[Output]
) -> Union[Dict[str, str], Tuple[Dict[str, str]], List[Dict[str, str]]]:
    pass
```

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Windows 10, Python 3.8

**Does this bug also happen on master?** To answer this, you have two options:

Yes, I installed black from master branch and this issue still occurs.

**Additional context** Add any other context about the problem here.

**Comment by ichard26** [comment] 2021-04-02 19:46
Closing as unable to reproduce the issue on the specified version (20.8b1) and current master (201b331e55948d187fc150101bebf5262e160290). I'm happy to reopen if a failing reproduction case can given.

**Closed by ichard26** 2021-04-02 19:46 UTC
Labels: bug, unstable formatting
