### ISSUE TITLE
mercurial/{pure/osutil.py,merge.py}: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by durin42** [psf/black#1843] opened 2020-11-27 21:55 UTC
**Describe the bug** Two files (mercurial/pure/osutil.py and mercurial/merge.py) make black sad when it does the second pass.

**To Reproduce** Steps to reproduce the behavior:

1. Take either https://www.mercurial-scm.org/repo/hg/file/f4a218331ff4/mercurial/pure/osutil.py or https://www.mercurial-scm.org/repo/hg/file/f4a218331ff4/mercurial/merge.py (raw link available on the left-hand side of the page).
2. Grab our black config: https://www.mercurial-scm.org/repo/hg/file/f4a218331ff4/black.toml
2. Run _Black_ on it with these arguments 'black --config=black.toml osutil.py merge.py'
3. See error

**Expected behavior** Black does the formatting magic.

**Environment (please complete the following information):** Reproduced on both Windows (by another hg hacker) and me. My details below.

- Version: [e.g. master] black, version 20.8b1
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] Fedora 33/Python 3.9.0

**Does this bug also happen on master?** Yes, using the web version.

**Additional context** Add any other context about the problem here.

second-pass diffs in both cases look like they're sad about trailing/leading whitespace on triple-quoted strings:

```
Mode(target_versions=set(), line_length=80, string_normalization=False, experimental_string_processing=False, is_pyi=False)
--- first pass
+++ second pass
@@ -291,11 +291,11 @@
 
         def __setattr__(self, name, value):
             """mimics the read-only attributes of Python file objects
             by raising 'TypeError: readonly attribute' if someone tries:
               f = posixfile('foo.txt')
-              f.name = 'bla' """
+              f.name = 'bla'"""
             return self._file.__setattr__(name, value)
 
         def __enter__(self):
             self._file.__enter__()
             return self
```

```
--- first pass
+++ second pass
@@ -548,11 +548,11 @@
                 _(b'conflict in file \'%s\' is outside narrow clone') % f
             )
  
 class mergeresult(object):
-    """ 'An object representing result of merging manifests.
+    """'An object representing result of merging manifests.
 
     It has information about what actions need to be performed on dirstate
     mapping of divergent renames and other such cases."""
  
     def __init__(self):
```

**Comment by durin42** [comment] 2020-11-27 22:09
FTR, the following two patches un-stick black: https://phab.mercurial-scm.org/D9428 and https://phab.mercurial-scm.org/D9429

**Comment by ichard26** [comment] 2021-04-25 19:56
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:56 UTC
Labels: bug, duplicate, unstable formatting
