### ISSUE TITLE
Indexing square brackets split on 3 lines

### ISSUE THREAD

**Issue by ikamensh** [psf/black#3068] opened 2022-05-11 09:04 UTC
**Describe the style change**
I have an assert statement that checks a condition on the last element in an array. To me what black does to the statement makes it less readable:

```python
assert self.ref_transitions[-1].terminal.all(), "Last ref transition must be terminal."
```

**Examples in the current _Black_ style**

```python
assert self.ref_transitions[
    -1
].terminal.all(), "Last ref transition must be terminal."
```

**Desired style**

```python
assert (
    self.ref_transitions[-1].terminal.all()
), "Last ref transition must be terminal."

# OR

assert self.ref_transitions[-1].terminal.all(), (
    "Last ref transition must be terminal."
)
```

**Additional context**

I think operation of taking [-1]th element is best visible with brackets and number grouped. Having to search them across a diagonal on 3 lines is tough.

**Comment by felix-hilden** [comment] 2022-05-11 09:08
Hi! The bracket break is tracked in #236, and assert formatting in #348.

**Comment by JelleZijlstra** [comment] 2022-12-20 02:15
As @felix-hilden said this is a duplicate of various older issues.

**Closed by JelleZijlstra** 2022-12-20 02:15 UTC
Labels: T: design, F: linebreak
