### ISSUE TITLE
Comments being removed in .pyi files

### ISSUE THREAD

**Issue by MarcoGorelli** [psf/black#2250] opened 2021-05-22 09:28 UTC
**Describe the bug** A clear and concise description of what the bug is.

`black` removes some comments in .pyi files

**To Reproduce** Steps to reproduce the behavior:

1. Take this file `t.pyi`
```python
def foo(
    x: int,
) -> None: # my awesome comment
    ...
```

1. Run _Black_ on it:

```diff
$ black t.pyi --diff
--- t.pyi	2021-05-22 09:25:07.254961 +0000
+++ t.pyi	2021-05-22 09:25:10.275061 +0000
@@ -1,4 +1,3 @@
 def foo(
     x: int,
-) -> None: # my awesome comment
-    ...
+) -> None: ...
would reformat t.pyi
All done! ✨ 🍰 ✨
1 file would be reformatted.
```

**Expected behavior** A clear and concise description of what you expected to happen.

That the comment be preserved

**Environment (please complete the following information):**

- Version: 
```console
$ black --version
black, version 21.5b1
```
- OS and Python version: \[e.g. Linux/Python 3.7.4rc1\]
```console
$ python -c 'import platform; print(platform.platform())'
Linux-5.4.0-73-generic-x86_64-with-glibc2.29
$ python --version
Python 3.8.5
```

**Comment by JelleZijlstra** [comment] 2021-05-29 04:14
This is actually a duplicate of #1239.

**Closed by JelleZijlstra** 2021-05-29 04:14 UTC
Labels: F: comments, T: bug
