### ISSUE TITLE
Single argument to nested function call placed on separate line

### ISSUE THREAD

**Issue by dirn** [psf/black#828] opened 2019-05-05 18:48 UTC
Operating system: macOS
Python version: 3.7.2
*Black* version: 18.9b0
Does also happen on master: Yes

It looks like Black is exploding arguments to a function within another function call, regardless of whether or not the former's arguments fight onto a single line.

Original code:
```
text = textwrap.dedent("""
    This
    is
    some
    text.
    """.strip("\n")
)
```

Expected output:
```
text = textwrap.dedent(
    """
    This
    is
    some
    text.
    """.strip("\n")
)
```

Actual output:
```
text = textwrap.dedent(
    """
    This
    is
    some
    text.
    """.strip(
        "\n"
    )
)
```

P.S. In this particular case I switched to `lstrip` and placed it after the call to `dedent`, but that probably won't always be an option.

**Comment by ichard26** [comment] 2020-09-27 01:39
Duplicate of #256.

**Closed by ichard26** 2020-09-27 01:39 UTC
Labels: design, duplicate
