### ISSUE TITLE
Cannot parse type annotated tuple packing

### ISSUE THREAD

**Issue by papr** [psf/black#1806] opened 2020-11-05 18:07 UTC
**Summary**

black, version 20.8b1 cannot parse a type-annotated tuple without parentheses (see last line). Apologies if the title uses incorrect terminology.

```py
a = 0,
a = (0,)
a: tuple = (0,)
a: tuple = 0,
```

**Steps to reproduce**

```sh
$ black -c "
a = 0,
a = (0,)
a: tuple = (0,)
a: tuple = 0,
"

Traceback (most recent call last):
  File "/Users/papr/.pyenv/versions/pupil/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/black/__init__.py", line 6607, in patched_main
    main()
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/black/__init__.py", line 525, in main
    print(format_str(code, mode=mode))
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/black/__init__.py", line 974, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/Users/papr/.pyenv/versions/3.8.2/envs/pupil/lib/python3.8/site-packages/black/__init__.py", line 1083, in lib2to3_parse
    raise exc from None
black.InvalidInput: Cannot parse: 4:12: a: tuple = 0,
```

**Environment (please complete the following information):**

- Version: 20.8b1, installed via pip 20.2.4
- OS and Python version: macOS 10.15 , Python 3.8.2 (pyenv build)

**Does this bug also happen on master?**
[Yes.](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AB9AE1dAD2IimZxl1N_WlOfrjriuRHjpjBACMVeEBNrnLnYQ7g2yWNJun4Zfanx2MgLdo0GL17KNolCCac2cBhTG25idFwlDdU2kjY7D7dxOnmgAAAAALnvv6azy64xAAFpfv45BCMftvN9AQAAAAAEWVo=)

**Comment by JelleZijlstra** [comment] 2020-11-05 19:43
Duplicate of #1189

**Closed by JelleZijlstra** 2020-11-05 19:43 UTC
Labels: bug
