### ISSUE TITLE
Unstable formatting with long `not in` clause

### ISSUE THREAD

**Issue by Zac-HD** [psf/black#1891] opened 2020-12-30 11:34 UTC
**Black v20.8b1**, repro at this [playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADMAGtdAD2IimZxl1N_Wlws4TJJv7BMvjydDGxoy3naeksqdk-Q-5FiMbcEAoNFozpE4y8WqHVleMqTKb3x7_BUbTbHro80xSGiP3CFrSBcp9AxEWjZ8aelKNi-IX8yCyjKe8pjUqrqyUWQzishp78AAAC65yuIG7NFGwABhwHNAQAA4YVleLHEZ_sCAAAAAARZWg==)
```python
if "a" not in ("AAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB") or "b" in ("A", "B"):
    pass
```
```diff
INTERNAL ERROR: Black produced different code on the second pass of the formatter.
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,2 +1,5 @@
-if "a" not in ("AAAAAAAAAAAAAAAAAAAAAAAAAA", "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB") or "b" in ("A", "B"):
+if "a" not in (
+    "AAAAAAAAAAAAAAAAAAAAAAAAAA",
+    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
+) or "b" in ("A", "B"):
     pass
--- first pass
+++ second pass
@@ -1,5 +1,9 @@
-if "a" not in (
-    "AAAAAAAAAAAAAAAAAAAAAAAAAA",
-    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
-) or "b" in ("A", "B"):
+if (
+    "a"
+    not in (
+        "AAAAAAAAAAAAAAAAAAAAAAAAAA",
+        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
+    )
+    or "b" in ("A", "B")
+):
     pass
```

For what it's worth I think the first-pass format is nicer, but I don't really care so long as it's autoformatted 😁

**Comment by mvolfik** [comment] 2021-02-22 20:26
Works with #1958, so likely a duplicate of #1629

**Comment by ichard26** [comment] 2021-04-25 20:02
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:02 UTC
Labels: bug, duplicate, unstable formatting
