### ISSUE TITLE
Black produced invalid code: f-string: expecting '}'

### ISSUE THREAD

**Issue by zachsa** [psf/black#4074] opened 2023-11-28 07:55 UTC
>$ black .
error: cannot format ..../__init__.py: INTERNAL ERROR: Black produced invalid code: f-string: expecting '}' (<unknown>, line 35). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: /tmp/blk_pq9jt9me.log

Oh no! 💥 💔 💥
63 files left unchanged, 1 file failed to reformat.

The line is this:

```py
f'SQL string to apply to input CSV (i.e. "select * from stdin"), or apply a built-in aggregation: {', '.join([f"\"{r}\"" for r in existing_reports])}'
```

**Comment by hauntsaninja** [comment] 2023-11-28 08:02
Duplicate of https://github.com/psf/black/issues/3746

(That is not valid Python syntax for Python 3.11 and lower)

**Closed by hauntsaninja** 2023-11-28 08:02 UTC
Labels: T: bug
