### ISSUE TITLE
Failed to format a file

### ISSUE THREAD

**Issue by n8jhj** [psf/black#1757] opened 2020-10-09 20:15 UTC
Black failed to reformat a file in my project. The diff is here:

[blk_8ypnr5pz.log](https://github.com/psf/black/files/5357299/blk_8ypnr5pz.log)

**Environment:**
- Version: 20.8b1
- OS and Python version: Windows 10, Python 3.6.4

**Does this bug also happen on master?**
Yes.

**Comment by simaki** [comment] 2020-10-29 02:09
Thanks, but I'm not sure I got what's failing there.

Could you provide a minimal snippet to show the expected and actual output respectively?

**Comment by ichard26** [comment] 2021-04-02 01:39
I concur with @simaki, we at the bare mininum need the source code or a MCVE to have chance at figuring out what is the issue here. Please comment more context and information and I'll be happy to reopen!

**Comment by n8jhj** [comment] 2021-04-02 17:54
@simaki @ichard26 Sorry for the lack of information. I've reduced the source code to the part that's failing (no longer valid Python code because of the removed parts). My CLI input was:
`black path/to/file.py -l 79`

Contents of the Python file:
```
def turndown_capacity(gen, gen_output, k):
    for i in range(3):
        if (
            gen[k]['type'] in ['CombinedHeatPower', 'ElectricGenerator']
            and gen[i]['type'] in ['CombinedHeatPower', 'ElectricGenerator']
        ):
            pass
```

Command line output is:
```
error: cannot format eagers\core\solver\minimize_start_costs_2.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\NATHAN~1\AppData\Local\Temp\blk_84lgv4ux.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```

And here's the referenced diff log:
[blk_84lgv4ux.log](https://github.com/psf/black/files/6250726/blk_84lgv4ux.log)

**Comment by ichard26** [comment] 2021-04-02 18:14
@n8jhj perfect! Thanks for the follow up!

**Comment by ichard26** [comment] 2021-04-25 19:55
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:55 UTC
Labels: bug, duplicate, unstable formatting
