### ISSUE TITLE
Black uses a lot of blank lines for the "conditionally define a different version of a function" idiom

### ISSUE THREAD

**Issue by chrish42** [psf/black#1691] opened 2020-09-09 20:29 UTC
I'm writing a piece of code that defines a function differently depending on something in the environment. I feel this is typically formatted as:

```
if some_condition:
    def foo():
        do_something()
else:
    def foo():
        do_something_else()
```

without whitespace. However, Black (even on master) adds whitespace there before and after the function definition. This certainly makes sense when the function is defined at the top level, but less so inside an if statement, I think.

Here's a full module that would actually parse and run, after formatting by Black:

```
from contextlib import contextmanager

# This would typically be computed by a function inspecting the environment...
ENABLED = True

if ENABLED:

    @contextmanager
    def foo(msg, *args, **kwargs):
        print(msg.format(*args, **kwargs))
        yield
        print("Done!")


else:

    @contextmanager
    def foo(msg, *args, **kwargs):
        yield
```

Again, I would personally have expected this to be written without blank lines after the `if` and around the `else`. Thoughts?

**Comment by asottile** [comment] 2020-09-14 04:58
duplicate of #450 (via #377)

**Comment by ichard26** [comment] 2020-10-01 21:14
Thank you @asottile; closing!

**Closed by ichard26** 2020-10-01 21:14 UTC
Labels: enhancement
