### ISSUE TITLE
Extraneous whitespace during simple line wrapping?

### ISSUE THREAD

**Issue by dwaxe** [psf/black#578] opened 2018-10-18 22:04 UTC
Operating system:
Python version: 3.6.5
*Black* version: black, version 18.6b4
Does also happen on master: Yes ([Example](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACxAIddAD2IimZxl1N_Wm_vtYh_HvOeVv7zYL03jVxsZ7-b7-vy3l-NKgonAGjK6F2mDgwSlX2fCXBLIpoKrZzXIVmPQa6bkH8Y6k0ok7hmecVaRgNc_ekYUnbrHz5qmPp00LpibHXHJNiFyzdmpTtgA3LJWDQUpMvuALproslWKaauNcSTuF-VurUPnAAAha9IDd17A6kAAaMBsgEAAAtyBNexxGf7AgAAAAAEWVo=))

Any input like:
```
{"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidatorWonkiness"},
```

Produces an output of:
```
{
    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidatorWonkiness"
},
```

Which is 1 character wider and 2 lines longer than the original.

**Comment by JelleZijlstra** [comment] 2022-01-29 15:54
Duplicate of #413

**Closed by JelleZijlstra** 2022-01-29 15:54 UTC
Labels: T: design, F: linetoolong
