### ISSUE TITLE
Black does not respect line length in case of long attribute chaining

### ISSUE THREAD

**Issue by adarshk7** [psf/black#1237] opened 2020-01-20 15:29 UTC
**Describe the bug**

In a case where there is code that chains a lot of attributes within a parentheses block (to avoid using backslashes) Black fails to respect the line length supplied to it.

**To Reproduce**

1. Take this file

```
class BlackTestingClass():
    def __getattr__(self):
        return self


def some_function():
    btc = BlackTestingClass()
    (
        btc
        .attribute1.something
        .attribute2.something
        .attribute3.something
        .attribute4.something
        .attribute5.something
    )
```

2. Run _Black_ on it with these arguments : `black . --diff -l 100`
3. See error

```
@@ -1,16 +1,11 @@
-class BlackTestingClass():
+class BlackTestingClass:
     def __getattr__(self):
         return self


 def some_function():
     btc = BlackTestingClass()
     (
-        btc
-        .attribute1.something
-        .attribute2.something
-        .attribute3.something
-        .attribute4.something
-        .attribute5.something
+        btc.attribute1.something.attribute2.something.attribute3.something.attribute4.something.attribute5.something
     )
```

**Expected behavior**

The existing code in the block should be kept as it is (if it doesn't break any formatting rules otherwise) as it is probably a well thought out pattern by a developer or at least black should not put everything to the same line which exceeds the line-length (in this case the output line is 113 characters whereas the limit supplied to black is 100.)

**Environment**

- Version: 19.10b0
- OS and Python version: macOS 10.14.6/Python 3.7.4

**Does this bug also happen on master?**

Yes (Verified from the playground)

**Additional context**

As to where one might encounter this kind of block in real life, mocking and patching specific things in tests might get fairly nested (especially with `unittest`s `.return_value`) or something like long ORM queries with SQLAlchemy.

**Comment by JelleZijlstra** [comment] 2022-01-29 15:59
Duplicate of #510

**Closed by JelleZijlstra** 2022-01-29 15:59 UTC
Labels: T: design, F: linetoolong
