### ISSUE TITLE
Black doesn't format scrapy file on vscode

### ISSUE THREAD

**Issue by trolliama** [psf/black#2352] opened 2021-07-01 22:15 UTC
**Describe the bug**

I am doing a scrapy project and i am unable to format the spider file. I am using vs code and i tried to format the file with cntrl+shift+p and "Format Document with..." and didn't work. I used the command `$ black -l 79 file_name.py` and it worked.
I used the same version and vscode settings.json to format files on my DjangoREST project and it worked as expected, the same thing with single python files

**To Reproduce**

```python
import scrapy


class PokemonSpider(scrapy.Spider):
    name = "pokemon"
    allowed_domains = ["pokemondb.net"]
    start_urls = ["https://pokemondb.net/pokedex/all"]

    def parse(self, response):
        poke_links = response.xpath("//table[@id='pokedex']/tbody//a/@href").extract()
```

1. Take this spider file 'pokemon.py'
1. try to format on vscode

**Expected behavior**

What i expected to happen is that the `response.xpath("//table[@id='pokedex']/tbody//a/@href").extract()` turns into something like this: 
```python
response.xpath(
   "//table[@id='pokedex']/tbody//a/@href"
).extract()
```

**Environment (please complete the following information):**

- Version: 21.6b0 and 21.5b1 (i tested just this two versions)
- OS and Python version: Linux/Python3.8

**Does this bug also happen on main?**
No

**Additional Context**

My vscode settings: 
```json
{
  "workbench.colorTheme": "Atom Material Theme",
  "workbench.iconTheme": "eq-material-theme-icons-darker",
  "kite.showWelcomeNotificationOnStartup": false,
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter.notebook.ipynb"
  },
  "editor.rulers": [80],
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "sync.gist": "105af5c62cd0c1d7c199c48dc9bf4c65",

  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.codeActionsOnSave": null,

  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
  "python.formatting.provider": "black",
  "python.linting.lintOnSave": true,
  "python.formatting.blackArgs": [
    "--line-length",
    "79"
  ],
  "gitlens.hovers.currentLine.over": "line",
  "editor.fontLigatures": null
}
```

.vscode settings path:
```json
{
  "editor.defaultFormatter": null,

  "python.testing.pytestArgs": ["app"],
  "python.testing.unittestEnabled": false,
  "python.testing.nosetestsEnabled": false,
  "python.testing.pytestEnabled": false,
  "python.testing.promptToConfigure": false
}

```

**Comment by ichard26** [comment] 2021-07-04 17:16
Can't reproduce even with the settings above copied over. More generally this is probably a problem with either your environment or the Visual Studio Code integration with Black. Checking the logs under the `Python` tab of the Output pane might reveal more helpful debug information.

**Comment by trolliama** [comment] 2021-07-30 01:21
I was able to fix this by uninstalling the virtual environment and setting up again

**Comment by ichard26** [comment] 2021-07-30 02:50
Great to hear you were able to resolve the issue! Since it appears this issue was caused by an environment issue, this is unactionable on our side and I'll be closing this issue.

**Closed by ichard26** 2021-07-30 02:50 UTC
Labels: C: integrations, S: needs repro, T: user support
