### ISSUE TITLE
Minimal file produces invalid code

### ISSUE THREAD

**Issue by codyd51** [psf/black#1369] opened 2020-04-29 14:32 UTC
**Describe the bug** Under certain circumstances, annotating a method with `# yapf: disable` among other inputs causes black to produce invalid code.

**To Reproduce** Steps to reproduce the behavior:

Minimal reproducing input:

```python
class BaseClass1:
    # yapf: disable
    def method1(self):
        pass


class BaseClass2:
    # yapf: disable
    def method2(self):
        pass


class Mixin(BaseClass1, BaseClass2):
    pass
```

```bash
$ black bad_input.py
error: cannot format bad_input.py: INTERNAL ERROR: Black produced invalid code: expected an indented block (<unknown>, line 8). Please report a bug on https://github.com/ambv/black/issues.  This invalid output might be helpful: /var/folders/y0/clprvktj3b5__hkvm2p4m_yr0000gn/T/blk_8rbcsejt.log
All done! 💥 💔 💥
1 file failed to reformat.
```

Here's the associated logfile: [blk_8rbcsejt.log](https://github.com/psf/black/files/4552266/blk_8rbcsejt.log)

**Expected behavior** The file is reformatted while preserving code structure.

**Environment (please complete the following information):**

- Version: Tested against `master` and `19.3b0`
- OS and Python version: macOS Catalina 10.15.3 Beta / Python 3.7.7

**Does this bug also happen on master?** Yes. I tested the sample file with https://black.now.sh/?version=master.

**Comment by greschd** [comment] 2020-08-26 15:29
I've just encountered the same issue, with ``black==20.8b0``, Python 3.7.9, Ubuntu 18.04. 

To add some observations, here's another reproducing example:

```python
def foo():
    # yapf: disable
    pass

1
```

It appears the error is that indentation is wrong after the reformatting: This is the result from ``black --fast``:

```python
def foo():
    # yapf: disable
    pass

    1
```

**Comment by ichard26** [comment] 2020-09-27 02:28
Duplicate of #569. `# yapf: enable/disable` are aliases to Black's own `# fmt: off/on`.

**Closed by ichard26** 2020-09-27 02:28 UTC
Labels: bug, duplicate
