### ISSUE TITLE
Docstring new line reformatting can violate line length constraint

### ISSUE THREAD

**Issue by DrGFreeman** [psf/black#2274] opened 2021-05-29 13:02 UTC
**Describe the bug**

Removal of new line in docstrings can violate the line length constraint if the last line is within two characters of the max line length value.

**To Reproduce** Steps to reproduce the behavior:

Run black on the following code with the default line-length constraint of 88 characters.

```python
def f():
    """89 123456789 123456789 123456789 123456789 123456789 123456789 123456789 12345678
    """
    pass
```

**Expected behavior**

No reformatting is performed.

**Actual behavior**

The code is reformatted as shown below, which violates the max line length constraint.

```python
def f():
    """89 123456789 123456789 123456789 123456789 123456789 123456789 123456789 12345678"""
    pass
```

In a CI setup with Flake8 running after black, Flake8 throws the following error:

```
test.py:2:89: E501 line too long (91 > 88 characters)
```

**Environment (please complete the following information):**

- All versions of black from 20.8b0 up to 21.5b1 as well as main (d3670d9c6568aef270ccda3006252ee3388cf587).
- Reproduced on Windows 10 & Ubuntu 18.04/20.04, Python 3.7 & 3.8

**Does this bug also happen on main?**

Yes

**Additional context**

black 19.10b0 does not have this behavior.
This was reported in https://github.com/psf/black/issues/1635#issuecomment-696230833.

**Comment by ichard26** [comment] 2021-05-30 02:25
I'll be closing this since this is a duplicate of GH-1632, thank you for the report though!

**Closed by ichard26** 2021-05-30 02:25 UTC
Labels: F: strings / docstrings, R: duplicate, T: bug

**Comment by DrGFreeman** [comment] 2021-05-30 16:18
Oh! I should have checked before. My bad. Sorry for wasting your time 😓

**Comment by ichard26** [comment] 2021-05-30 17:03
Don't worry about it, we do happen to have 250+ issues so it can be (very) annoying to discover whether your issue has been already reported or not. It's my job as a triager to catch the mistakes anyhow :)
