### ISSUE TITLE
Black for Jupyterlab  does not work correctly

### ISSUE THREAD

**Issue by Myname10** [psf/black#2473] opened 2021-09-03 10:08 UTC
Hi I install black to use it to format my notebooks using the following command: pip install black[jupyter]. 

When I run the command black notebook.ipynb it formats the notebook correctly. However when I open my notebook I get the following error message: File Load Error for Untiteled.ipynb Unreadable Notebook Untitled.ipynb NotJSONError('notebook does not appear to be Json: \'{\\n "cells": [\\n{\\n...')

Can anyone help thank you

**Comment by MarcoGorelli** [comment] 2021-09-03 10:21
HI @Myname10 - this sounds like a bug, thanks for the report. Any chance you could share your notebook?

**Comment by Myname10** [comment] 2021-09-03 10:34
@MarcoGorelli  Yes it happens with all notebooks.  I'm using jupyterlab and my notebook has just one cell: `def add(a,     b): return a+b`

**Comment by MarcoGorelli** [comment] 2021-09-03 10:37
I can't reproduce this - I made a notebook `Untitled.ipynb` with just `def add(a, b): return a+b`, ran `black Untitled.ipynb`, reopened it with Jupyter Lab, and it loaded fine.

What platform are you on? Perhaps, could you upload here the raw notebook _before_ running `black`, and the notebook _after_ having run `black`?

**Comment by Myname10** [comment] 2021-09-03 12:15
[after.txt](https://github.com/psf/black/files/7105765/after.txt)
[before.txt](https://github.com/psf/black/files/7105766/before.txt)
![Capture d’écran de 2021-09-03 14-14-51](https://user-images.githubusercontent.com/44066130/132003565-12e088d2-e318-4cba-987d-4e7032399036.png)

**Comment by felix-hilden** [comment] 2021-09-03 12:29
I tried it with the before notebook, and it ran fine after formatting!

![kuva](https://user-images.githubusercontent.com/25202257/132005142-39a51dea-e515-4739-aa88-fca8f929cb59.png)

```sh
pip install black jupyter
black test.ipynb
jupyter notebook
```

Then I selected the notebook in the server view.

**Comment by MarcoGorelli** [comment] 2021-09-03 13:08
OK, I _think_ I see the issue.

Can you post the output of
```
black --version
```
please?

I suspect you're running an earlier version of `black`, which did not yet have `jupyter` support, and hence your `.ipynb` file is getting formatted as if it were a Python file. That's why the extra trailing comma appears

When you ran `pip install black[jupyter]`, that was probably in an environment which already had `black` installed, right? Did you not get a warning like
```
WARNING: black 21.7b0 does not provide the extra 'jupyter'
```
?

You need at least version `21.8b0` to have Jupyter support - to install this in your same environment, you could run `pip install -U black[jupyter]` (notice the `-U`, so that your version will get upgraded)

@felix-hilden if this is the case, I think this can be closed

**Comment by sl-abdellahelyounsi** [comment] 2021-09-03 13:31
> I tried it with the before notebook, and it ran fine after formatting!
> 
> ![kuva](https://user-images.githubusercontent.com/25202257/132005142-39a51dea-e515-4739-aa88-fca8f929cb59.png)
> 
> ```shell
> pip install black jupyter
> black test.ipynb
> jupyter notebook
> ```
> 
> Then I selected the notebook in the server view.



> `black --version`

black, version 21.4b2

**Comment by sl-abdellahelyounsi** [comment] 2021-09-03 13:32
> OK, I _think_ I see the issue.
> 
> Can you post the output of
> 
> ```
> black --version
> ```
> 
> please?
> 
> I strongly suspect you're running an earlier version of `black`, which did not yet have `jupyter` support, and hence your `.ipynb` file is getting formatted as if it were a Python file. That's why the extra trailing comma appears, and it can't be read as valid json.
> 
> When you ran `pip install black[jupyter]`, that was probably in an environment which already had `black` installed, right? Did you not get a warning like
> 
> ```
> WARNING: black 21.7b0 does not provide the extra 'jupyter'
> ```
> 
> ?
> 
> You need at least version `21.8b0` to have Jupyter support - to install this in your same environment, you could run `pip install -U black[jupyter]` (notice the `-U`, so that your version will get upgraded)

Here is my black, version 21.4b2

**Comment by MarcoGorelli** [comment] 2021-09-03 13:32
OK, that's the issue then - please upgrade to the latest version (`pip install -U black[jupyter]`)

IMHO this could be closed now

**Comment by felix-hilden** [comment] 2021-09-03 13:36
Most probably! Thanks for the debugging, I'll close it for the time being. If the issue was not resolved by the upgrade, we'll reopen 👍

**Closed by felix-hilden** 2021-09-03 13:36 UTC
Labels: T: bug, S: needs repro

**Comment by sl-abdellahelyounsi** [comment] 2021-09-03 13:40
> OK, that's the issue then - please upgrade to the latest version (`pip install -U black[jupyter]`)
> 
> IMHO this could be closed now

I still have the same issue. There is something weird with the  versions idk if it's me or it's a bug on the code. I just Installed it on a new virtual env and here is what I found. pip freeze shows that I have black 21.8b0 and black --version show 21.4b2.
![Capture d’écran de 2021-09-03 15-38-39](https://user-images.githubusercontent.com/60093893/132014641-2869f021-ba36-4773-8607-87e2c5217494.png)
![Capture d’écran de 2021-09-03 15-38-27](https://user-images.githubusercontent.com/60093893/132014667-4b990305-ae92-4f82-bd33-e1a4b7e577ed.png)

**Comment by MarcoGorelli** [comment] 2021-09-03 13:41
what about `python -m black --version`?

**Comment by sl-abdellahelyounsi** [comment] 2021-09-03 13:42
> python -m black --version

python -m black, version 21.8b0

**Comment by MarcoGorelli** [comment] 2021-09-03 13:43
OK, I'd suggest you use run `black` like that then (`python -m black notebook.ipynb`)

**Comment by felix-hilden** [comment] 2021-09-03 13:44
Would you happen to have global packages enabled in the environment? I'm not sure how overlapping packages works in that case.

**Comment by sl-abdellahelyounsi** [comment] 2021-09-03 13:49
> OK, I'd suggest you use run `black` like that then (`python -m black notebook.ipynb`)
This one worked Thank you but I really don't understand why black why there is a confusion on versions :)

**Comment by felix-hilden** [comment] 2021-09-03 13:50
Just as a sanity check, is there a Black outside of the environment?

**Comment by sl-abdellahelyounsi** [comment] 2021-09-03 13:56
> Just as a sanity check, is there a Black outside of the environment?

Do you mean on the default virtual env ? if so yes

**Comment by felix-hilden** [comment] 2021-09-03 16:05
I mean the Python environment that you made the virtual one from. If there are competing versions, I'm not sure how they are handled but that might be the reason why the other version is older. Ordinarily the virtualenvs don't have access to the global packages but you might.
