### ISSUE TITLE
Chaining methods and comments

### ISSUE THREAD

**Issue by adaitche** [psf/black#1684] opened 2020-09-08 09:06 UTC
Putting comments between chained methods which are separate lines puts them sometimes on the same line. For example, the following code 

```python
result = (
    input.method1(arg1, arg2, arg3)
    .method2(arg1, arg2, arg3)
    # comment about method 3
    .method3(arg1, arg2, arg3, arg4)
)
```

is turned by black into 

```python
result = (
    input.method1(arg1, arg2, arg3).method2(arg1, arg2, arg3)
    # comment about method 3
    .method3(arg1, arg2, arg3, arg4)
)
```

However without the comment, `method2` is kept on a separate line, i.e. following code is not changed by black

```python
result = (
    input.method1(arg1, arg2, arg3)
    .method2(arg1, arg2, arg3)
    .method3(arg1, arg2, arg3, arg4)
)
```

Tested on `https://black.now.sh/?version=master`, commit `6284953`.

**Additional context**

When programming with `PySpark` long method call-chains are quite common. Then it is useful to put comments above some calls for explanation. Unfortunately this leads to formatting changes by black.

**Comment by ichard26** [comment] 2020-09-13 20:11
This is a duplicate of #458. Perhaps +1 the original issue?

**Closed by ichard26** 2020-09-13 20:11 UTC
Labels: bug, comments, duplicate
