### ISSUE TITLE
Failed to parse with statement w/parens

### ISSUE THREAD

**Issue by brannt** [psf/black#2372] opened 2021-07-15 12:26 UTC
**Describe the bug**

If a `with` or `async with` statement with multiple with items has parenthesises around the items, like in this example:
```
    async with (
        get_connection_pool() as pool, 
        get_cursor(pool) as read_cursor, 
        aiohttp.ClientSession() as session
    ):
        ...
``` 
`Black` fails to parse it with `error: cannot format ...: Cannot parse` error, even thought the regular Python interpreter has no problem executing the file.

**To Reproduce**

For example:
1. Take the lines 
```
from contextlib import contextmanager

@contextmanager
def mgr_a():
    yield "a"


@contextmanager
def mgr_b():
    yield "b"

with (mgr_a() as a, mgr_b() as b):
    print(a, b)
```
2. Run _Black_ on them
3. See error -->
```
error: cannot format black_test.py: Cannot parse: 24:14: with (mgr_a() as a, mgr_b() as b):
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior**
As it is valid Python file, _Black_ should be able to parse it.

**Environment (please complete the following information):**

- Version: 21.6b0
- OS and Python version: OS X/Python 3.9.5

**Does this bug also happen on main?**

Yes, I can reproduce it now on [black.vercel.app](https://black.vercel.app/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AG4ALFdAD2IimZxl1N_WlkPinBFn5AcTZNBQ_AiPaIDZEXqWp5sEV3IZXdXpcPPc95eZahlhvhdtyv1kxM4UEd1URDrDS5ESGUOGU2vSMdX0KuxpG4cPaN-PWmZKWYJR69n9rgL1P1-7eh_c_zYylp9Nz3r9Mr2Q1FAlhZrrrQh296NcLQDg2SjnV5eZdd8UMjz4x6_cphX5ZuYZ35sqeUTXiRz6ouK5DFMXCmzMnczZCBpPOOItAAAAAAsBd41DFbnGgABzQG5AwAATk9_MbHEZ_sCAAAAAARZWg==)

**Comment by JelleZijlstra** [comment] 2021-07-15 13:57
This is a duplicate of #1948.

**Closed by JelleZijlstra** 2021-07-15 13:57 UTC
