### ISSUE TITLE
Tab in docstring gives non equivalent result

### ISSUE THREAD

**Issue by Hoxbro** [psf/black#1766] opened 2020-10-16 11:05 UTC
**Describe the bug** A clear and concise description of what the bug is.
Tab in docstring give non equivalent result

**To Reproduce** Steps to reproduce the behavior:
```
def foo():
    """
    [1] 	tmp
    """
    pass
```

**Expected behavior** A clear and concise description of what you expected to happen.
That it does not give an error. 

**Environment (please complete the following information):**
Not important

**Does this bug also happen on master?** To answer this, you have two options:
[black.now.sh](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACIAFVdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXyRPNp3_8BJfVOeb_JVqI6J_dzVM5106__0buDDcHy5cwOTIkCGHSn4Wh84VlREhUlSU7DqOz1yUxwOY8fUYAAAAA7kxl1-lHtWkAAXGJAQAAAD-_YQexxGf7AgAAAAAEWVo=)
```
INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_54c3klr3.log

--- src
+++ dst
@@ -16,11 +16,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                '[1] \ttmp',  # str
+                '[1]         tmp',  # str
             )  # /Constant
         )  # /Expr
         Pass(
         )  # /Pass
       decorator_list=
```

**Comment by michelc1** [comment] 2020-10-16 20:49
I'm running into the same issues.

**Comment by ichard26** [comment] 2020-10-16 21:05
Hey thanks for reporting, but this is a duplicate of #1601 and therefore I will be closing this issue. Perhaps +1 the original issue?

**Closed by ichard26** 2020-10-16 21:05 UTC
Labels: bug, duplicate
