### ISSUE TITLE
File fails to auto format with internal error

### ISSUE THREAD

**Issue by ideasman42** [psf/black#2074] opened 2021-03-29 08:16 UTC
**Describe the bug** 

Black fails to auto format a Python script, reporting an internal error.

**To Reproduce**

1. Take this file https://developer.blender.org/diffusion/B/browse/master/tests/python/bl_pyapi_mathutils.py;84c537e68528177ef982479f5884af07cec322b9
2. Run _Black_ on it with these arguments ` black bl_pyapi_mathutils.py`
3. See error:
```
error: cannot format bl_pyapi_mathutils.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.
```

**Expected behavior** Auto format without any errors.

**Environment (please complete the following information):**

- Version: 20.8b1 & master.
- Arch Linux, Python 3.9.2

**Does this bug also happen on master?**

Yes, the error happens on master dc8b0a43837a6280e0d7d7d4e71a5282083c6b01

**Additional context**

Don't think any is needed.

**Comment by ichard26** [comment] 2021-04-25 20:19
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:19 UTC
Labels: bug, duplicate, unstable formatting
