### ISSUE TITLE
black formatter giving error message in misleading/unexpected place.

### ISSUE THREAD

**Issue by obtusedev** [psf/black#2442] opened 2021-08-24 21:39 UTC
**Describe the bug**
The issue with my code is I forgot to have a method to handle the route.
However black formatter is telling me it cannot parse what is otherwise valid code in a misleading / unexpected place.

Is this the default behavior of black or am I doing something wrong / having the wrong expectations?

**To Reproduce**
Run black on the following code snippet.

```python
import json
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/", methods=["GET"])
def home():
    return render_template("./index.html")

@app.route("/signup", methods=["GET", "POST"])
def signup():
    pass

@app.route("/login")

if __name__ == "__main__":
    app.run(debug=True)

```

black is giving me the following error:
`error: cannot format app.py: Cannot parse: 17:0: if __name__ == "__main__": `
`Oh no! 💥 💔 💥`
`1 file failed to reformat.`

**Expected behavior**

black not telling me it can't parse what is valid code below

```python
if __name__ == "__main__":
    app.run(debug=True)
```

**Environment (please complete the following information):**
- black, version 21.7b0
- Ubuntu 20.04.1, Python 3.8.10
- Sublime Text 4113

**Does this bug also happen on main?**
Yes, I am on 21.7b0 which is the main branch.

**Additional context**

**Comment by ichard26** [comment] 2021-08-24 22:04
OK, so this another variation of https://github.com/psf/black/issues/1263 but instead of us trying multiple grammars and using the last error, the blib2to3 library we use as Black's primary parser is simply raising confusing SyntaxErrors. This is mostly likely fixable, but might take a bunch of work. 

FWIW, until the recent work focused on vastly improving SyntaxErrors in 3.10 and 3.11, CPython would emit similarly confusing messages:
```console
❯ python test.py
  File "test.py", line 16
    if __name__ == "__main__":
    ^
SyntaxError: invalid syntax
```
This is on CPython 3.8.5. And before someone asks "can't you just use built-in parser from CPython?" well sorta. We use it as part of the safety checks so any SyntaxErrors during those should be all fine and dandy, but unfortunately the AST emitted just doesn't capture enough detail from the original source to allow Black to make the edits it does do. This is why we use a fork of lib2to3 which was designed with code modification in mind. 

Thanks for the report!

**Comment by obtusedev** [comment] 2021-08-24 22:08
@ichard26 I am still very much a beginner at python so this error message threw me for a loop and I'm wonder what is wrong with the code lol. I figured the error message would be confusing to beginners so I decided to make a report. Thanks for your time.

**Comment by JelleZijlstra** [comment] 2021-09-08 14:28
I'm going to close this since I don't think Black can do much here: the error comes from our underlying parser.

Also, precise messages for syntax errors shouldn't be a design goal for Black. We just need to tell users their code isn't valid Python, and they can run Python itself to get an exact SyntaxError.

**Closed by JelleZijlstra** 2021-09-08 14:28 UTC
Labels: T: enhancement, C: blib2to3, C: parser
