### ISSUE TITLE
Style suggestiong: allow aligned dict values

### ISSUE THREAD

**Issue by kaddkaka** [psf/black#4281] opened 2024-03-17 23:16 UTC
**Describe the style change**
Allow aligning dict values in dict literals. 

**Examples in the current _Black_ style**
```py
DATA = {
    "aa": 0x000F,
    "bbbb": 0x00F0,
    "cccccccc": 0x0F00,
    "dddddd": 0xF000,
}
```

**Desired style**
Having aligned values can aid readability in some cases.
```python
DATA = {
    "aa":       0x000F,
    "bbbb":     0x00F0,
    "cccccccc": 0x0F00,
    "dddddd":   0xF000,
}
```

If the values are already aligned, that could be an heuristic to leave them aligned, just like trailing comma is a heuristic to control 1 element per line.

**Comment by JelleZijlstra** [comment] 2024-03-18 18:03
Suggestions similar to this have appeared several times, but we have consistently rejected them. 

Duplicate of #502

**Closed by JelleZijlstra** 2024-03-18 18:03 UTC
Labels: T: style
