### ISSUE TITLE
Black's suggested indentation not accepted by pylint

### ISSUE THREAD

**Issue by grondman** [psf/black#1724] opened 2020-09-24 06:44 UTC
I got the following diff suggested by Black (code deliberately "anonymized"):
```
             elif self.get_object().some_property is None and not hasattr(
-                    some_object, "some_attribute"
+                some_object, "some_attribute"
             ):
                 some_flag = True
```
i.e. it wants to reduce the indentation of the two arguments to `hasattr` on the previous line. But `pylint` will complain, saying `bad-continuation / Wrong hanging indentation before block (add 4 spaces)`. IMHO it is indeed weird that Black suggests to leave these arguments (that are part of a function, which is part of an `elif` clause) at the same indentation level as the actual body of the clause.

**Comment by TylerYep** [comment] 2020-10-06 07:27
I believe that pylint is wrong in this case - there should be an issue on pylint that brings this up. Black is correct here - the code should only be indented once.

**Comment by grondman** [comment] 2020-10-06 10:12
PEP-8 on [Indentation](https://www.python.org/dev/peps/pep-0008/#id17): "When using a hanging indent the following should be considered; there should be no arguments on the first line and _further indentation should be used to clearly distinguish itself as a continuation line_"

The second example of the PEP-8 section on [Indentation](https://www.python.org/dev/peps/pep-0008/#id17), which I'll repeat here, also shows an extra level of indentation:
```
# Add 4 spaces (an extra level of indentation) to distinguish arguments from the rest.
def long_function_name(
        var_one, var_two, var_three,
        var_four):
    print(var_one)
```
I think the case I brought forward is quite similar. Black should be aware that the continuation here is part of an arguments list and should allow the extra level of indentation to distinguish these arguments from the actual body of the `elif` clause.

**Comment by hugovk** [comment] 2020-10-06 12:00
I find Black's frowny face `):` helps distinguish the two chunks clearly:

```python
def long_function_name(
    var_one,
    var_two,
    var_three,
    var_four,
    var_five,
    var_six,
    var_seven,
    var_eight,
    var_nine,
):
    print(var_one)
```

**Comment by grondman** [comment] 2020-10-06 12:39
It's a bit besides the point whether Black comes up with an alternative that is clear. I know Black is the "uncompromising" reformatter, but I don't think it should overrule PEP-8. The frowny face on a separate line thing is not seen in any example in PEP-8, I think.

I should probably also rephrase the example:
```
             elif self.get_object().some_property is None and not hasattr(
-                    some_object, "some_attribute"):
+                some_object, "some_attribute"
+            ):
                 some_flag = True
```
Difference with the previous one is that I now did not already have a frowny on a separate line, making the example more similar to the one in the PEP-8 documentation.

**Comment by hugovk** [comment] 2020-10-06 13:07
Is this a duplicate of https://github.com/psf/black/issues/1178? That issue was discussed at length and is unlikely to be changed. The conclusion: https://github.com/psf/black/issues/1178#issuecomment-614050678.

**Comment by JelleZijlstra** [comment] 2020-10-06 13:19
Yes, it is.

**Closed by JelleZijlstra** 2020-10-06 13:19 UTC
