### ISSUE TITLE
Black takes no decision about inline trailing comma?

### ISSUE THREAD

**Issue by iago-lito** [psf/black#1276] opened 2020-02-17 20:32 UTC
I would expect Black to identically format the last two lines in this file:

```python
a = 5
b = 8
c = 13


def method(l):
    return [i ** 2 for i in l]


result = method([a, b, c])
result = method([a, b, c,]) 
```
I mean, either choose to stick to `[a, b, c]` or to `[a, b, c,]` with the trailing comma, as they are semantically identical.

But it does not choose, and leave both as-is. Should it?

```
$ uname -a
Linux etak 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux

$ black --version
black, version 19.10b0

$ python --version
Python 3.8.1
```
This also seems to happen [on master](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADEAIZdAD2IimZxl1N_WlOfrjrkU9j1_tG5F7jd6kZaHysjrjIv69J6azJGXlFqETdLrlZGeaer4_CoDSrSaOomol__H1_VWHDrNl7syx41CfoQW1yW2Nbnrx2ApwnznvIcOhFDIPMdez6swWZRQRiyXYwL7LoVTHd8GpCeIxu7-Ki7i6DPrkScSboAAAAA0TNfm7qT5cwAAaIBxQEAAIs5sOqxxGf7AgAAAAAEWVo=).

If I understand the [black style spirit](https://black.readthedocs.io/en/stable/the_black_code_style.html) well, I think that the trailing comma in the last line should be removed. But I've just found out about Black tonight, so I'm not sure :\ Is this expected behaviour?

**Comment by zsol** [comment] 2020-02-18 12:33
This is a duplicate of #1169.

**Closed by zsol** 2020-02-18 12:33 UTC
Labels: bug
