### ISSUE TITLE
Inconsistent formatting of `**` in tenary expression.

### ISSUE THREAD

**Issue by randolf-scholz** [psf/black#4149] opened 2024-01-11 13:43 UTC
```python
m2 = None if not isinstance(dist, Normal) else μ**2 + σ**2
m2 = None if ... else μ**2 + σ**2
```

becomes ([black-playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADWAIBdAD2IimZxl1N_WmA--ISCB5EifcHtD-SC05S16MrO2s_CTIlU7kJn3hUYYEAR2UQPTBTwi80_HP-MWRwv-fM86Wk4t0tumjrAkl6y_aJWDqESGKOTm19NXn-bXgtU_nNq-Ina2D_Vmb_KpKm_IeMxherTcuswNovlvqb4_kcDY1DbAN1sYibT_XliAAGcAdcBAABCwNAuscRn-wIAAAAABFla))

```python
m2 = None if not isinstance(dist, Normal) else μ ** 2 + σ**2
m2 = None if ... else μ**2 + σ**2
```

There are spaces added to `μ**2` depending on unrelated code.

**Comment by JelleZijlstra** [comment] 2024-01-11 16:17
Similar to #3889, which was fixed in preview mode. However, this issue is not fixed even in the preview mode. I thought we might mess up some length calculation due to the Greek letters, but that's not the case as it also reproduces with Latin letters:

```
% black -c  '''m2 = None if not isinstance(dist, Normal) else m**2 + s**2
m2 = None if ... else m**2 + s**2
''' --preview
m2 = None if not isinstance(dist, Normal) else m ** 2 + s**2
m2 = None if ... else m**2 + s**2
```

**Comment by wannieman98** [comment] 2024-01-16 00:05
Is the expected behavior for black formatter to change 
`m2 = None if not isinstance(dist, Normal) else m ** 2 + s**2`
into
`m2 = None if not isinstance(dist, Normal) else m**2 + s**2`?

In that case, what is the expected behavior for
`m3 = foo() ** 2`?
Should it be 
`m3 = foo()**2` or `m3 = foo() ** 2`?

**Comment by wannieman98** [comment] 2024-01-17 18:06
Hi @JelleZijlstra! Please review #4154, it is my proposed to fix the bug.

**Closed** 2024-02-05 13:33 UTC
Labels: T: bug, S: accepted
