### ISSUE TITLE
black fails on type-annotated tuple assignment

### ISSUE THREAD

**Issue by williamflynt** [psf/black#1546] opened 2020-07-12 04:17 UTC
**Describe the bug** black fails to reformat files containing a line like `x: tuple = a, b`

**To Reproduce** Here's a test script.

```
from typing import Tuple


a = 1
b = 2

x = a, b  # works fine!
x = a, b + 1  # also works fine!
# x: Tuple = a, b + 1  # fails
# x: Tuple = a, b  # also fails
x: tuple = a, b  # fails
```

1. Take this file '...'
2. Run _Black_ on it with these arguments (optional): `--target-version py38`
3. See error `exit code 123`

```
error: cannot format tmp.py: Cannot parse: 11:12: x: tuple = a, b
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior** black reformats

**Environment (please complete the following information):**

- Version: [e.g. master] `master` direct from git (`black, version 19.10b0`)
- OS and Python version: [e.g. Linux/Python 3.7.4rc1]: `Ubuntu 19.10/Python 3.8.0`

**Does this bug also happen on master?** Yes - local and hosted demo.

**Comment by ichard26** [comment] 2020-07-19 23:11
Duplicate of https://github.com/psf/black/issues/1368.

**Closed** 2020-07-20 00:12 UTC
Labels: bug
