### ISSUE TITLE
Black and flake8 can't agree on line length limit

### ISSUE THREAD

**Issue by jaraco** [psf/black#1314] opened 2020-03-24 22:26 UTC
Given [this code](https://github.com/jaraco/recapturedocs/blob/cff1e26b9ad4b445b0474e532282237c730396c5/recapturedocs/server.py#L359-L361), flake8 (correctly) errors that the line is longer than the [declared line length](https://github.com/jaraco/recapturedocs/blob/cff1e26b9ad4b445b0474e532282237c730396c5/.flake8#L2), which is 88 to match the expectation of black. If I correct the syntax to satisfy flake8, black starts to fail, such as in [this commit](https://github.com/jaraco/recapturedocs/blob/74df1d056a59650b07d44ff84c73cdac89b64b30/recapturedocs/server.py#L359-L362).

Is there a way for black and flake8 to get along?

**Comment by kubasikus** [comment] 2020-03-27 11:57
I've recently been trying to use black in stuff I do, and i found that setting flake8 to l--max-line-length=~95-100 lets you live in relative peace. Black will sometimes overflow, but not by much. If it does overflow by a lot, it might be because it cannot split string (yet). So you will have to fix that manually - and flake will let you know.

**Comment by EgZvor** [comment] 2020-04-19 20:00
How do you format this part manually to satisfy line length requirement?

**Comment by retnikt** [comment] 2020-06-02 09:49
I have found the easiest way is to disable the relevant Flake8 errors and just let Black handle them - you can use `black --check` to add to your linting scripts.

**Comment by jaraco** [comment] 2020-06-03 00:56
I'd be okay with that as a resolution if that were the recommendation of the `flake8` team. I'm a little uneasy with accepting that outcome if it's one project deprecating another.

**Comment by davips** [comment] 2020-06-04 13:27
> I've recently been trying to use black in stuff I do, and i found that setting flake8 to --max-line-length=~95-100 lets you live in relative peace. Black will sometimes overflow, but not by much. If it does overflow by a lot, it might be because it cannot split string (yet). So you will have to fix that manually - and flake will let you know.

Please keep it that way, not breaking strings is a feature! Sometimes we all have strings which are not interesting at all to be read or changed. One can easily manually break the needed ones. If you are curious, e.g. encoders can have alphabets with hundreds of columns in a string. Error messages etc.

**Comment by jaraco** [comment] 2020-06-04 22:17
I don't think anything in my example suggests to break string lengths. The longest string in that block is 30 chars.

**Comment by JelleZijlstra** [comment] 2022-01-29 16:00
Duplicate of #413.

The sample code is:
```
            '/': {
                'tools.auth_basic.on': True,
                'tools.auth_basic.realm': 'RecaptureDocs admin',
                'tools.auth_basic.checkpassword': cherrypy.lib.auth_basic.checkpassword_dict(
                    dict(admin='g0tch4-h4x0r',)
                ),
            },
```

**Closed by JelleZijlstra** 2022-01-29 16:00 UTC
Labels: T: bug, T: design, F: linetoolong

**Comment by kwk** [comment] 2023-02-13 12:28
> Duplicate of #413.
> 
> The sample code is:
> 
> ```
>             '/': {
>                 'tools.auth_basic.on': True,
>                 'tools.auth_basic.realm': 'RecaptureDocs admin',
>                 'tools.auth_basic.checkpassword': cherrypy.lib.auth_basic.checkpassword_dict(
>                     dict(admin='g0tch4-h4x0r',)
>                 ),
>             },
> ```

@JelleZijlstra I don't see the similarity of #413 and #1314 . The latter is for flake8 and black to get along but the first seems to be for broken formatting.

**Comment by JelleZijlstra** [comment] 2023-02-13 17:13
The reason they don't "get along" is that Black doesn't split a line that is too long, so the fix is to make it so Black does split the line, which is what #413 is about. If there's anything else that this issue would cover, I'm not seeing it.
