### ISSUE TITLE
Can not format `method` code when method str parameter length default value too long

### ISSUE THREAD

**Issue by pengdada00100** [psf/black#4150] opened 2024-01-12 02:20 UTC
**Describe the bug**

Can not format `method` code when method str parameter length default value too long

**To Reproduce**
env: python 3.8.10
black: 23.12.1

```python
def demo_method(
    param1="this is a long long long long long long long long long long long long long long long long long long long long string",
):
    a = (
        "this is a long long long long long long long long long long long long long long long long"
        " long long long long string"
    )
    pass


if __name__ == "__main__":
    pass
```

And run it with these arguments:

```sh
python -m black .
```

The resulting is:

> cannot format file.py without error, But the 'param1="this is a long long long long long long long long long long long long long long long long long long long long string"' can not format

**Expected behavior**

The default param should be format

**Environment**

- Black's version: 23.12.1
- OS and Python version: 

**Additional context**
Also I can define a string constant out of this method and pass the constant to the method.
But I think black should format this scene

**Comment by pengdada00100** [comment] 2024-01-12 03:25
https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AHEAI9dAD2IimZxl1N_WlbvK5WUOuo5piIacmXZjV2Jd5cbGDbAZgLjDOUK4HDNCB64WCKQnd5ZR8luJ8LL1s62Y5Xg3nF8N9RQTnr5ZOHowiaeEgMBS2t8op3rOBvfkhBduxU_vCUer-3lxEZXEed-3kSzFH0iym-VUFQwzP71sfQ9J3k4aoIdPv_hOBhn_IkWjCtSAABTskh-SxxB-gABqwHFAwAALbw7zrHEZ_sCAAAAAARZWg==
You can see it through upper link.

**Comment by JelleZijlstra** [comment] 2024-01-12 03:33
Are you saying that Black is crashing, or just that in Black's output the line is still too long?

**Comment by pengdada00100** [comment] 2024-01-12 05:05
output the line is still too long

**Comment by hauntsaninja** [comment] 2024-01-12 05:08
In that case, I think this is basically a duplicate of https://github.com/psf/black/issues/3497

**Closed by hauntsaninja** 2024-01-12 05:08 UTC
Labels: T: bug
