### ISSUE TITLE
This project perpetuates racism

### ISSUE THREAD

**Issue by lennox824** [psf/black#1989] opened 2021-02-15 01:08 UTC
Similar to getting rid of "master", "whitelist", and other words laced with white supremacy, I would like to request we change the name of the black project to a different one that is a bit more sensitive and aware.

Running a black program that does menial tasks of formatting code is akin to slavery and perpetuates racism and white supremacy. In order to create a more inclusive Python community to all races, I suggest changing this popular project's name.

**Comment by g-bon** [comment] 2021-02-15 13:20
I'm wondering if it's a serious or a satyrical proposal, let's say it's the first one. The proposal makes no sense to me. It's a color, could have been any color, but black works best to clarify that not having a choice of which color (formatting) is a feature. There is zero reference to people, or skin or anything.  
I also disagree on the menial tasks, as any formatting tool (by the way there is fork called white) it does an incredibly useful task.

In case it's a joke, well done! I want this 5 minutes back 😄

**Comment by MarcoGorelli** [comment] 2021-02-15 13:42
duplicate of #1830 ?

**Comment by ichard26** [comment] 2021-02-15 16:33
Alright,

So first off, I want to make it clear that the concerns shared in this issue are valid. Also, racism does exist and is a valid concern, so chances are that this is a serious issue. 

Now, the name was coined as a humorous reference to Henry Ford's quote on the Model T: "Any customer can have a car painted any color that he wants so long as it is black." The readme begins with a shortened version of this quote. The logo is a play on the Ford logo. Any sort of racism was not intentional.

> duplicate of #1830 ?

Yes, and since I do not foresee any productive conversation coming from this, I'm closing this.

**Closed by ichard26** 2021-02-15 16:33 UTC
Labels: enhancement

**Comment by philiparvidsson** [comment] 2022-12-05 04:54
Could it be renamed to "white"?
