### ISSUE TITLE
Black reports code that is not equivalent when formatting a doc-string in a file that contains the exec statement

### ISSUE THREAD

**Issue by deymundson** [psf/black#1771] opened 2020-10-20 16:44 UTC
**Description**
If a file contains a doc-string that requires formatting, and the `exec` statement, _Black_ will complain that the change to the doc-string is not equivalent.

Note that this only applies to the `exec` statement. The `exec()` function works as expected. Therefore this issue only applies if the target Python version is 2.7.

**To Reproduce**
1. Using a file with the following contents
```
def Foo():
    """
    """


exec ""

```
2. Run _Black_ on it with these arguments `--target-version=py27`
3. See error

**Expected behavior**
Black would format the file, including the doc-string, without an error stating that the code is not equivalent.

**Environment**
- Version: 20.8b1
- OS and Python version: Windows/Python 3.9

**Does this bug also happen on master?**
[Yes](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACMAFFdAD2IimZxl1N_WlbvK5V3cxsh6agT5OjvWCG_HIVRpPbsP0jGcU21zGAhOJYB05HGZUhO2z469Ogu5jL0-OJP8ALoMSJ_HH7Xku2IlzY52w6NDgAAAACcRlZ8yFgRzQABbY0BAAAAH9v1hrHEZ_sCAAAAAARZWg==)

**Additional context**
The same issue exists when _Black_ reformats a doc-string with an Exception handler that uses the "comma" syntax to get the instance of the exception. i.e. `except Exception, e:`
See [here](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADJAG5dAD2IimZxl1N_WmhNCiRwQUbyNLdrUAop306CHnsa_ui5UrbueNzRuw02Uz6xznzH52ILziq-l8pWp2iSypfFXj7v-pEdfN5MW6peRgJnzpmew1syYRtWALT6q0j2b00XkNkJXLwr9sebYPJvsLkAAAAABcCHlXMCIXIAAYoBygEAAIauLFmxxGf7AgAAAAAEWVo=) for a snippet in the _Black_ playground.

**Comment by ichard26** [comment] 2020-10-26 22:19
Closing as a duplicate of #1635.

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ python --version ; git log -n 1 --oneline
Python 3.8.5
4070527 (HEAD -> main, upstream/master, caching) Switch to pytest and tox (#1763)
(black) ichard26@acer-ubuntu:~/programming/oss/black$ cat temp.py 
def Foo():
    """
    """


exec ""
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black temp.py -t py27 --fast --diff --color
--- temp.py	2020-10-26 22:16:15.861441 +0000
+++ temp.py	2020-10-26 22:16:42.500120 +0000
@@ -1,6 +1,5 @@
 def Foo():
-    """
-    """
+    """"""
 
 
 exec ""
would reformat temp.py
All done! ✨ 🍰 ✨
1 file would be reformatted.
```

**Closed by ichard26** 2020-10-26 22:19 UTC
Labels: bug, duplicate
