### ISSUE TITLE
Consider 90 columns as a default

### ISSUE THREAD

**Issue by RoboStephen** [psf/black#1725] opened 2020-09-24 16:25 UTC
88 is a very inauspicious number to have as the default column count:
https://en.wikipedia.org/wiki/Fourteen_Words

Hopefully it was just an unlucky coincidence that the default column length happens to match a white supremacist symbol. 

Anyway.  How about 90 as a default column length?  That's a nice round number, free of baggage.

**Comment by zsol** [comment] 2020-09-24 17:00
Duplicate of #1191.

**Closed by zsol** 2020-09-24 17:00 UTC

**Comment by RoboStephen** [comment] 2020-09-24 17:07
It looks like #1191 has been closed and comments locked.

With respect: I think it would be more than appropriate to revisit this question in 2020.  Attention has been drawn to the problem. Use of 88 was an innocent mistake - but a deliberate choice to continue using it raises concerns.

**Comment by LogicalDash** [comment] 2021-06-12 17:09
https://github.com/psf/black/issues/1191#issuecomment-562975586 "At this point Black is deployed to a large number of projects so it's unlikely we're going to change such a core aspect of the formatting."

If it's such a core aspect of the formatting, why is line length the one aspect of formatting that users can change with an option in black?
