### ISSUE TITLE
Docstring and raising exception in py2 style generates INTERNAL ERROR

### ISSUE THREAD

**Issue by lodagro** [psf/black#1722] opened 2020-09-23 11:13 UTC
When running black on the following file an INTERNAL ERROR is raised.

```python
 def bar():
     """some docstring
     """
     try:
         print('do some stuff')
     except Exception, e: 
         pass
```    

This is the generated diff.               

```
--- src
+++ dst
@@ -14,11 +14,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b'some docstring\n    ',  # bytes
+                b'some docstring',  # bytes
             )  # /Constant
         )  # /Expr
         TryExcept(
           body=
             Print(
```

This the full error:

```
INTERNAL ERROR: Black produced code that is not equivalent to the source.
```

- Version:
  - 20.8b1
  - master 20.8b2.dev24+g6dddbd7
- OS and Python version: Linux / Python 3.8

**Comment by ichard26** [comment] 2020-10-26 22:53
Hi, I'm closing this as it's a duplicate of #1635.

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ python --version ; git log --oneline -n 1
Python 3.8.5
4070527 (HEAD -> main, upstream/master, caching) Switch to pytest and tox (#1763)
(black) ichard26@acer-ubuntu:~/programming/oss/black$ cat temp.py
def bar():
    """some docstring
    """
    try:
        print("do some stuff")
    except Exception, e:
        pass
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black temp.py --diff --color
error: cannot format temp.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_9_gz0d1n.log
Oh no! 💥 💔 💥
1 file would fail to reformat.
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black temp.py --diff --color --fast
--- temp.py	2020-10-26 22:51:32.886060 +0000
+++ temp.py	2020-10-26 22:52:06.607420 +0000
@@ -1,7 +1,6 @@
 def bar():
-    """some docstring
-    """
+    """some docstring"""
     try:
         print("do some stuff")
     except Exception, e:
         pass
would reformat temp.py
All done! ✨ 🍰 ✨
1 file would be reformatted.
```

**Closed by ichard26** 2020-10-26 22:53 UTC
Labels: bug, duplicate
