### ISSUE TITLE
Always exclude files specified in config, even when call directly excluded file

### ISSUE THREAD

**Issue by llybin** [psf/black#1248] opened 2020-01-27 08:10 UTC
I have ignored files in pyproject.toml
```
[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
    \.eggs
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
    | __pycache__
    | _build
    | build
    | dist
  )/
  | java_wallet/models.py
  | java_wallet/models_new.py
  | java_wallet/migrations/0001_initial.py
)
'''
```

`black .` - works fine.

I use PyCharm IDE. I set up call `black`  in file watchers on file change. He call directly the changed file, in this case `black` ignore excluded files in config, and apply changes. 

![image](https://user-images.githubusercontent.com/5445357/73158165-a6655980-4115-11ea-9198-9aec7fa22ed2.png)

I'd like `black` always excludes files specified in config, even when call directly excluded file.

Just now I understood how to avoid it, the prev solution is I found in internet, this is mine, to call `black .` command, not with directly file.

![image](https://user-images.githubusercontent.com/5445357/73158458-71a5d200-4116-11ea-80af-b1c828bf7ec9.png)

Feel free to close, but maybe someone will find useful this solution in future by search. But, I still to think better always exclude excluded files even if direct call a file.

**Comment by zsol** [comment] 2020-01-27 12:27
Duplicate of #949.

**Closed by zsol** 2020-01-27 12:27 UTC
Labels: enhancement
