### ISSUE TITLE
Issue with click library upgrade

### ISSUE THREAD

**Issue by cormaza** [psf/black#2972] opened 2022-03-29 15:09 UTC
Upgrade on library click https://pypi.org/project/click/8.1.0/ broken, I think we can solve restricting version of library to 8.0.4

![image](https://user-images.githubusercontent.com/1674751/160643714-6dd14fba-55fd-4792-a4cf-587f59fee327.png)

**Comment by jack1142** [comment] 2022-03-29 15:14
This has already been fixed by Black 22.3.0.

**Comment by JelleZijlstra** [comment] 2022-03-29 15:41
Duplicate of #2964

**Closed by JelleZijlstra** 2022-03-29 15:41 UTC
Labels: T: bug
