### ISSUE TITLE
Internal error when using fmt directives around a decorator

### ISSUE THREAD

**Issue by sibsibsib** [psf/black#976] opened 2019-08-12 16:12 UTC
Operating system: macos
Python version: 3.7
*Black* version: 19.3b0
Does also happen on master: yes [[playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGcAKhdAD2IimZxl1N_Wk6rkWpnygC1OSONap039AryEPVZkijUCCenTkbU5Ldg_Gwijx3bSvf6TCea88ShfVEIfAE6Q4xWoY-UF8amAVA6kzXi4DstcDE9rQh5zJI7agVySe4oSbjb33Dq4vYA1xoExJyvQCN-Lcg23Tu2qf_S0_CPQ64LjDuxJcXvpQNjwiQNk8yy1fw2vZyQJz8Q16GMbz28NYPwrNhquHpTAAA1jjUUQ7WHtAABxAGdAwAA7yYgObHEZ_sCAAAAAARZWg==)]

Black outputs the following: 
`INTERNAL ERROR: Black produced invalid code: expected an indented block`

---

to reproduce:

```py
class A:
    # fmt: off
    @decorator(
        param=1,
        foo=2,
    )
    # fmt: on
    def __init__(self):
        pass
        

# this line will be incorrectly indented:
class B:
    # fmt: off
    @decorator(
        param=1,
        foo=2,
    )
    # fmt: on
    def __init__(self):
        pass
                
```

Additionally, if the second class has no formatting directives the entire class will be indented under the first one.

I'm working around this by moving the directives inside the decorator parens, eg:

```
@decorator(
    # fmt: off
    param=1,
    foo=2,
    # fmt: on
)
```

**Comment by zsol** [comment] 2019-08-16 07:59
This is a duplicate of #560.

**Closed by zsol** 2019-08-16 07:59 UTC
