### ISSUE TITLE
Line Length rule 

### ISSUE THREAD

**Issue by ljades** [psf/black#947] opened 2019-07-26 16:57 UTC
Operating system: Mac
Python version: 3.6
*Black* version: 19.3b0
Does also happen on master: Yes

Line length is set to 100, for context--no other options being used

```
CONSTANT_DEFINED_DICT = {
     "keyA": "valueA",
     "keyB": "valueB",
     "keyC": "valueC",
-    "keyThatAlsoHappensToBeSuperLongButStillWithinLengthLimit":
-        "valueThatAlsoHappensToBeSuperLongButStillWithinLengthLimit",
+    "keyThatAlsoHappensToBeSuperLongButStillWithinLengthLimit": "valueThatAlsoHappensToBeSuperLongButStillWithinLengthLimit",
}
```

There is a bug where, the former is being corrected to the latter, even though the latter exceeds line length limits.

**Comment by zsol** [comment] 2019-07-26 18:28
Duplicate of #847

**Closed by zsol** 2019-07-26 18:28 UTC
