### ISSUE TITLE
Formatting of methods exceeding max. line lenght is inconsistent with pylint

### ISSUE THREAD

**Issue by fkromer** [psf/black#1336] opened 2020-04-08 09:29 UTC
**Describe the bug** When formatting a method with a definition line length > max. length (e.g. 100 chars) the formatted code results in wrong indentation. When linting with `pylint` a warning `C0330: Wrong hanging indentation before block (add 4 spaces).` is raised. 

**To Reproduce**

Format method like this with `black`

    def very_long_function_name_which_exceeds_max_line_length(a: Decimal, b: Decimal, c: Decimal, d: Decimal, e: Decimal,)  -> Tuple[Decimal, Decimal]:
        return

results in:

    def very_long_function_name_which_exceeds_max_line_length(
        a: Decimal, b: Decimal, c: Decimal, d: Decimal, e: Decimal
    ) -> Tuple[Decimal, Decimal]:
        return

Lint the method with `pylint`.

    C0330: Wrong hanging indentation before block (add 4 spaces).

**Expected behavior**

    def very_long_function_name_which_exceeds_max_line_length(
            a: Decimal, b: Decimal, c: Decimal, d: Decimal, e: Decimal
        ) -> Tuple[Decimal, Decimal]:
        return

No error when linting with `pylint`.

**Environment (please complete the following information):**

- Version: black==19.10b0
- OS and Python version: Linux/Python 3.6.9

**Does this bug also happen on master?** To answer this, you have two options:

Yes, the issue happens with the online formatter as well.

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python setup.py test`; and
   - run `black` like you did last time.

**Additional context** Add any other context about the problem here.

**Comment by JelleZijlstra** [comment] 2020-04-08 21:50
This is how Black does formatting, and it's unlikely to change now, especially considering how widely Black has been adopted. Other tools may have different formatting preferences, but that's not a bug in Black. I'd recommend turning off formatting-related errors in linters if you're using Black.

**Comment by JelleZijlstra** [comment] 2020-04-08 21:51
Also a duplicate of #48.

**Closed by JelleZijlstra** 2020-04-08 21:50 UTC
Labels: bug
