### ISSUE TITLE
reformatting issue

### ISSUE THREAD

**Issue by vamshikrishna3105** [psf/black#2486] opened 2021-09-08 19:09 UTC
**Describe the bug**

error: cannot format /Users/vamshi.venkataswamy/ENV/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- Version: 
- OS and Python version: 

**Does this bug also happen on main?**

**Additional context**

**Comment by JelleZijlstra** [comment] 2021-09-08 19:15
Could you provide a copy of the file and tell us what version of Black you're running?

**Comment by jaap3** [comment] 2021-09-29 07:11
I think this might be a duplicate of #1629, the file mentioned in the description it's part of pip. The git history of that file in the pip repository mentions having to do a workaround for black: https://github.com/pypa/pip/commit/83c596ff70bef7e14d865f0f64f283b25d1a606c

Running black (21.9b0) on the version of that file before that commit works now.

**Comment by ichard26** [comment] 2021-12-12 20:28
Closing as I cannot reproduce this bug given the very limited information provided (thank you @jaap3!) [with 21.12b0](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4Bo9B_xdAD2IimZxl1N_Wk8FsFl0P0evfB_WRvOn0CEr9QUbnPdetllHlcG_Sngwj2BDhrTJtLDNacGXcKkZrRxx8N0XgMW1JeKLS0MIubrqLKcLFl6W5qEYKdZxEUQ1wZ5Bb8Xe0ys2nXmFT2Uoj0w-XAIzByIV4aXaW-e9J3Acesk_fXuiuv3IZCE2VXX3O_0wCg4lLUgaRUqoxxHA5mLnXtOutF0piJTw9cDFmFtXlynlfc_uqwhGe2kFt60rqam4lptN2NqYY4vpxNW8zMiIJdkIx7DiMjgcnI4NNgKnmauBpQGnzCK27gmKLUJEBNnej5V5a6zOnDbARmk3I2EG7i2xKjhD6RafV4pW4IatH8MoPllxjMyQg7szztGzKVHYg4IIuyMN1UJ63lMVTz_u9xobivcUTLJC2GEd_yY_NfqFzNTrjICs0ymhcFYv999CmlTyuVxQSk_XAQ6hFg1NxBM_CcIqk7f0Fhq8h7PDzzOorsjJQmJUBhTKG-Z7b6QSNeCRlPL53bKOCXQulEDHUAaTO0j3rQVPkk8aEUx7MYwTjo2wM6sS_4bgvCeusr2sPNTHWLC9ZQs76QlQUw6i9MOH6Erbv74I536_AEC6L9hU37l0FeJ_23v_gV9xQk3a9_VFKzgOA0TkKY6zG9KQSXyMwAR_1eKbagfvk_MK4bP5Tf8QQGIMGSTE9vslzeg0aeusXyHf9ksE5ZmFgSE_nXbKYpgoPQfNvLQLOLDW4S7Sm7alBHpuAKmynbfi5HKdaKLxpBlFh4iXcDk6K-LbN-tIt5glZcz6ZVYxdS9XLsNCgYjLj2Gex4sO_2QH4ejoKb3eVvLHkRP0PBiGkUOtXgKWF3KHdf59S39VulP9CsCH3l2o9ZrBRjjyI-QeM4Vh8CZHBguhallJwXSpfZBemBR4qWSGSMSLYqxcA2esrir3RkgMdGLiNkWMRqIwn315fsFsM3rZtg7EFLynLFVnD5QvbNdGUc4cPGx3ICqm1DCf_W4ALOKWQauGSR9E-uxOHIu3BeBPDt1b8pKaWSG0CDAUESkuyyfscM_X5c53XMm3K_TJWKorSEDmROJlbMKvBT9ptU89mBvUS2_2uGXM8TSPqb8EvFdLm_bjYMfRh6zkvoesCl1ECXnIjCGGq-0cFu8lY4tF_WrMqp-TK1lZmFzrXaumKGjU7Ozb694aXygvjM945oK8F6Nl11JvthtWI_F5WLJKSaQHy6mT8dWNtC1bcTjAhJ8dvD0o-xDCz0HaB8etAKSI8YgpnwttZKCD0t0sS5CfLuBi0uYk5_BVelZ8pwlpV9z9gtWCWs_Rz1UBj4LuPMyL8cSKD2PpEYig4Cvf80rIaBwbfk4tsObG2UnEk09pfMftLTaH2hWOM1R2fUTaPj1vRbZOeQaHCZodfHJjn5RH7tAv68K1pC5apQ8a00GTbuzSU49Fprd_rebMRrUX75JmXba3AV2e2Y7YbnIyT5x6f7nXRcdPk580PuHierMYTgZu4qiTQsY-WFz5owcFWHHETfVvpq2oqjOxfffRko7ptAwx5_Tgs1IQgJiopC6meFDdf7LLKL_sx1038d-WqOKDGQ4_QbSymbqp_ccj5nvHg_mXRuqEvdrPgfAmOU_RH7WhHfikuz2BfGtVX0hNFsOjVY9GMssFKoHmW-cjLvceWEjiE4rhpxvBG7eIj9GjVwHtTphejbO0LL9P991EgfH9Z9EjLvKRmN7NTQm247yF9VHxBGq8YKrjt-zhPv1ngcePiviTOhyZKiDRS_fA12BjiHsv2JgCXxH7nVGT0QQYOAkhv3vwHOr5SrnWkOJWV8yYLItDad9Gc7-Vtpibf03W6r8X6VGIDYl5B3XSlNIMru0f6sfiVrue0ERIcZNmXv51Mos-9nkOLeByXL6fzR9wJeM0ubfdMiN4q8jAOj7yxlJ6HUydTq3lW3EPXc_NxJkLi8HEh7uiTrXXvAtT8YZ1LLi7Q3WGBb0_vWYUaHXqhiBG6pvMYv31q6Tx3Gwzs-GeXfHmRrnNH8Nmlxl2D8PFJm7hOTGzJM0u_55p7l_VIJS7QObDTcfFanu2heIAZt62-i6gb_jZMqGgQxMkkjO5ljOpwBcOcKvB4HscW3Qoj1pAsC7U1KrQyn6RWG33b-Ah6H1cxz_blEp7lI1txnljZq17Rmv-Mm-hYj7Qw8JZrhQ-GQ3-SbI1fKt6B0CJkVDhLTXbK36TQFw7ZrAUEx2uHb-c4oCg-_H-3Bc4WLQegTAwE6x5vNtV9vQcvRsq3I7URUYV3vF-CwuEdmT0LSjzdflwbcrSTJj64yOOJ1uPXUBBD9UxM0r0Etv2qrZT-KU2a34inXw5_fl2vTIuHkvzRDO3QBoOLEaIhGDH_ec5fmcTEe0ttSi2LhYs3mqyq5dayTwrHgV50XyVZz7gWW8ZH0TU6ulJCNJl-ud9SlY01PqxSONS7dgguWv46JE7aq2qN4WxK4wHnJwy1Vr-dTgUgqFlywWHUT13sXVM51bOALfSrffN-4qUfqNE6ePP4f2HJR410JaEdOnjZ3-KNoemAy-reqkRuwiXbL6gtA8AtzgfwqOXEJzb5zhwydp9QQQ0np7LNCzGTjVlPrEyyf1bRKKDKwjU2coKYwQljczXzLuyDvzPNWNFacWc8j2CdiaSd3TG968gtml9yBlzn6kF2Ia1C2y_lupOadr4Fe4MTJtRQjOuDQtgJ8Kn30rZr-S3nxfMoi3WMwAAwI0hfQge8AMAAZgQvjQAAJSjT4yxxGf7AgAAAAAEWVo=).

**Closed by ichard26** 2021-12-12 20:28 UTC
Labels: T: bug, C: unstable formatting, S: needs repro, S: awaiting response
