### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by semajson** [psf/black#1850] opened 2020-12-01 17:21 UTC
**Describe the bug** When running black over the following code:
```
from TestIncl import imported_obj, newer_version_than_software, NOT_SUPPORTED_ERROR, V7_3_00

topology = "national"

if topology in [imported_obj.value,
                imported_obj.value2] and \
   newer_version_than_software(V7_3_00):
    raise NOT_SUPPORTED_ERROR
```
The error `INTERNAL ERROR: Black produced different code on the second pass of the formatter.` is reported

**To Reproduce** Run black over code snippet posted above

**Expected behavior** Black formats the file without error

**Environment :**

- Version: 20.8b1
- OS and Python version: Centos 7 / Python 2.7.5 (although code was from a python 2 script, I don't think it's a python 2 specific issue)

**Does this bug also happen on master?** Yes, it repos on https://black.now.sh/?version=master

**Additional context** Output of the of the diff file:
```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,10 +1,14 @@
-from TestIncl import imported_obj, newer_version_than_software, NOT_SUPPORTED_ERROR, V7_3_00
+from TestIncl import (
+    imported_obj,
+    newer_version_than_software,
+    NOT_SUPPORTED_ERROR,
+    V7_3_00,
+)
 
 topology = "national"
 
-if topology in [imported_obj.value,
-                imported_obj.value2] and \
-   newer_version_than_software(V7_3_00):
+if topology in [
+    imported_obj.value,
+    imported_obj.value2,
+] and newer_version_than_software(V7_3_00):
     raise NOT_SUPPORTED_ERROR
-
-
--- first pass
+++ second pass
@@ -5,10 +5,14 @@
     V7_3_00,
 )
 
 topology = "national"
 
-if topology in [
-    imported_obj.value,
-    imported_obj.value2,
-] and newer_version_than_software(V7_3_00):
+if (
+    topology
+    in [
+        imported_obj.value,
+        imported_obj.value2,
+    ]
+    and newer_version_than_software(V7_3_00)
+):
     raise NOT_SUPPORTED_ERROR

```

**Comment by ichard26** [comment] 2021-04-25 20:14
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:14 UTC
Labels: bug, duplicate, unstable formatting
