### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by loicgasser** [psf/black#1864] opened 2020-12-11 17:01 UTC
**Describe the bug** A clear and concise description of what the bug is.

[blk_y193se_3.log](https://github.com/psf/black/files/5680506/blk_y193se_3.log)

**Environment (please complete the following information):**

`black 20.8b1`
Python version 3.8.5

This error doesn't happen in `black 19.10b0`

**Comment by mvolfik** [comment] 2021-02-22 20:32
MCVE of the failing part:

```python3
def f():
    def f():
        message = ngettext(
            "%s rappel a bien été envoyé.", "%s rappels ont bien été envoyés", len(validations)
        ) % (len(validations))
```

Works with #1958, so likely a duplicate of #1629

**Comment by ichard26** [comment] 2021-04-25 19:49
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:49 UTC
Labels: bug, duplicate, unstable formatting
