### ISSUE TITLE
Black adding commas after ** unpacking operator

### ISSUE THREAD

**Issue by madscientist** [psf/black#3808] opened 2023-07-23 14:08 UTC
**Describe the bug**

I modified a file to remove commas after ** unpacking operators to support compatibility with older versions of Python, but Black added them back.  The docs say this will only happen if Black thinks my code requires Python 3.6 or above, and that it determines this by looking for other instances of commas following * or ** operators, or f-strings.  I've checked carefully and none of those things are present in the file as far as I can tell.

**To Reproduce**

I was modifying https://raw.githubusercontent.com/atlassian-api/atlassian-python-api/master/atlassian/bamboo.py
and I removed the trailing commas after ** in the three places it exists: lines 74, 386, and 575.  Then I run Black on it and it reformats the arguments of the first and third sections to one line (this project sets the line length to 120), but for the middle one it adds back the trailing comma:

```
@@ -381,11 +373,11 @@
             start_index=start_index,
             max_results=max_results,
             elements_key="results",
             element_key="result",
             label=label,
-            **params
+            **params,
         )

     def latest_results(
         self,
         expand=None,
```

**Expected behavior**

I don't want the trailing comma added back, because it breaks support for older versions of Python.

**Environment**

- Black's version: 23.3.0
- OS and Python version: This was done with the `make docker-qa` command in that project, so it's a Linux container and I believe it installs Python 3.7.

It's a little unfortunate how the magic comma interacts with trailing commas on **, so that you can't have both magic comma to avoid reformatting a long list and still support older versions of Python but I guess this problem will go away in the fullness of time 😄

**Comment by madscientist** [comment] 2023-07-23 14:35
I worked around this by adding `# fmt: skip` FWIW

**Comment by hauntsaninja** [comment] 2023-07-23 22:22
I couldn't reproduce. Perhaps you have a config file that explicitly sets a target version? If you could provide a smaller repro that doesn't involve me manually editing things, maybe I'll be able to better repro.

**Comment by hauntsaninja** [comment] 2023-08-04 02:23
Closing as per above

**Closed by hauntsaninja** 2023-08-04 02:23 UTC
Labels: T: bug
