### ISSUE TITLE
Internal error while formatting this code

### ISSUE THREAD

**Issue by knatten** [psf/black#1818] opened 2020-11-13 09:46 UTC
**Describe the bug**
Black fails with an `INTERNAL ERROR`, see below:

**To Reproduce**

1. Take this file `repro.py`:
```python
import numpy

def outer():
    coeff = numpy.zeros((3,3,3,3))

    def foo(a, b):
        return 1

    def bar(col_pos, row_pos, curr_iter):
        return sum(foo(
            coeff[col_pos, row_pos, 1, curr_iter],
            coeff[col_pos, row_pos, 2, curr_iter]) for idx in [1, 2]) / float(1)

    return bar(1,1,1)

print(outer())
```

2. Run `black --check repro.py`

3. See error:

```
error: cannot format repro.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_vtl3owu6.log
Oh no! 💥 💔 💥
1 file would fail to reformat.
```

**Expected behavior**
I expect the file to be formatted properly

**Environment (please complete the following information):**

- Version: `black, version 20.8b1`
- OS and Python version: Ubuntu 20.04 / Python 3.8.5

**Does this bug also happen on master?** 

This also happens at https://black.now.sh/?version=master

**Additional context**

Output from `/tmp/blk_vtl3owu6.log`:
```diff
cat /tmp/blk_vtl3owu6.log
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,16 +1,22 @@
 import numpy
 
+
 def outer():
-    coeff = numpy.zeros((3,3,3,3))
+    coeff = numpy.zeros((3, 3, 3, 3))
 
     def foo(a, b):
         return 1
 
     def bar(col_pos, row_pos, curr_iter):
-        return sum(foo(
-            coeff[col_pos, row_pos, 1, curr_iter],
-            coeff[col_pos, row_pos, 2, curr_iter]) for idx in [1, 2]) / float(1)
+        return sum(
+            foo(
+                coeff[col_pos, row_pos, 1, curr_iter],
+                coeff[col_pos, row_pos, 2, curr_iter],
+            )
+            for idx in [1, 2]
+        ) / float(1)
 
-    return bar(1,1,1)
+    return bar(1, 1, 1)
+
 
 print(outer())
--- first pass
+++ second pass
@@ -6,17 +6,20 @@
 
     def foo(a, b):
         return 1
 
     def bar(col_pos, row_pos, curr_iter):
-        return sum(
-            foo(
-                coeff[col_pos, row_pos, 1, curr_iter],
-                coeff[col_pos, row_pos, 2, curr_iter],
+        return (
+            sum(
+                foo(
+                    coeff[col_pos, row_pos, 1, curr_iter],
+                    coeff[col_pos, row_pos, 2, curr_iter],
+                )
+                for idx in [1, 2]
             )
-            for idx in [1, 2]
-        ) / float(1)
+            / float(1)
+        )
 
     return bar(1, 1, 1)
 
 
 print(outer())

```

**Comment by laktak** [comment] 2020-11-14 21:46
Here is another testcase for IMHO the same bug:

```
import os

def has_256cols():
    return os.environ.get("COLORTERM", "") in ["truecolor", "24bit", "8bit"] or "256" in os.environ.get("TERM", "")

print(has_256cols())
```


```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,6 +1,12 @@
 import os
 
+
 def has_256cols():
-    return os.environ.get("COLORTERM", "") in ["truecolor", "24bit", "8bit"] or "256" in os.environ.get("TERM", "")
+    return os.environ.get("COLORTERM", "") in [
+        "truecolor",
+        "24bit",
+        "8bit",
+    ] or "256" in os.environ.get("TERM", "")
+
 
 print(has_256cols())
--- first pass
+++ second pass
@@ -1,12 +1,16 @@
 import os
 
 
 def has_256cols():
-    return os.environ.get("COLORTERM", "") in [
-        "truecolor",
-        "24bit",
-        "8bit",
-    ] or "256" in os.environ.get("TERM", "")
+    return (
+        os.environ.get("COLORTERM", "")
+        in [
+            "truecolor",
+            "24bit",
+            "8bit",
+        ]
+        or "256" in os.environ.get("TERM", "")
+    )
 
 
 print(has_256cols())
```

**Comment by ichard26** [comment] 2021-04-25 20:14
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:14 UTC
Labels: bug, duplicate, unstable formatting

**Comment by knatten** [comment] 2021-04-26 07:12
Thanks for fixing, and for the detailed reply!
