### ISSUE TITLE
Code is formatted in a way that exceeds line limit

### ISSUE THREAD

**Issue by mfrlin** [psf/black#2729] opened 2021-12-28 01:19 UTC
If we start with "correctly" formatted code

```
my_dict = {
    something_long.SomethingLong.SOMETHING_LONG:
        lambda e: something_really_long.SomethingReallyLong.some_function_with_long_name(
            some_argument
    ),
}
```

and then run Black, we get lines that are over 120 characters in length

```
my_dict = {
    something_long.SomethingLong.SOMETHING_LONG: lambda e: something_really_long.SomethingReallyLong.some_function_with_long_name(
        some_argument
    ),
}
```

**Comment by JelleZijlstra** [comment] 2022-01-29 16:04
Duplicate of #413 or #808 or both.

**Closed by JelleZijlstra** 2022-01-29 16:04 UTC
Labels: T: bug, F: linetoolong, F: linebreak
