### ISSUE TITLE
Long key: value in a dictionary goes over line limit

### ISSUE THREAD

**Issue by therve** [psf/black#847] opened 2019-05-09 14:45 UTC
If a dictionary has a key value which doesn't fit, black reformats it incorrectly. For example

```
a = {
    'averylongkeywhichdoesntfitin40charsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx':
        'averylongvaluewhichwereallytostretch'
}
```

is reformatted to:
```
a = {'averylongkeywhichdoesntfitin40charsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx': 'averylongvaluewhichwereallytostretch'}

```

I believe the first version is correct. The second one is certainly not. Possibly related to #808.

Operating system: OS X
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

**Comment by bradyrx** [comment] 2019-06-02 01:32
I'm having the same issue here. This is problematic when `black` is combined with `flake8` in CI, since `black` forces one line key:item pairs which forces it over the line limit.

**Comment by marcelotrevisani** [comment] 2019-06-10 15:25
I am having the same problem, if the value is too long, black is not breaking it to new lines

**Comment by ljades** [comment] 2019-07-26 18:53
Did this issue ever get resolved? I'm running into it as well.

**Comment by zsol** [comment] 2019-07-30 19:45
I recently realized this is already reported. Let's move the conversation over there

Dupe of #620

**Closed by zsol** 2019-07-30 19:45 UTC

**Comment by Holt59** [comment] 2019-11-28 09:43
@zsol I've commented on #620, but this looks like two separate issues (my issue is very close to @therve original issue). 

#620 is about black splitting lines incorrectly and breaking code (or making code harder to read from some comments). This issue is (in my opinion) much simpler than #620, it simply seems that given such code:

```
a = {
    key: value
}
```

...`black` does not split `key: value` even if the line is too long (see https://github.com/psf/black/issues/620#issuecomment-481880006 and https://github.com/psf/black/issues/620#issuecomment-559415991).
