### ISSUE TITLE
Black 23.1 no longer respects trailing magic comma for single length list

### ISSUE THREAD

**Issue by gaborbernat** [psf/black#3542] opened 2023-02-02 17:03 UTC
```python
from typing import Literal

A = Literal[
    "DEFAULT",
]
```

```bash
❯ black magic.py --check
would reformat magic.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```
It turns it into:
```python
from typing import Literal

A = Literal["DEFAULT",]

```

I personally would prefer to respect trailing magic commas here, but at the very least remove the trailing comma if is going to be inlined into a single line.

**Comment by ichard26** [comment] 2023-02-03 03:51
This is as intended. See https://ichard26.github.io/blog/2022/12/black-23.1a1/#ignore-magic-trailing-comma-for-single-element-subscripts and https://github.com/psf/black/issues/2918.

This probably isn't documented in the style documentation though. Definitely important to fix that.

**Comment by felix-hilden** [comment] 2023-02-03 07:43
Definite +1 to removing the trailing comma on a single line though 😄

**Comment by JelleZijlstra** [comment] 2023-02-03 13:39
> Definite +1 to removing the trailing comma on a single line though 😄

That would be an AST-unsafe change. It happens to be safe for types, but it isn't safe in general.

```
In [30]: print(ast.dump(ast.parse("a[1]"), indent=2))
Module(
  body=[
    Expr(
      value=Subscript(
        value=Name(id='a', ctx=Load()),
        slice=Constant(value=1),
        ctx=Load()))],
  type_ignores=[])

In [31]: print(ast.dump(ast.parse("a[1,]"), indent=2))
Module(
  body=[
    Expr(
      value=Subscript(
        value=Name(id='a', ctx=Load()),
        slice=Tuple(
          elts=[
            Constant(value=1)],
          ctx=Load()),
        ctx=Load()))],
  type_ignores=[])
```

**Comment by felix-hilden** [comment] 2023-02-03 17:25
Oh true 👍

**Comment by hauntsaninja** [comment] 2023-06-29 06:37
The only alternative I see here is something like `A = Literal[("DEFAULT",)]` ... thoughts? Otherwise, we should just close this issue, because Black shouldn't modify AST.

**Comment by hauntsaninja** [comment] 2023-07-10 00:08
Closing as per my comment above (since no one seems to have loved the parenthesised tuple suggestion)

**Closed by hauntsaninja** 2023-07-10 00:08 UTC
Labels: T: bug, T: style, R: not a bug, F: trailing comma
