### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter. with walrus

### ISSUE THREAD

**Issue by KotlinIsland** [psf/black#1721] opened 2020-09-23 05:13 UTC
```py
if it := 'fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff':
    print(it)
```
```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,2 +1,4 @@
-if it := 'fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff':
+if (
+    it := "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
+):
     print(it)
--- first pass
+++ second pass
@@ -1,4 +1,4 @@
 if (
     it := "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
-):
+) :
     print(it)
```

**Comment by matthiask** [comment] 2020-11-21 11:38
I encounteted this as well:

```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -80,13 +80,15 @@
     )
 
 
 @student_required
 def buy(request):
-    if item := Item.objects.buyable_by(request.user).filter(
-        identifier=request.POST.get("identifier")
-    ).first():
+    if (
+        item := Item.objects.buyable_by(request.user)
+        .filter(identifier=request.POST.get("identifier"))
+        .first()
+    ):
         request.user.owned_items.add(item)
         request.user.equip_item(item)
         request.user.recalculate(save=True)
     return JsonResponse(
         {
--- first pass
+++ second pass
@@ -84,11 +84,11 @@
 def buy(request):
     if (
         item := Item.objects.buyable_by(request.user)
         .filter(identifier=request.POST.get("identifier"))
         .first()
-    ):
+    ) :
         request.user.owned_items.add(item)
         request.user.equip_item(item)
         request.user.recalculate(save=True)
     return JsonResponse(
         {
```

**Comment by ichard26** [comment] 2020-12-29 20:44
This was fixed in commit https://github.com/psf/black/commit/1d2d7264ec7c448744b771910cc972da03b1cb80 from PR https://github.com/psf/black/pull/1655: ''Fix incorrect space before colon in if/while stmts". This issue is technically a duplicate of https://github.com/psf/black/issues/1194 but I'll leave this open until a release ships with the fix mentioned above.

**Comment by jku** [comment] 2021-04-27 12:44
This can be closed now?

**Closed** 2021-04-27 14:34 UTC
Labels: bug, duplicate, unstable formatting
