### ISSUE TITLE
Parse failure on some Unicode identifiers

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#455] opened 2018-08-16 04:05 UTC
Black gives a syntax error on this file:
```python
import unittest

class PEP3131Test(unittest.TestCase):

    def test_valid(self):
        class T:
            ä = 1
            µ = 2 # this is a compatibility character
            蟒 = 3
            x󠄀 = 4
```
Error:
```
error: cannot format unident.py: Cannot parse: 10:13:             x󠄀 = 4
```

This is part of `Lib/test/test_unicode_identifiers.py` from the CPython test suite.

Operating system: OS X
Python version: 3.7.0
*Black* version: master

**Comment by ambv** [comment] 2018-08-17 14:00
Yeah, this is a bug to be fixed although fortunately low priority.

This only happens for atypical classes of Unicode identifiers. Usual Unicode identifiers work fine and real-world code is unlikely to encounter this (unless malicious code). What's unsupported in lib2to3 is a certain class of legacy identifiers and variant forms. The latter is what we're dealing with in this example.

I happen to have the UTF-8 decoding table on my desk, as you do, so I checked and this example is pretty insidious. It's a base `x` letter followed by a ["variation selector"](https://en.wikipedia.org/wiki/Variant_form_(Unicode)). Variants are for people to be able to choose which *glyph* should be used in rendering the character. It's ambiguous if a glyph variant should be considered a unique identifier since it's rendered with the base glyph if a given font lacks the variant (as is the case here, see example below).
```
# which one is variant-17?
x
x󠄀
```

**Comment by andersk** [comment] 2019-04-19 22:08
Another example with no variation selectors, reduced from https://github.com/uber/pyflame/blob/v1.6.7/tests/sleeper_ユニコード.py:
```python
មុ = 1
```
That’s U+1798 KHMER LETTER MO + U+17BB KHMER VOWEL SIGN U.

**Comment by prusse-martin** [comment] 2019-10-04 19:55
Part of our team develops physics simulation and they are used to have Unicode characters in the identifiers to better match the literature formulas (in python and c++ code).
We started to use Black in our projects and one problem we faced is having `Q̇_per_meter` ("Cannot parse" error). This is valid python code and have no malicious intent.

**Comment by dyus** [comment] 2019-10-07 14:14
I can give a try to replace re module in favor [regex package ](https://pypi.org/project/regex/) which has support for latest unicode standard (unicode 12.1.0)

**Comment by JelleZijlstra** [comment] 2019-10-07 14:19
@dyus that sounds promising, thanks!

**Comment by dyus** [comment] 2019-10-08 05:40
I didn't dive deep into re module, but fact is that java or several other languages has special symbol for any letter `\L` and re module doesn't. Module regex also has that symbol for any letter match. And  I suppose it works different with unicode symbol. I think the problem is related to how re module works with unicode.

**Comment by zsol** [comment] 2019-10-13 17:25
This is fixed in #1047

**Closed by zsol** 2019-10-13 17:25 UTC
Labels: bug, help wanted, lib2to3

**Comment by cas--** [comment] 2019-12-13 12:41
There should be an alternative to a hard dependency of `regex` for a year old low priority bug that causes widespread disruption to users. Also relying on third-party library in pull requests and packaging availability must be questioned.

The author of `regex` is not going to provide wheels:

https://bitbucket.org/mrabarnett/mrab-regex/issues/343/wheel-for-linux
> @Seth Morton: I, personally, am not interested in building wheels for anything other than Windows (and I’m not sure how long I’ll be building ones for Python 2, what with it about to reach end-of-life), but I would accept a contribution that would enable others to do build them.

Why not revert the fix and dependency to reconsider a better solution?

**Comment by jezdez** [comment] 2019-12-13 13:23
@ambv Hey there, given the fairly low priority of this bug I'd like to suggest to revert the change made in #1047 since it added a non-trivial burden on black users by requiring a C compiler for the installation of the newly added dependency "regex". 

The "regex" library author has indicated that they have [no interest in providing whl files for other than Windows and possibly Python 2](https://bitbucket.org/mrabarnett/mrab-regex/issues/343/wheel-for-linux#comment-55179534) at the moment. I'm happy to open a PR to revert it.

**Comment by jonathanlunt** [comment] 2020-01-09 23:20
@jezdez As a user, I think this should be reverted as well. 

Our team started running black on our builds and now we need a C compiler on even native-python packages. We use black primarily as a minimal sanity test in a testing/cicd setting so I ask the maintainers to please consider reducing system configuration overhead.

Alternatively you could have regex as an `extras_require` and do something along the lines of

```python
try:
    import regex as re
except ImportError:
    import re
```

Best of both worlds?
