### ISSUE TITLE
Format nested string quotes

### ISSUE THREAD

**Issue by TomFryers** [psf/black#2827] opened 2022-01-29 21:38 UTC
**Is your feature request related to a problem? Please describe.**

Currently, Black (even with `--preview`) won’t do anything to the following code
```python
f'N is {things["N"]}'
f"N is {things['N']}"
```

**Describe the solution you'd like**

It would be nice to be able to format these two expressions in the same way. 

**Describe alternatives you've considered**

The obvious question is which one to choose, but I think it’s clear that the latter is more natural considering Black’s current style.

**Additional context**

* Perhaps this should be under `--preview`.
* Triple-quoted strings have a similar problem, but they are much rarer.

**Comment by JelleZijlstra** [comment] 2022-01-29 21:39
Duplicate of #567

**Closed by JelleZijlstra** 2022-01-29 21:39 UTC
Labels: T: enhancement
