### ISSUE TITLE
INTERNAL ERROR: Black produced invalid code: invalid syntax (<unknown>, line 37)

### ISSUE THREAD

**Issue by traditio** [psf/black#2030] opened 2021-03-09 23:55 UTC
Black daemon throws an internal error on the following file.
Error: INTERNAL ERROR: Black produced invalid code: invalid syntax (`<unknown>`, line 37)

- Version: black, version 20.8b1
- OS Windows
- Conda environment: conda version : 4.9.2
- Python verison: 3.8.5.final.0

Log file content:
```
  File "c:\tools\miniconda3\envs\tools\lib\site-packages\black\__init__.py", line 6141, in assert_equivalent
    dst_ast = parse_ast(dst)
  File "c:\tools\miniconda3\envs\tools\lib\site-packages\black\__init__.py", line 6052, in parse_ast
    return ast27.parse(src)
  File "c:\tools\miniconda3\envs\tools\lib\site-packages\typed_ast\ast27.py", line 50, in parse
    return _ast27.parse(source, filename, mode)
import unittest
from polymer.core.exceptions import short_callstack


def _failing_test_method():
    num = 5 / 0


class FormatExceptionsTest(unittest.TestCase):
    def test_short_callstack(self):
        try:
            _failing_test_method()
            self.fail("Not expected to pass")
        except Exception as exc:
            self.assertRegexpMatches(short_callstack(exc), "test_exceptions_format.py:\d,_failing_test_method,num = 5 / 0$")

        try:
            self._failing_test_method()
            self.fail("Not expected to pass")
        except Exception as exc:
            self.assertRegexpMatches(short_callstack(exc), "test_exceptions_format.py:\d+,_failing_test_method,num = 5 / 0$")

        try:
            # keep multiline for test purpose
            num = 5 / 0
            self.fail("Not expected to pass")
        except Exception as exc:
            self.assertRegexpMatches(short_callstack(exc), "test_exceptions_format.py:2\d+,test_short_callstack,0$")

    def test_short_callstack_multiline(self):
        try:
            # keep multiline for test purpose
            # fmt: off
            num = 5 /\
                  0
            self.fail("Not expected to pass")
            except Exception as exc:
                self.assertRegexpMatches(short_callstack(exc), "test_exceptions_format.py:2\d+,test_short_callstack,0$")

        def _failing_test_method(self):
            num = 5 / 0
```

**Comment by JelleZijlstra** [comment] 2021-03-09 23:59
Could you share the initial contents of the file?

**Comment by traditio** [comment] 2021-03-10 00:10
It shared in the bug description under "log file content"
Also the issue reproduces on shorter file:
```
class Test():
    def test(self):
        try:
            # keep multiline for test purpose
            # fmt: off
            num = 5 /\
                  0
        except Exception as exc:
            pass

```


command line output:
```
$ black --version
black, version 20.8b1

$ black test.py
error: cannot format test.py: INTERNAL ERROR: Black produced invalid code: invalid syntax (<unknown>, line 8). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: C:\Users\dmipatra\AppData\Local\Temp\blk_wf6xwmwy.log
Oh no! � � �
1 file failed to reformat.
```
```

**Comment by JelleZijlstra** [comment] 2021-03-10 00:13
Thanks, I think the log file shows Black's output, not input. The issue is that there is no `# fmt: on` to match the `fmt: off`; the documentation (https://github.com/psf/black#the-black-code-style) specifies that they have to both be present at the same level of indentation. I suppose ideally we still shouldn't crash.

**Comment by ichard26** [comment] 2021-03-10 01:06
This is another case of #569. [Proof from the Black Playground](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEnAKddAD2IimZxl1N_WlXnON2nzOXxnCQE38O8a34eAxKfeNpXgL42WMyz9mMdK-dkeMyN3FZy_nL9aDPsjoD9oHPlHW1q67AL37E-o9CqGUZMR02G6X03GHM9JQbcZoY4eVmEu-S0lR6ytuq2PIOsJgrGpq30QeMJnoqbyTTekKonEjj13LfnC8emzbSHbhgNAx_ZRTYU8e4Wx1E2WPoZQ61Fh1yd0rp3w0oAAAC4yyyx1zJwdwABwwGoAgAA83QS4rHEZ_sCAAAAAARZWg==)

**Comment by JelleZijlstra** [comment] 2021-05-30 02:35
Closing as a duplicate of #569.

**Closed by JelleZijlstra** 2021-05-30 02:35 UTC
Labels: C: invalid code, T: bug
