### ISSUE TITLE
Wildcards don't work on Windows

### ISSUE THREAD

**Issue by asweigart** [psf/black#1198] opened 2019-12-10 01:53 UTC
**Describe the bug** A clear and concise description of what the bug is.

Running black with wildcards doesn't work on Windows (specifically Python 3.7, Black 19.10b0, Windows 10)

**To Reproduce** Steps to reproduce the behavior:

Run `black *.py` on Windows and you'll get the error:

C:\Users\Al\Desktop>black *.py
Usage: black [OPTIONS] [SRC]...

Error: Invalid value for "src": Path "*.py" does not exist.

This error also appears if you run `black *`. I believe that Command Prompt (and also PowerShell) isn't expanding the wildcard the same way as it does on Linux. Running `black .` will correctly format all the files in the current working directory and all subdirectories.

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: Black 19.10b0
- OS and Python version: Windows 10, Python 3.7

**Does this bug also happen on master?** To answer this, you have two options:

Yes, this happens on the master branch that I checked out on 2019/12/09.

**Comment by mk-pmb** [comment] 2019-12-10 15:51
This looks like a shell bug, not one in black. When you invoke `black *.py` without quotes, the wildcard is usually resolved by the shell. Which shell did you use? If just the regular windows command line, try using a windows build of zsh or bash.

**Comment by zsol** [comment] 2019-12-10 18:59
Yep, this is not a bug in Black. If you're in powershell, you can do this instead: `black @(get-childitem -name *.py)`

**Closed by zsol** 2019-12-10 18:59 UTC
Labels: bug

**Comment by asweigart** [comment] 2019-12-10 21:41
Ah, this looks like a bug in the Click package. I'll file a bug with them.
