### ISSUE TITLE
Not formatting long string length

### ISSUE THREAD

**Issue by sandasdotpack** [psf/black#955] opened 2019-08-01 11:03 UTC
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system:
Python version:3.6.8
*Black* version:19.3b0
Does also happen on master: Yes

I have an issue that black is not formating string length on the line 34

https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AkOAx9dAD2IimZxl1N_Wg094ywRrUwpW2pZmc2PAj2q4kRQNbeBtOACQBLSERqJb1YhigIu8qKscf18jpL0L0M_vWeRwlca8_Yhk2-VqPNVvszmCGTy6uF3vTgqcOsLaYPieOyPd-SrURSJy6pnBVxk9i-AXYb5qMhH5YAID0VTwBJ4-suTbpqDDslUTcRqSpAxJTLVK_mUbaKJ6FeQducIEqduWmdX1JjwxZFulb4Gqpu7yu9DiSJ5FukG9iH610NROZdDrfeySRBNxgN8-y03hkVaatco-UyaaQHVkq2uiVWTkRhBGsMEMiVKYMUevCn3H4lG_v8ADRXOepDEsKmX6xT1a9BZyKQacnHAQBEc307EmG2qvCwRnFdEskZtaxrNidnqwUVcKNnL_7aMgGWxyuABGpm86yNKhjzYZEBeesmYJDSM5Ke7mdrg7KPCCd4T_FvhD0akihPgqQOeC2TKyR48TVSDhRnvfGo3wIQ5Yr_AbzVarcs2Ut2AeB9DJLkmhphE70Zux5p7zSvf4HYb_h5yP0Olr240XPUj6Nx_xQiKEyVQE3QXpClJyaG292jP4c4VQxa1hZm9Sb5z28-Q7mUU4fVPqCgFAvdSzznWemD2cqyrKrXRqH2bE5sieAS0ndras7Uym-uZy6KLfhKY49TuCKa7DS1fuEtrXoAg6vTuqKZyTdeeXuDWNT2ZVSzrSn8fSZXDvnWSVcVHo4ynoHqOTmHwNnd8isBC50CTZKFyoFmdvzuOMrL9MrREOsk4f2M43kdQeIFyzKQiDIBc4WpMYeydFzVs3-WcLqXP1L4L8itjRj-NYounGznwY44md_1VQfKoQnkATelpGfTfkRpe-hzsBtdK_kgl4pGBd3NqDAVghvZkRmLsY0p3L-YZdXmNrPIGWC2mpIDwh2pX2NJHQGOjcI1e7-OUMxLI6VQKpMugkNBhvsVQrGRP_Q4xb8fRUZ-p3xkXoVcoVUM5-kz2iJvXCozdV_lyviTNuriVWVDt3FwIcZ9Zod3idH95sQ6fBI2q7A3mxB7-m8sOGITG2h_6sDlci-ROfgFoWQRWewAAAFKdVOr0c459AAG7Bo8SAAC4E4CWscRn-wIAAAAABFla

**Comment by zsol** [comment] 2019-08-02 18:45
Black doesn't currently break strings apart to make them shorter.

Duplicate of #182

**Closed by zsol** 2019-08-02 18:45 UTC
