### ISSUE TITLE
Put imports to correct order based on PEP8

### ISSUE THREAD

**Issue by milanbalazs** [psf/black#2088] opened 2021-04-06 13:04 UTC
It would be nice if `Black` would be able to order the imports based on `PEP8` (At least the "standard" library imports). Alphabetically sorted modules are quicker to read and searchable.

[Import section of PEP8](https://www.python.org/dev/peps/pep-0008/#imports)

After Black formatting the Python Linter can give `wrong-import-order` warning.

**Python Linter earning example:**

    test.py:22:0: C0411: standard import "import json" should be placed before "import requests" (wrong-import-order)
    test.py:23:0: C0411: standard import "import re" should be placed before "import requests" (wrong-import-order)

**Formatting example:**

Before `Black`:

    import request
    import json

After `Black`:

    import json
    import request

I think something similar like `Isort` solution would be very helpful in `Black`: https://pycqa.github.io/isort/

**Comment by ichard26** [comment] 2021-04-06 13:16
I'd rather not have the added complexity of import handling (which btw isn't so clear cut!) in Black (especially as Black aims to not break your code). isort has this profiles feature since version 5 and higher, and it's awesome (`isort --profile black`). The isort project is also mature, so I don't see the need for import handling when the existing tool works well alone and with Black.

**Comment by milanbalazs** [comment] 2021-04-06 13:46
I got your point but honestly I don't agree with you totally. If I want to format my code that way it can be compatible with PEP8, I have to use 2 different tools.

**For example:**

    isort --profile black my-package  # Formatting only my imports
    black --check --diff my-package  # Formatting my code (w/ imports)

A similar solution is mentioned on the official site (For `travis` integration): 
 - https://pycqa.github.io/isort/docs/configuration/black_compatibility/

I think it would be nice to do with one tool (with `Black`).

**Comment by JelleZijlstra** [comment] 2021-04-06 14:10
Duplicate of #333

**Closed by JelleZijlstra** 2021-04-06 14:10 UTC
Labels: enhancement

**Comment by adam-grant-hendry** [comment] 2022-04-07 15:42
In some cases, modules must be imported in a specific order. e.g. `setuptools` must be imported before `Cython` when creating an extension module since `setuptools` monkeypatches the `distutils.core.Extension` class. If `Cython` is imported first, the list of Extensions returned by `cythonize` will have a type that doesn't match that used by `setuptools` when it [checks Extension lists](https://github.com/python/cpython/blob/a43fd45918cef48187053d7c56d3b9bb902151d0/Lib/distutils/command/build_ext.py#L342).

Granted (arguably), this is the kind of thing that should be overridable in a configuration file, or similar, to `isort` or `black`, and I would count this as an ugly hack required to get running code that should be fixed in Cython ([it breaks the heart of modules as a language feature being compiled independently of translation units and not depending on import order](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-170)).

However, I agree with @ichard26:

> Black aims to not break your code

If you have a "sort on save" set in your editor, this can be the kind of thing that breaks your code/causes tests to fail right before a check in and is easy to miss.
