### ISSUE TITLE
vim shows error after executing Black

### ISSUE THREAD

**Issue by mrassili** [psf/black#730] opened 2019-03-03 00:13 UTC
Hi,

I installed Black as a vim plugin and it outputs errors whenever I execute `:Black` (formatting is applied) it's annoying! how can I hide those errors? ("error detected while processing bufwrite") see screenshots

I have this command on my .vimrc
`autocmd BufWritePre *.py execute ':Black'`

![screen shot 2019-03-03 at 1 10 16 am](https://user-images.githubusercontent.com/25288435/53689220-d7dc7600-3d48-11e9-9434-0a73eb0d3db7.png)

![screen shot 2019-03-03 at 1 00 37 am](https://user-images.githubusercontent.com/25288435/53689175-736ce700-3d47-11e9-9c8d-5bbb6c32a760.png)

Operating system: Ubuntu 18.04
Python version: 3.6.7
*Black* version: latest (not sure just installed the latest vim plugin from github)

**Comment by gsong** [comment] 2019-03-15 23:21
For those looking for a workaround for now:

> If you need to do anything special to make your virtualenv work and install Black (for example you want to run a version from master), create a virtualenv manually and point g:black_virtualenv to it. The plugin will use it.

Just install `black==18.9b0` for now.

Duplicate of #755.

**Closed** 2020-03-04 21:48 UTC
Labels: integrations
