### ISSUE TITLE
Don't insert extra blank lines at the start of an indent

### ISSUE THREAD

**Issue by Rizhiy** [psf/black#3089] opened 2022-05-27 13:59 UTC
**Describe the style change**

If a function/class is defined at the start of a non-scoping indent (e.g. `if`, `for`) a blank line is inserted before the function.
I would like this removed, since:
* If an indent is scoping (e.g. `def`, `class`) no blank line is inserted and I would prefer if style was consistent.
* I believe this is redundant since the indent already separates the function/class definition well enough.

**Examples in the current _Black_ style**

```python
# No blank lines
def f():
    def g():
        pass


class A:
    def g():
        pass


# Blank lines
for _ in range(10):

    def g():
        pass


if True:

    def g():
        pass
```

**Desired style**

```python
# No blank lines
def f():
    def g():
        pass


class A:
    def g():
        pass


# Also, no blank lines
for _ in range(10):
    def g():
        pass


if True:
    def g():
        pass
```

**Additional context**

The issue came up when my team was developing a tool to remove blank lines at the start of indents, would be cool if black autocorrected that as well.

**Comment by felix-hilden** [comment] 2022-05-30 07:37
Thanks for submitting! We've pretty much agreed that this is wanted, and it's already implemented in #3035 (which started as a fix to #902). I'll link this issue as a closing target there.

**Comment by Rizhiy** [comment] 2022-05-30 14:00
@felix-hilden I just checked #3035 and it doesn't work for my case.
Please note that my case specifically talks about function/class definition inside a block.

I believe there is another format rule which enforces one black line before function/class declaration and there is a conflict as a result.

**Comment by JelleZijlstra** [comment] 2023-04-29 01:24
Duplicate of #450

**Closed by JelleZijlstra** 2023-04-29 01:24 UTC
Labels: T: style, F: empty lines
