### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by rrobby86** [psf/black#1856] opened 2020-12-02 10:14 UTC
**Describe the bug** Black raised error in title and asked to report.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file 'buggy.py' (obscured names and strings from original file, but both of them raise the bug)
```
from xxx.yyy.zzz import foo_bar


def test_one_thing(some_fixture):
    assert foo_bar(some_fixture, {"key1": "value1", "key2": "value2", "key3": "value3", "key4": "value4"}) == {"value1"}


def test_another_thing(some_fixture):
    assert foo_bar(some_fixture, {"key1": "value1", "key2": "value2", "key3": "value3", "key4": "value4"}) == {"value1"}
```
2. Run `black buggy.py`
3. See error

**Expected behavior** File formatted without errors

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Linux/Python 3.8.3

**Does this bug also happen on master?** Yes (tested on online formatter)

**Additional context**

Generated log file: [blk_q1lct_78.log](https://github.com/psf/black/files/5628483/blk_q1lct_78.log)

**Comment by wjdp** [comment] 2020-12-08 12:28
Getting very similar, can reproduce with the following:

```python
class Test:
    def test_thing(self):
        assert (
            module.get_thing(
                arg_1=self.get_another_thing("LONGLONGLONGLONGLONGLONGLONGLONGLONG"),
                arg_2=Decimal(5)
            ) == (Decimal('1.50'), None)
        )
```

The diff

```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -1,8 +1,6 @@
 class Test:
     def test_thing(self):
-        assert (
-            module.get_thing(
-                arg_1=self.get_another_thing("LONGLONGLONGLONGLONGLONGLONGLONGLONG"),
-                arg_2=Decimal(5)
-            ) == (Decimal('1.50'), None)
-        )
+        assert module.get_thing(
+            arg_1=self.get_another_thing("LONGLONGLONGLONGLONGLONGLONGLONGLONG"),
+            arg_2=Decimal(5),
+        ) == (Decimal("1.50"), None)
--- first pass
+++ second pass
@@ -1,6 +1,9 @@
 class Test:
     def test_thing(self):
-        assert module.get_thing(
-            arg_1=self.get_another_thing("LONGLONGLONGLONGLONGLONGLONGLONGLONG"),
-            arg_2=Decimal(5),
-        ) == (Decimal("1.50"), None)
+        assert (
+            module.get_thing(
+                arg_1=self.get_another_thing("LONGLONGLONGLONGLONGLONGLONGLONGLONG"),
+                arg_2=Decimal(5),
+            )
+            == (Decimal("1.50"), None)
+        )
```

**Environment (please complete the following information):**

-    Version: 20.8b1
-    OS and Python version: Linux/Python 3.8.0

**Comment by wjdp** [comment] 2021-03-10 17:48
Have checked this again against the master branch as I see there's not been a release since last summer. Issue still present.

**Comment by ichard26** [comment] 2021-04-25 20:07
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:07 UTC
Labels: bug, duplicate, unstable formatting
