### ISSUE TITLE
Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by Debakel** [psf/black#1993] opened 2021-02-18 23:14 UTC
**Describe the bug:** When formatting [this](https://gist.github.com/Debakel/637ef714fea9375191ba7ff6e500d62a) file an error occurs:

```
error: cannot format test_compliance_check/test_fetch_target_rights.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/jd/wpwhg6ls5cbc_007sjkzn08h0000gn/T/blk_gmoo7yei.log
```

**To Reproduce** Steps to reproduce the behavior:

1. Take [this](https://gist.github.com/Debakel/637ef714fea9375191ba7ff6e500d62a) file
2. Run _Black_ on it
2. Error; See above

**Expected behavior**   
Black should successfully format the file.

**Environment (please complete the following information):**

- Version: master

**Does this bug also happen on master?** Yes.

**Comment by mvolfik** [comment] 2021-02-22 17:19
Likely a duplicate of #1629 , as this file works after applying #1958

**Comment by ichard26** [comment] 2021-04-25 20:18
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:18 UTC
Labels: bug, duplicate, unstable formatting
