### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter

### ISSUE THREAD

**Issue by semajson** [psf/black#1852] opened 2020-12-01 17:29 UTC
**Describe the bug** When running black over the following code:
```
class Schema(object):
    def __init__(self):
        self.long_name = "test"
        self.vendor_id = "test"
        self.avp_code = "test"
        self.syntax = "test"
        self.must_flags = "test"
        self.must_not_flags = "test"
        self.short_name = "test"

    def __repr__(self):
        return "Base(long_name=%s, avp_code=%s, vendor_id=%s, syntax=%s, must_flags=0x%2.2x, must_not_flags=0x%2.2x, short_name=%s)" % \
               (repr(self.long_name),
                self.avp_code,
                self.vendor_id,
                repr(self.syntax),
                self.must_flags,
                self.must_not_flags,
                repr(self.short_name))```
```
The error `INTERNAL ERROR: Black produced different code on the second pass of the formatter` is reported

**To Reproduce** Run black over code snippet posted above

**Expected behavior** Black formats the file without error

**Environment :**

- Version: 20.8b1
- OS and Python version: Centos 7 / Python 2.7.5 (this might be a python 2 specific issue, I'm unsure)

**Does this bug also happen on master?** Yes, it repos on https://black.now.sh/?version=master

**Additional context** Output of the of the diff file:
```
Mode(target_versions=set(), line_length=88, string_normalization=True, experimental_string_processing=False, is_pyi=False)
--- source
+++ first pass
@@ -7,13 +7,17 @@
         self.must_flags = "test"
         self.must_not_flags = "test"
         self.short_name = "test"
 
     def __repr__(self):
-        return "Base(long_name=%s, avp_code=%s, vendor_id=%s, syntax=%s, must_flags=0x%2.2x, must_not_flags=0x%2.2x, short_name=%s)" % \
-               (repr(self.long_name),
+        return (
+            "Base(long_name=%s, avp_code=%s, vendor_id=%s, syntax=%s, must_flags=0x%2.2x, must_not_flags=0x%2.2x, short_name=%s)"
+            % (
+                repr(self.long_name),
                 self.avp_code,
                 self.vendor_id,
                 repr(self.syntax),
                 self.must_flags,
                 self.must_not_flags,
-                repr(self.short_name))
+                repr(self.short_name),
+            )
+        )
--- first pass
+++ second pass
@@ -7,17 +7,14 @@
         self.must_flags = "test"
         self.must_not_flags = "test"
         self.short_name = "test"
 
     def __repr__(self):
-        return (
-            "Base(long_name=%s, avp_code=%s, vendor_id=%s, syntax=%s, must_flags=0x%2.2x, must_not_flags=0x%2.2x, short_name=%s)"
-            % (
-                repr(self.long_name),
-                self.avp_code,
-                self.vendor_id,
-                repr(self.syntax),
-                self.must_flags,
-                self.must_not_flags,
-                repr(self.short_name),
-            )
+        return "Base(long_name=%s, avp_code=%s, vendor_id=%s, syntax=%s, must_flags=0x%2.2x, must_not_flags=0x%2.2x, short_name=%s)" % (
+            repr(self.long_name),
+            self.avp_code,
+            self.vendor_id,
+            repr(self.syntax),
+            self.must_flags,
+            self.must_not_flags,
+            repr(self.short_name),
         )
```

**Comment by ichard26** [comment] 2021-04-25 20:13
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 20:13 UTC
Labels: bug, duplicate, unstable formatting
