### ISSUE TITLE
f-string with internal same-quote expression

### ISSUE THREAD

**Issue by quittle** [psf/black#4138] opened 2023-12-31 17:39 UTC
Verified with https://black.vercel.app/?version=main

**Describe the bug**

Black fails to parse format strings (f-strings) where an express

**To Reproduce**

Default black settings with either of these

```python
f"{""}"
```
**Error**
> cannot use --safe with this file; failed to parse source file AST: f-string: expecting '}' (<unknown>, line 1)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.

```python
f"{'"'}"
```
**Error**
> Cannot parse: 1:5: f"{'"'}"

```python
f'''{'''"""'''}'''
```
**Error**
> Cannot parse: 1:8: EOF in multi-line string

**Expected behavior**

The code can be parsed successfully, just as Python `3.10`, `3.11`, and `3.12` can successfully evaluate the code.

**Environment**

- Black's version: `main` and `23.10.1`
- OS and Python version: Python `3.10`, `3.11`, and `3.12` on `Ubuntu 22.04.2` in **WSL**

**Additional context**

Using `f"""{""}"""` works fine so long as the triple quotes aren't present internally.

**Comment by hauntsaninja** [comment] 2023-12-31 21:47
Thanks, duplicate of https://github.com/psf/black/issues/3746

**Closed by hauntsaninja** 2023-12-31 21:47 UTC
Labels: T: bug
