### ISSUE TITLE
Black could not format file

### ISSUE THREAD

**Issue by lissom** [psf/black#2497] opened 2021-09-17 12:51 UTC
error: cannot format black_src_error2.py: INTERNAL ERROR: Black produced code that is not equivalent to the source on pass 1.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: black_error2.log

black --line-length 130

black 21.9b0

Linux/Python 3.7.10
[black_error2.log](https://github.com/psf/black/files/7185739/black_error2.log)

[black_src_error2.zip](https://github.com/psf/black/files/7185745/black_src_error2.zip)

**Comment by ichard26** [comment] 2021-09-19 17:04
Hello! This is actually an issue we are already aware of: #569. The gist of it is that Black really misbehaves when an indented fmt: off comment's scope continues even after the indentation is gone. There seem to a minor mix-up in your code that triggers this:
```python
    @staticmethod
    def add_args(parser):
        # fmt: on
        parser.add_argument('--log-group-name', required=True, type=str, help='The cluster config field to pull the AWS log group name from')
        parser.add_argument('--log-stream-name', default=get_instance_id(), type=str, help='The AWS log stream name, defaults to the instance id')
        parser.add_argument('--watch-path', required=True, type=str, help='The directory with files to monitor')
        parser.add_argument('--suffix', default='.log', type=str, help='Only monitor files with this suffix.  Defaults to .log; default python rotation is x.{1,2,3...}')
        parser.add_argument('--log-sent-lines', default=False, action='store_true', help='Log lines sent to aws')
        # fmt: off
```
Obviously it would be better if Black didn't mess up the indentation in this situation but we haven't gotten around to that yet. I'll be closing this issue as this is a duplicate of #569. Thanks for the report and my apologies Black didn't work right for you!

**Closed by ichard26** 2021-09-19 17:04 UTC
Labels: T: bug, R: duplicate, C: invalid code, F: fmtoff
