### ISSUE TITLE
Multi line if clauses

### ISSUE THREAD

**Issue by Quappas** [psf/black#2599] opened 2021-11-10 16:59 UTC
**Describe the style change**

I write python modules that are configured by .yml files which look something like this:
```
Category_X:
  Subcategory_Y:
    Enable_Condition_Z: true
```
After reading them in, they are addressed like a nested dictionary (see below). Then I write `if` clauses that check if a condition is to be checked `and` if the condition is fulfilled. Black messes that up a bit.

**Examples in the current _Black_ style**

```python
def black_if_test():
    if complicated_settings_dict["Category_X"]["Subcategory_Y"][
        "Enable_Condition_Z"
    ] and fullfills_condition_Z(my_object):
        work()

    if complicated_settings_dict["Category_X"] and True not in important_function(
        some_long_argument, some_other_longer_argument
    ):
        work()
```

**Desired style**

```python
def black_if_test():
    if (
        complicated_settings_dict["Category_X"]["Subcategory_Y"]["Enable_Condition_Z"]
        and fullfills_condition_Z(my_object)
    ):
        work()
```

**Additional context**

Note that the line `        complicated_settings_dict["Category_X"]["Subcategory_Y"]["Enable_Condition_Z"]` is only 86 characters long. I think black only wants to break it, because it wants to put the `and` on the same line. Putting the `and` on the next line (as for all binary operators) would make everything more readable in my opinion. In any case there is no reason here not to keep each condition I am checking for in its own single separate line.

**Comment by felix-hilden** [comment] 2021-11-10 17:08
Hi, this is a duplicate of #2156, so let's continue the discussion there!

**Closed by felix-hilden** 2021-11-10 17:08 UTC
Labels: T: design
