### ISSUE TITLE
trailing space after parenthesized walrus operator

### ISSUE THREAD

**Issue by xrisk** [psf/black#1522] opened 2020-06-26 12:55 UTC
Consider this snippet (as produced after running Black):

```
if (val := func()) :
    pass
```

Ideally, Black would remove the redundant parentheses (although I realize this is pretty hard to do). 

However, why does Black insist on the single space before the terminating colon? This causes flake8 to complain (and rightly so I feel).

I skimmed through the [PEP](https://www.python.org/dev/peps/pep-0572/#syntax-and-semantics) and I can’t seem to find any example where that space is used. Is this a deliberate design decision?

**Comment by xrisk** [comment] 2020-06-26 13:04
On closer reading through the PEP, I don’t see why (val := expr) shouldn’t be transformed into val := expr as they are equivalent as far as I can tell (in the context of an if-conditional). The only cases where that transformation is not valid are in top-level statements and such.

**Comment by JelleZijlstra** [comment] 2020-06-28 02:38
We definitely shouldn't put a space before the colon, that's a bug.

I'm not as sure we should remove the parentheses, maybe it's better for clarity to have them? Black is opinionated, but we should make sure we're opinionated in the right way.

**Comment by xrisk** [comment] 2020-06-28 10:31
@JelleZijlstra black does convert `if (expr):` to `if expr` so...

**Comment by nixjdm** [comment] 2020-08-15 18:00
The title of this issue, which I'd take as the primary point of this issue, is a duplicate of #1174. I suggest closing this issue as a duplicate and opening a new issue just for discussing whether assignment expressions in ifs should be contained in parentheses.

**Comment by ichard26** [comment] 2020-08-29 23:47
> The title of this issue, which I'd take as the primary point of this issue, is a duplicate of #1174. I suggest closing this issue as a duplicate and opening a new issue just for discussing whether assignment expressions in ifs should be contained in parentheses.

I agree and I've done that (see #1656). Thanks!

**Closed by ichard26** 2020-08-29 23:47 UTC
Labels: bug, duplicate
