### ISSUE TITLE
line-break on conditional assignment

### ISSUE THREAD

**Issue by LucidOne** [psf/black#1050] opened 2019-10-08 21:11 UTC
This is how I want my code to look
```python
_cfg_dir = (_os.environ.get('RYO_USER_CONFIG_DIR')
            or _appdirs.user_config_dir('ryo-iso', 'HxR'))
```

and I'm OK with something like
```python
_cfg_dir = (
    _os.environ.get('RYO_USER_CONFIG_DIR')
    or _appdirs.user_config_dir('ryo-iso', 'HxR')
)
```

but this is how `black` wants my code to look
```python
_cfg_dir = _os.environ.get(
    "RYO_USER_CONFIG_DIR"
) or _appdirs.user_config_dir("ryo-iso", "HxR")
```

:man_shrugging: 

Operating system:
Python version: 3.6.8
*Black* version: 19.3b0
Does also happen on master: yes

**Comment by felix-hilden** [comment] 2022-02-01 18:19
I'll close this as a duplicate of #2156.

**Closed by felix-hilden** 2022-02-01 18:19 UTC
Labels: R: duplicate, T: design, F: linebreak
