### ISSUE TITLE
long subscript expressions

### ISSUE THREAD

**Issue by kmulka-medigo** [psf/black#1965] opened 2021-02-04 22:04 UTC
**Describe the style change**

It doesn't make sense to me that a dictionary key should go on its own line. There should be a different way to format what is below to improve readability.

**Examples in the current _Black_ style**

```python
blah = blahaoeuuisndthaoheinthoaeusnthaoeusnhoeausthnoeusnthtsthnoaeustnh["blah"][
    "blah"
]
```

**Desired style**

```python
blah = (
    blahaoeuuisndthaoheinthoaeusnthaoeusnhoeausthnoeusnthtsthnoaeustnh["blah"]["blah"]
)
```

**Additional context** Add any other context about the problem here.

**Comment by ichard26** [comment] 2021-05-30 03:42
While the duplication in this area is absolutely ridiculous, I'll be closing this as a duplicate of https://github.com/psf/black/issues/1280.

**Closed by ichard26** 2021-05-30 03:42 UTC
Labels: R: duplicate, T: design
