### ISSUE TITLE
frozenset defined inline isn't formatted by black (gives error)

### ISSUE THREAD

**Issue by SamuelMarks** [psf/black#1821] opened 2020-11-14 11:33 UTC
**Describe the bug**
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

**To Reproduce**
```py
import typing
from itertools import chain

BUILTIN_TYPES = frozenset(chain.from_iterable(map(lambda s: (s, 'typing.{}'.format(s), '_extensions.{}'.format(s)),
                          filter(lambda s: s[0].isupper() and not s.isupper(), dir(typing))))
                          ) | frozenset(("int", "float", "str", "dict", "list", "tuple"))

print("BUILTIN_TYPES:", BUILTIN_TYPES, ";")
```

**Expected behavior** A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Python 3.9.0rc1

**Does this bug also happen on master?** 
Yes

https://black.now.sh/?version=master,&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AHpARNdAD2IimZxl1N_WlwxRhR7MSgFUcTLI8hN1VTiqSc6I8LAH6EHQRd_DW_FQ2Acs-7eyVLlLqFlJY97xcFQgMNqfMsPfyRA1tn2uZK4G_SB8EnPLudh36ydjJATZhNupmrJeBpMdTR7wxNc4GXb15gSBMp0wzRXkGxp_T6u_4293hZIp4O0xyaUEyZf5SW3ykrFzUvsza9kFN8ODCBiMfmAEXkeYI0l4QxWOvrrkYq4CjwPQEy2pIAm528m5HXb4GrtveyIAqNqBQQZ180J1MX5Nl73Tz_YprfV_LP97eWOY8teby2-QIdDYG7smuPqV5e1VSf_X6Ts08wojl1P041mtP8bxtW6mNQVs5hjqn-w7akYZzYXAADui1ofwGDjWwABrwLqAwAAgztb6rHEZ_sCAAAAAARZWg==

**Additional context**

**Comment by ichard26** [comment] 2021-04-25 19:45
Hello!

All reproduction cases in this issue format without error on master. The fixing commit was 8672af35f052a636545e38110f0419ea92aeca0f from PR GH-2126.  I'll be marking this issue as a duplicate of GH-1629 since that's what GH-2126 aimed to fix and it's highly likely this issue falls under GH-1629.

Since we use the issue tracker as a reflection of what's on master, I'll be closing this issue. If you have any issues, especially with the new (but stable) output, please open a new issue. Oh and the fix should be available in a published release soon, see GH-2125 for more info. 

Thank you for reporting!

**Closed by ichard26** 2021-04-25 19:45 UTC
Labels: bug, duplicate, unstable formatting
