### ISSUE TITLE
Sort `import` statements in lexicographical order

### ISSUE THREAD

**Issue by aryanpingle** [psf/black#4260] opened 2024-02-28 23:40 UTC
Currently, Black doesn't affect the order of import statements (or the order of their imported objects). I'll be surprised if this hasn't been brought up already, because it would highly improve the reproducibility of the the formatter. Plus, having imports in a sorted way lets you go through them faster (and is generally easier to read). There are a couple of potential problems though, and I've listed them at the end of this request.

Here's the rules (examples given below):

1. Imports will be rearranged within groups of discovery, separated by non-import statement lines of code
2. Imports are sorted in ascending lexicographical order of the module name
3. Relative imports are placed after all absolute imports, with a newline separating them
4. Within each import, the imported objects are positioned in ascending lexicographical order of the object's original name
5. Comments placed before an import statement or in the same line will be treated as part of the statement, (to preserve the link between the comment and the import statement)
6. As always, the user can prevent shuffling of imports by placing them in blocks within `# fmt: off` and `# fmt: on`

## Rule 1 (& 2)

Original code:

```python
import module_b
import module_a

a = 0 # non import statement

import module_d
import module_c
```

After formatting:

```python
import module_a
import module_b

a = 0 # non import statement

import module_c
import module_d
```

## Rule 3

Original code:

```python
import module_c # absolute import (local module in the same dir)
from .module_a import x # relative import
from ..module_c import y # relative import
import module_b # absolute import (global module)
```

After formatting:

```python
import module_b # absolute import (global module)
import module_c # absolute import (local module in the same dir)

from .module_a import x # relative import

from ..module_c import y # relative import
```

## Rule 4

Original code:

```python
from module import dog, apple as Z, cat, ball
```

After formatting:

```python
from module import apple as Z, ball, cat, dog
```

## Rule 5

Original code:

```python
import module_b
# Here's the reason we're importing module_a
# blah blah
import module_a # inline comment
```

After formatting:

```python
# Here's the reason we're importing module_a
# blah blah
import module_a # inline comment
import module_b
```

# Discussion

The most obvious potential issue with rearranging import statements is that it might affect the order of execution of the imported modules. If the user is aware of this, he can simply wrap it in `# fmt: off` and `# fmt: on`.

If the user isn't aware of this... Not much we can do, I'm afraid. In my opinion, codebases using Black are usually designed well enough that they consciously avoid putting executable statements in the top level of modules. There's the other issue of variable name collision, but that's not as serious as affecting the execution order.

Worst case, this could be a feature locked behind a flag. But I believe it's a good enough improvement to warrant being the default. It would be great if we can poll developers who use Black about what they feel.

**Comment by JelleZijlstra** [comment] 2024-02-28 23:44
Duplicate of #333.

We decided not to do this, for better or for worse. There are various other tools you can use to sort imports in conjunction with Black, e.g. Ruff, isort, or usort.

**Closed by JelleZijlstra** 2024-02-28 23:44 UTC
Labels: T: style

**Comment by aryanpingle** [comment] 2024-02-29 00:36
Ahh I see. I'll look into those, thanks.
