### ISSUE TITLE
A bug when replacing quote variations

### ISSUE THREAD

**Issue by Susexe** [psf/black#4309] opened 2024-04-13 21:35 UTC
**Describe the bug**

It fails on `.replace('"', "'")`.

**To Reproduce**

```import os

output_folder = "Output"
row = {'name': '"Sample Movie"'}

file_path = os.path.join(output_folder, f"{row['name'].replace('"', "'")}.md")
print(file_path)
```

And run it with these arguments:

```sh
$ black file.py
```

The resulting error is:

> INTERNAL ERROR: Black produced code that is not equivalent to the source.

**Environment**

- Black's version: 24.4.0
- OS and Python version: Windows/Python 3.12.3

**Additional context**

[blk_7gcnr_o1.log](https://github.com/psf/black/files/14968704/blk_7gcnr_o1.log)

**Comment by hauntsaninja** [comment] 2024-04-13 21:42
Duplicate of https://github.com/psf/black/issues/3746 (this is only valid syntax on Python 3.12 and newer)

**Closed by hauntsaninja** 2024-04-13 21:42 UTC
Labels: T: bug
