### ISSUE TITLE
black and isort incompatible with comments in import

### ISSUE THREAD

**Issue by tbicr** [psf/black#772] opened 2019-03-20 16:43 UTC
```
> black --safe -S --diff .

import time
 
 import numpy as np
 import pandas
 import scipy.sparse as sp
+
 # from sklearn.grid_search import GridSearchCV
 from sklearn.linear_model import ElasticNet, ElasticNetCV, enet_path
```

isort config:
```
[isort]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
line_length = 100
combine_as_imports = True
sections = FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
default_section = THIRDPARTY
```

Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 16.04.6 LTS
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.

**Comment by asfaltboy** [comment] 2019-04-02 08:30
I having the same issue, black adds a space before that commented out import, but isort does not like that space and removes it ... like so:
```
import time

import numpy as np
import pandas
import scipy.sparse as sp
# from sklearn.grid_search import GridSearchCV
from sklearn.linear_model import ElasticNet, ElasticNetCV, enet_path
```

**Comment by Sharadh** [comment] 2019-06-03 02:02
This seems to be a duplicate of an existing issue: https://github.com/python/black/issues/251

**Comment by ambv** [comment] 2020-03-04 11:13
Sharadh is right. Let's focus on #251 instead.

**Closed by ambv** 2020-03-04 11:13 UTC
Labels: enhancement
