### ISSUE TITLE
Newline added after `Path` `/`

### ISSUE THREAD

**Issue by davidgilbertson** [psf/black#3598] opened 2023-03-09 22:24 UTC
I have some code that uses one of a few different files. So I'm commenting out certain lines to switch between files.

But the combination of `Path`, `/`, and a commented out line results in incorrect behaviour.

Workaround is to put a comma at the end of the line.

**Black https://github.com/psf/black/commit/4a063a**

[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AD8AJddAD2IimZxl1N_WlsgJGL5Th9rwn0ffOInnwH3UJGLFUg2uan3GmixKnBQYx-AdWcO8Snc6t9fyRxi7osWyQvMCqTB5gOsgMZtgXPm95MxMH7b5i9hppj8y-0AuisslKbX3k9O0m_gLxCK0eOcu0qR79vksIjWYMuJYwb9vrtHr4peH0WCNxUAmxMuslgkfOmgSmA9Y0HREQAAAGph93sJtm4QAAGzAf0BAAD7OKUXscRn-wIAAAAABFla)

## Options

`--line-length=88`
`--safe`

## Input

```python
here = Path(__file__).parent

def get_file(path):
    pass

file = get_file(
    # here / "other_file_file.txt"
    here / "one_file.txt"
)
```

## Output

```python
here = Path(__file__).parent


def get_file(path):
    pass


file = get_file(
    # here / "other_file_file.txt"
    here
    / "one_file.txt"
)

```

## Expected

**Comment by JelleZijlstra** [comment] 2023-12-09 20:28
Duplicate of #4026 

(This issue is older but the newer one has a better diagnosis.)

**Closed by JelleZijlstra** 2023-12-09 20:28 UTC
Labels: F: linebreak
