### ISSUE TITLE
Black is not enforcing E: 501 

### ISSUE THREAD

**Issue by kunal5** [psf/black#1582] opened 2020-08-11 08:45 UTC
Below is my pyproject.toml file 
```
[tool.black]
target-version = ['py27']
line-length = 120
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
  | apps/core/migrations/0002_auto_20200707_1828.py
)
'''

```
Below is my .flake8 file
```
[flake8]
max-line-length = 120
```
**I have attached a screenshot of a dict in python**
<img width="1036" alt="Screenshot 2020-08-11 at 2 11 28 PM" src="https://user-images.githubusercontent.com/15965156/89876784-c5709800-dbdc-11ea-92c8-139887b1441a.png">

In the above image, line no 319 the line-length has exceeded the max length(120) given in the file. Black is not formatting this and flake8 is throwing error every time. Why is black not enforcing E: 501?
**You can see this in the error snapshot**
<img width="719" alt="Screenshot 2020-08-11 at 2 16 53 PM" src="https://user-images.githubusercontent.com/15965156/89877274-7c6d1380-dbdd-11ea-99a0-eeb935543839.png">

Black version is : 19.10b0
Python: 2.7

Please help!!
Thanks

**Comment by hugovk** [comment] 2020-08-11 09:17
What does that line 318 look like? Does it have a long string? Might be that Black couldn't make that line fit and you'll need to manually adjust it.

**Comment by kunal5** [comment] 2020-08-11 09:31
Please look at line 319... error message is showing line 318 because I deleted one line before taking a snapshot. Also, if I am placing the rest of the sentence after `:` in the next line then the black formatter is again formatting it and placing it on the same line

**Comment by hugovk** [comment] 2020-08-11 09:41
Ah right! One idea is to append `  # noqa: E501` to the line:

```python
thing = {
    a: a,
    looooooooooooooooooooooooooooooooooooooooooooooooooooong: looooooooooooooooooooooooooooooooooooooooooooooooooooong,  # noqa: E501
}
```

**Comment by kunal5** [comment] 2020-08-11 09:57
what I am currently doing is appending `fmt: off` and `fmt: on` between whom I don't want black to format. But is there a way that black show always respect `line-length` property as given in `pyproject.toml`. There are many instances in my project where when black is formatting it is not respecting `line-length=120` property. One more instance is 
**Ideal solution should be as given below in line 6001-6002**
<img width="910" alt="Screenshot 2020-08-11 at 3 21 00 PM" src="https://user-images.githubusercontent.com/15965156/89883928-76c7fb80-dbe6-11ea-91b1-2c729ed95e48.png">
**But, when I run black formatter, it is formatting the above file as given in line 6001-6002 which is again not following `line-length property` **
<img width="1033" alt="Screenshot 2020-08-11 at 3 23 42 PM" src="https://user-images.githubusercontent.com/15965156/89884180-cdcdd080-dbe6-11ea-8aa9-bdaa7b3d73d1.png">

This is happening at many places and I would not want to append `fmt: off` and `fmt: on` everywhere. Can I do anything different for fixing this issue

**Comment by JelleZijlstra** [comment] 2020-08-11 15:18
There are indeed certain patterns where Black is not able to fit lines in the desired line length, usually involving unreasonably long identifiers. We should fix such cases so that Black does obey the desired line length limit.

#620 and #510 are similar previous issues.

**Comment by JelleZijlstra** [comment] 2021-05-29 03:30
Going to call this a duplicate of #620.

**Closed by JelleZijlstra** 2021-05-29 03:30 UTC
Labels: T: bug
