### ISSUE TITLE
Replace f-strings with regular strings

### ISSUE THREAD

**Issue by KAction** [psf/black#3081] opened 2022-05-21 13:55 UTC
Often as result of refactoring I end up with f-string with no
`{substitutions}`, and my editor (integrated with flake8) keeps
reminding me about it.

With some stretch one can argue that this is actually formatting issue
and as such within scope of black(1). Would you be interested in patch
that implement this proposal?

```python
print(f"Hello")
```

to become

``` python
print("Hello")
```

**Comment by JelleZijlstra** [comment] 2022-05-21 13:58
Preview mode does this in some cases but not here. I agree that it's worthwhile, although it does change Python's AST.

**Comment by PBNMH22** [comment] 2022-05-21 15:16
Hi I am new to this, I was searching for this but the code base is huge. 
Request you to please navigate me to desired file or folder. 
I will try my best.

**Comment by KAction** [comment] 2022-05-21 15:30
I think it is as simple as dropping `drop_useless_fstring` conditional. I'd like to grab lock on this issue for coming 72 hours. I'll do my best to come with PR within this timeframe.

**Comment by SUDDSDUDDS** [comment] 2022-05-21 16:45
Hi ur happy est being with out no one knows

**Comment by JelleZijlstra** [comment] 2022-05-26 18:50
@graingert (responding to your comment on #3087, where I'd like the focus to stay on the broader propsal). This does change the AST:

```
>>> ast.dump(ast.parse('f"x"'))
"Module(body=[Expr(value=JoinedStr(values=[Constant(value='x')]))], type_ignores=[])"
>>> ast.dump(ast.parse('"x"'))
"Module(body=[Expr(value=Constant(value='x'))], type_ignores=[])"
```

**Comment by JelleZijlstra** [comment] 2022-05-28 03:14
Duplicate of #1156

**Closed by JelleZijlstra** 2022-05-28 03:14 UTC
Labels: F: strings / docstrings
