### ISSUE TITLE
Black Vim Error Formatting File: Error invoking `python_execute`

### ISSUE THREAD

**Issue by rollschild** [psf/black#1293] opened 2020-03-03 18:37 UTC
**Describe the bug** A clear and concise description of what the bug is.

When saving/formatting a python file via `:Black` in Vim, it produced the following error: 
```
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host): 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 92, in Black
  File "<string>", line 128, in get_configs
AttributeError: module 'black' has no attribute 'find_pyproject_toml'
```
**To Reproduce** Steps to reproduce the behavior:

1. Open up some python file, writing something, and leave insert mode
2. Type `:Black` and hit Enter to save
3. Produce the error above

**Expected behavior** 
Python code should be formatted without errors

**Environment (please complete the following information):**

- Version: 19.10b0
- OS and Python version: macOS 10.14.6 / Python 3.7.5

**Does this bug also happen on master?** To answer this, you have two options:
No I don't think so.
**Additional context** Add any other context about the problem here.

**Comment by duarteocarmo** [comment] 2020-03-04 09:54
Same here!

**Comment by BurnhamG** [comment] 2020-03-04 11:06
It looks like this function was added in #1273, so the Vim plugin was updated to call this function, while the installed package doesn't (yet) have this function. Looks like [this comment](https://github.com/psf/black/pull/1273#issuecomment-594114067) holds the current solution:


> You need to install black from sources instead of from PyPI, or downgrade the plugin to the last release. To upgrade black:
> 
> ```shell
> source ~/.vim/black/bin/activate  # make sure to install in the right venv
> pip install --upgrade git+https://github.com/psf/black.git
> ```
> 
> Would be nice if these kinds of breaks could be avoided in the future, although I am not sure how. Problem is that `Plug` or `Vundle` pulls the black vim plugin from current master but black gets installed only for releases on PyPI. Perhaps you should point `Vundle` or whatever at a tagged release, if possible.

**Comment by evrenkutar** [comment] 2020-03-04 12:03
for a temp local solution this works for me:
```
cd ~/.vim/bundle/black/
git checkout ce14fa8b497bae2b50ec48b3bd7022573a59cdb1
```

**Comment by rollschild** [comment] 2020-03-04 16:25
> for a temp local solution this works for me:
> 
> ```
> cd ~/.vim/bundle/black/
> git checkout ce14fa8b497bae2b50ec48b3bd7022573a59cdb1
> ```
> 
> or to checkout to the version tag: `git checkout 19.10b0` instead.

I'm using `vim-plug` so I did a `cd ~/.vim/plugged/black`. But this workaround works for me. Thanks!

**Comment by bkjohnson** [comment] 2020-03-07 18:18
Here's a workaround using `vim-plug` that should be a bit easier to manage:

```
Plug 'psf/black', { 'tag': '19.10b0' }
```

**Comment by im-n1** [comment] 2020-03-21 07:46
Just ran into this. This basicaly makes whole Black unusable in Vim.

**Comment by traviswaelbro** [comment] 2020-03-23 12:22
> Just ran into this. This basicaly makes whole Black unusable in Vim.

The problem is with the installed `black` package not having the functionality that the vim plugin is trying to use. Upgrade your installed package [as @BurnhamG suggested](https://github.com/psf/black/issues/1293#issuecomment-594459074) and you shouldn't have any more issues in vim.

**Comment by im-n1** [comment] 2020-03-23 17:09
@traviswaelbro didn't help - my version:  `Black, version 19.10b0 on Python 3.7.6 (default, Jan 19 2020, 22:34:52)`

**Comment by rpdelaney** [comment] 2020-03-25 05:47
The fix from @bkjohnson has the advantage of pinning the vim version to match the installed release. Thank you for that.

**Comment by mkinet** [comment] 2020-04-08 14:37
I had the same issue and could solve it with the proposed fix. However, I observed that it only occurred in the python environments in which pynvim was installed.

**Comment by traviswaelbro** [comment] 2020-04-08 14:58
> I had the same issue and could solve it with the proposed fix. However, I observed that it only occurred in the python environments in which pynvim was installed.

For what it's worth, I also have `pynvim` installed in my case.

**Comment by rpdelaney** [comment] 2020-04-08 18:21
I do not

**Comment by niuxuliang929** [comment] 2020-04-09 04:14
> 使用以下解决方法`vim-plug`应该更容易管理：
> 
> ```
> Plug 'psf/black', { 'tag': '19.10b0' }
> ```

Your method is very good, thank you!

**Comment by erikr** [comment] 2020-04-12 13:31
```
cd ~/.vim/bundle/black/
git checkout 19.10b0
```

used to work, but now whenever I run `vim`, I get the warning `This script requires vim7.0+ with Python 3.6 support`:

```$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
$ vim +PluginInstall +qall
$git checkout 19.10b0
Note: checking out '19.10b0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 6bedb5c Remove Poetry metadata
$ vim +PluginInstall +qall                               black -> 6bedb5c
This script requires vim7.0+ with Python 3.6 support.
Press ENTER or type command to continue```

If checked out to `19.10b0` and I run Black from inside of Vim, I get the error `E492: Not an editor command: Black`.

However, if the original error described by @rollschild no longer appears when using a fresh install of master, I have no complaints!

**Comment by erikr** [comment] 2020-04-20 10:17
This fix is no longer working.

Now after checking out `19.10b0`, if I run `vim` I get the following error:

```
Error detected while processing /Users/$USER/.vim/bundle/black/plugin/black.vim:
line   43:
E221: Marker cannot start with lower case letter
  File "<string>", line 1
    << endpython3
     ^
SyntaxError: invalid syntax
line   44:
E1042: import/export can only be used in vim9script
line   45:
E1042: import/export can only be used in vim9script
line   46:
E1042: import/export can only be used in vim9script
line   48:
E1077: Missing argument type for exec_prefix
line   49:
E488: Trailing characters:   try:
line   50:
E492: Not an editor command:     default = vim.eval("g:pymode_python").strip(
line   51:
E492: Not an editor command:   except vim.error:
line   52:
E492: Not an editor command:     default = ""
line   53:
E121: Undefined variable: default
line   54:
E133: :return not inside a function
line   56:
E133: :return not inside a function
line   57:
E133: :return not inside a function
line   59:
E1077: Missing argument type for venv_path
line   61:
E133: :return not inside a function
line   62:
E133: :return not inside a function
line   64:
E1077: Missing argument type for venv_path
line   66:
E133: :return not inside a function
line   67:
E133: :return not inside a function
line   69:
E1056: expected a type: [NULL]
line  152:
E1057: Missing :enddef
line  153:
E171: Missing :endif
Press ENTER or type command to continue```

**Comment by dlukes** [comment] 2020-04-20 17:41
With `vim-plug`, you can even use a wildcard tag, to avoid having to specify a particular tagged version and updating your init file when a new `black` version is released:

```vim
Plug 'psf/black', { 'tag': '*' }
```

**Comment by duarteocarmo** [comment] 2020-04-20 17:53
@ambv sorry to at you, but do you have an idea when this could be potentially be fixed? Thanks for your great effort and amazing job!

**Comment by ldragan** [comment] 2020-04-22 04:07
The solution from #1273 didn't work for me since I had black installed at the system level and that was the one picked up so I had to do something like 
```
pip3 install --upgrade git+https://github.com/psf/black.git
```
which seems to have replaced my systemwide install of black with the tip of git.

**Comment by weaming** [comment] 2020-04-24 04:57
I added this key mapping `Alt + f` to use external `black` command in `$PATH`:

```vimscript
au FileType python nnoremap <buffer> <a-f> :silent !black -S %<CR><CR>
```

No more black plugin!

**Comment by dlukes** [comment] 2020-04-24 07:24
> No more black plugin!

That can be noticeably slower though, as you incur black's startup time cost each time you format.

**Comment by akselsjogren** [comment] 2020-04-29 09:11
I ran into problems when Vim was upgraded to 8.2.587.

My temporary workaround:
I have the vim plugin installed with vim-plug, make sure it's using master branch (since the released black/vim-black aren't compatible with latest vim):
```
Plug 'psf/black'
```
Update vim-plugin:
```
:PlugUpdate black
```
Upgrade *black* used by the vim-plugin to the latest from master:
```
cd ~/.vim
black/bin/pip install --upgrade git+https://github.com/psf/black.git
```

This should work when there is a new release of Black on PyPI I reckon.

**Comment by dlukes** [comment] 2020-04-29 09:20
@akselsjogren That gets you a bleeding edge version of `black` though, which might be asking for trouble. If you want to keep using the latest PyPI release of `black`, you can just ask `vim-plug` to install the plugin from the latest tag in the repo, which should correspond to the latest version released on PyPI: `Plug 'psf/black', { 'tag': '*' }`.

**Comment by akselsjogren** [comment] 2020-04-29 09:41
> @akselsjogren That gets you a bleeding edge version of `black` though, which might be asking for trouble. If you want to keep using the latest PyPI release of `black`, you can just ask `vim-plug` to install the plugin from the latest tag in the repo, which should correspond to the latest version released on PyPI: `Plug 'psf/black', { 'tag': '*' }` (and rerun `PlugUpdate black` obviously).

As I wrote, the bleeding edge of master (8654e8d7aef5253faa7f8ff31d4be3b0b8b9c392) is what is needed to get the plugin working with later vim versions.

**Comment by dlukes** [comment] 2020-04-29 10:42
> As I wrote, the bleeding edge of master (8654e8d) is what is needed to get the plugin working with later vim versions.

Oh right, sorry :) I misunderstood the purpose of your comment because that's a somewhat different issue -- the latest release of the plugin being incompatible with latest Vim, and how to get around that.

This issue is about the fact that current installation instructions are likely to result in different versions of the `black` Vim plugin vs. Python library (master vs. latest PyPI release). For which I think the safer solution is to stay off the bleeding edge if you can afford to (Neovim, Vim older than 8.2.587).

But maybe `black` devs will chime in to say that `master` is safe and the ultimate solution to this issue might be that the plugin switches to installing `black` from `git+https` instead of PyPI, who knows.

**Comment by erikr** [comment] 2020-05-03 16:22
@dlukes I'm on macOS 10.15.4, vim 8.2 (installed via home-brew, `+python3`). I tried your fix but cannot run black in vim. This is frustrating, as I run black in vim without issues on my Ubuntu machines following the default installation instructions.

I put `Plug 'psf/black', { 'tag': '*' }` in my `.vimrc`, installed Black via `vim -c PlugInstall`, and the latest tag was `19.10b0`:
![Screen Shot 2020-05-03 at 12 14 23 PM](https://user-images.githubusercontent.com/1253422/80919375-a0e06680-8d37-11ea-97e9-20630f6f3c08.png)

However, when I run vim, I get the following error:

```
Error detected while processing /Users/erik/.vim/plugged/black/plugin/black.vim:
line   43:
E221: Marker cannot start with lower case letter
  File "<string>", line 1
    << endpython3
    ^
SyntaxError: invalid syntax
line   44:
E1042: import/export can only be used in vim9script
line   45:
E1042: import/export can only be used in vim9script
line   46:
E1042: import/export can only be used in vim9script
line   48:
E1077: Missing argument type for exec_prefix
line   49:
E488: Trailing characters:   try:
line   50:
E492: Not an editor command:     default = vim.eval("g:pymode_python").strip()
line   51:
E492: Not an editor command:   except vim.error:
line   52:
E492: Not an editor command:     default = ""
line   53:
E121: Undefined variable: default
line   54:
E133: :return not inside a function
line   56:
E133: :return not inside a function
line   57:
E133: :return not inside a function
line   59:
E1077: Missing argument type for venv_path
line   61:
E133: :return not inside a function
line   62:
E133: :return not inside a function
line   64:
E1077: Missing argument type for venv_path
line   66:
E133: :return not inside a function
line   67:
E133: :return not inside a function
line   69:
E1056: expected a type:
line  152:
E1057: Missing :enddef
line  153:
E171: Missing :endif
Press ENTER or type command to continue
```

If I:
1. edit `$HOME/.vim/plugged/black/plugin/black.vim` and change `endpython3` to `Endpython3`, or
2. `cd $HOME/.vim/plugged/black/plugin && git checkout master -- black.vim`

and run vim, I get a new error:
```
Error detected while processing /Users/erik/.vim/plugged/black/plugin/black.vim:
line  147:
Traceback (most recent call last):
  File "<string>", line 63, in <module>
ModuleNotFoundError: No module named 'black'
Press ENTER or type command to continue
```

Do you or @akselsjogren have other suggestions? Thanks in advance for your time.

**Comment by erikr** [comment] 2020-05-03 17:25
@weaming's workaround did not work for me.

I made my own workaround in `~/.vimrc` to call `black` from the command line within vim by hitting `F9`:

`nnoremap <F9> :silent execute "! /usr/local/bin/black % &" <bar> redraw!<CR>`

but I still have to hit `ctrl+L` or `enter` a few times to get the screen to redraw.

**Comment by weaming** [comment] 2020-05-04 03:00
> @weaming's workaround did not work for me.
> 
> I made my own workaround in `~/.vimrc` to call `black` from the command line within vim by hitting `F9`:
> 
> `nnoremap <F9> :silent execute "! /usr/local/bin/black % &" <bar> redraw!<CR>`
> 
> but I still have to hit `ctrl+L` or `enter` a few times to get the screen to redraw.

@erikr Why put the process into background using `&` ? I can't understand the purpose of `<bar> redraw!`.

**Comment by erikr** [comment] 2020-05-04 03:05
@weaming Running the process in the background gives an illusion of speed, since this approach incurs startup time per @dlukes.

If I call the command without `redraw`, the screen goes blank and the output from `black` from the command line appears and the vim editor disappears until I redraw manually via `ctrl + L`:
![Screen Shot 2020-05-03 at 11 04 44 PM](https://user-images.githubusercontent.com/1253422/80933605-7bcd1180-8d92-11ea-8e62-0cb57911273c.png)

**Comment by weaming** [comment] 2020-05-04 03:08
@erikr Try `au FileType python nnoremap <buffer> <F9> :silent !black -S %<CR><CR>`

**Comment by dlukes** [comment] 2020-05-04 11:27
@erikr The solution I suggested makes sure that both the Vim plugin and the Python library are set to the latest released version. Unfortunately, as @akselsjogren has pointed out, Vim 8.2.587 is incompatible with the latest released version of the plugin, so your best bet is to [use the `master` branch version for both until the next release happens](https://github.com/psf/black/issues/1293#issuecomment-621082845).

**Comment by dlukes** [comment] 2020-05-04 11:29
By the way, I think **this issue can now be closed** thanks to #1318. For `vim-plug`, the officially recommended way to install the stable version of the plugin now seems to be `Plug 'psf/black', { 'branch': 'stable' }`.

**Comment by erikr** [comment] 2020-05-04 12:57
@weaming @dlukes Thanks so much for both of your comments.

I cleaned up prior installs of `black`:

```
rm -rf ~/.vim/black
rm -rf ~/.vim/plugged/black
```

Then changed my `.vimrc` to `Plug 'psf/black', { 'branch': 'stable' }`.

Then ran `vim -c PlugInstall` successfully.

However I still get this error:
```
Error detected while processing /Users/erik/.vim/plugged/black/plugin/black.vim:
line   43:
E221: Marker cannot start with lower case letter
  File "<string>", line 1
    << endpython3
```

Any other steps you'd suggest?

**Comment by dlukes** [comment] 2020-05-04 14:43
@erikr You can't currently use the stable branch of black with Vim 8.2.587, so the advice to `Plug 'psf/black', { 'branch': 'stable' }`, which solves the original problem that this issue is about, won't help you. You'll end up with versions of the black Vim plugin and Python library that are mutually compatible, but the plugin will still be incompatible with your Vim version (that's the error you're getting).

Please follow [the instructions by akselsjogren that I've linked to in my previous reply](https://github.com/psf/black/issues/1293#issuecomment-621082845), they should help you make sure that you have the latest master of both the Vim plugin and the Python library.

**Comment by erikr** [comment] 2020-05-04 16:13
Hi @dlukes Thanks for clarifying.

I am trying to perform the following instructions from @akselsjogren that you linked to:
> Upgrade black used by the vim-plugin to the latest from master:
> 
> ```
> cd ~/.vim
> black/bin/pip install --upgrade git+https://github.com/psf/black.git
> ```

However I do not have `pip` in `bin`:
```
$ tree ~/.vim/black
.
├── bin
│   ├── python
│   ├── python3
│   └── vim
├── include
├── lib
│   └── python3.8
└── pyvenv.cfg
```

#1375 seems similar.

What step am I missing here?

**Comment by dlukes** [comment] 2020-05-04 19:52
@erikr That's weird, but I can confirm this happens with Homebrew Vim 8.2.654 on macOS (I normally use Neovim). It seems to be a completely unrelated problem though, so please file a different issue for that. Feel free to re-use any information provided in the Details section below :) (I made it collapsible because I'd rather not hijack this thread anymore, the issue mentioned in OP has been addressed and this issue should be closed.)

<details>
<summary>Details</summary>

When the virtualenv is created, `vim` gets somehow substituted instead of `python3` as the executable name when `ensurepip` is run:

```
Please wait, one time setup for Black.
Creating a virtualenv in /Users/david/.vim/black...
(this path can be customized in .vimrc by setting g:black_virtualenv)
Error detected while processing /Users/david/.vim/plugged/black/plugin/black.vim:
line  195:
Traceback (most recent call last):
  File "<string>", line 87, in <module>
  File "<string>", line 70, in _initialize_black_env
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 391, in create
    builder.create(env_dir)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/david/.vim/black/bin/vim', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

On that last line, it should be `'/Users/david/.vim/black/bin/python3'`, not `'/Users/david/.vim/black/bin/vim'`. So ensurepip fails and the installation of the black Python package aborts. Not sure why.

If you can't see that error message, wipe the black virtualenv and restart Vim. If it flies by too quickly, you can redisplay it with `:messages`.

</details>

**Comment by NISH1001** [comment] 2020-10-20 03:55
> Here's a workaround using `vim-plug` that should be a bit easier to manage:
> 
> ```
> Plug 'psf/black', { 'tag': '19.10b0' }
> ```

Hi, I upgraded all the vim-plug plugins recently. And it seems `black` was broken with the same error. I had to switch to that tag 19.

Is this happening with recent release too?

**Comment by wojciechkepka** [comment] 2020-10-23 03:57
Hi, I have a similar situation. I'm also getting errors about pyproject_toml with `stable` branch of Black. Specifying `{ 'tag': '19.10b0' }` resolves the issue.

**Comment by bataak** [comment] 2020-11-26 02:58
Guys, please just update your pip version to 20 and python3 to 3.9 then that problem will be solved. At least you can use the latest version of black on your vim.

**Comment by wwwehr** [comment] 2023-01-03 17:01
for lua configs, this worked for me:
```
use { 'psf/black', tag = '19.10b0', cmd = {'Black'}}
```

**Comment by hauntsaninja** [comment] 2023-07-05 03:01
I think this has been fixed by later releases and https://github.com/psf/black/pull/1318

**Closed by hauntsaninja** 2023-07-05 03:01 UTC
Labels: T: bug, C: vim
