### ISSUE TITLE
Black fails to format complicated f-string

### ISSUE THREAD

**Issue by georgepittock** [psf/black#4126] opened 2023-12-23 20:14 UTC
**Black fails to format complicated f-string**

**To Reproduce**

[Black Playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AG2AQBdAD2IimZxl1N_WkV5Dh9aT_4mT9MT7V5nzxAkY1qUMRYn2RPF3WE6th5dEtdMoo46NUrugxJoAe_jhMZ-PBa7cq1SqOzihEYQNvj9jyYVoAs0ab6udf1STlHAkCVSkPfuGaRQy5YC8KIBIZV4AV0019fpNWJF316cq_8OXvDKlbqFg_-vH1zLlOsrILWmnumk6nBudqNaHpjZuatmh1NmYXExe0Y65A-Ups84j0OWlMU5ch-j-CGDHBxUGlq_6XxkLa4r5n96LZPPyxLl69MHIbqWaicGIoz15o0WkJ6r8l0B_5wnAtPEsYb7RqstanaB47SGT83Eg1JVdwnolsDLugAAOeh16nQf9X8AAZwCtwMAAP-Z0lGxxGf7AgAAAAAEWVo=)

```python
SUBSCRIPTS = {i: chr(0x2080 + i) for i in range(10)}

def cant_format(row):
    return " + ".join(
                f"{coefficient if coefficient != 1 else ""}x{''.join(SUBSCRIPTS[int(digit)] for digit in str(i+1))}"
                for i, coefficient in enumerate(row)
            )


cant_format([1, 2])
```

And run it with these arguments:

```sh
$ black simplex\utils.py
```

The resulting error is:

```sh
> [cannot format file.py: INTERNAL ERROR: ...](error: cannot format: simplex\utils.py: INTERNAL ERROR: Black produced invalid code: f-string: expecting '}' (<unknown>, line 6). Please report a bug on https://github.com/psf/black/issues.  This invalid output might be helpful: Temp\blk_k8cady1s.log)
```
**Log File Output**

```python
  File "src\black\__init__.py", line 1476, in assert_equivalent
  File "src\black\parsing.py", line 140, in parse_ast
SUBSCRIPTS = {i: chr(0x2080 + i) for i in range(10)}


def cant_format(row):
    return " + ".join(
        f"{coefficient if coefficient != 1 else "
        "}x{''.join(SUBSCRIPTS[int(digit)] for digit in str(i+1))}"
        for i, coefficient in enumerate(row)
    )


cant_format([1, 2])
```

The error is due to the `}`being carried to the next line. I would expect the whole f-expression to be on one line. 

If single quotes are used in the first statement after the else, then black correctly formats this i.e. the below works fine.

```python
SUBSCRIPTS = {i: chr(0x2080 + i) for i in range(10)}

def cant_format(row):
    return " + ".join(
                f"{coefficient if coefficient != 1 else ''}x{''.join(SUBSCRIPTS[int(digit)] for digit in str(i+1))}"
                for i, coefficient in enumerate(row)
            )


cant_format([1, 2])
```

**Expected behaviour**

Black should correctly format the code, I would expect something very similar to the following:

```python
SUBSCRIPTS = {i: chr(0x2080 + i) for i in range(10)}


def cant_format(row):
    return " + ".join(
        f"{coefficient if coefficient != 1 else ''}x{''.join(SUBSCRIPTS[int(digit)] for digit in str(i+1))}"
        for i, coefficient in enumerate(row)
    )


cant_format([1, 2])
```

**Environment**

````sh
>black --version
black, 23.12.1 (compiled: yes)
Python (CPython) 3.12.0

**Comment by Lilneo786** [comment] 2023-12-23 20:18
This should work:

```
SUBSCRIPTS = {i: chr(0x2080 + i) for i in range(10)}

def cant_format(row):
    return " + ".join(
        [
            f"{coefficient if coefficient != 1 else ''}x{''.join(SUBSCRIPTS[int(digit)] for digit in str(i+1))}"
            for i, coefficient in enumerate(row)
        ]
    )

print(cant_format([1, 2]))
```

**Comment by hauntsaninja** [comment] 2023-12-23 20:31
Thanks, duplicate of https://github.com/psf/black/issues/3746

**Closed by hauntsaninja** 2023-12-23 20:31 UTC
Labels: T: bug
