### ISSUE TITLE
Long method chaining inside a dictionary looks bad

### ISSUE THREAD

**Issue by archiif** [psf/black#2591] opened 2021-11-05 13:49 UTC
**Describe the style change**

Break up and indent long method chaining inside a dictionary in a more readable way

**Examples in the current _Black_ style**

How black breaks up method chaining in variable assignments:
```python
value = (
    fn.chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
)
```

How black does it with dictionary key assignments:
```python
d = {
    foo: fn.chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain()
    .chain(),
    bar: "value",
    more: "stuff",
}
```

**Desired style**

```python
d = {
    foo: (
        fn.chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
    ),
    bar: "value",
    more: "stuff",
}
```

or maybe:

```python
d = {
    foo: fn.chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain()
        .chain(),
    bar: "value",
    more: "stuff",
}
```

**Additional context**

**Comment by felix-hilden** [comment] 2021-11-05 13:52
Hi, this is a duplicate of #620, we'll continue the discussion there!

**Closed by felix-hilden** 2021-11-05 13:52 UTC
Labels: T: design
