### ISSUE TITLE
`'ModuleNotFoundError' No module named 'tomli'` after installing using pip and venv

### ISSUE THREAD

**Issue by mateuszkojro** [psf/black#3447] opened 2022-12-17 16:53 UTC
**Describe the bug**

After installing `black` using `pip` inside venv  running it results in `'ModuleNotFoundError' No module named 'tomli'` exception beeing raised:

**To Reproduce**

1. Create new virtual environment and activate it

```s
python -m venv venv
```

and 

```s
.\venv\Scripts\activate.ps1
```

3. `pip install black`
4. `black --version`

output:
```
Traceback (most recent call last):
  File "C:\Users\PC1080Ti\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC1080Ti\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC1080Ti\Downloads\black-repro-bug\venv\Scripts\black.exe\__main__.py", line 4, in <module>
  File "src\black\__init__.py", line 45, in <module>
  File "c:\users\pc1080ti\downloads\black-repro-bug\venv\lib\site-packages\black\files.py", line 32, in <module>
    import tomli as tomllib
ModuleNotFoundError: No module named 'tomli'
``` 

**Expected behavior**
output:
```
black, 22.12.0 (compiled: yes)
Python (CPython) 3.8.8rc1
```

**Environment**

- Black's version: 22.12.0
- OS and Python version: Windows (21H2 19044.2364) running Python 3.8.8rc1

**Additional context**
The same behavior is observed when installing black from the main branch.

**Comment by JelleZijlstra** [comment] 2022-12-17 17:14
tomli is a dependency for 3.8: https://github.com/psf/black/blob/main/pyproject.toml#L70

I can't reproduce this on MacOS with 3.8.10. The one thing that stands out in your report is that you're using `3.8.8rc1`: maybe something is mishandling deps for RC versions.

**Comment by mateuszkojro** [comment] 2022-12-17 17:38
Hi,
This might indeed be the issue with Python versions using the postifx notation since Tomli is automatically installed for Python 3.10.9 and not for 3.10.0b1 (I cannot test it for 3.8 because they no longer provide those on the official website).

**Comment by JelleZijlstra** [comment] 2022-12-17 18:35
@ichard26 looked into this with me on Discord and found:

* The root cause is a bug in `packaging`, fixed in pypa/packaging#523
* pip hasn't yet updated `packaging` to pick up this fix
* We can prevent getting hit by this bug by changing our version requirement to `python_version < '3.11'` instead of listing a specific alpha. I'm about to submit a PR doing that.

**Comment by mateuszkojro** [comment] 2022-12-17 18:51
Tested in my environment and it solves it. Thanks a lot!

**Closed** 2022-12-18 03:02 UTC
Labels: T: bug

**Comment by NavyaAJ** [comment] 2023-08-24 11:22
I've reproduced this issue on mac  today after the Python update to 3.11. Later realised I hadn't changed the version of Python in ci.yaml. 
So the conclusion is that this issue can occur when the  version of black installed for 3.10 is not compatible with 3.11

Error details:
`Traceback (most recent call last):

  File "/opt/hostedtoolcache/Python/3.10.12/x64/bin/black", line 5, in <module>

    from black import patched_main

  File "src/black/__init__.py", line 52, in <module>

  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/black/files.py", line 27, in <module>

    import tomli as tomllib

ModuleNotFoundError: No module named 'tomli'

Error: Process completed with exit code 1.`
