### ISSUE TITLE
Possible to format a Python code contained in a string variable?

### ISSUE THREAD

**Issue by misrasaurabh1** [psf/black#4147] opened 2024-01-10 00:15 UTC
I'm building a developer tool that generates code. The code we want to generate should be formatted according to black. The only way I've found to do that until now has been to write the new file to disk and then call black executable to format the file. But this seems pretty unnecessary and wasteful in time and performance. 

It could be much better if I could just call black through some python library/API function and provide it a string variable with the unformatted python code. I would expect it to return a formatted code. Is this something black implements already somehow? If not, this could be pretty useful for developer tools to interface with black directly without involving a disk write.

**Comment by hauntsaninja** [comment] 2024-01-10 01:00
This is a duplicate of https://github.com/psf/black/issues/779

Look at the functions in `black/__init__.py`, they can do what you want, e.g. see `format_str`. Just know that Black doesn't currently provide any backward compatibility guarantees for these APIs.

**Closed by hauntsaninja** 2024-01-10 01:00 UTC
Labels: T: enhancement
