### ISSUE TITLE
Cannot format whitespace after backslash

### ISSUE THREAD

**Issue by rabarberski** [psf/black#3079] opened 2022-05-20 06:58 UTC
**Describe the bug**

Black generates an INTERNAL ERROR with a file that has a docstring that contains a backslash with a trailing space character. Removing the trailing space solves the issue.

**To Reproduce**

Create a file `file.py` with the following content. Note, the 5th but last line (i.e., just above the line with `other option`) contains a trailing space after the backslash!

```python
def foo():
    """
    Some description
                            ['some option'] 
                            /
                            /    --- ['option b']
    something[here]
                            \    --- ['option c']  (['d', 'e', 'f', 'g'])
                            \ 
                            ['other option']
    """
    pass

```

And run it with these arguments:

```sh
$ black file.py
```

The resulting error is:

> error:` cannot format file.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug ...`.

**Expected behavior**

No error

**Environment**

- Black's version: 22.3
- OS and Python version: macos 11.6, python 3.7

**Comment by felix-hilden** [comment] 2022-09-11 13:51
This is a duplicate of #3263, or technically the other way around but the linked issue has ever so slightly more complete information, so I'll close this issue.

**Closed by felix-hilden** 2022-09-11 13:51 UTC
Labels: T: bug, C: invalid code, F: docstrings
