### ISSUE TITLE
New lines for generics in functions

### ISSUE THREAD

**Issue by framunoz** [psf/black#4534] opened 2024-12-17 22:57 UTC
**Is your feature request related to a problem? Please describe.**

I have noticed that when writing functions with generics, black splits the generics into more space. This is frustrating, as it makes it harder to read. Also, I feel it goes against black's philosophy, as black always tries to minimise space whenever possible.

For example, instead of writing a function like:
```python
def foo[TypeA](
    input_a: TypeA,
    input_b: TypeA,
    input_c,
    input_d,
    input_e,
    input_f,
    input_g,
    input_h,
    input_i,
) -> list[TypeA]: ...
```
Black formats like this:
```python
def foo[
    TypeA
](
    input_a: TypeA,
    input_b: TypeA,
    input_c,
    input_d,
    input_e,
    input_f,
    input_g,
    input_h,
    input_i,
) -> list[TypeA]: ...
```

**Describe the solution you'd like**

I would like to consider having a format like the one in the first code cell, to make it more concise.

**Comment by MeGaGiGaGon** [comment] 2024-12-17 23:15
This looks to be a duplicate of #4254

**Comment by framunoz** [comment] 2024-12-18 01:28
@MeGaGiGaGon Yep, it is. At least, the expected behaviour is the mentioned in that Issue.

**Comment by hauntsaninja** [comment] 2024-12-18 03:09
Duplicate of https://github.com/psf/black/issues/4071 , PR welcome

**Closed by hauntsaninja** 2024-12-18 03:09 UTC
Labels: T: enhancement
